ubccr/xdmod

- docs/simpleSAMLphp-ldap.md
- docs/simpleSAMLphp.md
Update documentation related to nginx and ldap configuration for simplesaml
Hopefully this makes things a bit clearer and makes sure things work when setting them up.
Performed steps on centos7 virtual machine to make example documentation work.
Documentation change only
> update ldap and nginx documentation

- docs/simpleSAMLphp-ldap.md
- docs/simpleSAMLphp.md
This applies #15 to Open XDMoD 6.5. It is a documentation update that applies to Open XDMoD 6.5, so it should be included there as well.
> Apply #15 to Open XDMoD 6.5

- html/gui/js/modules/metric_explorer/MetricExplorer.js
In the Metric Explorer, the Y axis context menu prevented the axis min/max value(s) and log scale controls from being changed together. The menu's log scale control, if toggled, caused unsaved axis min and max values to be disregarded. This was a misleading result as there is an Ok/Cancel button pair provided on the menu. This behavior is corrected with the fix in this pull request.
In the Metric Explorer's Y axis context menu, the control that toggles log scaling is changed to a form.checkbox from a menu.checkitem. The existing handler is adapted to include the new checkbox. The handler now incorporates any set of changes made in the context menu into a single change on the change stack. User input of log plot min value <=0 is corrected prior to plotting. Log scale and scaling are …
> Y axis context menu behavior in Metric Explorer

- docs/configuration.md
> Fix typo in JSON example

- .travis.install.sh
- docs/configuration.md
This merges pull request #35 into Open XDMoD 6.6.
> Merge #35 into 6.6

- NOTICE
- docs/notices.md
- licenses/gpl-2.0.txt
This pull requests documents the license information for PDOOCI, which was added in #34.
This brings our dependency licensing information back up to date.
N/A
- Documentation Update
> Added license info for PDOOCI

- etl/js/lib/dataset_processor.js
This aids the process of debugging configuration file problems.
Makes it easier to spot incorrect settings since they are printed out.
Ran etl.cluster code and obsered that the database name and collection name were correctly printed out.
> Added extra debug messages that list database and collection names.

- docs/faq.md
fix the link to LDAP Authentication
Broken links are bad
Checked that the link rendered properly
> FAQ: fix the link to LDAP Authentication

- classes/NewRest/Controllers/BaseControllerProvider.php
Bugfix addresses fallout from an impulsive change to correct a method signature. The correction to the method signature caused a test for a null param to fail, so some users could not log in.
Fix was needed, as users with only a single role assigned (e.g. certain test users who are only Program Officer or only Center Director) were unable to log in.
- Look! Now all my integration and unit tests work again! (See supremm tests that use Program Officer and Center Director users)
- Also tested on port 9004 of dev instance.
> Bugfix: Check empty array in authorize() function

- classes/CCR/Log.php
Changes the composite logger to no longer be a singleton.
Fixes issue where creating multiple loggers results in incorrect logging.
Installed and then ran the processes that were creating the errors (query log and ingestion).
> Replace singleton composite logger

- docs/upgrade.md
Adds a note about database migrations performed during upgrade.
We have similar notes for previous upgrades, so this continues that trend.
No tests.
> Add upgrade notes

- composer.json
- composer.lock
> Add xdmod-test-artifacts as a compuser dev dependency.

- html/internal_dashboard/index.php
The file included by the removed script tag is part of the App Kernels
module.
Removes a script tag from the internal dashboard index HTML file.
See ubccr/xdmod-appkernels#19
The removed tag should be part of the App Kernels module.
Installed with and without App Kernels module.  Confirmed that the tag was present only when the App Kernels module is installed and that no JavaScript errors were produced.
> Remove script tag

- html/about/publications.html
Updated 2016 publication citation with DOI
Looked at it in the browser
> Updated publication with doi

- docs/index.md
Adds changes to Open XDMoD overview documentation.
These changes need to be on the `master` branch to be displayed on [the website](http://open.xdmod.org/).
> Cherry-pick changes to Open XDMoD overview changes

- html/about/presentations.html
- html/about/publications.html
Updated publications and presentations to include 2016 presentations and PEARC17 accepted publications.
Keep information up-to-date.
Viewed in browser.
> Update presentations & publications for 6.7

- CHANGELOG.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/xdmod.spec.in
This pull request updates the change log and release notes for the release of Open XDMoD 6.6.0. The release notes contain user-friendly lists of changes, whereas the change log contains deeper, more technical notes.
**Please do not merge until dates and notes are finalized.**
Verified files rendered as expected.
> Added change log and release notes for 6.6.0

- CHANGELOG.md
- README.md
- classes/DataWarehouse/Access/Usage.php
- classes/NewRest/Controllers/MetricExplorerControllerProvider.php
- docs/index.md
- html/about/release_notes/xdmod.html
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- open_xdmod/modules/xdmod/xdmod.spec.in
Merges `xdmod6.6` into `xdmod6.7`.
Conflicts:
- `html/about/publications.html`
> Merge xdmod6.6 into xdmod6.7 (#96, #123, #130, #132, #135, #140)

- bin/xdmod-slurm-helper
- docs/resource-manager-slurm.md
Update documentation to match current behavior of the `xdmod-slurm-helper` script. Also, now throw an exception if the shredder resource has not been set when determining the arguments used with sacct.
The current documentation is incorrect.
See https://listserv.buffalo.edu/cgi-bin/wa?A2=ccr-xdmod-list;ff772fb.1706
Ran Open XDMoD tests.
> Update Slurm helper documentation

- db/data/moddb.sql
- db/migrations/6.6.0-6.7.0/moddb.sql
- db/migrations/6.6.0-7.0.0/moddb.sql
Replaces 6.7.0 with 7.0.0.
Previously planned 6.7.0 release has been cancelled, and 7.0.0 will be the next release.
No tests.
> Change migration version numbers

- .travis.yml
Basically what the title says
Saves us some Travis build time while making PRs
N/A
> don't run style tests more than once

- html/gui/js/modules/Usage.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/usageTab.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/usageTab.page.js
Pull request #60 introduced a bug where usage tree nodes that were configured to be disabled were not. The change fixes the regression and restores the original behaviour.
Also add automated tests to check that the code works.
Fix regression.
Naturally.
> Fix regression bug in Usage Tree.

- README.md
- docs/support.md
Add Support section to README.md
> Add Support section to README.md

- docs/_includes/menu.md
~~Updates support documentation to match #202 and~~ move support heading in menu
Make ~~support documentation consistent and~~ support link more prominent.
No tests.
> Update support documentation

- open_xdmod/modules/xdmod/automated_tests/package-lock.json
- open_xdmod/modules/xdmod/automated_tests/package.json
- open_xdmod/modules/xdmod/automated_tests/wdio.conf.js
Changes WebdriverIO test reports.  See http://webdriver.io/guide/reporters/spec.html
The default test report format is difficult to read.
Ran the tests.
> Add and configure wdio-spec-reporter for WebdriverIO tests

- classes/ETL/DbModel/Entity.php
- classes/ETL/DbModel/Table.php
- tools/etl/etl_table_manager.php
etl_table_manager was left out in the DbModel update. Bring it into line. Also updated comments as appropriate.
```
./etl_table_manager.php -c ../../../etc/etl/etl.json -d modw_cloud.asset -o dump-discovered -x sql
./etl_table_manager.php -c ../../../etc/etl/etl.json -d modw_cloud.asset -o dump-discovered -x sql -i
./etl_table_manager.php -c ../../../etc/etl/etl.json -d modw_cloud.asset -o dump-discovered -x json
./etl_table_manager.php -c ../../../etc/etl/etl.json -d modw_cloud.asset -o dump-parsed -t ../../../etc/etl/etl_tables.d/cloud/asset.json -x sql
./etl_table_manager.php -c ../../../etc/etl/etl.json -d modw_cloud.asset -o dump-parsed -t ../../../etc/etl/etl_tables.d/cloud/asset.json -x json
```
> Update etl_table_manager.php for changes to DbModel

- classes/Xdmod/HostListParser.php
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/HostListParserTest.php
Update HostListParser to prevent empty hosts from being returned.
When running full ingest ran into issues with jobs with empty node lists.
ran the unit tests with added tests, saw failures, updated code to account for new test cases.
The diff looks pretty bad, but it was because of the addition of an else, if you view without whitespace changes it is much easier to see the changes
> update hostlist parser

- html/about/publications.html
- html/about/team.html
- html/about/xdmod.php
Added Rudra to the team list, updated 2017 citations now that PEARC17 is over, standardized the citation format, and formatted the html so its easier to manage in an editor.
> Add Rudra to team list, update and clean up publications

- CHANGELOG.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/xdmod.spec.in
This pull request updates the change log and release notes for the release of Open XDMoD 7.0.0. The release notes contain user-friendly lists of changes, whereas the change log contains deeper, more technical notes.
**Please do not merge until dates and notes are finalized.**
Verified files rendered as expected.
> Updated release notes and change log for 7.0.0

- docs/upgrade.md
Adds a note about changes to the `moddb` schema.
> Add 7.0.0 upgrade notes

- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
> Update spec file changelog to indicate Java fix

- open_xdmod/modules/xdmod/automated_tests/package.json
- open_xdmod/modules/xdmod/automated_tests/runtests.sh
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/loginPage.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/reportGenerator.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/usageTab.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/xdmod.page.js
- open_xdmod/modules/xdmod/automated_tests/wdio.conf.js
- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
- shippable.yml
- Increase robustness of metric explorer test.
- Add headless capability to tests.
> Add webdriverio-based GUI tests to shippable CI.

- CHANGELOG.md
- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version700To701/ConfigFilesMigration.php
- classes/OpenXdmod/Migration/Version700To701/DatabasesMigration.php
- configuration/portal_settings.ini
- docs/upgrade.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
- package.json
> Add 7.0.0 to 7.0.1 migration, etc.

- html/about/publications.html
Remove duplicate publication entry from the publication list
> Remove duplicate publication entry

- shippable.yml
> Ignore ui tests for the time being

- classes/DataWarehouse/Access/Common.php
- classes/DataWarehouse/Access/MetricExplorer.php
- classes/DataWarehouse/ExportBuilder.php
- docs/software-requirements.md
- html/gui/js/ExportPanel.js
- libraries/charting.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
- open_xdmod/modules/xdmod/xdmod.spec.in
> Add PDF support to XDMoD

- CHANGELOG.md
- bin/acl-config
- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version700To701/ConfigFilesMigration.php
- classes/OpenXdmod/Migration/Version700To701/DatabasesMigration.php
- configuration/portal_settings.ini
- docs/upgrade.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
- package.json
> Sync Xdmod7.0

- open_xdmod/modules/xdmod/automated_tests/runtests.sh
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/loginPage.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.page.js
This click was missing a check for the mask
> Improve robustness of metrics explorer GUI tests.

- html/gui/js/modules/job_viewer/JobViewer.js
> Add itemid to facilitate tests

- open_xdmod/modules/xdmod/automated_tests/runtests.sh
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/reportGenerator.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/usageTab.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/xdmod.page.js
- shippable.yml
> More test improvements needed for job viewer tests

- classes/DataWarehouse/Access/Usage.php
Fixes a bug introduced by #266 .  Apparently I only tested time series plots and not aggregate.
> Fix bug in usage drill downs

- README.md
- docs/software-requirements.md
- docs/support.md
- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
- open_xdmod/modules/xdmod/xdmod.spec.in
Updates the list of dependencies along with the RPM spec file and integration tests.  Also updates the support page to explain what versions we will support.
If we aren't going to support it, it shouldn't be in the documentation.
Ran automated tests.
> Update dependencies and support documentation

- .gitignore
- classes/Xdmod/Config.php
Fixes an XDMoD crash where a key is present but no value is assigned in Config.
Improper Configuration shouldn't impede the program as a whole; rather it should be apparent from missing functionality.
Surely.
> Make null config value an empty array

- classes/Models/Services/Tabs.php
- The previous query did not include tabs from acls that did not participate in
a hierarchy. This one does.
We like to see all the tabs, even the ones that are a little bit wild and don't like being forced to conform to a hierarchy. 
Manual Tests:
**Test 1**
- Add a new tab to the system ( via roles.json::permited_modules ) 
- or, as in my case, log on to a system that has one already. In this case smgallo-dev.ccr.xdmod.org
- Log In as a User that has been assigned an acl that has access to the new tab.
- in this case it's the 'acl.custom-query-tab' acl and it was already assigned to my user. 
- The new tab should be visible
- in this case it was the 'Custom Query' tab
> Updated the Tabs::getTabs query

- composer.json
- composer.lock
> authglobus update

- docs/configuration.md
Add note regarding setup of database on different server.
Some people think this may be necessary.
> Add database setup note

- background_scripts/report_schedule_manager.php
- classes/XDReportManager.php
These were debug level messages, which are not stored in the database.  We'd like them to be logged to the database for analytics purposes.
> Change report schedule manager log levels

- classes/XDReportManager.php
Fixes typo in report manager code.
Compliance report was missing additional information text.
Sent compliance report via email.
- [] All new and existing tests passed.
> Fix typo in XDReportManager

- open_xdmod/modules/xdmod/automated_tests/package-lock.json
- open_xdmod/modules/xdmod/automated_tests/package.json
- open_xdmod/modules/xdmod/automated_tests/runtests.sh
- open_xdmod/modules/xdmod/automated_tests/wdio.conf.js
This updates
* the dependencies needed for the automated tests
* selenium-standalone to a version that has chromedriver that works without issue on mac
* the title to match the directory name
> Automated test updates

- bin/xdmod-build-filter-lists
- bin/xdmod-ingestor
- docs/commands.md
add a build-filter-lists script  not currently used.  Will be used later.
> add build-filter-list

- classes/DB/Aggregators/JobTimeseriesAggregator.php
- classes/DB/FilterListBuilder.php
- classes/DB/TimePeriodGenerators/TimePeriodGenerator.php
- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByJobTime.php
- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByNodeCount.php
- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByProvider.php
- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByQueue.php
- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByResource.php
- classes/DataWarehouse/Query/Jobs/Raw.php
- classes/DataWarehouse/Query/Jobs/Statistics/ActiveResourceCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/JobCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/JobSizeWeightedByCPUHours.php
- classes/DataWarehouse/Query/Jobs/Statistics/MaxProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/MinProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/NodeUtilizationStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/NormalizedAverageProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageCPUHoursStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageNodeHoursStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageProcessorCountStatistic.php
This cleans up the files that are known to need editing for the future hpcdb-modw changes.
phpcfb was run as well as some other manual cleanup.
Should be 0 impact as this is formatting and readability changes only
> cleanup in prep for changes

- configuration/etl/etl_tables.d/storage/user_usage_by.aggregation.json
Fixes typo in database column comment defined in ETL configuration.
Having a comment with the proper text is preferable.
No tests.
> Fix typo in comment

- docs/databases.md
Updates manual database setup documentation.
There are commands that need to be run during the manual database setup that were not documented.
No tests.
> Add ACL commands to manual database setup docs

- tools/dev/manage_saved_charts.php
While creating a chart for a workload analysis I got into a situation where modifying the chart legend would not trigger a dirty state. This modification allows me to quickly update the chart legend and export the chart for the analysis.
XDMoD bug workaround.
Updated legend, exported chart.
> Add support for changing the legend of a chart data series

- open_xdmod/modules/xdmod/component_tests/lib/User/Roles/CenterDirectorRoleTest.php
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- Fixing the component tests (Acl related) so that they utilize the new
environment specific location for files that contain the expected results.
Not broken tests are good.
the tests?
> Fix Component Tests

- bin/xdmod-check-config
Changes the minimum requried version of PHP in `xdmod-check-config`.
This should have been included in #289 .
No tests.
> Update PHP version check

- docs/faq.md
- docs/software-requirements.md
Adds documentation regarding MySQL Server SQL Modes. (Strict modes are not supported.)
Multiple Open XDMoD users have reported issues with strict SQL modes and some vendors are shipping MySQL/MariaDB with these modes enabled by default.
No tests.
> Add MySQL Server SQL Modes documentation

- docs/commands.md
Adds the ACL commands to the list of commands.
Since this page exists, might as well keep it up to date.
No tests.
> Add ACL commands to command reference docs

- classes/ETL/Loggable.php
Check to be sure that an exception has been provided before trying to access it.
Bugfix
Ran tests
> Fix possible undefined variable access

- open_xdmod/modules/xdmod/automated_tests/package-lock.json
- open_xdmod/modules/xdmod/automated_tests/package.json
issues running tests on reference db seems related to https://github.com/webdriverio/webdriverio/pull/2424/files
This updates webdriverio and the chromedriver service to resolve the issue.
> update to allow tests to work

- classes/Models/Services/Acls.php
- classes/User/Roles/CenterDirectorRole.php
- classes/XDAdmin.php
- classes/XDUser.php
- configuration/portal_settings.ini
- html/controllers/user_admin/create_user.php
- html/controllers/user_admin/update_user.php
- html/gui/js/CCR.js
- html/internal_dashboard/js/admin_panel/AclGrid.js
- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- html/internal_dashboard/js/admin_panel/SectionNewUser.js
- open_xdmod/modules/xdmod/automated_tests/artifacts/.gitignore
- open_xdmod/modules/xdmod/automated_tests/artifacts/update-artifacts.sh
- open_xdmod/modules/xdmod/automated_tests/runtests.sh
- open_xdmod/modules/xdmod/automated_tests/test/helpers/artifacts.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/exportDialog.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/loginPage.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/reportGenerator.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/reportGenerator.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/usageTab.js
- open_xdmod/modules/xdmod/component_tests/bootstrap.php
- open_xdmod/modules/xdmod/component_tests/lib/Roles/CenterDirectorRoleTest.php
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- open_xdmod/modules/xdmod/component_tests/phpunit.xml.dist
- open_xdmod/modules/xdmod/component_tests/runtests.sh
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/TestFiles.php
- Actually added the code that handles processing / reporting when an acl
requires additional information to function properly. In particular, when an
acl requires a 'provider' ( center / service_provider ).
Kinda required.
Manual Tests:
- Spin up a the supremm docker image / install xdmod (this branch), appkernels, supremm / setup & ingest everything
- open a browser and point it at XDMoD / the internal dashboard
- behold, things be less broke then before.
> Handling acls that require centers to be provided

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- Forgot to add this in the last PR.
UI should report correct information to the user.
Manual Tests:
**Test 1:**
- Navigate to 'User Management' -> 'XDMoD Account Requests'
- Click 'Create & Manage Users'
- Select the 'Current Users' Tab
- Click on a few users in the default group ( 'Demo Users' ).
- Ensure that the Center Count displayed is correct
- Select the 'Internal Users' group
- Click on a few users and ensure that the Center Count is displayed correctly.
- Click 'Close'
- Click 'Create & Manage Users'
- Click around on a few more users and ensure that the Center Count is displayed correctly.
**Test 2:**
- Navigate to 'User Management' -> 'Existing Users' ->
- Click 'Create & Manage Users'
- Select the 'Current …
> Ensuring that the Center Count stays current

- open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
This is needed for easier support of multi environment / module regression tests.
> Force artifacts to be relative to test

- html/gui/lib/ie-object-values-polyfill.js
- html/index.php
- html/internal_dashboard/index.php
Internet Explorer ( non-Edge ) does not support `Object.values` so this
polyfill provides that functionality if it does not already exist.
It's nice to have all javascript methods used in an app to work in all supported browsers.
Manual Test in xdmod docker image
**Test 1:**
- Login to internal dashboard
- Navigate to 'User Management' -> 'Existing Users'
- Click 'Create & Manage Users'
- Select the 'New User' Tab
- Fill out the required information
- Click the 'Save' button
- The user should be successfully created
- *NOTE: on a docker instance an error will be returned as `sendmail` is not setup. But if you go to / refresh the 'Existing Users' tab then the newly created user will be present*
> Adding Object.values polyfill

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
This was originally in https://github.com/ubccr/xdmod/pull/388 but was removed as it was out of scope. This PR is so that the fix can be incorporated into the code base.
It's nice to not get into an infinite record is dirty loop
> PR for dirtySettings fix from xsede_to_federated

- html/controllers/user_admin/update_user.php
- The default center selection code in `create_users.php` needed to be added to
`update_users.php`.
- and because I closed the previous PR....
> Resolve issues w/ Updating users with center related acls

- classes/XDUser.php
- html/internal_dashboard/js/CurrentUsers.js
- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
i have no comments, I am to sad.[Your Code is bad](http://s2.quickmeme.com/img/29/292febc5ac05e551a651eacfa9ecf9eeeb1081e088ed0c3c1f7575e1eed90aaa.jpg)
> set make timestamps look the same

- html/internal_dashboard/js/UserStats.js
> switch xsede to federated

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
This file should not have been modified in commit 901185df91ee9868c6713081f6acc34e95512bf3. This restores the file to the previous version.
> Revert inccorect change in  901185df91ee9868c6713081f6acc34e95512bf3

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- Just adding some documentation to clarify what this block of code is doing.
Documentation is good.
N/A
> Adding some documentation

- composer.json
- composer.lock
- configuration/portal_settings.ini
- html/.eslintrc.json
- html/controllers/mailer/contact.php
- html/controllers/mailer/sign_up.php
- html/gui/js/CaptchaField.js
- html/gui/js/ContactDialog.js
- html/gui/js/SignUpDialog.js
- html/index.php
- html/recaptcha.php
- libraries/recaptcha.php
- libraries/utilities.php
- templates/portal_settings.template
> Revert "switching to captcha v2"

- bin/xdmod-slurm-helper
- docs/resource-manager-slurm.md
See title.
Due to the way slurm handles duplicate jobs, some jobs may be missing from `sacct` output unless this option is specified depending on when `sacct` was ran.
Ran `xdmod-slurm-helper`.
> Add `--duplicates` to list of `sacct` options

- classes/Models/Services/Centers.php
- A center is an organization that has a corresponding entry in resourcefact
Not sure why this didn't make it in one of the earlier PR, but it's still needed
> Update Centers::getCenters sql

- classes/ETL/Loggable.php
- classes/ETL/aRdbmsDestinationAction.php
- open_xdmod/modules/xdmod/tests/lib/ETL/SqlParser/SqlParserTest.php
Add a test for the SQL parser. Also
- Allow Loggable::setLogger() to accept a null argument and use the empty logger
- Improve handling of SQL reserved words such as DISTINCT
Test upgraded SQL parser
Ran existing test suite
> Add test for SQL parser

- html/about/presentations.html
- html/about/publications.html
- html/about/team.html
Update about pages.
Viewed in docker
> Update publications, presentations, and team

- configuration/cron.conf
- docs/configuration.md
- docs/install-source.md
- docs/upgrade.md
- open_xdmod/modules/xdmod/xdmod.spec.in
Changes RPM spec file to create an xdmod user and group.  Updates permissions and ownership of `portal_settings.ini`.  Updates documentation.
To improve security of files containing passwords.
Built and installed new RPM.
> Update RPM spec file, add xdmod user/group

- html/gui/js/SignUpDialog.js
Make spacing more consistent
view branch name for further explanation...
Before
After
> Updating styles to be more consistent

- open_xdmod/modules/xdmod/regression_tests/runtests.sh
make tests exit properly when failing...
> fix test runner to actually wait

- composer.json
- composer.lock
update composer to force version 5.4.16 instead of 5.3.3
> update php version

- composer.json
- composer.lock
Composer version now matches spec version
> Make composer match spec

- classes/DataWarehouse/Visualization/HighChart2.php
Resolves asana issue https://app.asana.com/0/159049597309611/559722007607298
See issue ticket for bug diagnosis and steps to reproduce.
> Only change series legend colour if the series has a legend

- html/gui/css/LoginPrompt.css
Before:
After:
Consistency is nice.
Yeah.
> Updated padding for forgot password form

- classes/ETL/Ingestor/pdoIngestor.php
As per discussion with @jpwhite4 we should be flushing the load file prior to calling `LOAD DATA INFILE` to ensure that all data is present on disk.
Data consistency.
Yes in local docker with OSG data.
> Flush data file before calling LOAD DATA INFILE

- docs/support.md
Adds 7.5 to the supported versions table.  Removes the old, now unsupported, versions.
> Update supported versions table

- html/gui/js/modules/Summary.js
- html/gui/js/modules/Usage.js
Pass timeframe label to Metric Explorer from the Usage and the Summary tabs. This enables the Metric Explorer Duration drop-down to display the correct timeframe (in addition to the already-correct start and end dates) on imported charts.
Old (Previous Month chart imported with default duration display):
New (Previous Month chart imported with proper duration display):
In Metric Explorer, the Duration drop-down was improperly populated with the default value on import of charts from Usage or Summary tabs. This change corrects this behavior.
Issue is described here:
https://app.asana.com/0/inbox/14787510600561/564173274039902/564478888587652
This change is very lightweight in that it affects only the display of the control; It also does not affect other areas of the code. However, the …
> Fix display of duration label on chart import to Metric Explorer

- etl/js/lib/schema.js
Need to be able to specify a table alias for the derived queries.
> Update the js etl library to support specifying table aliases

- configuration/etl/etl.d/hpcdb-modw.json
- configuration/etl/etl_tables.d/hpcdb-modw/jobhosts.json
- configuration/etl/etl_tables.d/hpcdb-modw/system-account.json
- configuration/etl/etl_tables.d/xdmod/field-of-science.json
- configuration/etl/etl_tables.d/xdmod/job-tasks.json
> Fixes for hpcdb-modw conversion

- bin/xdmod-ingestor
- classes/OpenXdmod/Migration/Version750To800/DatabasesMigration.php
- configuration/etl/etl_tables.d/hpcdb-modw/job_record_hpc.json
- configuration/etl/etl_tables.d/xdmod/system-account.json
- db/migrations/7.5.0-8.0.0/modw.sql
> Hpcdb modw fixes v2

- configuration/etl/etl_tables.d/hpcdb-modw/job_record_hpc.json
- configuration/etl/etl_tables.d/xdmod/job-tasks.json
> items needed for job performance data

- docs/index.md
Add "how to cite Open XDMoD" to home page.
> Add Open XDMoD citation information

- docs/index.md
Add "how to cite Open XDMoD" to home page. Making this change to 7.5 so it makes it into the current online docs.
> Add Open XDMoD citation information for 7.5

- configuration/etl/etl_tables.d/xdmod/job-tasks.json
Some of the performance is slow, lets add some of the indexes back that are needed for some of the processes
> Add indexes to job_tasks

- bin/acl-config
- bin/xdmod-ingestor
- classes/OpenXdmod/Migration/Version750To800/DatabasesMigration.php
- classes/OpenXdmod/Setup/AclEtl.php
- classes/OpenXdmod/Setup/AclImport.php
- classes/OpenXdmod/Setup/DatabaseSetup.php
- docs/storage.md
- tools/etl/dump_database_table_definition.sh
- tools/etl/etl_action_state_mgr.php
- tools/etl/etl_overseer.php
- tools/etl/etl_table_manager.php
sane defaults make life easier
> default etl config file for ease of use

- docs/install-source.md
> Fix doc typo chmod -> chown

- tools/dev/verify_table_data.php
Allow mapping of column names between the source and destination tables. This is useful in cases where columns have been renamed. For example: `php verify_table_data.php -v debug -s modw_aggregates -d modw_aggregates_test -t jobfact_by_day -m job_count=ended_job_count` .
Make @plessbd's life easier. And he bribed me with chocolate.
Manual testing.
> Add support for mapping column names between tables

- configuration/etl/etl_data.d/xdmod/resource-type.json
> update resource defaults

- html/gui/js/modules/Summary.js
When testing functionality no related to having aggregated or ingested data it is helpful to be able to continue pas the error message shown.
using server with invalid database schema verified that after hitting the ok button that the mask is removed and allowed me to interact.
> remove mask after error acknowledgement

- composer.json
- composer.lock
- docs/simpleSAMLphp.md
- docs/software-requirements.md
- open_xdmod/modules/xdmod/integration_tests/scripts/samlSetup.sh
- open_xdmod/modules/xdmod/xdmod.spec.in
- shippable.yml
Updates the simplesamlphp dependency
> Fix for CVE-2018-6519/CVE-2018-7644/CVE-2018-7711

- classes/XDUser.php
- composer.json
- composer.lock
- db/migrations/7.5.0-8.0.0/moddb.sql
- db/schema/moddb.sql
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
See asana issue https://app.asana.com/0/14740318781081/578673499549601
redo of #449
> Use stronger password hashing algorithm.

- configuration/etl/etl_data.d/jobs/job_task_type.json
Add dimension for job array task
Tested as part of ubccr/xdmod-xsede#89
> Add dimension for job array task

- classes/ETL/DbModel/Trigger.php
- tools/dev/verify_table_data.php
Case insensitive search for trigger BEGIN. Also fix output in table verifier.
@plessbd found a bug when using lowercase in trigger body definition.
> Case insensitive search for trigger BEGIN

- configuration/etl/etl.d/jobs_common.json
Chang the source and destination data endpoints from `modw_cloud` to `modw` for common jobs tables.
> Change destination to modw for common jobs tables

- html/index.php
Mostly just re-formatting to fit the current style guide. There was one line added to ensure that the `CCR.xdmod.ui.mappedPName` property was properly encoded before outputting it to javascript. 
Encountered a Person name that included a `'` character. This broke the population of javascript properties in `index.php`. To resolve this problem the `rawurlencode` function was added to the affected data ( `rawurlencode` was used so that spaces were encoded to spaces as opposed to `+` which is how `urlencode` functions. ). 
Manual Tests were performed 
- Associate a user with a person who has a `'` in their name.  
- Log in as that user
- Notice that the page does not load successfully
- clear the browser cookies
- Make the functional changes from this PR
- Log in as the user
- Notice that the …
> rawurlencode person name to avoid breaking XDMoD

- bin/xdmod-admin
Update `xdmod-admin` to truncate `modw.job_records` and `modw.job_tasks` in place of `modw.jobfacts` based on `xdmod-upgrade` output that `modw.jobfacts` is replaced by those two tables.
To get truncating working on new tables.
Ran truncation on test data in docker:
```shell
[root@4b309869edcc xdmod]# xdmod-admin -t -j -v --debug
2018-04-19 16:58:07 [info] Command: '/usr/bin/xdmod-admin' '-t' '-j' '-v' '--debug'
Truncate all job data? (yes/no): [no] yes
2018-04-19 16:58:08 [notice] Truncating job data
2018-04-19 16:58:08 [info] Truncating job tables in mod_shredder
2018-04-19 16:58:08 [info] Truncating shredded_job_pbs
2018-04-19 16:58:08 [info] Truncating shredded_job_sge
2018-04-19 16:58:08 [info] Truncating shredded_job_slurm
2018-04-19 16:58:08 [info] Truncating shredded_job_lsf …
```
> Update xdmod-admin truncate to operate on tables that replaced modw.jobfacts

- html/about/publications.html
Update XDMoD publications based on Tom's list.
> Update XDMoD related publications

- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UserAdminTest.php
- open_xdmod/modules/xdmod/integration_tests/runtests.sh
- shippable.yml
* update integration tests to fail on error of either group
* separate output files
* make Get Menus message easier to read
> Fix integration tests

- classes/ETL/Aggregator/pdoAggregator.php
- classes/ETL/DbModel/Entity.php
- classes/ETL/Ingestor/RestIngestor.php
- tools/etl/etl_overseer.php
Various minor bugfixes:
- Fix chunk size in argument processing
- Fix log warning for actions that don't support multiple destination tables 
- Move log message from debug() to trace() level
Ran unit and component tests.
> Various minor bugfixes

- classes/ETL/Maintenance/VerifyDatabase.php
Fix cut-and-paste error on 3rd argument.
> Fix bad cut-and-paste

- _config.yml
- _includes/google_analytics.html
> Add google analytics tracking

- _config.yml
- _includes/google_analytics.html
This reverts commit cffac8c8427a4212a7465fd752d7e23c8cd915ae.
> Revert "Add google analytics tracking"

- configuration/etl/etl_tables.d/jobs/xdw/job-tasks.json
local_jobid should be an int(11) not a string
> Fix column type for the local_jobid column.

- classes/ETL/Aggregator/JobListAggregator.php
#525 changed the name of the function in the parent class but ignored the child class.
> Fix regression bug introduced in #525

- bin/acl-config
- classes/Xdmod/Config.php
- open_xdmod/modules/xdmod/tests/lib/Xdmod/ConfigTest.php
Just backporting the changes from PR 510 to xdmod7.5
Because the functionality is required for xdmod-va
> Backport PR 510

- CHANGELOG.md
- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version750To751/ConfigFilesMigration.php
- classes/OpenXdmod/Migration/Version750To751/DatabasesMigration.php
- configuration/portal_settings.ini
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
> Preparation for 7.5.1 release

- html/.eslintrc.json
- html/js_classes/DateUtilities.js
Bug fix.
The start date of calendar quarters was being calculated incorrectly if the current day of the month is not in the previous month (e.g. 31 May since April only has 30 days).
No new tests.
> Fix calendar quarter calculation

- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/SSOLogin.js
- open_xdmod/modules/xdmod/integration_tests/scripts/samlSetup.sh
sipmlesaml-idp updated the action that triggers a sign on so the test needed to
be updated.
Updated the expected sign in form action for the SSO tests.
This change was necessary because of this change in the saml-idp repo (https://github.com/mcguinness/saml-idp/commit/03d6ca053dd6b1278c75ce7e1e762ff7912fe8a1) 
The saml tests were re-run after the modification was made.
> Updating sso login form action

- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/BaseUserAdminTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/ControllerTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UserAdminTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/PeopleHelper.php
- shippable.yml
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/input/create_users.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/user_quick_filters-update_enumAllAvailableRoles.json
Removes person ID values from test data and updates corresponding tests.
These person ID values are not guaranteed to remain the same.  Future ETL changes may result in changes to auto-generated database keys.
> Remove person ID values from test data

- classes/DataWarehouse/Access/Usage.php
- This bit of code should not have been introduced, reverting it to it's
previous contents.
Because having things that work is nice.
- [X ] Bug fix (non-breaking change which fixes an issue)
> Reverting unintended changes to Usage

- classes/ETL/LockFile.php
Improve the error message if the lock directory exists and is actually a file.
> Improve error message if lock directory exists and is a file

- configuration/etl/etl_tables.d/jobs/xdw/job-records.json
- configuration/etl/etl_tables.d/jobs/xdw/job-tasks.json
Update the column definitions for foreign key columns to match the column type of the column that they are the foreign key for.
> Fix the schema definitions to be the correct datatypes

- configuration/etl/etl_data.d/jobs/xdw/error-descriptions.json
- etl/js/lib/metric_errors.js
Update the text of the error messages that can be reported by the js based etl framework. Add a coupld of new messages too.
Also run eslint --fix on the js file so that it confirms to the code standards.
> Update the error messages

- classes/ETL/Ingestor/StateReconstructorTransformIngestor.php
Reverts ubccr/xdmod#590
I must have hit the wrong button
> Revert "Enable User Defined Default Times"

- classes/CCR/DB/PostgresDB.php
Postgres supports an optional `application_name` connection parameter. Add this so XDMoD sessions can more easily be identified.
Improved debugging
Manual testing.
> Specify optional postgres application name

- classes/OpenXdmod/Migration/Version560To600/DatabasesMigration.php
- classes/Rest/Controllers/AuthenticationControllerProvider.php
- classes/Rest/Controllers/BaseControllerProvider.php
- classes/Rest/Controllers/LegacyControllerProvider.php
- classes/Rest/Controllers/MetricExplorerControllerProvider.php
- classes/Rest/Controllers/SummaryStatisticsControllerProvider.php
- classes/Rest/Controllers/UserControllerProvider.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- classes/Rest/RestFacade.php
- classes/Rest/Utilities/Authentication.php
- classes/Rest/Utilities/Conversions.php
- classes/Rest/XdmodApplicationFactory.php
- configuration/rest.d/authentication.json
- configuration/rest.d/metric_explorer.json
- configuration/rest.d/summary_statistics.json
- configuration/rest.d/user.json
- configuration/rest.d/warehouse.json
- configuration/rest.d/z_legacy.json
- docs/modules.md
- html/report_image_renderer.php
- html/rest/index.php
- open_xdmod/modules/xdmod/tests/lib/NewRest/Controllers/BaseControllerTest.php
Just renaming the NewRest namespace to Rest. Some additional cleanup was performed on some of the files that were moved so that the style checks would pass. 
NOTE: There will be PR's in both appkernels and xsede that will need to be merged when this goes in as well.
No reason to have `NewRest` anymore as we've already migrated everything in the old `Rest`. 
All unit, component, integration and regression tests were run and passed.
> Rename NewRest -> Rest

- configuration/etl/etl_action_defs.d/common/hpcdb/resources.json
- open_xdmod/modules/xdmod/integration_tests/lib/Database/ResourceNamesTest.php
- tests/artifacts/xdmod-test-artifacts/xdmod/integration/database/output/resource_names.json
Changes the field used for the resource name (not code).
Fixes regression introduced in #596 .
Added new test to check expected values in database.
> Fix resource name regression

- classes/ETL/Configuration/EtlConfiguration.php
- classes/ETL/EtlOverseer.php
- classes/ETL/Ingestor/pdoIngestor.php
- classes/ETL/aAction.php
Correct a bug where an uninitialized variable was being used to check whether or not to initialize the mapping between resource codes and ids, causing the map to never load and ingestion to fail. Also corrected an issue where a disabled action had a subset of of its configuration options set, which caused an issue when creating the action object.
Improved logging of source and destination endpoints.
Bugfix and improved logging.
Tested manually in docker.
> Fix loading of resource code to id mapping

- configuration/etl/etl_action_defs.d/common/hpcdb/resources.json
- open_xdmod/modules/xdmod/integration_tests/lib/Database/SharedJobsTest.php
- tests/artifacts/xdmod-test-artifacts/xdmod/integration/database/output/shared_jobs.json
Changes default value for the resource shared jobs option.
Fixes regression introduced in #596 .
Added new test to check expected values in database.
> Fix "shared_jobs" regression

- docs/configuration.md
Adds some documentation about shared jobs in the resource configuration file.
This isn't documented anywhere else.
> Add "shared_jobs" documentation

- classes/ETL/aRdbmsDestinationAction.php
When building the ETL destination field maps, the current code generates a warning if a given table does not map all available source fields. When populating more than one table from the same source query this is not desirable. Instead, we want to be warned only when a source field is not mapped to any of the tables.
Improved logging.
> Check for unmapped fields globally over all tables

- bin/acl-config
- classes/Models/Services/Acls.php
- configuration/etl/etl_action_defs.d/cloud_common/initialize_unknown_dimension_values.json
- configuration/etl/etl_tables.d/acls/modules.json
- configuration/etl/etl_tables.d/jobs/xdw/account.json
**This is related to ubccr/xdmod-xsede#116**
MySQL 5.7 sets `sql_mode` to `ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION` by default. This has caused several errors in the ingestion process. Rather than simply remove the restrictions and let MySQL convert the data as it sees fit, I changed `sql_mode='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'` and attempted to make changes to the ingest queries so that we manage the conversions ourselves.
However, in the end I set `sql_mode=''` because the solution to ingesting [ISO 8601 dates](https://en.wikipedia.org/wiki/ISO_8601) (e.g., "2018-12-01T01:01:50.592558+05:00") from the cloud log data files would require that the date be ingested …
> Improve data sanitization for tighter checks in MySQL 5.7

- classes/CCR/Loggable.php
- classes/Configuration/CommentTransformer.php
- classes/Configuration/Configuration.php
- classes/Configuration/JsonReferenceTransformer.php
- classes/Configuration/iConfigFileKeyTransformer.php
- classes/ETL/Configuration/EtlConfiguration.php
- classes/ETL/DbModel/Entity.php
- classes/ETL/DbModel/SchemaEntity.php
- classes/ETL/EtlOverseer.php
- classes/ETL/EtlOverseerOptions.php
- classes/ETL/JsonPointer.php
- classes/ETL/LockFile.php
- classes/ETL/Maintenance/ManageTables.php
- classes/ETL/State/ActionState.php
- classes/ETL/Utilities.php
- classes/ETL/VariableStore.php
- classes/ETL/aAction.php
- classes/ETL/aEtlObject.php
- classes/XDUser.php
- open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/ConfigurationTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/Rfc6901Test.php
- open_xdmod/modules/xdmod/tests/lib/ETL/JsonPointer/JsonPointerTest.php
- Migrating various ETL classes into CCR's namespace so that they can be used
other portions of CCR's code.
- Updated references to these classes so that they point at their new locations.
We'd like to use some of the code in ETL in the rest of CCR's code ( Configuration / Loggable )
- Unit Tests
- Component Tests
- Integration Tests
- UI Tests
> Migrating Select ETL code into CCR's namespace

- docs/configuration.md
Add the resource type information to our documentation.
> Add resource type information to docs

- configuration/logrotate.conf
Updates the logrotate configuration to use the `su` and `create` options.   These are necessary due to the permissions on the log directory.
The current logrotate configuration produces error messages. See #455 for more details.
> Update logrotate configuration

- configuration/etl/etl_action_defs.d/common/hpcdb/resource-specs.json
Changes resource specs ingestion so that rows are inserted in the resource specification table only if a resource has data in `resource_specs.json`.
Inserting rows into the resources specs table without node and core counts generates warnings.  e.g.:
```
2018-08-15 04:08:17 [warning] SQL warnings on table '`mod_hpcdb`.`hpcdb_resource_specs`' generated by action xdmod.hpcdb-ingest-common.resource-specs
2018-08-15 04:08:17 [warning] Warning 1048 Column 'node_count' cannot be null
2018-08-15 04:08:17 [warning] Warning 1048 Column 'cpu_count' cannot be null
2018-08-15 04:08:17 [warning] Warning 1048 Column 'cpu_count_per_node' cannot be null
2018-08-15 04:08:17 [warning] Warning 1048 Column 'node_count' cannot be null
2018-08-15 04:08:17 [warning] Warning 1048 Column 'cpu_count' cannot be …
```
> Update resource specification ETL

- open_xdmod/modules/xdmod/component_tests/runtests.sh
Renamed the test suites in the component tests without changing the script.
So the tests actually run.
See above.
> Updated Component Tests to Properly Run

- docs/simpleSAMLphp.md
Initial commit for adding documentation about the `organization` saml property.
Documentation good.
> Updating the SSO documentation with `organization` property

- configuration/etl/etl.d/staging.json
- docs/storage.md
Replace hard-coded storage log file directory source path with ETL variable.
It is desirable to allow users to specify the directory used for storage data instead of forcing them to use a specific directory.
> Change storage source directory path

- classes/OpenXdmod/Setup/ResourcesSetup.php
Replaces cloud specific functions with generic ones.  Addresses feedback from #635 and #656 .
Changes were requested to #656 that are better addressed separately.
> Make resource setup roles changes more generic

- classes/OpenXdmod/Setup/ResourcesSetup.php
Fix bug in #658 .
Not sure how it passed before, but tests are now failing.
> Fix resource setup

- configuration/etl/etl.d/xdmod-migration-7_5_1-8_0_0.json
- configuration/etl/etl_sql.d/migrations/7.5.1-8.0.0/hpcdb/truncate-email-addresses.sql
Adds truncation of HPCDB email addresses table to migration for 8.0.0.
Fixes issue created by #625 
Tested manually and ran automated tests.
> Add migration to remove old, incorrect, data

- classes/Authentication/SAML/XDSamlAuthentication.php
- classes/Rest/Controllers/AuthenticationControllerProvider.php
- html/gui/general/login.php
- html/gui/js/CCR.js
- html/index.php
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/SSOLogin.js
Deep linking into XDMoD is broken when you login via SSO. This fixes it.
> Fix SSO redirects

- composer.json
Update to latest release of Globus Auth Module.
Contains a SAML attribute bugfix.
> Use latest Globus plugin

- docs/_includes/menu.md
- docs/storage.md
Adds more storage documentation.
> Improve storage documentation

- composer.json
- composer.lock
Behold, the new Globus module. Now actually with composer lockfile updated.
Because we forgot to do it last time.
> Properly updated composer lockfile

- classes/OpenXdmod/Migration/Version751To800/ConfigFilesMigration.php
- classes/OpenXdmod/Setup/GeneralSetup.php
- classes/XDUser.php
- composer.json
- composer.lock
- configuration/constants.php
- configuration/portal_settings.ini
- html/controllers/user_admin/create_user.php
- html/controllers/user_admin/pass_reset.php
- html/controllers/user_auth/pass_reset.php
- html/password_reset.php
- open_xdmod/modules/xdmod/component_tests/lib/RIDTest.php
- templates/portal_settings.template
Harden the password reset process.
**NOTE:** When testing this change it is important to look at emails generated during user creation, triggering a password reset via the internal dashboard, and login -> 'Forgot password'. 
MD5 can be brute forced fairly easily in the time before the link is expired. We now use SHA256 to calculate the hashes.
Manual Testing via docker
> Hardening Password Reset Process

- configuration/etl/etl_sql.d/cloud_eucalyptus/post_ingest_updates.sql
These are internal things that should not be here.
> Removed internal things that shouldnt be part of public release

- etl/js/lib/dataset_processor.js
By code inspection there is a race condition on the currentlyProcessing counter that could result in the process exiting before all documents have been processed.
> Fix premature end bug in etl

- html/about/presentations.html
- html/about/publications.html
- html/about/release_notes/xdmod.html
Update publications, presentations, and release notes for 8.0
Reviewed by Bob & Jeanette.
> Update pubs, presentations, release notes

- classes/DataWarehouse/Query/Storage/GroupBys/GroupByNSFDirectorate.php
Restores unintentionally removed function.
The top-level hierarchy group by was broken.  This fixes that issue.
Tested manually on development server.
> Fix Storage Top-Level Hierarchy Group By

- classes/Authentication/SAML/XDSamlAuthentication.php
- classes/Rest/Controllers/AuthenticationControllerProvider.php
- html/controllers/user_admin/create_user.php
- html/controllers/user_admin/update_user.php
- html/internal_dashboard/js/AccountRequests.js
- html/internal_dashboard/js/CurrentUsers.js
- html/internal_dashboard/js/Summary/TabPanel.js
- html/internal_dashboard/js/admin_panel/AdminPanel.js
- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- html/internal_dashboard/js/admin_panel/SectionNewUser.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/internalDashboard.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/internalDashboard.page.js
- tests/artifacts/xdmod-test-artifacts/xdmod/automated_tests/output/internalDashboard.json
- create_user.php: 
- The organization associated with the newly created user was solely based off of the person they were mapped to. The organization and person mappings are now independent of each other. 
- update_user.php
- The organization associated with the user to be updated was solely based off of the person they were mapped to. The organization and person mappings are now independent.
- TGUserDropDown.js
- If there is a callback specified, it should be called. Regardless of whether or not the value has changed.
- SectionExistingUsers.js
- Ensure that when the 'Unknown' person is mapped that the institution drop down is enabled for manual override.
- SectionNewUser.js
- Ensure that when the 'Unknown' person is mapped that the institution drop down is enabled for manual override. …
> Unlock org for unknown person

- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/SSOLoginTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/XdmodTestHelper.php
- open_xdmod/modules/xdmod/integration_tests/phpunit.xml.dist
- open_xdmod/modules/xdmod/integration_tests/runtests.sh
- shippable.yml
Now we have the capabilty to reliably test the SSO login procedure. This will support the work in #692
> Add SSO integration tests

- configuration/etl/etl_tables.d/acls/acl_group_bys.json
- configuration/etl/etl_tables.d/acls/acl_hierarchies.json
- configuration/etl/etl_tables.d/acls/acl_tabs.json
- configuration/etl/etl_tables.d/acls/acl_types.json
- configuration/etl/etl_tables.d/acls/acls.json
- configuration/etl/etl_tables.d/acls/group_bys.json
- configuration/etl/etl_tables.d/acls/hierarchies.json
- configuration/etl/etl_tables.d/acls/realms.json
- configuration/etl/etl_tables.d/acls/statistics.json
- configuration/etl/etl_tables.d/acls/tabs.json
- configuration/etl/etl_tables.d/acls/user_acl_group_by_parameters.json
- configuration/etl/etl_tables.d/acls/user_acls.json
Add FK's to the acl related tables.
Now that we have support for FK's the acl related tables should be updated.
All automated tests: Unit, Component, Integration, UI
> Adding foreign keys / unique indexes for acl* tables

- classes/CCR/DB/MySQLHelper.php
Specifically adding references to list of permissions as now that the etl supports foreign keys this permission is required.
Added a few more that probably should have been in there as well.
> Update Database Privileges

- classes/ETL/DbModel/ForeignKeyConstraint.php
- classes/ETL/DbModel/Table.php
- configuration/etl/etl_tables.d/acls/acl_group_bys.json
- configuration/etl/etl_tables.d/acls/acl_hierarchies.json
- configuration/etl/etl_tables.d/acls/acl_tabs.json
- configuration/etl/etl_tables.d/acls/acl_types.json
- configuration/etl/etl_tables.d/acls/acls.json
- configuration/etl/etl_tables.d/acls/group_bys.json
- configuration/etl/etl_tables.d/acls/hierarchies.json
- configuration/etl/etl_tables.d/acls/realms.json
- configuration/etl/etl_tables.d/acls/statistics.json
- configuration/etl/etl_tables.d/acls/tabs.json
- configuration/etl/etl_tables.d/acls/user_acl_group_by_parameters.json
- configuration/etl/etl_tables.d/acls/user_acls.json
- open_xdmod/modules/xdmod/tests/lib/ETL/DbModel/DbModelTest.php
- tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/dbmodel/input/table_def-charset.json
- tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/dbmodel/output/table_def-charset.sql
- Add an index for each ACL foreign key constraint
- Add verification that each foreign key constraint has a corresponding index
- Fix comparison function to correctly check "ON DELETE" and "ON UPDATE" operations
First time some ETL actions would run everything would work properly.  Subsequent runs would produce errors due to attempts to modify tables that shouldn't be modified.
Added new unit tests.
> Fix foreign key constraints

- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByNSFDirectorate.php
- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByParentScience.php
- classes/DataWarehouse/Query/Storage/GroupBys/GroupByNSFDirectorate.php
- classes/DataWarehouse/Query/Storage/GroupBys/GroupByParentScience.php
Changes column used in joins by NSF Directorate and Parent Science Group By classes.  Note that this function has been moved to the parent class for the storage classes.
Incorrectly joining on these columns breaks the "remainder" feature in the metric explorer.
> Fix "Group By" joins

- CHANGELOG.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/xdmod.spec.in
> Update release notes and changelog for 8.0

- docs/software-requirements.md
Changes Java 7 to Java 8.
The Java requirement was changed in a previous version, but this documentation was not updated.
No tests.
> Update Java version in RPM list

- classes/OpenXdmod/Migration/Version800To810/DatabasesMigration.php
Needed for https://github.com/ubccr/xdmod-supremm/pull/139
> Add boilerplate migration code.

- configuration/etl/etl_tables.d/cloud_common/event.json
Ran into some issues with the cloud tables when doing the cloud federation, fixing them up a bit...
> Fix some indexes in the cloud

- configuration/etl/etl_action_defs.d/cloud_common/cloud_transient.json
- configuration/etl/etl_tables.d/cloud_common/cloud_transient.json
- configuration/etl/etl_tables.d/cloud_common/event.json
Removed start event ids from the cloud transient table. Also made the wallduration datatype consistent between transient and aggregate tables.
Event ids are no longer part of any unique constraints.
Made sure the existing numbers weren't changed.
> Remove unused columns

- bin/xdmod-ingestor
These should have been added when the options were added, but they were not, and I need to keep reminding myself what they are, so I added some help.
> Update with some of the options that are avalbile

- classes/ETL/Maintenance/VerifyDatabase.php
Add proper namespace `ETL\Utilities`.
> Add proper namespace

- open_xdmod/modules/xdmod/build.json
Accidentally removed these in #815
> Restore gray images

- classes/ETL/Ingestor/CloudStateReconstructorTransformIngestor.php
- configuration/etl/etl_action_defs.d/cloud_common/cloud_state.json
- configuration/etl/etl_action_defs.d/cloud_common/cloud_transient.json
- configuration/etl/etl_action_defs.d/cloud_generic/event.json
- configuration/etl/etl_action_defs.d/cloud_generic/event_asset.json
- configuration/etl/etl_action_defs.d/cloud_generic/instance_data.json
- configuration/etl/etl_action_defs.d/cloud_generic/ip_address.json
- configuration/etl/etl_action_defs.d/cloud_generic/root_volume.json
- configuration/etl/etl_action_defs.d/cloud_generic/staging_event.json
- configuration/etl/etl_action_defs.d/cloud_generic/volume.json
- configuration/etl/etl_action_defs.d/cloud_openstack/event.json
- configuration/etl/etl_action_defs.d/cloud_openstack/event_asset.json
- configuration/etl/etl_action_defs.d/cloud_openstack/instance_data.json
- configuration/etl/etl_action_defs.d/cloud_openstack/root_volume.json
- configuration/etl/etl_action_defs.d/cloud_openstack/staging_event.json
- configuration/etl/etl_action_defs.d/cloud_openstack/volume.json
- configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
- configuration/etl/etl_tables.d/cloud_common/asset.json
- configuration/etl/etl_tables.d/cloud_common/event.json
- configuration/etl/etl_tables.d/cloud_common/event_reconstructed.json
- configuration/etl/etl_tables.d/cloud_generic/staging_event.json
- configuration/etl/etl_tables.d/cloud_openstack/raw_volume.json
- configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
- open_xdmod/modules/xdmod/component_tests/lib/ETL/CloudStateReconstructorTransformIngestorTest.php
- tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_action_defs_8.0.0.d/cloud_state.json
Update column names to be more descriptive of the data within
> Change column names in cloud realm

- classes/Rest/Controllers/WarehouseControllerProvider.php
This change was incorrectly ommited in #733.
Tests will be added to the xdmod-supremm repo to check this code path
> Fix regression in getJobDataSet introduced in #733

- classes/Configuration/Configuration.php
These functions allow us to remove a good deal of the boilerplate that was
involved w/ replacing the old `Config` code w/ `Configuration` code.
Less boilerplate is good
We're just adding new functions, not actually using them yet. Any additional testing will be addressed when they are used.
> Adding factory helper methods

- classes/Configuration/Configuration.php
- classes/Models/Services/Tabs.php
- classes/User/Roles.php
- html/controllers/ui_data/summary3.php
> Feature branch merge

- configuration/etl/etl_tables.d/cloud_common/event.json
removing event_id from the event table primary key
All tests pass and tested manually in docker
> removing event_id from the event table primary key

- classes/Rest/Controllers/WarehouseControllerProvider.php
Regression introduced in #818 and found by automated testing in the xdmod-supremm module.
> Fix regression from #818

- classes/Rest/Controllers/SummaryControllerProvider.php
Changes needed as a consequence of #840
> Update SummaryController to work with new config code from #840

- configuration/etl/etl.d/cloud_state_machine.json
- tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_8.0.0.d/cloud_state_test_config.json
remove cloud-transient for reals
> Remove reference to cloud-transient in two more places

- docs/faq.md
Just update the documentation for clarity.
> Update broken url and change wording of supported software

- classes/OpenXdmod/Setup/ResourcesSetup.php
Didnt correctly update the function I was trying to fix in #878
> Fix invalid comparison

- classes/Configuration/ModuleConfiguration.php
> only process extends for non local config files (#885)

- docs/upgrade.md
Updates the upgrade guide for 8.1.0 and removes upgrade notes for old versions.  Now that we have versioned documentation those are no longer necessary.
The documentation needs to be updated before every new release.
> Update upgrade guide for 8.1.0

- docs/simpleSAMLphp.md
Clarifying the SAML docs a bit.
> Update SAML ocs to be a bit more clear

- CHANGELOG.md
- docs/support.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/xdmod.spec.in
> Update dates for release

- classes/OpenXdmod/Migration/Version800To810/DatabasesMigration.php
the $dwi->isRealmEnabled('Cloud') doesnt do what it seems like it shoud.
> Fix upgrade when cloud does not exist

- CHANGELOG.md
- bin/xdmod-upgrade
- configuration/portal_settings.ini
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
> Version 8.1.1 updates

- docs/storage.md
Updates command example that included `acl-import`.
> Remove reference to acl-import

- classes/OpenXdmod/Migration/Version810To811/ConfigFilesMigration.php
- classes/OpenXdmod/Migration/Version811To812/ConfigFilesMigration.php
- open_xdmod/modules/xdmod/integration_tests/lib/Configuration/VersionNumberTest.php
Adds migrations to update the version number in `portal_settings.ini`.
This version number is used by the upgrade system so it is important that the version number in `portal_settings.ini` is the same as the version of Open XDMoD that has been installed.
Added a test to compare the version number in `build.json` with the version number in the installed (or upgraded) `portal_settings.ini`.
> Add configuration file migrations and test

- CHANGELOG.md
- bin/xdmod-upgrade
- configuration/portal_settings.ini
- docs/upgrade.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
> 8.1.2 release

- classes/DataWarehouse/Query/Query.php
Adding some date validation in the `Query` class. Previously it was not an error case to have a start date that occurred after an end date.
We keep users from submitting requests w/ these wonky kinda dates on the front end but we weren't also handling them on the back end. 
Manual testing was performed. But it should be noted that some additional tests that exercise this code are present in #911
> Adding some backend date validation

- docs/_data/toc.yml
- docs/hardware-requirements.md
Adds hardware requirements documentation and updates documentation menu.
This will hopefully people from asking us what the hardware requirements are.  And if they do ask we can point them to this page.
No tests.
> Add hardware requirements documentation

- docs/faq.md
This should have been included in #922
> Update hardware requirements FAQ

- tests/ci/Docker/Dockerfile
- tests/ci/Docker/Dockerfile.centos7:xdmod-base
- tests/ci/Docker/assets/copy-caches.sh
- tests/ci/Docker/assets/google-chrome.repo
- tests/ci/Docker/assets/mysql-server.cnf
- tests/ci/Docker/assets/npmrc
- tests/ci/Docker/bin/buildrpm
- tests/ci/Docker/bin/mariadb-wait-ready
- tests/ci/Docker/bin/services
- tests/ci/Docker/bin/services-replication
- tests/ci/Docker/bin/setup.php
- tests/ci/README.md
Since these don't need to be private, we can have them out there for everyone to see and use at their own discretion.
> Add Dockerfiles used for test builds

- tests/artifacts/xdmod/etlv2/configuration/input/etl_8.0.0.d/structured_file.json
- tests/artifacts/xdmod/etlv2/configuration/input/etl_action_defs_8.0.0.d/structured_file/organizations.json
- tests/artifacts/xdmod/etlv2/configuration/input/etl_action_defs_8.0.0.d/structured_file/people.json
- tests/artifacts/xdmod/etlv2/configuration/input/etl_data.d/structured_file/people.json
- tests/artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/structured_file/organizations.json
- tests/artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/structured_file/people.json
- tests/component/lib/ETL/IngestorTest.php
Add a test that reads the same structured file input multiple times to ensure that the file is properly rewound.
Preparation for future work.
Yes
> Add structured file test to re-read same file multiple times

- classes/Rest/Controllers/WarehouseControllerProvider.php
- tests/integration/lib/Rest/JobViewerTest.php
update the job viewer search endpoint so that it is permissible to run a search with no extra
filters.
This change is needed for the novice user JobPortal. This will run a filterless search which will
return all jobs that the user has access to.
Added a load of extra tests to make sure the input data are validated and added a test for the no parameter case.
> Allow search to be run without extra parameters

- classes/Configuration/Configuration.php
- tests/unit/lib/ETL/Configuration/ConfigurationTest.php
Cached `Configuration` objects were previously invalidated if the max last modified time of a config file found on the filesystem was greater than that found in the cache. This did not take into account restoring of backup files, which will have an _older_ last modified time. The new code checks to see if _any_ last modified time has changed and invalidates the cached object if this is the case.
The PHP stat cache is also cleared so changes are available immediately, although `stat()` only supports 1-second granularity so we may need to `sleep(1)` during tests or modify the timestamp accordingly via `touch()`.
Improve cache invalidation.
Yes
> Improve mechanism to invalidate cached objects

- classes/DataWarehouse/Realm/iGroupBy.php
- classes/DataWarehouse/Realm/iRealm.php
- classes/DataWarehouse/Realm/iStatistic.php
Initial interfaces for Realm, GroupBy, and Statistic.
> Initial set of interface specifications

- configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
The has to happen at aggregation time.
> Don't migrate the aggregate table.

- classes/CCR/ColumnLayout.php
- classes/Rest/Controllers/SummaryControllerProvider.php
- configuration/roles.d/summary.json
- docs/novice_user.md
Also updated the documentation and set sensible defaults for the
portlets.
> Added default layout configuration options.

- html/gui/js/modules/NoviceUser.js
- html/index.php
As per UI design meeting.
Also tone down the brightness of the side space to make it more
obvious that it is not part of the interactive display.
> Fix summary page to two columns.

- classes/Rest/Controllers/SummaryControllerProvider.php
- configuration/assets.json
- configuration/etl/etl_data.d/xdb/report-templates.json
- html/gui/css/ReportThumbnailsPortlet.css
- html/gui/js/modules/summary/ReportThumbnailsPortlet.js
- html/gui/js/modules/summary/SavedChartsReportsPortlet.js
- tests/artifacts/xdmod/report_builder/output/cd_enum_templates.json
- tests/artifacts/xdmod/report_builder/output/cs_enum_templates.json
- tests/artifacts/xdmod/ui/output/reportGenerator.json
- tests/ui/test/specs/xdmod/reportGenerator.js
This PR fixes/changes the following things:
​​1. Duration selected for report charts is now indicated using a bold period
2. Config file how uses 'timeframe' instead of 'role' to specify the timeframe
3. Change template name to 'Summary Page Report'  which is more descriptive
4. Set report schedule to once
5. Change 'recent' to 'saved'
6. Show unknown data in saved charts and reports portlet
7. Show current time range selection 
8. Add icon class to time range selection
9. Adjust spacing summary report portlet 
10. Inherit charts and report portlet form Greg's portlet
Bug fixes reported by Joe and modifications discussed in the meeting.
Manual tests
> Bug Fixes and Changes

- html/gui/js/modules/summary/ChartPortlet.js
As per the UI meeting update the title so that it explicitly
states the date range. The auto ellipses code was updated to
use the libary function.
> Update ChartPortlet for UI consistency.

- classes/Common/Identity.php
- classes/DataWarehouse/Query/Model/Parameter.php
- classes/DataWarehouse/Realm/GroupBy.php
- classes/DataWarehouse/Realm/Realm.php
- classes/DataWarehouse/Realm/Statistic.php
- classes/DataWarehouse/Realm/iGroupBy.php
- classes/DataWarehouse/Realm/iRealm.php
- classes/DataWarehouse/Realm/iStatistic.php
- classes/ETL/Configuration/EtlConfiguration.php
**These are expected to change as we continue the refactor but I want to get them in while they are still fresh in my mind.**
Initial version of Realm, GroupBy, and Statistics classes.
Some manual testing.
> Initial version of Realm and associated classes

- tests/ui/test/specs/xdmod/metricExplorer.page.js
Wait for the Data Series menu animation to finish before clicking on it.
> Improve robustness of UI tests

- html/gui/js/modules/summary/ReportThumbnailsPortlet.js
change `-` to `to` for consistency
> Fix typo in ReportThumbnailsPortlet

- classes/DataWarehouse/Visualization/HighChart2.php
Previously the colour override only worked for the first dataset.
Now the colour override works for all datasets in aggregate view. The datasets that use
the auto colour will get the next colour in the list. The list pointer is
updated when a dateset colour is overridden. This should minimise the chances
of two datasets getting the same colour.
The behaviour for the aggregate pie chart and timeseries plots is unchanged by this update. Rudra is going to fix these.
> Allow colour override for all datasets

- tools/dev/format-slurm/README.md
- tools/dev/format-slurm/package-lock.json
- tools/dev/format-slurm/package.json
- tools/dev/format-slurm/parse.js
this is to make sure dev tools that might be dirty and quick hacks are not lost and can be used by others
> add format slurm helper script

- html/gui/js/modules/job_viewer/AnalyticChartPanel.js
- html/gui/js/modules/job_viewer/JobPanel.js
This change removes a chunk of unused or unnecessary code from the AnalyticChartPanel. This forms the prep work for a UI bugfix and some updates as part of the user dashboard work. These will be in a future pull request.
> Remove unnecessary code from Analytic Chart Panel

- .gitignore
- tests/ci/bootstrap.sh
I need to pay more attention...
This fixes a few issues introduced in previous test updates
> update bootstrap and gitignore to be more specific

- html/gui/js/modules/NoviceUser.js
Update the tour text to be more consistent in tense voice and style.
> Update tour text

- docs/_data/toc.yml
- docs/dw-export.md
Adds data warehouse export documentation for the system administration audience.
We do try to have some sort of documentation.
No tests.
> Add data warehouse export documentation

- html/gui/js/CCR.js
- html/gui/js/modules/NoviceUser.js
Move the Tour to be part of `CCR.js` instead of the UserDashboard.
> Update tour construction

- tests/ci/bootstrap.sh
> Fix sso login test diff path

- background_scripts/batch_export_manager.php
Adds a file lock to the batch export script.
This will prevent the script from being run multiple times simultaneously, which could cause problems.
> Add file locking to Data Warehouse Export script

- classes/DB/FilterListBuilder.php
- classes/DataWarehouse.php
- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Data/ComplexDataset.php
- classes/DataWarehouse/Data/SimpleData.php
- classes/DataWarehouse/Data/SimpleDataset.php
- classes/DataWarehouse/Data/SimpleTimeseriesDataset.php
- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/Query/TimeseriesQuery.php
- classes/DataWarehouse/Realm/GroupBy.php
- classes/DataWarehouse/Realm/Realm.php
- classes/DataWarehouse/Realm/Statistic.php
- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
- classes/User/Elements/QueryDescripter.php
- html/controllers/user_interface/get_menus.php
- tests/artifacts/xdmod/realm/datawarehouse.d/cloud.json
- tests/artifacts/xdmod/realm/datawarehouse.d/jobs.json
- tests/component/lib/Query/AggregateQueryTest.php
- tests/unit/lib/Realm/GroupByTest.php
- tests/unit/lib/Realm/RealmTest.php
Fix a variety of issues found during testing with @ryanrath and @plessbd
> Fix issues found during testing

- html/gui/js/profile_editor/ProfileEditor.js
Also change the conditional statement to be more obvious as to its
purpose.
> Update profile editor for renamed rest interface.

- classes/Realm/GroupBy.php
- tests/artifacts/xdmod/realm/datawarehouse.d/jobs.json
- tests/component/lib/GroupBy/GroupByTest.php
- tests/component/lib/Query/AggregateQueryTest.php
> Improve support for attributes with multi-column keys

- configuration/etl/etl_data.d/xdb/report-templates.json
- html/gui/js/modules/dashboard/SavedChartsReportsComponent.js
- tests/artifacts/xdmod/report_builder/output/cd_enum_templates.json
- tests/artifacts/xdmod/report_builder/output/cs_enum_templates.json
- tests/artifacts/xdmod/ui/output/reportGenerator.json
> Minor text changes

- configuration/datawarehouse.d/cloud.json
- configuration/datawarehouse.d/ref/Cloud-group-bys.json
- configuration/datawarehouse.d/ref/Cloud-statistics.json
- configuration/datawarehouse.d/ref/Storage-group-bys.json
- configuration/datawarehouse.d/ref/Storage-statistics.json
- configuration/datawarehouse.d/storage.json
initial storage configuration
spilt up cloud in prep for more work
> add storage / breakup cloud

- classes/DataWarehouse/Access/Usage.php
Include array_keys() when comparing statistic ids
> Include array_keys() when comparing statistic ids

- classes/DataWarehouse/Data/RawDataset.php
Changes raw data set class to use the alternate timezone ("Timezone") field when available.
Changes made during the data warehouse export implementation changed the capitalization of the field alias during the query.
https://app.asana.com/0/159049597309611/1137168599943978
Tested on development server.
> Check for alternate timezone field

- docs/storage.md
Improve storage documentation.
https://ubccr.freshdesk.com/a/tickets/22080
No tests.
> Document required file name extension

- configuration/datawarehouse.d/include/Jobs-norm-avg-proc-agg.sql
- configuration/datawarehouse.d/include/Jobs-norm-avg-proc-time.sql
- configuration/datawarehouse.d/include/Jobs-sem-avg-proc-agg.sql
- configuration/datawarehouse.d/include/Jobs-sem-avg-proc-time.sql
- configuration/datawarehouse.d/include/Jobs-sem-avg-wait-hours-agg.sql
- configuration/datawarehouse.d/include/Jobs-sem-avg-wait-hours-time.sql
- configuration/datawarehouse.d/include/Jobs-sem-avg-wall-hours-agg.sql
- configuration/datawarehouse.d/include/Jobs-sem-avg-wall-hours-time.sql
- configuration/datawarehouse.d/include/Jobs-util-agg.sql
- configuration/datawarehouse.d/include/Jobs-util-time.sql
- configuration/datawarehouse.d/jobs.json
- configuration/datawarehouse.d/ref/Jobs-group-bys.json
- configuration/datawarehouse.d/ref/Jobs-statistics.json
- configuration/datawarehouse.d/ref/group-by-none.json
- configuration/datawarehouse.d/ref/group-by-time-period.json
- html/gui/js/modules/Usage.js
- tests/regression/lib/Controllers/UsageExplorerJobsTest.php
- tests/regression/lib/TestHarness/RegressionTestHelper.php
- Merge changes from plessbd/feature/groupby-refactor
- Set dataset type for GroupBy None to be timeseries as per historical Jobs/GroupBys/GroupByNone.php
- Set chart_options.dataset_display_type in GroupBy NSF Directorate
> Incorporate @plessbd changes and set custom chart options as per new features

- classes/DataWarehouse/Query/Jobs/RawData.php
- tests/integration/lib/Rest/JobViewerTest.php
These fields are needed for the JobPortlet.
> Ensure Jobs realm data access class provides required fields

- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/Query/iQuery.php
Expose the realm object in the Query class
> Expose the realm object in the Query class

- classes/DataWarehouse/Access/MetricExplorer.php
- classes/DataWarehouse/Data/ComplexDataset.php
- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
can things that do not exist be added?  and eternal question for the ages...
> check for statistic existance before adding

- html/gui/js/report_builder/ReportsOverview.js
Fix bug reported https://app.asana.com/0/159049597309611/1141900082957794/f
> Force refresh dashboard tab

- configuration/roles.d/dashboard.json
- html/gui/js/modules/dashboard/ReportThumbnailsComponent.js
Replace previous year with 1 year
Manual
> Replace previous year with 1 year

- configuration/etl/etl_action_defs.d/xdb/report-template-charts.json
- configuration/etl/etl_action_defs.d/xdb/report-templates.json
Moved where clause outside of join. 
I manually checked to make sure that this works as it is supposed to. The code creates a staging table when  with all the templates and then copies over the missing templates in the production table.
> Move where

- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Query/Query.php
- classes/Realm/GroupBy.php
- Fix missing `%s` in `sprintf()` statement
- Check that group by exists before trying to add it to a query
- Use alternate group by column if specified in `GroupBy::addWhereJoin()`
> Fix bugs found by @plessbd

- classes/DataWarehouse/Query/Jobs/RawData.php
The `RawQuery` class overrides the data table prefix so bring it up to date with current convention (ending in an underscore).
> Add underscore to data table prefix for consistency

- configuration/etl/etl.d/jobs_cloud_openstack.json
- configuration/etl/etl_action_defs.d/cloud_openstack/domains.json
These changes ensure that the `domains` table is populated only with a distinct
set of records from `openstack_raw_event` that do not already exist in
`domains`.
working == good
Manual inspection of the table after multiple ingestions.
> Updating modw_cloud.domains population

- configuration/etl/etl_sql.d/cloud_openstack/unknown_domain.sql
The  had a subquery that was not limited to 1 record returned.
This caused problems when the source table ended up being populated multiple times.
Preventing error emails == good
all automated tests run / passed.
> Updated Unknown Domain sub-query to return, at most, one row

- bin/acl-config
Per convo with @jpwhite4, we don't want to add anything `xsede` to OpenXDMoD.
We can handle this by updating the ETLv2 pipeline.
Don't want to litter OpenXDMoD with XSEDE references / code.
Automated tests w/
> Removing unneeded code from `acl-config`

- classes/OpenXdmod/Shredder/Slurm.php
- docs/resource-manager-slurm.md
Adds additional job states to those passed to the `sacct` command by the `xdmod-slurm-helper` script.
These additional states are necessary to ingest all jobs that have completed running.
> Update list of slurm job states

- CHANGELOG.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/xdmod.spec.in
> update release notes and changelogs

- docs/_data/toc.yml
- docs/storage.md
Updates storage documentation.
> Remove beta label from storage realm

- docs/configuration.md
- docs/support.md
- docs/upgrade.md
> Update upgrade and support documentation

- CHANGELOG.md
- docs/support.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/xdmod.spec.in
> Update release date

- html/gui/js/modules/DataExport.js
Fixes to UI issues in the data warehouse export tab both related to opening links contained in email sent when data is available.  The first is that the cancel button now works.  The second is that if the exported data file does not exist an error message is displayed instead of the prompt to download the file.
https://app.asana.com/0/15230011293693/1145818486503673
Just fixing bugs.
> Fix Data Warehouse Export UI download/cancel issues

- configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
This should have been included in #1138
> Fix migration

- classes/ETL/DataEndpoint/ConfigurationFileEndpoint.php
- classes/ETL/Ingestor/pdoIngestor.php
- tests/ci/validate.sh
Also add a test to check that no new files are left around
after the bootstrap.
> Fix bugs where temporary files were not being removed.

- html/gui/js/CCR.js
See issue https://app.asana.com/0/342819846538629/837361317696509
> Focus on username field when login dialog is expanded

- classes/DataWarehouse/Export/BatchProcessor.php
- classes/DataWarehouse/Export/FileManager.php
- classes/DataWarehouse/Export/QueryHandler.php
- configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
- configuration/etl/etl_tables.d/xdb/batch-export-requests.json
- tests/component/lib/Export/FileManagerTest.php
Mark export requests as deleted instead of deleting them from the database.
This makes it easier to track old requests.  Also simplifies logic used to delete files associated with deleted requests.
https://app.asana.com/0/15230011293693/1146676887787306
Updated automated tests.
> Refactor data warehouse batch export deleted state

- open_xdmod/modules/xdmod/xdmod.spec.in
Replaces the `cronie` requirement with the `crontabs` virtual requirement.
This will allow other cron implementations to be used.  See https://fedoraproject.org/wiki/Packaging:CronFiles
> Improve SPEC file cron requirement

- classes/Rest/Controllers/WarehouseExportControllerProvider.php
Move instantiation of `FileManager` instance from controller constructor to action.
This will prevent error messages caused by issues with the data warehouse export directory.  The variable is only used in one function so it doesn't need to be a member variable.
> Minor change to Data Warehouse Export controller

- classes/Configuration/Configuration.php
- classes/Configuration/JsonReferenceWithOverwriteTransformer.php
- tests/artifacts/xdmod/etlv2/configuration/input/sample_config_with_json_overwrite_transformer_keys.json
- tests/artifacts/xdmod/etlv2/configuration/input/sample_config_with_missing_json_overwrite_key.json
- tests/artifacts/xdmod/etlv2/configuration/output/sample_config_with_json_overwrite_transformer_keys.expected
- tests/unit/lib/ETL/Configuration/ConfigurationTest.php
added to `feature/groupby-refactor` but not exclusively related
see #1078 for more details
> Allow JSON references to overwrite keys

- docs/_data/toc.yml
Add roadmap link to documentation.
The roadmap is currently only linked to from the portal about page.
No tests.
> Add roadmap link to documentation

- tests/ci/scripts/xdmod-upgrade-jobs.tcl
- tests/ci/scripts/xdmod-upgrade.tcl
> Update upgrade test scripts

- classes/OpenXdmod/Migration/Version851To870/ConfigFilesMigration.php
- classes/Rest/XdmodApplicationFactory.php
- configuration/portal_settings.ini
- templates/portal_settings.template
Add configuration option to allow CORS requests.
> Add CORS configuration

- html/about/links.html
- html/about/openxd.html
- html/about/presentations.html
- html/about/publications.html
- html/about/release_notes/xdmod.html
- html/about/xdmod.php
Most of these links go to pages that are controlled by the project
anyway. Even so it doesn't hurt to use sensible defaults in the hrefs.
> Resolve sonarcloud: Links with "target=_blank" should prevent phishing attacks

- classes/DataWarehouse/Export/BatchProcessor.php
- classes/DataWarehouse/Export/FileManager.php
- classes/DataWarehouse/Export/FileWriter/FileWriterFactory.php
- classes/DataWarehouse/Export/QueryHandler.php
- classes/Rest/Controllers/WarehouseExportControllerProvider.php
Reverts addition of class constants added in #1223 to satisfy Sonar code smells.
Most of these constants make the code less readable and only improve maintainability minimally.
No new tests.
> Revert excessive use of class constants

- tests/ci/Docker/README.md
Fixing a couple of typos in the build script
> Fixing ben's typos

- classes/DataWarehouse/Query/Jobs/RawData.php
Add job_name to response on job search
> return user supplied jobname in search

- configuration/etl/etl_action_defs.d/migrations/7.5.1-8.0.0/hpcdb/schema-version-history.json
- configuration/etl/etl_action_defs.d/migrations/7.5.1-8.0.0/shredder/schema-version-history.json
- configuration/etl/etl_action_defs.d/migrations/7.5.1-8.0.0/xdw/schema-version-history.json
- configuration/etl/etl_data.d/migrations/7.5.1-8.0.0/hpcdb/schema-version-history.json
- configuration/etl/etl_data.d/migrations/7.5.1-8.0.0/shredder/schema-version-history.json
- configuration/etl/etl_data.d/migrations/7.5.1-8.0.0/xdw/schema-version-history.json
- configuration/etl/etl_sql.d/migrations/7.5.1-8.0.0/hpcdb/truncate-email-addresses.sql
Removes old migration files from a previous version.
These files are no longer used.
> Remove old migration files

- tests/ui/test/specs/xdmod/about.page.js
the trello tests seem to be failing, it might be that sometimes the class doesnt show up this looks for a different class that seems to be there more.
> update trello tests to work

- tests/integration/lib/Rest/JobViewerTest.php
Change tests to use more specific assertions and reverse expected/actual arguments where appropriate.
I'm debugging a broken test on a feature branch and getting better output from these tests would help.
> Improve job viewer test assertions

- tests/regression/README.md
Update regression tests README file.  Replaces the suggested command to generate reference data and updates the list of environment variables.  Also, various other wording changes, etc.
The reference command was incorrect and the list of environment variables was out of date.
I should really test to see if the command I put in here actually works, but I'm currently out of the office.
> Update regression tests documentation

- shippable.yml
make composer be quiet so logs are easier to read in shippable
> Make composer be quiet so we can read the logs better

- classes/DataWarehouse/Query/Query.php
these catches are hiding real errors.
> get rid of catches that hide errors for no reason

- classes/DB/Aggregator.php
Make sure it uses the correct loggable
> Fix Loggable in Aggregators

- classes/DataWarehouse/Query/Cloud/GroupBys/GroupByDomain.php
- tests/artifacts/xdmod/regression/chartFilterTests.json
when doing the groupby refacor, found that this groupby doesnt do what it is supposed to.  this makes it work.  it will be deleted as part of the group by refactor
> Fix cloud groupby domain to work

- html/controllers/ui_data/summary3.php
Moves the try around the call that will actually fail.
> Catch exception when aggregation has not been done

- classes/ETL/DbModel/Table.php
- tests/artifacts/xdmod/etlv2/dbmodel/input/table_def-charset.json
- tests/artifacts/xdmod/etlv2/dbmodel/input/table_def_2-charset.json
- tests/artifacts/xdmod/etlv2/dbmodel/output/table_def-charset.sql
- tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/verification-failure.json
Adds verification of database table engine to ensure that foreign key constraints are supported.
If the table engine does not support foreign key constraints MySQL will ignore the SQL and the ETL system will attempt to create the constraint every time the table is managed.
See https://app.asana.com/0/159049597309611/1162594769796873
Added test case.
> Check engine during foreign key constraint verification

- classes/ETL/DbModel/Table.php
- tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
- tests/unit/lib/ETL/DbModel/TableTest.php
When the schema of a database table model is set set the schema for all
properties of the table that have a schema that is not set.
Fixes a bug introduced in #1252 that resulted in false positives when comparing foreign key constraints.
> Alter database table model schema change handling

- shippable.yml
set default realms for testing
> set default XDMOD_REALMS

- shippable.yml
- tests/ci/runtest-include.sh
- tests/component/runtests.sh
- tests/integration/runtests.sh
- tests/regression/runtests.sh
- tests/ui/runtests.sh
- tests/ui/wdio.conf.js
- tests/unit/runtests.sh
Not all of the tests are logging in shippable.  Lets make sure they do.
> make sure tests log

- .travis.yml
- tests/integration/runtests.sh
- tests/unit/runtests.sh
Change test scripts to explicitly use the bash shell.  Also set XDMOD_REALMS in Travis CI configuration.
These files now use bash-specific features so they should really be using the bash shell.
Something in #1261 started producing these errors in travis (https://travis-ci.org/github/ubccr/xdmod/jobs/662577846#L1193):
```
tests/unit/runtests.sh: 2: tests/unit/runtests.sh: Bad substitution
tests/unit/runtests.sh: 3: tests/unit/runtests.sh: source: not found
Unit tests beginging: Sun Mar 15 01:43:44.413 2020
tests/unit/runtests.sh: 19: tests/unit/runtests.sh: log_opts: not found
```
Lack of XDMOD_REALMS produces this error (https://travis-ci.org/github/ubccr/xdmod/jobs/663961746#L1196):
```
XDMOD_REALMS is not set
Default for core xdmod is: XDMOD_REALMS='jobs,storage,cloud'
Default for …
```
> Change test script shell and set XDMOD_REALMS

- tests/regression/README.md
Update the regression test documentation example command for generating expected test output data.
Another environment variable is now required because of #1261 (https://github.com/ubccr/xdmod/pull/1261/files#diff-e1f376fb60d9f8f89e3b18bb833b4ae4L12)
Used new command to generate expected test output data.
> Update regression test documentation

- html/gui/js/report_builder/SaveReportAsDialog.js
- tests/ui/test/specs/xdmod/reportGenerator.js
After saving a report using the "Save As" feature close the "Save As" window.
https://app.asana.com/0/15230011293693/62691924780816
Updated UI test
> Close report generator "Save As" dialog after saving

- configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
> Remove use of shredder and hpcdb config sections

- libraries/charting.php
Removes a couple functions that haven't been used since many versions ago.  Removes some commented-out code.  Changes some white space.  Updates some doc blocks.
I was intending to remove those functions several years ago, but forgot.  Otherwise, just general code cleanup.
No new tests.
> Remove unused functions

- classes/XDController.php
- classes/XDUser.php
- classes/XDUserProfile.php
Removes a few `require_once` statements from some PHP classes.
These statements are not needed since they should be loaded though the autoload and the linker should already be loaded.
No new tests.
> Remove unnecessary require statements

- configuration/datawarehouse.d/ref/Jobs-statistics.json
- configuration/datawarehouse.d/ref/group-by-common.json
Updates some wording on the group bys
> Update some wording for groupbys

- classes/DataWarehouse/Access/BatchExport.php
- classes/DataWarehouse/Data/BatchDataset.php
- classes/DataWarehouse/Data/RawStatisticsConfiguration.php
- classes/DataWarehouse/Export/RealmManager.php
- classes/DataWarehouse/Query/Jobs/JobDataset.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- classes/Rest/Controllers/WarehouseExportControllerProvider.php
- html/gui/js/modules/DataExport.js
- html/index.php
- tests/artifacts/xdmod/schema/warehouse-export/GET-realms.schema.json
- tests/integration/lib/Rest/WarehouseExportControllerTest.php
Adds a separate column for downloading exported data and adds the descriptions of all the fields that are exported for the selected realm.
Before:
After:
Also, refactor raw statistics configuration file use.
https://app.asana.com/0/15230011293693/1137016263723284
Altered automated tests and tested manually.
> Update data warehouse export UI

- tests/regression/lib/Controllers/MetricExplorerChartsTest.php
sonarcloud has been complaining about this code.
This just calls the other function with the different data.
> remove duplicated code

- bin/xdmod-build-filter-lists
- classes/DB/FilterListBuilder.php
with the creation of https://github.com/jpwhite4/xdmod-introspection lets make logging better.
> Make filter list building logging a bit better

- classes/OpenXdmod/DataWarehouseInitializer.php
- configuration/etl/etl.d/jobs_cloud_common.json
- configuration/etl/etl.d/jobs_cloud_generic.json
- configuration/etl/etl.d/jobs_cloud_openstack.json
Moving this action to the jobs-cloud-ingest-pi pipeline help prevent issues with the xsede module
Tested manually in docker and all automated tests pass
> Move UpdateCloudProjectToPI action to jobs-cloud-ingest-pi pipeline

- html/index.php
Removes script tag for `oldie-console-patch.js`.
This file was removed by #1308.  The script tag was removed from the internal dashboard, but not the `html/index.php`.
No tests.
> Remove reference to deleted file

- html/internal_dashboard/index.php
I accidentally removed a file still 'in use' (I dont really know if it is used, but it should not have been removed since I dont really know what it is doing)
> revert mistakenly removed line from #1308

- classes/OpenXdmod/Shredder/Sge.php
Updates the SGE shredder to copy the job ID to the `job_id_raw` field.
This makes the SGE shredder consistent with the PBS and LSF shredders (those that don't have an explicit "raw" job ID).
> Add `job_id_raw` to SGE shredder

- classes/DataWarehouse/Access/BatchExport.php
Change function used for data warehouse export access control.
There's only one realm that has a different name and display, and it's only in XSEDE as of now.  The "name" is used by the `rawstatistics` JSON files, so that is what must be used.
No new tests.
> Fix batch export realm access

- classes/ETL/Maintenance/ExecuteSql.php
Continuing my quest for better logging
This moves notification of start of executeSQL to a notice level, and moves some debugging into info for analysis later
> Update ETL executeSQL logging

- classes/ETL/Aggregator/pdoAggregator.php
Save some mental math by putting the d m Y in log instead of just Y00z
> put "d m Y" in as well as Y00z

- tests/ci/scripts/xdmod-setup-start.tcl
Replaces ccr-xdmod-help email address with a reserved domain email address.
Sending emails to the help address creates tickets in our help desk.  We shouldn't be creating help tickets if we're just testing.
> Replace CCR XDMoD Help email address

- html/gui/js/modules/DataExport.js
Fixes when the "Request Submitted" message is displayed.  It was incorrectly being displayed when requests were deleted and not when requests were resubmitted.
https://app.asana.com/0/0/1177416728295602/f
> Fix data export submission confirmation message

- docs/install-source.md
See #1328 
https://app.asana.com/0/342819846538629/1178746552707810/f
> Update source installation log directory notes

- classes/DataWarehouse/Query/Jobs/JobDataset.php
Adds `DISTINCT` to the jobs realm `JobDataset` queries to prevent duplicates due to jobs that span multiple days.
https://app.asana.com/0/342819846538629/1179297094155667/f
> Add DISTINCT to Jobs realm JobDataset query

- classes/DataWarehouse/Query/Jobs/JobDataset.php
- classes/DataWarehouse/Query/Jobs/RawData.php
- classes/DataWarehouse/Query/Query.php
Adds an option to the Data Warehouse Query class to support queries that use `DISTINCT`.  Refactors subclasses to use this functionality.
Also removes a block of dead code.
Reduce duplicate and similar code.  See #1332 for duplicate code.
Uses existing tests.
> Refactor Query class to allow DISTINCT queries

- docs/simpleSAMLphp.md
After some feedback add some more details to the SSO documentation
> More detail for SSO setup

- configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
> Fix bugs in definition of cloud fact tables.

- classes/Rest/XdmodApplicationFactory.php
> Need to catch the right Exception

- docs/cloud.md
- docs/configuration.md
- docs/docs-conventions.md
- docs/dw-export.md
- docs/etl/data-endpoint-oracle.md
- docs/faq.md
- docs/hierarchy.md
- docs/howto-node-utilization.md
- docs/howto-summary-charts.md
- docs/integrations.md
- docs/logo-image.md
- docs/nginx.md
- docs/resource-manager-slurm.md
- docs/simpleSAMLphp.md
- docs/software-requirements.md
Updates fenced code blocks language identifiers.
Now that the documentation is syntax highlighted will improve the appearance a bit.
No tests.
> Update code block syntax highlighting identifiers

- classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
Change query used to find slurm jobs that may contain GPU data.
The new query only returns rows that contain strings that indicate GPU data.  This reduces the number of rows returned by the query and excludes rows that definitely don't contain GPU data.
I ran into an out-of-memory situation while trying to process over 21 million job rows.
Tested query manually.
> Adjust Slurm GPU migration query

- docs/upgrade.md
Add more details to the upgrade documentation regarding the GPU metrics.
There was no mention of the PBS GPU data.
No tests.
> Improve GPU Metrics upgrade documentation

- composer.json
- composer.lock
Just adding the new ubccr/simplesamlphp-module-authoidcoauth2 module for authenticating with oidc tested w/ dex. Specifically for OpenOnDemand & XDMoD tutorial 
For the OpenOnDemand / XDMoD Tutorial.
> Adding the new ubccr/simplesamlphp-module-authoidcoauth2 module

- configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
Set the delimiter for the SQL query.
The queries still run, but the wrong query count is displayed.
> Set delimiter for migration

- docs/integrations.md
> Update Integration Documentation

- composer.lock
Just version bumping ubccr/simplesamlphp-module-authoidcoauth2 in the composer.lock file.
We want to ensure the latest version of ubccr/simplesamlphp-module-authoidcoauth2 is installed.
> Updating ubccr/simplesamlphp-module-authoidcoauth2 to 1.0.3

- configuration/etl/etl.d/jobs_cloud_common.json
Add the new staging_resource_specifications table to etl action that manages the cloud tables.
> Add staging_resource_specifications table to cloud manage tables action

- docs/hierarchy.md
Update hierarchy guide steps for removal of hierarchy dimensions.
These instructions were outdated.
Tested manually in docker.
> Update hierarchy dimensions removal process

- configuration/etl/etl_schemas.d/cloud_openstack/event.schema.json
Just removing one duplicate key, `root_gb`, and fixing the spelling on another,
`ephermeral` -> `ephemeral`.
OCD?
> Minor Cleanup of the OpenStack event schema

- classes/Configuration/Configuration.php
See title.
No reason to use a bitwise operator in this statement.
No tests.
> Replace bitwise operator with logical operator

- configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
Update table list in cloud migration.
One of these tables is needed for the CSV import.
https://app.asana.com/0/342819846538629/1187621461905017/f
> Add table to migration

- docs/cloud.md
Changes the example command to re-ingest the cloud realm.
I'm not sure if there's a better way to do this, so if there's a better way please let me know.
The previous version potentially re-ingests and re-aggregates all the other realms.
Tested commands (for OpenStack) in docker.
> Update cloud re-ingest example commands

- docs/cloud.md
Updating cloud documentation to add details about script to use to get hypervisor facts and commands to run for cloud utilization.
> Update cloud documentation with information for cloud utilization 

- docs/configuration.md
- docs/faq.md
- docs/software-requirements.md
- docs/troubleshooting.md
- docs/upgrade.md
Moves the MySQL configuration text from the software requirements to the configuration guide.
This text contains primarily configuration instructions so I think it makes more sense to have it in the configuration guide.  The configuration guide covers configuring both Open XDMoD and configuring the software that Open XDMoD depends on so it may make more sense to split those instructions in two.
> Rearrange MySQL configuration documentation

- docs/upgrade.md
Rearranges some of the 9.0 specific notes.  Adds a warning and updates the list of database changes.
> Add more upgrade notes

- configuration/datawarehouse.d/include/Jobs-node-util-agg.sql
- configuration/datawarehouse.d/include/Jobs-node-util-time.sql
- docs/howto-node-utilization.md
Adds SQL files for node utilization statistics and updates documentation.
These statistics were removed during the group by refactor because they are not enabled by default.
https://app.asana.com/0/808093868887967/1185788753197267/f
> Restore node utilization statistics

- html/gui/css/viewer.css
Adjust padding of chart layout and time frame radio buttons.
Before:
After:
Also removes trailing white space, replaces tabs with spaces, and removes commented-out CSS.
The padding fixes button crowding issues with the combination of Firefox and some Ubuntu themes.
https://app.asana.com/0/0/835282853904695/f
https://app.asana.com/0/826872005880486/827143607859035/f
> Fix chart layout and timeframe radio button crowding

- tests/ui/runtests.sh
There were issues with running this script from a directory other then `<xdmod-dir>/tests/ui`, this small
change allows the script to be run from anywhere and still function as expected.
> Update the directory that ui/runtests.sh runs from

- configuration/datawarehouse.d/ref/group-by-common.json
Updates and adds missing "category" configuration for common Group Bys.
I noticed these were uncategorized:
Then noticed that some of the other categories are incorrect.
> Update and add GroupBy categories

- tests/ui/test/specs/xdmod/internalDashboard.js
- tests/ui/test/specs/xdmod/reportGenerator.page.js
Was able to reliably make this test fail when trying to use chromium instead of chrome for the tests.
Since this could possibly show up in chrome as well, pushing this on its own.
> Make tests more robust

- classes/Configuration/Configuration.php
Replace use of `apc_store` with `apcu_store`.
APCu is used elsewhere in the `\Configuration\Configuration` class.  [APC is considered unmaintained and dead.](https://www.php.net/manual/en/intro.apc.php)
I'm not really sure how to test this.
> Replace APC function with APCu function

- classes/Configuration/Configuration.php
Fix typos.
```
Call to undefined method Configuration\Configuration::getMaxLastModifiedTime()
```
> Fix call to non-existent method

- composer.json
- composer.lock
Updating this dependency to a new version.
> Updating ubccr/simplesamlphp-module-authoidcoauth2 to 1.1.0

- etl/js/lib/etl_profile.js
Adds support for additional tables, formula fields and error fields defined in the JavaScript ETL configuration.
These changes support moving SUPReMM analysis fields into the raw statistics configuration file.
https://app.asana.com/0/0/1192929664503858/f
> Add additional raw statistics features

- tests/component/lib/Export/BatchProcessTest.php
Replace use of `array_diff`with diffirent tests.
These tests were generating notices which causes problems.
> Improve batch data export tests

- etl/js/package.json
Update dependency of nodejs ini package
> Update version of ini package

- AUTHORS.md
- html/about/team.html
Updated lists of maintainers/contributors (AUTHORS markdown) and personnel and their current locations (team html page). Changed bold tags to strong in accordance with current guidance from CI.
The AUTHORS markdown page dated to 2016, the team page under the About tab was also out of date.
Viewed files in browser.
> Updated XMS project's authors and team listings

- html/about/presentations.html
- html/about/publications.html
Update Publications and Presentations listed in the XDMoD/Open XDMoD About tab.  Namely:
- Add Gateways20 tutorial to Presentations; include link to the hpc-toolset-tutorial repo
- Update PEARC20 tutorial in Presentations to include repo link
- Update Publications to include recent DOIs
These changes are documentation/HTML only!
Keep our About tab up to date with recent publications and presentations
Viewed in browser.
> Update About tab with recent Publications and Presentations details

- html/about/presentations.html
Add SC'20 and NYSERnet conference demos to presentations page. Change is HTML only.
Keeping our presentations up to date.
Viewed in browser.
> Update listing of XDMoD demos from Autumn 2020

- .circleci/config.yml
- tests/ci/samlSetup.sh
- tests/ui/test/specs/xdmod/SSOLogin.js
- tests/ui/test/specs/xdmod/internalDashboard.js
This PR adds the files required for running our CI Pipeline on CircleCI and a few test changes required to overcome timing issues encountered. 
We needed to find a new host for our CI pipeline due to Shippable being sunset in the near future.
> Circleci project setup

- html/about/publications.html
- Added the BW workload analysis arXiv link to the 2017 publications
- Addition performed at Tom Furlani's request. The guy has sharp eyes!
- I'm associating this with 9.5, but his could be saved for the next release as appropriate.
This publication was omitted from the original list of XMS research output.
Viewed html in browser.
> Added Blue Waters workload analysis to publications list

- .gitignore
Update `.gitignore` file.
`plotly` was added to `composer.json` in #1473 (https://github.com/ubccr/xdmod/pull/1473/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R236), but wasn't added to the `.gitignore` file.
Install plotly and check if `git` ignores it or not:
```
composer install
git status
```
> Add plotly to .gitignore

- README.md
- docs/_data/toc.yml
Also switch SUPReMM to Job Performance (SUPReMM) since I was editing the file anyway.
> Update docs to include the OnDemand module.

- configuration/linker.php
Change exceptions.log to use default log file permissions (`0660`).
The permissions on this file were changed in the RPM spec file, but the permissions on the file are changed when exceptions are written to the file.
Tested manually in Docker.
> Change exceptions.log file permissions

- classes/DataWarehouse/Data/TimeseriesDataset.php
- tests/integration/lib/Controllers/UsageExplorerTest.php
This was erroneously removed during the groupby refactor work
done in XDMoD 9.0.
and cherry-picked from the other pull request into 10.0 #1532
> Add exportJson function back.

- classes/CCR/CCRDBHandler.php
This change handles the scenario when there is a long delay
between two different log message calls (for the database logger).
This can happen when aggregating / ingesting large amounts of data
and the log level is set low.
The change is to attempt a single retry if the specific 'server has
gone away' error is seen. This shouldn't change the behaviour for any
other types of sql error. If the retry fails then it does not try again.
There is not an easy way to test this in the CI builds so I manually tested
as follows:
This was tested by changing the `/etc/my.cnf.d/server.cnf` file in a
docker instance and adding the following:
```ini
wait_timeout = 30
```
I then put a `sleep(60)` as the last line of the run_aggregation() function
in /usr/lib64/xdmod/aggregate_supremm.php and ran it. (I …
> Handle MySQL server has gone away errors.

- classes/XDUser.php
Removes `XDUser::isCampusChampion`.  This function references the database table `modw.peopleonaccount` that no longer exists.
See https://app.asana.com/0/1200028182662861/1200819016815736/f
No new tests.
`grep`'d source code (including xdmod-xsede) for `isCampusChampion`.
> Remove unused function

- README.md
- docs/_data/toc.yml
Also switch SUPReMM to Job Performance (SUPReMM) since I was editing the file anyway.
> Update docs to include the OnDemand module (cherry-pick into 9.5 for continuity).

- configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
Replaces use of the "shredder" config value.
This configuration doesn't exist in the XSEDE configuration and that breaks XSEDE.  This value doesn't really matter since all of the MySQL databases use the same credentials.
```
Processing local file /data/www/xdmod/etc/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json: ETL\Configuration\EtlConfiguration (/data/www/xdmod/etc/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json): Error adding action 'xdmod.migration-9_5_0-10_0_0.alter-shredded_job_slurm' in section 'xdmod.migration-9_5_0-10_0_0': ETL\Configuration\EtlConfiguration (/data/www/xdmod/etc/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json): Error registering destination endpoint for xdmod.migration-9_5_0-10_0_0 'xdmod.migration-9_5_0-10_0_0.alter-shredded_job_slurm': ('Shredder/Staging Database', …
```
> Replace use of "shredder" ETL config

- configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
> Replace use of "hpcdb" ETL config

- classes/OpenXdmod/Migration/Version950To1000/DatabasesMigration.php
This mitigates a problem seen in testing where the persistent
connection would timeout due to the etl pipelines taking longer
to run then the connection timeout.
> Change table exists checks to use dedicated connections.

- classes/ETL/Maintenance/ExecuteSql.php
This time I tested by running the docker build with a database
timeout of 10 seconds.
```
echo "wait_timeout = 10" >> /etc/my.cnf.d/server.cnf
```
On my workstation this timeout is short enough that the upgrade
fails on the alter shredded job slurm action
```
2022-02-14 21:34:23 [warning] Stopping ETL due to exception in xdmod.migration-9_5_0-10_0_0.alter-shredded_job_slurm (ETL\Maintenance\ExecuteSql)
xdmod.migration-9_5_0-10_0_0.alter-shredded_job_slurm (ETL\Maintenance\ExecuteSql): Error executing SQL Exception: 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away'
```
With this patch in place (and the timeout still set to 10 seconds), the upgrade
completes.
Note that a 10 second timeout in the docker then causes the cloud
ingest steps to fail.
> Second attempt to fix db timeouts.

- docs/support.md
- open_xdmod/modules/xdmod/xdmod.spec.in
Update documentation.
Preparing for new release.
No tests.
> Update spec file change log and supported versions

- CHANGELOG.md
- html/about/release_notes/xdmod.html
> Update change log

- docs/_data/toc.yml
- docs/rest.html
- docs/xdmod-rest-schema.json
Merge changes from #1558
Don't want to forget to do this.
No tests
> Merge 10.0 into 10.5

- configuration/internal_dashboard.json
Adds configuration to display ETL overseer logs in the admin dashbaord.
People may want to see these logs in the dashboard.
> Add ETL Overseer logs to admin dashboard

- AUTHORS.md
- html/about/team.html
Update team about page and authors file.
We have new team members and one team member has left.
See https://app.asana.com/0/1201929110850019/1202102074264224/f
No tests
> Update XMS team members list

- classes/Rest/XdmodApplicationFactory.php
These changes add the POST data when present and the total elapsed time
taken to process a given REST request to the information logged to the
mod_logger.log_table.
This feature was requested by @eiffel777
All automated tests pass
> Adding post data & total elapsed request time

- docs/simpleSAMLphp-ldap.md
- docs/simpleSAMLphp.md
- tests/ci/samlSetup.sh
Updates broken links and removes comment containing broken links from a test file.
Noticed that these links were returning 404 pages.
Opened the new links in a web browser.
> Update broken SimpleSAMLphp links

- docs/index.md
- html/gui/js/CCR.js
Add new NSF award grant number.
New award, new number.
See https://app.asana.com/0/1201929110850019/1202189774148511/f
Tested using a `gh-pages` fork.
> Update NSF award grant numbers

- docs/rest.html
Changes the content of the HTML title tag on the REST documentation page.
I'm not sure if this page should have a different title than the other pages in <https://open.xdmod.org/>, but I don't think it should be "Redoc".
No tests.
> Change REST API documentation page title

- bin/xdmod-check-config
- docs/software-requirements.md
Update documentation and `xdmod-check-config` script.
See https://app.asana.com/0/1201929110850019/1202400711696424/f
No tests.
> Update PHP and MariaDB version requirements

- .circleci/config.yml
Add `.circleci/config.yml` to the `gh-pages` branch.
CircleCI fails on the `gh-pages` branch.
This is the test.
> Add CircleCI configuration to ignore gh-pages

- update.sh
Updated the comments at the top of update.sh
Recent changes to update.sh include using python3, which must be clarified in the comments
> Added comments to update.sh

- html/controllers/metric_explorer/get_rawdata.php
- html/gui/js/AddDataPanel.js
**NOTE: This is just backported from XDMoD 10.5 for the Rocky8 work on xdmod-supremm** 
* Updating the datasetid float comparison
Comparing floats as strings is not desirable due to the way they are represented
internally. Per https://www.php.net/manual/en/language.types.float.php they
should be compared to within a certain number of digits. This was found by
investigating an error where the "Show Raw Data" context menu item was not
showing the associated jobs. It turns out that the id's being compared were the
following:
- 0.22694672549385309
- 0.22694672549385
The latter number having been truncated after 14 digits, which was a problem
as they were being compared as strings, not floats. By comparing them as floats
we can mitigate this type of rounding / truncating error in the future.
* …
> Updating the datasetid float comparison (PHP7.2) (#1612)

- classes/OpenXdmod/Shared/DatabaseHelper.php
Restore removed code.
This was removed in #1631, but is still needed by `xdmod-supremm` (see <https://app.circleci.com/pipelines/github/ubccr/xdmod-supremm/363/workflows/79b9da1c-830c-41f9-89ff-57993ab90d89/jobs/780?invite=true#step-109-2020>.)
Build and install `xdmod-supremm` along with these changes and check if the tables are created.
> Revert removal of database initialization code

- classes/CCR/DB/MySQLHelper.php
- classes/XDReportManager.php
- libraries/utilities.php
Move code for creating a temporary directory to `xd_utilities` and use that where applicable.
This function was added in #1635 but can be used in other places.
No new tests.
> Refactor duplicate code

- html/about/team.html
This PR updates the team members listed under About -> Team in XDMoD.
1.) Removed old team members
2.) Added new team members from ACCESS sub awards
The list of team members needs to be updated as part of the transition from XSEDE to ACCESS.
Visually tested on my development port.
> Update XMS team members

- html/gui/js/profile_editor/ProfileGeneralSettings.js
If the tech_support_url is present, then the text to points the user to https://support.access-ci.org/open-a-ticket instead of ccr-xdmod-help@buffalo.edu. If this is not present or 'false' then this text is unchanged.
With tech_support_url (updated):
Without tech_support_url (original/default):
Update for ACCESS transition.
Original issue:
https://app.asana.com/0/1202679277743034/1202840692396212
Tested on my development port (images above).
> Update dialog text in My Profile for ACCESS.

- html/about/xdmod.php
Change the main link to the ACCESS instance.
> Update text description of XDMoD.

- docs/faq.md
- docs/support.md
Updating FAQ with information about Rocky/RHEL 8 and PHP 7.2 information. After this is approved I will create pull requests for other branches where updates are needed, such as the gh-pages branch.
> Update FAQ documentation

- docs/index.md
- docs/support.md
The link to sign up for the XDMoD mailing list has changed. This change has the correct link.
> Updating link to sign up for mailing list

- docs/howto-reconstruct-slurm.md
- docs/howto.md
This PR adds instructions to the __HOWTOs__ section of the XDMoD documentation regarding reconstructing Slurm accounting logs from an instance of XDMoD.
The instructions show how to query XDMoD's `mod_shredder.shredded_job_slurm` table to obtain the original information from the Slurm accounting logs ingested into that XDMoD instance.
This may be a useful utility for upgrading very old instances of XDMoD. Instead of upgrading incrementally, the latest version could be installed with the Slurm logs reconstructed then shredded and ingested in the latest version of XDMoD. These instructions could also be useful when the original Slurm logs are no longer available. 
This query was tested by querying two months worth of jobs per cluster from the development XDMoD instance. The output file was …
> Add docs for how to reconstruct Slurm logs from XDMoD

- classes/DataWarehouse.php
The following has been changed: 
- the `request` table and it's where clauses were removed as the table is no longer being populated and having it included as   
an inner join kept the query from returning any data. 
- Reformatted the SQL so that it's easier to read. 
Since the `request` table is not being populated anymore and it's inclusion was keeping this query from returning data it's removal is necessary. 
Manual testing was performed on dev & prod.
> Removing the acct.request table

- .circleci/config.yml
- CHANGELOG.md
- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version1000To1001/ConfigFilesMigration.php
- configuration/portal_settings.ini
- docs/_config.yml
- docs/upgrade.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
Release prep for the 10.0.1 version. 
Note I added a CI build to test the 10.0.0 to 10.0.1 path and had to mess with the config a bit because the 10.0 docker has different version of the chromedriver used for the UI tests.
> Update version number to 10.0.1

- .circleci/config.yml
- CHANGELOG.md
- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version1000To1001/ConfigFilesMigration.php
- configuration/portal_settings.ini
- docs/_config.yml
- docs/upgrade.md
- html/about/release_notes/xdmod.html
- libraries/charting.php
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
> Merge 10.0.1 changes back into 10.0 branch

- html/about/presentations.html
- html/about/publications.html
- html/about/team.html
These are updates to the Publications, Presentations and Team list. Please look them over and let me know if anything is missing.
> Updates for publications, presentations, and team members

- docs/latest-releases.md
- docs/software-requirements.md
- docs/upgrade.md
Just wanted to clarify the fact that nodejs is a dependency now.
> Minor updates to the requirements documentation.

- html/about/publications.html
Add new paper from Vipin Chaudhary
> Add new paper from Vipin Chaudhary

- docs/latest-releases.md
- docs/software-requirements.md
- Updating our documentation so that it has the latest 10.0.2-2 release url for the Rocky8 RPM. 
- Updated the software requirement steps for Rocky 8 to include the `pecl install mongodb` step that is now required. 
Having up to date documentation is good.
> Doc updates rocky8

- docs/index.md
- docs/support.md
Backport from https://github.com/ubccr/xdmod/pull/1686.
> Backport: Updating link to sign up for mailing list

- README.md
This adds a citation for the XDMoD reference paper to the main README.
This is meant to make the reference paper more visible and encourage references to it.
I viewed the README on GitHub and confirmed the reference appeared as desired.
> Add reference paper citation to README.

- .circleci/config.yml
We want to start testing the upgrade path for el8 systems, so removing the excludes from the circleci config is the easiest way to do that.
> Adding the upgrade path for el8

- .circleci/config.yml
- classes/Realm/GroupBy.php
- tests/integration/lib/Controllers/MetricExplorerTest.php
Update the filter parsing code to handle case where a filter value has a quote character in it.
> Handle case where filters contain a quote character

- classes/CCR/RequestLogger.php
- html/controllers/metric_explorer/get_data.php
- html/controllers/metric_explorer/get_rawdata.php
- html/controllers/user_interface/get_charts.php
We currently only have logging for requests that go through the REST stack but would like to have visibility into when some html controller operations are requested.
This commit adds request logging for the following controllers:
- metric_explorer/get_data
- metric_explorer/get_rawdata
- user_interface/get_charts
Manual testing was performed on local docker containers.
> Adding DB Logging to select controllers

- classes/Realm/GroupBy.php
Backport the bug fix for commas in filters.
> Backport filter validation change to 9.5

- docs/configuration.md
- docs/install.md
- docs/latest-releases.md
- docs/software-requirements.md
- docs/support.md
- docs/upgrade.md
These changes contain updates that ensure Rocky 8 specific instructions are included in our documentation.
Rocky 8 is becoming an officially supported operating system and as such our documentation should reflect this.
> el8 documentation updates for 10.5

- docs/upgrade.md
This adds notes about the Data Analytics Framework to the *Upgrade Guide* web page under the *10.5.0 Upgrade Notes* section to document that the 10.5.0 upgrade involves the addition of new portal settings and a new database table to support the new Data Analytics Framework.
I followed these steps on my laptop:
1. [Make sure Jekyll is installed](https://jekyllrb.com/docs/installation/).
1. Change to the `docs` directory.
1. `git clone https://github.com/ubccr/xdmod-jekyll-theme`.
1. `bundle install`.
1. `bundle add webrick`.
1. `bundle exec jekyll serve`.
1. Browse to the URL and confirm the page is correct.
> Add upgrade notes about the Data Analytics Framework.

- docs/install-source.md
We support both el7 and el8 in this release so this should be noted in our source install documentation.
> Updating Source Install Instructions

- classes/DataWarehouse/Query/Cloud/JobDataset.php
- classes/DataWarehouse/Query/Gateways/JobDataset.php
- classes/DataWarehouse/Query/Jobs/JobDataset.php
Wrong variable in the checking code.
> Fix typo in data check

- classes/Rest/Controllers/WarehouseControllerProvider.php
- tests/integration/lib/Rest/WarehouseControllerProviderTest.php
This PR removes the remaining references to `classes/DataWarehouse/Query/Exceptions/BadRequestException.php` that were missed in https://github.com/ubccr/xdmod/pull/1794.
This PR adds integration tests that cover the changed code.
> Replace redundant exception classes with ones provided by Symfony.

- docs/simpleSAMLphp-ldap.md
- docs/simpleSAMLphp.md
This PR fixes our links to pertinent SimpleSAMLPHP documentation pages within our documentation.
bad links === bad
> Updating SimpleSAMLPHP links

- docs/support.md
This syncs the `xdmod11.0` branch with the change to `support.md` from https://github.com/ubccr/xdmod/pull/1811.
> Update list of supported versions on website.

- .circleci/config.yml
This was always a minor optimization that's ended up causing problems when making changes to composer dependencies.
This change will ensure that we always have the dependencies defined in `composer.json` present.
> removing the composer cache from circleci

- tests/ui/test/specs/xdmod/about.page.js
Just disabling the Roadmap UI test so that we can get our other PRs to pass while we track down why this intermittently fails in the CI.
> Disabling roadmap Test

- html/about/presentations.html
- html/about/publications.html
Update publications and presentations list
> Update publications and presentations list

- html/about/presentations.html
- html/about/publications.html
Backporting new publications and presentations into xdmod10.5. PR for 11.0 is #1829 
> Backporting new publications and presentations

- tests/ui/.eslintrc.json
- tests/ui/test/specs/xdmod/internalDashboard.js
- tests/ui/test/specs/xdmod/internalDashboard.page.js
This make sure the dialog box has rendered properly before trying
to edit the form.
The webdriver tests are going away so I'm not going to refactor the
code for the object-shorthand eslint rule!
> Fix timing error in internal dashboard UI test

- docs/install-source.md
- docs/support.md
- tests/ui/test/specs/xdmod/about.page.js
This PR backports the changes from https://github.com/ubccr/xdmod/pull/1811 and https://github.com/ubccr/xdmod/pull/1867 to the `xdmod10.5` branch to keep the branches in sync and from https://github.com/ubccr/xdmod/pull/1832 so the CI tests can pass.
> Backport docs changes from 11.0 to 10.5.

- open_xdmod/modules/xdmod/build.json
> Updates for rc1

- configuration/datawarehouse.d/ref/Cloud-group-bys.json
- configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
- configuration/datawarehouse.d/ref/group-by-common.json
<!--- The title text will be used to populate Changelog and associated documentation.
Minor fixes to documentation.
> Fixed minor spelling and grammer errors

- 10.5/software-requirements.md
Specify `mongodb-1.16.2` due to errors on Rocky 8 if pulling latest version. Also make this doc consistent with docs from `xdmod10.5` branch
> Specify `mongodb` version in software requirements

- open_xdmod/modules/xdmod/build.json
Bump to rc.2 for XDMoD 11.0 
We're ready for rc.2
All Automated Tests.
> Upping the release to rc.2

- docs/support.md
This PR updates the website documentation to extend the support for version 10.5 to October 31, 2024 and to update the description of CentOS 7 support.
This PR is for the `xdmod10.5` branch. There are also PRs that port these changes to the [`xdmod11.0`](https://github.com/ubccr/xdmod/pull/1905) and [`gh-pages`](https://github.com/ubccr/xdmod/pull/1906) branches.
> Extend support window for 10.5.

- docs/install-rpm.md
- docs/install-source.md
- docs/notices.md
- docs/upgrade.md
This PR makes various fixes to the online docs:
* In the RPM instructions, use `dnf` and `el8` instead of `yum` and `el7`, since we have ended support for EL 7.
* Remove EL 7 source install instructions since there will be no EL 7 source code for 11.0.
* Fix a copy-paste error in the jQuery notice.
* Add `xdmod-ondemand` to the list of modules mentioned in the upgrade guide.
* Fix a couple of steps in the upgrade guide that need to be run as root since the subsequent command is also run as root.
> Various doc fixes.

- docs/upgrade.md
Adding upgrade information related to the `resources.json` and `resource_specs.json` files to `upgrade.md`.
> adding upgrade information for resource specs

- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
Update `build.json`  and `xdmod.spec.in` file for 11.0.0 release
> Update `build.json`  and `spec` file for 11.0.0 release

- html/about/team.html
Just updating the current team listing to current members.
> Updating Team Page

- html/about/team.html
Adding Jennifer as Co-Pi and removing Matt Cawood.
> Adding Jennifer as Co-Pi

- docs/upgrade.md
This PR updates the upgrade notes for 11.0.0 to include information about upgrading the `xdmod-data` Python API and additional information about configuration file and database changes.
> Update upgrade notes for 11.0.0.

- docs/support.md
This PR updates the support page to list the 11.0 support window.
> Add 11.0 to the support docs.

- CHANGELOG.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/xdmod.spec.in
This PR updates the changelog to set the release date for v11.0.0 to the date the RPMs were actually built instead of the date we anticipated they would be built.
This PR also updates the release notes to include missing notes from the changelog and to include sections for the optional modules.
The release notes can be viewed as rendered HTML [on my developer port](https://xdmod-dev.ccr.xdmod.org:9001/about/release_notes/xdmod.html).
> Update changelog and release notes.

- docs/software-requirements.md
This PR updates the software requirements documentation page to list the correct updated version of MongoDB.
> Update version of MongoDB in software requirements docs.

- CHANGELOG.md
- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version1100To1101/ConfigFilesMigration.php
- configuration/portal_settings.ini
- docs/_config.yml
- docs/upgrade.md
- open_xdmod/modules/xdmod/build.json
This PR prepares the `xdmod11.0` branch for development of version `11.0.1`.
> Prep for v11.0.1 development.

- composer-el7.json
- composer-el7.lock
- composer-el8.json
- composer-el8.lock
- html/highchart_template.html
- html/index.php
- html/internal_dashboard/index.php
*NOTE: the Centos7 builds will always fail as the repo's for updates have been taken offline* 
This is to address CVE-2020-11023
Less vulnerabilities are a good thing.
All automated tests.
> Updating jQuery to 3.7.1

- .circleci/config.yml
- tests/component/lib/QueryTest.php
Same as https://github.com/ubccr/xdmod-supremm/pull/391.
In a Docker container running the CircleCI steps, I confirmed that bugs similar to https://github.com/ubccr/xdmod-supremm/pull/392 cause exceptions in `/root/xdmod/logs/exceptions.log`.
> Add missing exception testing.

- html/about/presentations.html
- html/about/publications.html
Adding recent publications and presentations for 11.0.1 release. There is already a PR, #1962, for the main branch.
> Adding recent publications and presentations to xdmod11.0 branch

- .circleci/config.yml
- html/password_reset.php
- html/plotly_template.html
There were a couple of jQuery links that were not updated in https://github.com/ubccr/xdmod/pull/1970; this PR updates them.
This PR also removes CentOS 7 from the list of OSes in the CircleCI config workflow since we do not support CentOS 7 anymore.
> Finish updating jQuery to 3.7.1.

- .circleci/config.yml
- docs/software-requirements.md
- docs/upgrade.md
Downloading the current mongodb version with pecl has issues, `yes '' | pecl install mongodb || true` results in:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /usr/lib64/php/modules/mongodb.so (/usr/lib64/php/modules/mongodb.so: undefined symbol: _zval_ptr_dtor), /usr/lib64/php/modules/mongodb.so.so (/usr/lib64/php/modules/mongodb.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
pecl/mongodb requires PHP (version >= 8.1.0, version <= 8.99.99), installed version is 7.4.33
No valid packages found
install failed
```
Our 11.0 [docs](https://open.xdmod.org/11.0/upgrade.html) specify the mongodb version to …
> Use specific mongodb version

- .circleci/config.yml
- docs/software-requirements.md
- docs/upgrade.md
Use the mongodb driver that we recommended in the xdmod 11.0 docs originally. We should consider looking into the latest mongodb drivers / MongoDB version when we update to >= PHP8.1. This is partial revert from #1993 (we now specify 1.18.1 instead of 1.20.1)
If we don't specify the mongodb version it will pull latest. Which is good for development, but not for patch releases (unless it is a critical bug).
docker container
> Specify php mongodb driver (1.18.1)

- classes/DataWarehouse/Visualization/AggregateChart.php
Port of https://github.com/ubccr/xdmod/pull/1994 for the `main` branch.
> Fix regression introduced in efbd9ce0d2dbe5e1f214d72fe0cf0cc1523ea487

- classes/DataWarehouse/Visualization/AggregateChart.php
- classes/DataWarehouse/Visualization/TimeseriesChart.php
@aaronweeden found examples where series incorrectly had markers rendered. I looked at the changes make in #1941 and noticed it did not use the same marker logic as in xdmod10.5 (highcharts implementation) which matches our desired behavior. This PR corrects the logic that enables markers to be the same as in 10.5 [timeseries](https://github.com/ubccr/xdmod/blob/b2f8b3e629423a5656532bb578f0871d099e8e4a/classes/DataWarehouse/Visualization/HighChartTimeseries2.php#L451) and [aggregate ](https://github.com/ubccr/xdmod/blob/b2f8b3e629423a5656532bb578f0871d099e8e4a/classes/DataWarehouse/Visualization/HighChart2.php#L1124) charts
Improve the clarity of charts. The incorrectly rendered markers made it difficult to see other series on the same date.
Tested on my dev port.
> Use xdmod10.5 logic for enabling markers

- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Visualization/TimeseriesChart.php
- html/.eslintrc.json
- html/gui/js/PlotlyChartWrapper.js
- html/gui/js/PlotlyPanel.js
- html/gui/js/libraries/PlotlyUtilities.js
- html/gui/js/modules/Usage.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- html/plotly_template.html
Port of https://github.com/ubccr/xdmod/pull/1992 for the `main` branch.
> Refactor timeseries ticklabels

- classes/OpenXdmod/Migration/MigrationFactory.php
Port of https://github.com/ubccr/xdmod/pull/1991 for the `main` branch.
> Add ability to add additional database migration classes.

- CHANGELOG.md
- html/about/release_notes/xdmod.html
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/xdmod.spec.in
Port of https://github.com/ubccr/xdmod/pull/1950 for the `main` branch.
> Update changelog and release notes for 11.0.1.

- docs/_config.yml
- docs/install-rpm.md
- docs/install.md
- docs/upgrade.md
Port of https://github.com/ubccr/xdmod/pull/2008 for the `main` branch.
> Update upgrade docs.

- open_xdmod/modules/xdmod/xdmod.spec.in
Port of https://github.com/ubccr/xdmod/pull/2011 for the `main` branch.
> Fix date in spec changelog.

- tests/playwright/Docker/docker-compose.yml
- tests/playwright/package-lock.json
- tests/playwright/package.json
- tests/playwright/runtests.sh
Just updating the version number so tests don't break.
This change was made following @aaronweeden finding that it was a playwright version mismatch between what was in `package.json` and the version installed by `npm install -g @playwright/test`.
> Updating playwright docker image version

- html/about/supremm.html
The performance monitoring software tacc_stats has been renamed to HPCPerfStats. These changes reflect that rename.
https://github.com/ubccr/xdmod-supremm/pull/423
Tested on https://xdmod-dev.ccr.xdmod.org:9007
> Update tacc_stats Package Name

- classes/Rest/Controllers/WarehouseControllerProvider.php
- configuration/resource_metadata.json
This adds a REST endpoint that lists all the resources known to XDMoD. The SQL is in a configuration file since we have extra information that we support in the ACCESS version of XDMoD.
> Add REST endpoint for resource metadata

- open_xdmod/modules/xdmod/build.json
Port of #2068 for the `main` branch.
> Add resource_metadata.json to build.json.

- classes/DataWarehouse.php
Port of #2071 for the `main` branch.
> Fix slow queries in the allocations.

- classes/DataWarehouse/Data/BatchDataset.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- docs/cloud.md
- docs/etl/data-endpoint-oracle.md
- docs/etl/data-verification.md
- docs/etl/json-references.md
- docs/gateways-realm.md
- docs/integrations.md
- docs/module-assets.md
- docs/openidc.md
- docs/shredder.md
Merge #2095 and #2085 into main.
> Merge #2095 and #2085 into main.
