- classes/DataWarehouse/Visualization/HighChart2.php
Aggregate dataset value labels are merged now, instead of being taken from last dataset added.
When dataseries is being truncated (Show Remainder is checked), new x axis labels are the result of merged values from all datasets plotted.
This is a fix to the following behavior:
When multiple aggregate datasets are plotted, labels were derived from the last dataset added to the plot. If that dataset lacks any values, they are labeled improperly when Show Remainder is checked.
Bug was reported here:
https://app.asana.com/0/14787510600562/207594235757737
Behavior was tested on multi-dataset plots that lacked data for one dataset, such as:
- SUPREMM avg cpu pct idle, by job size, filtered on: shared/exclusive and plotted as two datasets
- SUPREMM number of jobs finished, by Application, …
> Correct merging of labels from multiple aggregate datasets, with Show Remainder checked.

- docs/simpleSAMLphp-ldap.md
Fix an error in the link for documentation
Make documentation links work
used `bundler` and `jekyll serve` to run local server to verify documentation output
> fix case error in documentation link

- classes/Authentication/SAML/XDSamlAuthentication.php
notices are thrown if the idp does not have the right indexes
Dont want to throw notices if they are not needed
Verified that the notices were no longer shown when display_errors = On in php.ini
> fix notices in xdsamlauth

- html/gui/js/report_builder/ReportCreator.js
Adds additional checks when an attempt is made to preview a report.
Currently, when a user attempts to preview a report that has not been saved they will be presented with what appears to be a report filled with errors.  This change prevents that behavior and instead presents a friendlier message that is consistent with those displayed when an attempt is made to either download or email an unsaved report.
Created a report and attempted to preview it without first saving it.  Observed new error message.  Saved and then successfully previewed the report.  Altered the report and again attempted to preview before saving.  Observed new error message.
> Prevent errors when previewing a report

- classes/DataWarehouse/Query/Jobs/Statistics/AverageProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/MaxProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/MinProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/NormalizedAverageProcessorCountStatistic.php
Removes use of the `CEIL` function in SQL for processor count statistics.
The average processor count values are displayed as decimals in the chart tooltips (as well as value labels, etc.).  This would imply that the precision of these numbers is higher than what is being returned from the data warehouse.  While the maximum and minimum processor counts are expected to be integers, it is reasonable to have non-integer (average) job size (core counts).
Viewed usage tab charts for the altered statistics and observed the now non-integer values.
> Remove rounding from processor count statistic classes

- .travis.build.sh
- .travis.yml
Travis Ci will run the linter on any modifed js or php files. If
there are errors or warnings, then lint will be run on the previous
version of the file. If new errors or warning have been introduced then
the build is in error.
Improve the code quality for new code without putting an undue burden on developers to fix the existing code.
Tested using travis during development. Already running with this code on the xdmod-supremm module and tested by creating pull requests with different code changes.
> Enforce new code must have no errors or warns

- classes/OpenXdmod/Ingestor/Hpcdb/Accounts.php
- classes/OpenXdmod/Ingestor/Hpcdb/Allocations.php
In Open XDMoD, save the PI group or accounting group of a job as the charge number in the account and allocation tables.
To help support allocations in Open XDMoD, save the job's PI or accounting group as the charge number in the  allocations and accounts tables. Initially, sites can then run a post-ingest ETL action to update the allocation values. In the case of SDSC this will allow them to send the same data that is sent to the XDCDB into their Open XDMoD instance. **Display of allocations data in Open XDMoD is not currently supported, but planned for the future.**
Provide support for allocations at SDSC. If the allocations are included in the modw.allocations table then a post-ingest process can update the initial and remaining allocation values.
The following steps were performed:
1. …
> Save the pi/group as the account and allocation charge number

- phpcs.xml
Relax the phpcs rules so that it does not disallow perfectly reasonably indented code.
Forcing a clurly brace on one line vs the next does not result in a big improvement to the code quality, but it does result in a onerous burden on the developers. This change relaxes these types of rules.
Ran phpcs on the code with the new ruleset.
> Update rules to exclude restrictions on control structure indentation.

- classes/ETL/DataEndpoint/JsonFile.php
Wrap JSON ETL DataEndpoint filter execution in try/catch block for improved error logging.
Wrap JSON ETL DataEndpoint filter execution in try/catch block for improved error logging. Also fix phpcs warnings.
Improved logging
Provided the patch to IU for testing on their system.
> Improve ETL JSON data endpoint filter logging

- classes/ETL/EtlOverseer.php
- classes/ETL/EtlOverseerOptions.php
- classes/ETL/LockFile.php
- classes/ETL/Maintenance.php
- classes/ETL/Maintenance/ExecuteSql.php
- classes/ETL/Maintenance/TestAction.php
- configuration/etl/etl.d/test_suite.json
- tools/etl/etl_overseer.php
ETLv2 allows multiple ETL processes to be run concurrently but concurrent executions should not include the same action. To support this, lock files are not solely pid-based but also take into account the names of the actions that are being executed. This allows multiple ETL pipelines to be executed concurrently as long as the actions being performed do not overlap.
A new `ETL\LockFile` class supports a lock file that contains a PID as well as a unique list of actions to be executed by that process. Prior to obtaining a lock, all ETLv2 lock files are checked to make sure that no running process is executing an action that overlaps the new process. Orphaned files are also cleaned up at this point. Note that a prefix (default of `etlv2_`) is required to identify ETLv2 lock files since …
> Create per-pipeline ETL locks

- classes/CCR/DB/PDODB.php
Bug fix.
Fixes my grep blunder in not identifying all code accessing these variables directly.
Ran sample ETLv2 and ETLv1 process to verify class integrity.
> Restore underscores to db connection parameter variable names

- classes/ETL/DbEntity/Query.php
Fix ETLv2 Query group-by generation
Add concatenation operator to include group-by in generated queries.
bugfix
Re-tested query generation and verified group by is incorrect before fix and in place after fix.
> Fix ETLv2 Query group-by generation

- classes/ETL/DbEntity/Column.php
- classes/ETL/DbEntity/Join.php
- classes/ETL/DbEntity/Query.php
- classes/ETL/DbEntity/Trigger.php
- classes/ETL/DbEntity/aNamedEntity.php
Allow comments in queries to contain characters after #
Comments in JSON files are defined as any key starting with "#". This enables the same behavior in ETL query definitions (previously only a "#" was allowed and not "# name" for example).
Improve ETL inline documentation and testing workflow.
Tested with "#" and "# name" as comments, verified results are correct.
> Allow comments in queries to contain characters after #

- classes/ETL/Aggregator/pdoAggregator.php
- classes/ETL/Utilities.php
Not all information returned for an aggregation period was available as a bind parameter for aggregators. Now, any columns returned by `getDirtyAggregationPeriods()` will automatically be made available as a bind parameter for use in aggregation queries.
Laying the groundwork for using `start_date` and `end_date` in the new Accounts realm rather than `start_date_ts` and `end_date_ts`, which are not available.
Ran ingestion and aggregation of the past 100 days worth of jobs including experimental batch aggregation.
> Improve aggregation bind params

- classes/ETL/Aggregator/JobsAggregator.php
- classes/ETL/Aggregator/pdoAggregator.php
- classes/ETL/DataEndpoint/Mysql.php
- classes/ETL/DataEndpoint/Oracle.php
- classes/ETL/DataEndpoint/Postgres.php
- classes/ETL/DataEndpoint/aRdbmsEndpoint.php
- classes/ETL/DbEntity/Table.php
- classes/ETL/Ingestor/RestIngestor.php
- classes/ETL/Ingestor/StructuredFileIngestor.php
- classes/ETL/Ingestor/UpdateIngestor.php
- classes/ETL/Ingestor/pdoIngestor.php
- classes/ETL/Loggable.php
- classes/ETL/Maintenance/ExecuteSql.php
- classes/ETL/Maintenance/VerifyDatabase.php
- classes/ETL/Utilities.php
- classes/ETL/aRdbmsDestinationAction.php
Improve ETLv2 query debuging
Augment Loggable::logAndThrowException() to accept a list of options and customize messages based on these options. This allowed us to merge Loggable::logAndThrowSqlException() into Loggable::logAndThrowException() and improve the display of SQL in debug mode.
Also display the DataEndpoint associated with every query now and fix phpcs style issues.
**Note that commits 216aa24, 8bfbcac, 729b1da were from a local merge and have already been merged in #45.**
ETL is getting more complex pulling data from multiple databases, schemas, and files. It is important when debugging to know the queries being generated and the databases and schemas (DataEndpoints) that they are being run against.
Ran the following ETLv2 pipelines: xdcdb-jobs (with and without aggregation …
> Improve ETLv2 query debug

- README.md
- composer.json
- composer.lock
Update lock file with php-codesniffer dependency stuck to a specific version, bring all repositories in line with same version
Make sure all composer.lock files match composer 1.3.x version
ran composer install without errors.
> update composer and php-codesniffer dep

- classes/ETL/DbEntity/Query.php
- classes/ETL/Ingestor/pdoIngestor.php
Handle proper escaping of backslashes to preserve source data
Source data containing backslashes must be properly escaped to preserve the backslashes.
See #52 
Tested using SimpleDatabaseIngestor with the following source data and verified that backslashes were not preserved prior to but were after the patch.
```
'\', '\\', '\\n\\'
```
> Handle proper escaping of backslashes to preserve source data

- classes/DB/PDODBMultiIngestor.php
Escape backslashes in data fields.
Backslashes must be escaped in data fields (see https://dev.mysql.com/doc/refman/5.5/en/load-data.html).  Depending on what character directly follows the backslash a variety of issues arise.  If a field contains only a backslash it escapes the enclosing character corrupting all data that follows.
Shredded and ingested data containing a backslash.  Confirmed that the correct data was ingested.
> Escape backslashes in PDODBMultiIngestor for MySQL LOAD DATA INFILE

- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version650To660/ConfigFilesMigration.php
- classes/OpenXdmod/Migration/Version650To660/DatabasesMigration.php
- configuration/portal_settings.ini
- db/data/moddb.sql
- db/migrations/6.5.0-6.6.0/moddb.sql
- db/schema/moddb.sql
- docs/simpleSAMLphp.md
- open_xdmod/modules/xdmod/build.json
- package.json
Adds migration to remove the `parent_user_id` column from the `Users` table in the `moddb` database.
Also bumps version numbers and adds migration boilerplate.  This could be moved to a separate PR, but is needed for testing purposes.
This column is not used and causes problems with [MySQL's strict `sql_mode`s](https://dev.mysql.com/doc/refman/5.5/en/sql-mode.html) since it is `NOT NULL` and does not have a default value and no value was being set.
Manually tested migration:
- Installed Open XDMoD 6.5.0
- Upgraded to a build of this branch
- Ran `xdmod-upgrade`
- Observed that the column was removed
> Remove unused database table column (`moddb`.`Users`.`parent_user_id`)

- classes/OpenXdmod/Shredder.php
- classes/OpenXdmod/Shredder/Pbs.php
- classes/OpenXdmod/Shredder/Sge.php
- classes/OpenXdmod/Shredder/Slurm.php
- docs/configuration.md
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/LsfShredderTest.php
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/PbsShredderTest.php
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/SgeShredderTest.php
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/SlurmShredderTest.php
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/UgeShredderTest.php
Removes the `getResourceForNode` method from the shredder base class.  This method was originally intended to provide a feature where the resource name could be determined from name of a node used by a job on a given day.  This would allow for defining sub-resources within a given resource.  It was never fully implemented and the removed method effectively returned the resource name that was set for a shredder instance (since the resource name is always required by the `xdmod-shredder` command).
The tests have also been improved to ensure that the resource name corresponds to the one which is set and not the resource name that may be contained in the accounting data (which is what is expected elsewhere in the ingestion process).
Since this feature was never fully implemented it provides …
> Remove experimental shredder feature

- classes/UnitTesting/RunTests.sh
- open_xdmod/modules/xdmod/tests/runtests.sh
Changes tests scripts so that they explicitly use the `phpunit` command installed by composer.
The travis scripts set the `PATH` to include the composer vendor directory, but there is no guarantee that a developer running the tests scripts will do the same or that they will not have a different version of PHPUnit installed elsewhere in their `PATH`.  These changes ensure that the `phpunit` that is installed in the vendor directory will be used.
There may be a better way to do this, or we may not want to do it at all, so I'm open to discussion.  I do think we should do something to make sure that it's easy for developers running these scripts on the command line to know the correct version of PHPUnit is being used.
Ran updated tests scripts on the command line.
> Ensure use of PHPUnit installed by composer

- classes/DataWarehouse/Query/Query.php
- libraries/utilities.php
- Added a file logger to Query.php ( query.log )
- Added logic to the function 'execute' such that, when called and 
'sql_debug_mode' is true, the query string that is about to be executed is logged.
It allows some visibility into the queries being generated / executed by the Query class.
- I deployed the change to my cloud instance ( rr-db1 ), verified there were no issues creating the log file.
- verified that when 'sql_debug_mode' was set to 'on' queries were logged as expected. 
- verified that when 'sql_debug_mode' was set to 'off' queries were not logged as expected.
> Adding Logging to Query.php

- classes/DataWarehouse.php
- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Visualization/HighChart2.php
- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
- html/controllers/metric_explorer/get_dw_descripter.php
- html/controllers/user_interface/get_menus.php
- html/gui/js/AddDataPanel.js
- html/gui/js/common/data_warehouse/FilterStore.js
- html/gui/js/modules/Usage.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
This pull request allows related realms to be grouped together in categories. Further, it reorganizes the web client's UI to be based around categories rather than realms.
In order to prepare and present grant data addressing different focuses, the in-development Value Analytics module currently provides two realms: `ValueAnalyticsGrants`, which operates on data for individual grants as a whole, and `ValueAnalyticsGrantRoles`, which operates on each assignment onto each grant. However, presenting these realms as separate entities in the Open XDMoD web client led to confusion about what the different entities meant and where to find all of the metrics that pertained to the subject of grants.
To begin to address this problem, this pull request introduces categories. A realm may now declare …
> Organize realms under categories

- classes/ETL/Aggregator/AggregatorOptions.php
- classes/ETL/DbEntity/Column.php
- classes/ETL/EtlOverseerOptions.php
- classes/ETL/Ingestor/IngestorOptions.php
- classes/ETL/Maintenance/MaintenanceOptions.php
- classes/ETL/aOptions.php
- libraries/utilities.php
@ryanrath added a fix for the PHP 5.3 filter_var bug in xd_utilities. Remove the ETL specific filter_var fix and use new fix in xd_utilities. Also added a test for the specific case where filter_var() fails.
Cleaner code
Re-ran ETLv2 after changes were made.
> Remove ETL specific filter_var fix and use new fix in xd_utilities

- configuration/etl/etl.d/jobs_hpc.json
- configuration/etl/etl_macros.d/jobs/xdcdb_start_time_calc.sql
- configuration/etl/etl_macros.d/jobs/xdcdb_start_time_ts_calc.sql
- configuration/etl/etl_macros.d/jobs/xdcdb_wallduration_calc.sql
- configuration/etl/etl_sql.d/jobs/job_record_hpc_post_ingest_updates.sql
- configuration/etl/etl_tables.d/jobs/job_record_hpc.json
- configuration/etl/etl_tables.d/jobs/jobfact_hpc_aggregation.json
Move ETLv2 job ingest/aggregation files from xdmod-xsede to xdmod repo as a foundation for Open XDMoD cloud development.
See ubccr/xdmod-xsede#17
These files are no longer XSEDE-specific.
Re-built code and ran XSEDE job ingestion.
> Move ETLv2 job files from xdmod-xsede to xdmod repo

- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Data/ComplexDataset.php
- classes/DataWarehouse/Query/Jobs/Statistics/AverageCPUHoursStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/AverageNodeHoursStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/AverageProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/AverageWallHoursStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/NormalizedAverageProcessorCountStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/RunningJobCountStatistic.php
- classes/DataWarehouse/Query/Statistic.php
This pull request prevents metrics that cannot be accurately calculated from data that has been aggregated by fixed time periods from appearing in aggregate charts and datasets.
In the Metric Explorer, attempting to use one of these metrics on an aggregate chart will result in an error suggesting that the chart be switched to timeseries or that the metric in question be modified or deleted. In the Usage tab, since the only available option for any given chart is to switch to a timeseries chart, this is done automatically.
XDMoD should not be displaying data that isn't being calculated correctly. These metrics could be calculated correctly over arbitrary time periods if access to the raw data were readily available. However, getting access may require extensive rework, and this solves the …
> Fixed non-aggregate metrics being allowed in aggregate datasets

- tools/dev/verify_table_data.php
Add a place to keep useful development tools.
The `verify_table_data.php` script is based on the script from @plessbd and @jpwhite4 but has been extended with features that were needed to make verification of ETL changes easier. This script compares 2 tables, first the structure and then the contents. The following checks are made and if any fail the table does not match:
1. The number of columns in both tables must be the same. If a column is excluded using `--exclude-column` then that column will not be used for the comparison.
2. The type and key type for each column must be the same
3. The data in the tables must be the same such that a left join of the source to the destination on all columns (except those that were explicitly excluded) does not return empty rows in the destination …
> Add a development tools directory

- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/XdmodTestHelper.php
New keyword was omitted on exception invocation.
Attempt to throw an exception was throwing an exception.
Tested during development of integration tests for xdmod-supremm pull request 28 (https://github.com/ubccr/xdmod-supremm/pull/28/)
> Fix exception throw in XdmodTestHelper

- .eslintrc.json
- package.json
This pull request updates the style guide for JavaScript code and enforces the changes with ESLint.
The commits in this pull request:
1. Update ESLint to a newer version compatible with the latest version of the [Airbnb ES5 rules][airbnb-es5].
1. Modify the ESLint config file to use strings instead of integers for clarity (e.g. `"error"` instead of `2`).
1. Apply the [Airbnb ES5 rules][airbnb-es5]. This commit also removes redundant custom rules and ensures that conflicting custom rules are still applied. (See [this][eslint-overrides] for more information on how rule overrides work in ESLint.)
1. Tweaked custom rules further based on team preferences.
Our current style guide is a good start, but it leaves room for a number of inconsistencies. When ESLint's auto-fixer is run, it can …
> Updated style guide for JavaScript

- classes/ETL/DataEndpoint/File.php
When `verify()` was consolidated into `initialize()` in `classes/ETL/aEtlObject.php`, the call to `verify()` from `classes/ETL/DataEndpoint/File.php` was not removed. When that call is made, the system crashes. This pull request removes that call from `File`.
crashing bad. working good
I performed this fix on a test instance that uses file endpoints and verified that it no longer crashed.
> Fixed ETLv2 file endpoint verification

- classes/ETL/Maintenance/VerifyDatabase.php
Fix misspelling of utility class name.
Fix misspelling of utility class name in `VerifyDatabase.php`
Bugfix.
```
$ php etl_overseer.php -c ../../../etc/etl/etl.json -a VerifyXsedeJobReporting -n 5 -v info
2017-04-05 09:15:06 [info] Command: 'etl_overseer.php' '-c' '../../../etc/etl/etl.json' '-a' 'VerifyXsedeJobReporting' '-n' '5' '-v' 'info'
2017-04-05 09:15:06 [notice] dw_extract_transform_load start (process_start_time: 2017-04-05 09:15:06)
2017-04-05 09:15:06 [info] Loading configuration file /home/smgallo/xdmod-6.6-test/etc/etl/etl.json
2017-04-05 09:15:06 [info] Loading configuration file /home/smgallo/xdmod-6.6-test/etc/etl/etl.d/action_state_setup.json
2017-04-05 09:15:06 [info] Loading configuration file /home/smgallo/xdmod-6.6-test/etc/etl/etl.d/jobs_cloud.json
2017-04-05 …
```
> Fix misspelling of utility class name

- classes/ETL/Aggregator/pdoAggregator.php
- classes/ETL/Ingestor/pdoIngestor.php
- configuration/etl/etl_tables.d/jobs/jobfact_hpc_aggregation.json
- tools/dev/verify_table_data.php
Changes to accompany issues found in OSG modifications
See ubccr/xdmod-xsede#23
The aggregation query for job records and tasks now uses a datatype of `DECIMAL(36,4)` rather than `DOUBLE` for the `sum_wallduration_squared`, `sum_waitduration_squared`, `sum_cpu_time_squared`, `sum_local_charge_xdsu_squared`, and `sum_node_time_squared` columns. The waitduration has been defaulted to `NULL` to support cases when we do not have this information (e.g., OSG).
Several enhancements to the table comparison tool were made:
- Ability to ignore number of columns between source and destination tables. This is useful for comparing tables with added columns to baseline tables
- Ability to ignore column types between source and destination tables. This is useful for comparing data when migrating column …
> Changes to accompany issues found in OSG modifications

- open_xdmod/modules/xdmod/xdmod.spec.in
Adds a post-install script to the RPM spec file that outputs some text if the RPM is being upgraded.
After upgrading the xdmod RPM the `xdmod-upgrade` must be executed.  This is currently not done automatically because it may take hours to run or require user interaction.  This addition is intended to remind users to run this command. 
Upgraded RPM and checked for the new message.  Also did a clean install of the RPM to confirm the message is not displayed in that situation.
> Add upgrade notice post-install script to RPM spec file

- configuration/etl/etl.d/jobs_hpc.json
- configuration/etl/etl_tables.d/jobs/jobfact_hpc_aggregation.json
Remove unused columns. Add resource restrictions to XSEDE job ingestor.
Remove unused columns from XDCDB jobs aggregator. Add resource restrictions to HPC jobs aggregator so we don't remove those records from the aggregation table (i.e., OSG records are excluded from ingestion and are handled by their own ingestor so don't delete them from the aggregate table when handling the other HPC jobs).
Keeping ETL configurations consistent.
Re-ran ingestion.
> Remove unused columns. Add resource restrictions to XSEDE job ingestor.

- classes/NewRest/Controllers/BaseControllerProvider.php
Framework exceptions were being instantiated incorrectly (symfony). 
Some home-grown exceptions were also being thrown. These were replaced with Symfony framework exceptions.
Fixes bug; allows rest stack to throw exceptions.
Thoroughly exercised as part of https://github.com/ubccr/xdmod-supremm/pull/28 integration tests; working on unit test now.
Pull requests that depend on this fix are: 
- https://github.com/ubccr/xdmod-supremm/pull/28
- https://github.com/ubccr/xdmod/pull/73 (xdmod repo)
- https://github.com/ubccr/xdmod-appkernels/pull/12
> Fixed exception instantiations in BaseControllerProvider

- classes/ETL/DataEndpoint/aRdbmsEndpoint.php
- classes/ETL/Ingestor/pdoIngestor.php
- configuration/etl/etl.d/jobs_hpc.json
- configuration/etl/etl_tables.d/jobs/jobfact_hpc_aggregation.json
On a busy server, it is possible that the mysql server will close the connection on us if we are using an unbuffered query and the loading of the data takes longer than the net_write_timeout (See https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_net_write_timeout)
This may happen using an unbuffered query because the server writes result data to the connection (presumably there is some buffer) and the client reads the data, transforms it, and adds it to a load file. When the number of records hits a threshold, the files are loaded and the process does not read from the connection during loading. If loading takes longer than the net_write_timeout, the server will close the connection on us. The client will read whatever is left in the result buffer and assume that …
> Improve handling of the "MySQL server has gone away" error

- .travis.yml
See ubccr/xdmod-supremm#34.
See ubccr/xdmod-supremm#34.
> Travis: Cache npm cache directory instead of node_modules directories

- README.md
XDMoD requires two additional PHP deps to build
These deps are required to build on Ubuntu.
Until those deps are pulled in by one of the build tools, we should specify those in the README.
> Added PHP dependancies to README

- open_xdmod/modules/xdmod/build.json
The SUPReMM ETL framework was previously included in the SUPReMM Open
XDMoD module package.
Changes build configuration to include the SUPReMM ETL framework in the Open XDMoD package.
See ubccr/xdmod-supremm#40
What is referred to here as the SUPReMM ETL framework is not specific to SUPReMM and is considered part of the base Open XDMoD package.  Therefore, it should be packaged as such.
Installed Open XDMoD and the SUPReMM module before and after this change.  Compared both installations to ensure that all the same files are installed.  Also compared contents of tarballs before and after the changes to ensure the files were present where expected.
> Add SUPReMM ETL framework to Open XDMoD package

- html/gui/general/login.php
Fix the forgot password form so that it looks correct
Improve UX
Before:
After:
Verified that the form looks correctly when viewed
> fix forgot password form

- classes/OpenXdmod/Migration/Version660ToVersion700/ConfigFilesMigration.php
- configuration/portal_settings.ini
- html/gui/general/login.php
- html/gui/js/Viewer.js
- html/index.php
- templates/portal_settings.template
The non-module-capable auto_login option is removed. The behaviour now
is that a login box is created if you try to browse to a tab that is
only available to logged in users.
Preliminary changes to support deep linking into the job viewer.
Yes
> Remove auto_login option. Always prompt for login if login required.

- html/gui/js/CCR.js
- html/gui/js/Viewer.js
- html/unit_tests/coverage.html
- html/unit_tests/index.html
- html/unit_tests/spec/.eslintrc.json
- html/unit_tests/spec/CCRTokenizeSpec.js
This change removes the unnecessary duplicate tokenize code. It also
replaces the function with a much simpler one that has full unit test
coverage.
General cleanup in preparation for deep linking support.
Ran the javascript unit_tests to confirm that the location hashes are parsed correctly. Ran code coverage
tools to confirm the new code has 100% test coverage (although the tools cannot check that all possible states have been hit in the regex state machine).
> Remove redundant tokenize code

- html/gui/js/modules/metric_explorer/MetricExplorer.js
- Typing a '%' character in a form field contained within the
MetricExplorer chart options menu would not have the desired effect. Instead,
the whole menu would close and the '%' character would not be recorded in the
field. The reason for this was because of an interaction between the FireFox
browser and the Ext.KeyNav / Ext.MenuNav components. In FireFox, when the '%'
character was entered into a form field contained within a menu, the
Ext.KeyNav.relay function would fire, interpret the keyCode value of '37' to
be the 'left' key, for which the Ext.MenuNav component has a handler. This
handler would then merrily went about closing the menu ( because that's what
you do when you press the left key? I'm guessing to support navigating a menu
/ toolbar via the arrow keys. ). Now, when Ext …
>  Resolving Firefox MetricExplorer menu bug

- .travis.build.sh
- html/unit_tests/.eslintrc.json
- html/unit_tests/phantom.js
Have javascript unit tests run as part of travis using phantomJS to do testing
Allow javascript unit test failures to prevent merging
ran test travis builds on my own branch
> Add Auto running of javascript unit tests

- open_xdmod/build_scripts/build_package.php
- When executing a local deploy ( as opposed to pulling down the source from a
git repo ) this script consistently runs out of memory. Bumping the limit to
256M alleviates this issue.
The script was running out of memory, now it does not. 
- Manual testing, running a local deploy completes successfully
- Manual testing, running a remote deploy ( from git ) completes successfully
> Bumped build_packager script memory limit

- html/gui/js/modules/metric_explorer/MetricExplorer.js
- Back porting fix for NavKey handlers being executed for non-NavKey key presses.
Making sure that this fix gets into 6.6 as well as 6.7
- Manual Testing 
- Automated Test added to xsede/tests/automated
> Back Porting 6.7 Metric Explorer fix to 6.6

- html/gui/js/modules/job_viewer/JobViewer.js
- html/unit_tests/coverage.html
- html/unit_tests/index.html
- html/unit_tests/spec/.eslintrc.json
- html/unit_tests/spec/JobViewerSpec.js
The job viewer activate function needs to be updated to support the deep
linking feature. A review of the existing code found some dead code
paths and redundant code. This is removed in this pull request. 
Note that I had to add an eslint override to allow calls to the existing underscore prefix function. The eslint rule is poorly implemented because it prevents _calls_ to badly named existing functions, rather than preventing function declarations.
prep work for deep linking support.
Added unit tests for the replacement compareNodePath() function (this function has 100% unit tests coverage).
Manually tested that the job viewer navigation works identically in Firefox linux and Chrome linux.
> Update JobViewer activate function in preparation for deep linking code.

- classes/DB/PDODBMultiIngestor.php
Add a character set specification for XRAS ingestors to handle 4-byte UTF8 data ingested from Postgres.
See also PR ubccr/xdmod-xsede#31.
The XRAS data has text likely copied from word processing files that contains UTF8 characters. [Postgres UTF8](https://www.postgresql.org/docs/9.1/static/multibyte.html) character sets support 4-bytes but [MySQL UTF8](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb3.html) supports only 3 bytes unless the [UTF8MB4](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html) character set is used.
From the MySQL [LOAD DATA INFILE](https://dev.mysql.com/doc/refman/5.5/en/load-data.html) documentation:
When loading the data on one host into a database on another host, the server uses the character set indicated by the …
> Add 'character set' specification for XRAS ingestors

- html/gui/js/modules/metric_explorer/MetricExplorer.js
The Metric Explorer has a help graphic that is active when there is no data to display (for example, when a new chart has been created). If a user chooses an invalid configuration while this graphic is active, the error message will still be written on the chart, but the chart is hidden by the graphic. This pull request ensures that the chart will not be hidden if an error message is written on it.
It is important to inform users why their settings are invalid and not just appear to do nothing.
Ran automated UI tests and verified that they ran the same as before. Performed manual testing in Chrome and Firefox to ensure other Metric Explorer functionality was not impacted.
> Metric Explorer: Fixed errors not displaying if help graphic active

- classes/OpenXdmod/Build/Config.php
- classes/OpenXdmod/Build/Packager.php
- open_xdmod/modules/xdmod/xdmod.spec.in
Adds support for a pre-release build configuration option.  The pre-release tag is used for versioning of alpha/beta/release candidate packages.
Comments have also been added to the `OpenXdmod\Build\Config` class.
Version/release numbers generated by our current process result in incorrectly versioned RPM packages.  e.g.:
For the configuration:
- version: 5.6.0rc1
- release: 0.1
Results in:
- Tarball: xdmod-5.6.0rc1.tar.gz
- CentOS 6 RPM: xdmod-5.6.0rc1-0.1.el6.noarch.rpm (note that rc1 is before 0.1)
The proper CentOS 6 RPM name is: xdmod-5.6.0-0.1.rc1.el6.noarch.rpm (note that 0.1 is defore rc1)
Moving "rc1" into the "release" portion of the configuration would fix the RPM, but then it is not used as part of the tarball (since that is not intended to be used as part of the tarball …
> Add pre-release build option

- html/gui/js/modules/job_viewer/JobViewer.js
The algorithm that determines whether a node should be selected
was incorrectly broken in the cleanup task in #117. This pull request
restores the original code.
manual revert of erroneous change
Ran the automated UI tests 
XDMoD
General
✓ Verify Logo and Title (859ms)
Login
✓ Click the login link (642ms)
✓ Should Login (345ms)
✓ Display Logged in Users Name (698ms)
Job Viewer
✓ Selected (739ms)
✓ Has Instructions (12ms)
✓ Instructions look the same as previous run (1702ms)
Quick Lookup
No results
✓ Click the search button (188ms)
✓ Perform a basic search (478ms)
✓ Have no results (343ms)
✓ Cancel search (90ms)
With results
✓ Click the search button (43ms)
✓ Perform a basic search (1021ms)
✓ View saved job then delete it. (2692ms)
Advanced Search
Simple single filter lookup
✓ Click the …
> Fix the node selection algorithm broken in #117

- docs/index.md
Updates Open XDMoD overview text.
Changes requested by Thomas Furlani.
Ran `remark` on file and viewed changes using GitHub to check for errors.
> Update Open XDMoD overview

- classes/NewRest/Controllers/MetricExplorerControllerProvider.php
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- Change to Metric Explorer javascript updates the timestamp on the current record of the queries store when a chart is saved.
- Change to Metric Explorer controller parses the current timestamp from the request object and saves it, when saving the "query" associated with an existing chart. This step was previously missing.
Addresses xdmod6.6 bug: https://app.asana.com/0/14787510600562/335273737938313
Tests run by hand:
- Alter existing ME charts, check displayed timestamp before and after saving and reloading.
- Verify that no change is made to proper behavior: save existing chart under new name
- Verify that no change is made to proper behavior: create new chart
Ran all unit and integration tests
> Fix chart last modified date (metric explorer)

- README.md
Found another dependency that isnt mentioned.
Composer doesn't notify the user of this missing dep, but it complains of not having executed an unzip command.
> Updated README with additional php extension dep.

- classes/DataWarehouse/Access/Usage.php
Fix bug where Usage Export dialog 'Show chart title' box had no effect.
Fix functionality of the "Show chart title" box on the Usage tab Export dialog. In the Metric Explorer, if the "Show chart title" box on the Export dialog is checked then the chart title is not shown. If there is a subtitle (added due to a filter, for example) then the subtitle is promoted to the title (explicitly set in ` HighChart2::setChartTitleSubtitle()`). The Usage tab now mimics this functionality.
Bugfix.
Opened chart in metric explorer, added a filter, and verified that the "show chart title" checkbox properly removed the title and promoted the subtitle. Opened a chart in the Usage tab and verified that the "show chart title" checkbox properly removed the title and promoted the subtitle. Also clicked "open in …
> Fix bug where Usage Export dialog 'Show chart title' box had no effect

- html/gui/css/MetricExplorer.css
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- html/index.php
Cosmetic improvements to the Metric Explorer Load Chart dialog.
In Load Chart menu:
- Display the dirty chart icon next to Last Modified Date for unsaved chart records. This replaces the text "Unsaved", matches the appearance of the Save drop-down, and preserves space in the Load Chart menu.
- For charts with long names (>72 characters), display chart name in tooltip.
These changes were requested here: https://app.asana.com/0/14787510600562/75162375641137
These changes are strictly cosmetic. They have been tested by hand to ensure they behave as intended, and to ensure they don't disturb existing functionality. Existing, complete tests pass.
> Load Chart drop-down menu: cosmetic improvements

- classes/ETL/DataEndpoint/File.php
- classes/ETL/DataEndpoint/Filter/ExternalProcess.php
- classes/ETL/DataEndpoint/JsonFile.php
- classes/ETL/DataEndpoint/aStructuredFile.php
- classes/ETL/DataEndpoint/iDataEndpoint.php
- classes/ETL/DataEndpoint/iFile.php
- classes/ETL/DataEndpoint/iStructuredFile.php
- classes/ETL/DbModel/Column.php
- classes/ETL/DbModel/Index.php
- classes/ETL/DbModel/Join.php
- classes/ETL/DbModel/Table.php
- classes/ETL/DbModel/Trigger.php
- classes/ETL/Ingestor/StructuredFileIngestor.php
- composer.lock
- configuration/etl/etl.json
- libraries/utilities.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/FileTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/StructuredFileTest.php
- tools/dev/verify_table_data.php
This PR is a rewrite of the StructuredFile data endpoint to support ingesting Eucalyptus accounting records. A number of small debugging enhancements implemented during testing are also included.
This PR is a prerequisite for ubccr/xdmod-value-analytics#14.
Structured files contain data in a known (structured) format including CSV, tab-delimited, and JSON. Records are separated by an optional Record Separator (RS) and individual fields may be separated by a Field Separator (FS) if the format allows or requires it (e.g., CSV and TSV). Typically, we will read a structured file by iterating over the records and operating on the fields within the record.
This PR implements a `StructuredFile` data endpoint that implements `Iterator`, allowing ETL actions to parse the file and then simply …
> Rewrite of StructuredFile data endpoint to support Euca ingest

- html/gui/js/modules/job_viewer/AnalyticChartPanel.js
- html/gui/js/modules/job_viewer/ChartPanel.js
Ensure the Highcharts charts are destroyed properly when the container
panel is removed or the chart is replaced.
memory leaks === bad
Manually opened loads of charts in the job viewer then closed them again. Then ran the following in the firefox console to list the current chart objects.
```
for(var i=0; i < Highcharts.charts.length; i++) { if (Highcharts.charts[i]) { console.log(Highcharts.charts[i].renderTo);}}
```
* Bug fix (non-breaking change which fixes an issue)
> Fix memory leak in Job Viewer.

- etl/js/lib/mysql.js
Make the SQL work with the federation, and more consistent with current sql schema files
xdmod setup and comparison of tables created
> Update js etl

- classes/ETL/DbModel/Query.php
Fix newlines for ORDER BY and GROUP BY in ETL DbModel
A new line was missing when both an ORDER BY and GROUP BY was specified in a constructed ETLv2 query.
Bugfix
Tested query generation with only GROUP BY, only ORDER BY, and both by modifying the OSG job reporting verification action.
```
php etl_overseer.php -c ../../../etc/etl/etl.json -a VerifyOsgJobReporting -t -v debug -n 5
```
Generated queries:
```
SELECT
r.id AS id,
r.name AS name,
r.code AS code,
max(maxts.max_ts) AS last_entry_date,
5 AS number_of_days
FROM `federated_osg`.`resourcefact` AS r
JOIN `federated_osg`.`raw_jobs_test` AS j ON r.code = 'OSG'
JOIN ( SELECT 2799 as resource_id, max(j.ts) as max_ts FROM federated_osg.raw_jobs_test j ) AS maxts ON maxts.resource_id = r.id
WHERE maxts.max_ts < (NOW() - INTERVAL 5 DAY)
AND …
```
> Fix newlines for ORDER BY and GROUP BY in ETL DbModel

- .travis.install.sh
- etl/js/package-lock.json
- package-lock.json
This pull request adds the lock files generated by npm v5 to this repo. This will lock down the npm dependencies in a manner similar to how Composer locks dependencies.
It also updates a Travis setup script to ensure npm is up to date.
If approved, similar pull requests will be opened for other XDMoD repos.
npm v5 automatically generates `package-lock.json` files similar to how Composer generates `composer.lock` files. Like the latter's lock files, they are designed to ensure that consistent environments are generated across instances and are intended to be checked into source control.
I verified that tools pulled in by npm continue to work, and I verified that the changes to the Travis script work as intended.
> Added npm lock files

- .travis.yml
- composer.json
- composer.lock
- open_xdmod/modules/xdmod/tests/artifacts/.gitignore
- open_xdmod/modules/xdmod/tests/artifacts/update-artifacts.sh
- open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/ConfigurationTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/EtlConfigurationTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/Rfc6901Test.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/FileTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/StructuredFileTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DbModel/DbModelTest.php
- open_xdmod/modules/xdmod/tests/runtests.sh
This pull request moves responsibility for retrieval of `xdmod-test-artifacts` from Composer to the scripts that use it.
Copying/paraphrasing from an email exchange between @smgallo, @jpwhite4, and I:
Composer's design is built around pulling in runtime and development software packages in a consistent, well-considered manner, and the lock file's use of hashes for both individual dependencies and the contents of the lock file is meant to help guard against changes that haven't been tested. For example, if two pull requests both change the lock file and one gets merged, the other will be in conflict with the target branch due to the lock file's content hash being changed by both pull requests. As part of resolving the conflict, the outstanding pull request's lock file will need to be …
> Use Git to manage XDMoD test artifacts

- html/gui/js/modules/job_viewer/JobViewer.js
The assist panel did not show when the job tabs were removed due to a
right-click delete search in the search history tree. This was because
the tab.removeAll() function did not fire the close event. Changed the
code to listen to the destroy event which is always fired.
Bug fix
Steps to test:
- Open one or more jobs in the job viewer
- in the searhc history tree right click on a search node and select
'Delete Search'
- Click 'yes' when prompted
With the original code the main tab panel is blank. This change results
in the assist panel being displayed again.
> Ensure assist panel shows when there are no job tabs.

- classes/ETL/DataEndpoint.php
- classes/ETL/DataEndpoint/DirectoryScanner.php
- classes/ETL/DataEndpoint/File.php
- classes/ETL/DataEndpoint/aDataEndpoint.php
- classes/ETL/DataEndpoint/aStructuredFile.php
- classes/ETL/aOptions.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/DirectoryScannerTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/StructuredFileTest.php
This is the initial implementation of the DirectoryScanner data endpoint to support ingestion of cloud data.
The Directory Scanner Data Endpoint is designed to be a drop-in replacement for a Structured File
endpoint. It is designed as a wrapper around the Structured File endpoint that allows a Structured
File endpoint to be instantiated for each file in a directory (or subdirectory) matching a specified
criteria. It supports directory and file name pattern filtering as well as filtering on last
modified dates. The Directory Scanner implements the `Iterator` interface and the iteration spans
the union of the records in each of the files matching the criteria. For example, if 2 files are found in a
directory then the Directory Scanner iterator will span all of the records in both files. …
> DirectoryScanner data endpoint

- classes/DataWarehouse/Query/Exceptions/AccessDeniedException.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
The existing access-denied error message was a statement almost, but not quite entirely unlike a useful   comprehensible message. This one is hopefully less so.
Improve UI
Added integration test.
- My code follows the code style of this project as found in the **CONTRIBUTING** document.
- I have added tests to cover my changes.
- All new and existing tests passed.
> Improve the accesss denied error message.

- classes/DataWarehouse/Access/Common.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
The checkDateParameters function was trying to throw a non-existent \Datawarehouse\Access\Exception object. Change this to throw the appropriate exception that actually exists!
Added integration tests to check the change. Note that if we ever add an elephants group by then we will have to update this test case.
- My code follows the code style of this project as found in the **CONTRIBUTING** document.
- I have added tests to cover my changes.
- All new and existing tests passed.
> Fix the start and end time validation code.

- classes/ETL/DataEndpoint.php
- classes/ETL/DataEndpoint/DirectoryScanner.php
- classes/ETL/DataEndpoint/File.php
- classes/ETL/DataEndpoint/JsonFile.php
- classes/ETL/DataEndpoint/Mysql.php
- classes/ETL/DataEndpoint/Oracle.php
- classes/ETL/DataEndpoint/Postgres.php
- classes/ETL/DataEndpoint/Rest.php
- tools/etl/etl_overseer.php
Allow DataEndpoint singleton to auto-discover available data endpoints
Rather than require a developer to modify `ETL\DataEndpoint.php` and explicitly list each available data endpoint and it's configuration code, we now allow the `DataEndpoint` singleton to automatically discover what data endpoints are available. As per PSR-4 the contiguous sub-namespace names after the "namespace prefix" (`ETL` in our case) correspond to a subdirectory within a "base directory", in which the namespace separators represent directory separators. From this, we can assume the `ETL\DataEndpoint` sub-namespace is in the `DataEndpoint` subdirectory relative to where the `DataEndpoint` singleton class is defined. Using this knowledge we use reflection to recursively examine each file in the `DataEndpoint` …
> Allow DataEndpoint singleton to auto-discover available data endpoints

- shippable.yml
Add shippable configuration that builds the RPM, installs and runs the
integration tests. The tests are run in a Centos 7 container that
contains the reference data.
tests === good
Yes
> CI for RPM build and integration tests.

- classes/NewRest/Controllers/WarehouseControllerProvider.php
- html/gui/js/modules/job_viewer/ChartTab.js
- html/gui/js/modules/job_viewer/GanttChart.js
- html/gui/js/modules/job_viewer/JobViewer.js
- html/index.php
Change the Peers node in the search history so that it opens a new tab with an interactive graphical display of the job's peer jobs (i.e. the jobs that ran on the same shared hardware). The individual job peers no longer show as leaf nodes because this display was not useful and did not scale when there were lots of job peers. Jobs with many peers are now handled using the paging toolbar in the graphical display.
These code changes:
- Add new REST endpoint to retrieve the peer data
- Change the peer tree node type and metadata
- Add new Gantt chart class
- Add new base class for job viewer chart tabs.
Note that the new ChartTab base class is intended to be used as the base class for all job viewer timeseries plots. This should significantly reduce the amount of cut-and-paste boilerplate …
> Add gantt chart view of job peers

- classes/NewRest/Controllers/WarehouseControllerProvider.php
- html/gui/js/modules/job_viewer/JobViewer.js
- html/gui/js/modules/job_viewer/SearchHistoryPanel.js
Right clicking on a job in the search history tree now gives a context
menu with the option to get a sharable link. This URL can be used to
directly link to a given job for all users of the system (although the
job permissions are not changed, so only those users that have
permission will be able to actually view the job data.
Job search based on the local job id is also possible, but requires the
knowledge of the primary key for the resource that ran the job. This
feature is intended for developer use (e.g. to link to the job viewer
from an external system).
Commonly requested feature
Manually tested loading the links in firefox Linux and chrome Linux. Tested following combinations:
- Not logged in, then login w/ CD account (confirm that job loads)
- Not logged in, then login w/ unpriv …
> Added ability to link directly to jobs.

- html/gui/js/modules/job_viewer/GanttChart.js
Job peer clicks now use the job search action that was added in pull
request #156. The benefit of this mechanism is that it gracefully
handles the case where the user does not have access to the underlying
job data.
> Switch peer click to use the run_search_action mechanism.

- classes/ETL/Configuration/JsonReferenceWithMacroTransformer.php
Changes a variable name.
Tried using JSON references and received this notice:
```
PHP Notice:  Undefined variable: localConfigObj in /opt/xdmod/share/classes/ETL/Configuration/JsonReferenceWithMacroTransformer.php on line 32
```
No tests.
> Fix undefined variable name

- classes/ETL/LockFile.php
Change ETLv2 file locking to use flock
The current ETLv2 file locking uses a pid in the lockfile to determine if a process is currently running and using the lockfile. This causes a problem for processes using moderate amounts of memory because PHP hits the script memory limit when attempting to fork/exec to run the `ps` command. This PR changes the behavior to use `flock()` instead.
PHP script out of memory errors.
Tested running an ETL pipeline
- Single pipeline running at a time
- Two of the same pipelines running at the same time
- Kill a pipeline and observe proper lockfile cleanup
- @ryanrath confirmed that memory errors are no longer present
> Change ETLv2 file locking to use flock

- html/gui/js/modules/job_viewer/JobViewer.js
When the user clicked through from the metric explorer or via a peer
click or from a shared link there was no visual indication that the
borwser was loading data. This adds a load mask whenever these clicks happen.
The reviewer with a keen eye will notice that new Ext.History.add() callbacks have been added to the error dialog box OK button. The reason for this is that this guarantees that, after an error, the panel is reloaded in a safe state and the load mask will be cleared.
Improve UI
- check mask works with metric explorer click through
- checked mask works with peers click through
- checked mask is cleared when processing an access denied external link
- check mask is cleared when processing a no jobs found external link.
- New feature (non-breaking change which adds functionality) …
> Add load mask for the internal search events.

- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/MetricExplorerTest.php
- open_xdmod/modules/xdmod/integration_tests/runtests.sh
- open_xdmod/modules/xdmod/integration_tests/secrets_TEMPLATE
- shippable.yml
The new CI image has multiple user accounts defined. This updates to the
new image and add some tests that exercise those user accounts.
Also update the secrets_TEMPLATE to reflect the expected user accounts that should exist on the test system.
testing
yes
- New tests
> Update CI image to latest version. Add new tests

- classes/ETL/LockFile.php
Improve handling of cases when no lock directory or lock file prefix are specified. Rather than using the current directory when a lock directory has not been provided, use the system temp directory. Default to a lock file prefix of "etlv2_" but allow specifying an empty string for no prefix. This eliminates the case where the code assumes that the current directory is the lock directory and "cleans" files that are not associated with a running process.
Yes
> Improve handling of lock handling defaults

- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-setup.tcl
- shippable.yml
Shippable tests now run two scenarios:
- A fresh rpm install of XDMoD
- An upgrade of XDMoD from the most recent production release
yes
> Add support for testing fresh install as well as upgrade.

- html/gui/js/CCR.js
- html/gui/js/ContactDialog.js
I increased the maximum number of characters allowed in the 'Name' field of the contact forms.
I changed the hard-coded number for maximum character count (100) allowed in the 'Name' field of the contact forms to 130.
If a user had a first and last that is the maximum number of characters long (50 each), and then tried to fill out a contact form, it would say underneath the 'Name' field that the maximum number of characters (100) has been exceeded because the form automatically adds the first name, a space, then the last name (totaling 101).  This would force the user to have to delete characters in their name.  I increased the maximum number of characters allowed in the field as a simple fix and now any user that would have a maximum length first and last name can easily fill out a …
> fixed bug by increasing character count

- html/controllers/mailer/contact.php
- html/controllers/user_admin/create_user.php
- html/controllers/user_admin/pass_reset.php
- html/controllers/user_auth/pass_reset.php
I removed some code pertaining to catching errors with PHPMailer objects.
Since PHPMailer objects can throw phpmailer exceptions, some error handling code is not needed because it is redundant.  Since we catch all exceptions using a generic exception, getMessage() and ErrorInfo will provide the same message, but from different sources.  Another reason to delete ErrorInfo is because if the error occurs in the initMailWrapper, a mail object will not exist, and therefore ErrorInfo will be useless. getMessage() would still be able to provide us with the same error response ErrorInfo would normally provide us, so ErrorInfo is not needed.
I (purposely) caused a mail-related error with only getMessage printing the error, and then with only ErrorInfo printing the error, and the messages were the …
> Bug fix - removed some Mail code

- classes/DataWarehouse/Query/Jobs/Statistics/AverageWallHoursStatistic.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/UsageExplorerHelper.php
- Also update help text to explain what is being displayed.
- Also add an integration test that confirms that the aggregate plot data
is correct.
https://ubccr.freshdesk.com/helpdesk/tickets/7556
Of course.
> Revert change that disabled Walltime Per Job aggregate plot

- classes/DataWarehouse/Access/Usage.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
There was code in the usage explorer that controls whether the error bar tick boxes were displayed, but inexplicably it was not being sent the correct information. Perhaps this was a bug introduced when the code was change to use the metric explorer backend? 
Fix annoying bug where the error bards tick boxes could be ticked even when plotting data that has no error bars.
Asana issue:
https://app.asana.com/0/search/389297140308050/71363948851100
Naturally.
> Make Error bars tick box hidden when not applicable.

- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/loginPage.page.js
- There was an issue running the tests under *nix / Firefox that occurred due to
Firefox not switching back to the default frame context which lead any further
tests to fail ( as it would not be able to locate anything ).
Because tests would not run on *nix / Firefox
Ran full test suite under Firefox / Chrome
> Resolving issue with tests not running on *nix/Firefox

- classes/XDUser.php
- per http://php.net/manual/en/function.unset.php
"It is not possible to unset $this inside an object method since PHP 5."
- that and the Travis tests were failing on php7.1 ( but not 5.3, 5.4, 7.0 )
#justphpthings
Getting the Travis tests to pass for php7.1
pushed these changes to a branch w/ Travis enabled, watched all the tests pass this time as opposed to all of the tests except for the ones run under php7.1.
> Removing "impossible" code

- .travis.build.sh
- Fix bug where new files were not being checked by the php syntax
checker.
- Fix bug where javascript files were being scanned with eslint with no
rc file. This causes the ES6 compliant files to be erroneously marked
as errored.
Note that the javascript file syntax checking is performed in the style
tests.
> Fix travis build script.

- classes/ETL/Aggregator/DummyAggregator.php
- classes/ETL/Ingestor/DummyIngestor.php
- classes/ETL/Ingestor/pdoIngestor.php
- classes/ETL/Maintenance/TestAction.php
- classes/ETL/Maintenance/VerifyDatabase.php
Fix syntax error and define abstract methods in subclasses
When the abstract methods `performPreExecuteTasks()` and `performPostExecuteTasks` were moved up into `aAction` `aRdbmsDestinationAction` some classes that directly extended `aAction` were not properly updated. Also fix syntax error in `pdoIngestor` logging.
Bugfix
Ran tests.
> Fix syntax error and define abstract methods in subclasses

- open_xdmod/modules/xdmod/automated_tests/check-version.js
- open_xdmod/modules/xdmod/automated_tests/package-lock.json
- open_xdmod/modules/xdmod/automated_tests/package.json
Add a node version check for the automated tests.
A few people when running the automated tests tried to use a different version of node than what is needed by the automated tests.
ref: https://medium.com/@adambisek/how-to-check-minimum-required-node-js-version-4a78a8855a0f
> added a check for node version >6

- html/gui/js/modules/metric_explorer/MetricExplorer.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.page.js
- Add new test that creates and saves a chart
- Update one of the test suites so that it actually checks that the
charts are correct and runs consistently without having to add pause()
calls
- Also add a couple of id's to metric explorer menu objects to make
testing easier.
Note that the existing other tests have been left as is. These need
to be improved.
testing
yes
> Update metric explorer tests so they work.

- classes/OpenXdmod/Ingestor/Shredded/Jobs.php
- docs/faq.md
Changes ingestor SQL query to exclude jobs with a start or end time that is 0.
Jobs with zero start time should not be included in the data warehouse.
Shredded and ingested data containing jobs with zero start time.  Observed that before the change there were rows in `modw.jobfact` with `start_time_ts` zero before the change, but none after.
> Prevent ingestion of jobs with 0 start or end time

- configuration/linker.json
- configuration/linker.php
- open_xdmod/modules/xdmod/build.json
This pull request allows modules to specify PHP autoloaders and include paths using JSON config files in `etc/linker.d`.
XDMoD requires additional PHP libraries beyond Open XDMoD's requirements. This pull request allows those libraries to be used without having to directly reference them in Open XDMoD.
Deployed modified code and verified that the instance worked as expected. Modified deployments with debug code to verify that the final include path stayed identical to the path before this change.
> Modified PHP linker to use configurable autoloaders and include paths

- bin/acl-config
- configuration/etl/etl_sql.d/acls/xdmod/create_public_user.sql
- Due to the inability of MySQL to handle UTF-8 -> latin1 coercion ( which
mariadb apparently has no problem with ). We cast all values that are provided
as strings to 'BINARY' during comparison with column values that are stored as
latin1 ( Which are also cast to BINARY ). This was done for the following files:
- acl-config
- create_public_user.sql
When executing these scripts against a MySQL box the queries involved errored out against a MySQL db but not against a MariaDB instance. 
Manual Testing: 
- select a query that is currently failing due to illegal mix of collations error.
- execute: SELECT COLLATION('dfsdf');
- this will tell you what collation is being used for string literals for your db.
- execute: ``` 
SELECT table_schema, table_name, column_name, character_set_name, …
```
> MariaDB vs MySQL adaptations

- html/controllers/mailer/contact.php
I took the hard coded signature string of the project team and moved it into the config.
This signature can now be used in more than one place without having to be hard coded, and reduces the amount of hard coded values.
I sent completed contact forms via email with the signature coming from the config rather than using a hard coded value.
> relocated string to config

- classes/OpenXdmod/Shredder/Pbs.php
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/PbsShredderTest.php
This pull request adds support for PBS/Torque logs where the host of a job is not included in the job's ID string. This log data was already being ignored in favor of the resource specified when invoking the shredder, so removing it from this function and the arrays it returns does not have any side effects.
This allows Torque logs that would otherwise cause errors to be successfully ingested.
I successfully ingested real-world Torque logs with this change that were causing errors without this change. I also added a new unit test for this case.
> PBS Shredder: Handle case where job hostname is not part of ID string

- classes/ETL/Aggregator/aAggregator.php
- classes/ETL/Configuration/JsonReferenceTransformer.php
- classes/ETL/DataEndpoint/DirectoryScanner.php
- classes/ETL/DataEndpoint/JsonFile.php
- classes/ETL/DataEndpoint/aStructuredFile.php
- classes/ETL/DataEndpoint/iComplexDataRecords.php
- classes/ETL/DataEndpoint/iStructuredFile.php
- classes/ETL/DbModel/Column.php
- classes/ETL/DbModel/Table.php
- classes/ETL/Ingestor/StructuredFileIngestor.php
- classes/ETL/Ingestor/aIngestor.php
- classes/ETL/Ingestor/pdoIngestor.php
- classes/ETL/JsonPointer.php
- classes/ETL/Loggable.php
- classes/ETL/Maintenance/ExecuteSql.php
- classes/ETL/Utilities.php
- classes/ETL/aAction.php
- classes/ETL/aOptions.php
- classes/ETL/aRdbmsDestinationAction.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/DirectoryScannerTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/JsonPointer/JsonPointerTest.php
Support references into complex source records such as JSON objects, improve verification of ETLv2 configuration files, add support for ETL variables in source fields.
Structured file endpoints may support complex data records where the value of a field is not a
scalar but an array or an object (e.g., a JSON object). These require a method for handling complex
records and addressing individual fields within those records during the ingest process. Source
field names specified in an action's destination field map may be simple scalars (e.g., simply the
name of the source field) or references to data with a complex record with a format that is specific
to the particular endpoint (e.g., JSON pointers for referencing data in a JSON object). The `DirectoryScanner` endpoint is configurable and …
> Support references into complex source records such as JSON objects

- classes/ETL/EtlOverseer.php
- tools/etl/etl_overseer.php
When calling `exit()` with a string you cannot also return an exit status of 1. Log and write errors to `STDERR` and call `exit(1)` to indicate a failure.
Tested with and without JSON syntax errors during action verification.
> Fix ETL overseer exit status

- tools/etl/etl_overseer.php
This pull request removes PHP's memory limit when invoking ETLv2 through `etl_overseer.php`. It uses an approach taken by some other Open XDMoD scripts, such as `xdmod-ingestor`.
With default PHP settings on CentOS 7 and a sufficiently-complex chain of ETL actions, ETLv2 can run out of the memory PHP has allocated for it.
Ran a set of ETL actions that was running out of memory before this change was made and verified that the change resolved the issue.
> ETLv2: Removed memory limit from main script

- .travis.install.sh
- .travis.yml
php 5.3.3 is old, we are not going to be supporting it and travis was having issues.  It still is, but this mitigates it to some degree.
Remove the tests for 5.3.3, remove the distribution being forced to precise, update to allow pear to install packages properly on php 7.0.7
Make things better
Lots of builds to get travis to not yell
> remove php 533 from travis testing

- html/gui/js/CCR.js
Discovered a small bug during 7.0 testing. If the 'About' tab is the first tab you visit after loading XDMoD, while using Chrome, the 'activate' listener would error out due to the Ext.History.getToken() function returning: null. On Firefox the function returns "null" and does not error out. 
It's good to have consistent behavior across browser. 
Manual Testing: (Chrome) 
- Navigate to XDMoD ( ensure that there is no hash, so just https://<xdmod_address>/
- Click the 'About' Tab
Expected Outcome:
- That the first item in the left hand navigation pane is automatically selected.
> 7.0/fix about tab

- .travis.install.sh
- .travis.yml
Travis has issues with php 5.3.3 since this is no longer going to be supported after 7.0, remove it from the 7.0 branch testing automatically, any bug fixes need to be verified separately to make sure the build still works.
> Remove 5.3.3 from travis builds

- classes/ETL/Configuration/EtlConfiguration.php
- classes/ETL/Ingestor/pdoIngestor.php
- html/about/publications.html
- html/about/team.html
- html/about/xdmod.php
- html/gui/js/CCR.js
Always regenerate source query string prior to execute to ensure modified ETL variables are properly applied.
**Note that this also includes updates made to the 7.0 branch during testing**
The Google SQL parser does not handle complex queries well so we need the ability to specify the source record fields in a child class that overrides `pdoIngestor::getSourceQueryString()` to set the query string. In addition, if the query defined in `getSourceQueryString()` makes use of ETL variables/macros, those variables must be re-applied prior to each execution. For example, if we are chunking a ingestion long period into year chunks.
Also ensure that the data endpoints are registered for actions that are not explicitly marked as enabled (now that actions are enabled by default).
Required to …
> Regenerate source query string prior to execute

- classes/CCR/DB/PDODB.php
- classes/DataWarehouse/Query/Query.php
- classes/NewRest/XdmodApplicationFactory.php
- libraries/response.php
This pull request adds SQL debugging information to responses sent by the server when an unhandled exception occurs. (This data is only included if both debug mode and SQL debugging are enabled.)
Before the commit adding this feature, there is a commit that consolidates the logic for determining if SQL debugging is enabled. This refactoring makes the SQL debugging code simpler to interact with.
When trying to figure out why an error occurs, having the SQL queries and parameters that were used is helpful.
For the refactoring, I tested all combinations of general and SQL debug options being enabled or disabled and verified that SQL debug data was only being sent when both options were enabled. For the feature, I verified that the SQL debug data was included when an unhandled exception …
> Add SQL debugging info to exception responses

- html/gui/js/modules/job_viewer/JobViewer.js
The existing code used the half-baked CCR.encode function to try to
encode data for a rest call. This change uses the ExtJS library function
that encodes the parameters correctly.
Bug fix
Steps to reproduce / verify:
1) Create metric explorer chart with a '#' symbol in the chart title; Add some supremm data
2) Click show raw data in the chart; Click on a job in the "raw data" window and confirm that job viewer loads and has a search node with the aforementioned chart title.
3) Go back to the metric explorer and click on another job. 
4) Confirm that the job viewer loads again and the second job appears under the same tree node as the first one (the buggy code would incorrectly create a duplicate search node).
> Use the Ext.ajax API call correctly.

- classes/NewRest/Controllers/MetricExplorerControllerProvider.php
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/MetricExplorerTest.php
The chart name field could have been used to inject html into the page. This
pull request addresses this issue.
Notes:
The 'New Chart' dialog already htmlEncoded the chart name so any charts that we created
using this mechanism using the old code will be displayed exactly the same (except of course the
display bug in the chart menu is fixed).
The code change on the server will prevent any existing saved charts with embedded html
from being executed. These charts will obviously have the name appear different in this
new code, by design!
1a) Create a chart name with injected img and script tags using old code
2a) update to new code and confirm that the injected script is not run and the raw html gets displayed instead.
1b) Try to use the Name text box to enter html code. Confirm that the …
> Make the Chart Name field html 'clean'.

- bin/acl-config
- classes/OpenXdmod/Build/Packager.php
- classes/Xdmod/Config.php
Configuration files such as those in `roles.d` are named for the module that they support. For example, supremm.json and value-analytics.json. Modules are named using an "xdmod-" prefix such as "xdmod-supremm" and "xdmod-value-analytics". To attempt to link a module to its corresponding files, the current code uses the module name and splits on a "-" taking the 2nd array element after the split as the module name. This fails if the module name contains more than one "-" as xdmod-value-analytics does. This update finds the first occurrence of "-" and uses the entire string after that as the module name (less any extension).
A module may also provide more than one file in roles.d. For example, supremm.json and supremm-job-viewer.json. The current code assumes that the module name that the …
> Fix discovery of module names based on filename

- classes/CCR/MailWrapper.php
- html/controllers/mailer/contact.php
Fix 2 instances where `sendMail()` was being called in all lower-case `sendmail()`
Bugfix
Did not perform tests.
> Fix sendMail() function name capitalization when called

- classes/DataWarehouse/Visualization/HighChart2.php
This addresses [Tom Furlani's bug](https://app.asana.com/0/387470245161503/424407219764834).
The XDMoD UI presents data aggregated at particular units (day, month, quarter, year). It is
sometimes necessary to adjust the user-specified start or end date to align with aggregation
unit boundaries as we do not display partial aggregation units (the user must switch to a
finer-grained unit for this). This means that the start date may need to be adjusted to the
start of the unit that it falls into, similarly the end date may need to be adjusted to align
with the end date of the unit. For example, viewing a monthly aggregation unit the date range
2017-1-15 - 2017-08-20 must be adjusted to 2017-01-01 - 2017-08-31 to include whole months
since that is the data that will be returned.
XDMoD does …
> Do not show future dates in lower right of XDMoD plots

- docs/nginx.md
updated location directives to work with default centos7 nginx install
Mainly so the knowledge doesnt get lost if someone else wants to try the unsupported (for now) nginx configuration
> update to secret nginx documentation

- .travis.install.sh
- CHANGELOG.md
- classes/NewRest/Controllers/MetricExplorerControllerProvider.php
- docs/upgrade.md
- html/about/release_notes/xdmod.html
- html/gui/js/modules/job_viewer/JobViewer.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/MetricExplorerTest.php
- open_xdmod/modules/xdmod/xdmod.spec.in
This pull request merges work done for 7.0 into the 7.1 branch. Merged pull requests include: #226, #229, #232, #235, #236, #239, #247, and #248.
File conflicts manually resolved:
- `.travis.install.sh`
> Merge 7.0 work into 7.1

- .travis.build.sh
- .travis.yml
This pull request modifies our Travis tests to run all tests in one job per platform instead of one job per test suite per platform.
When the Travis tests were originally split up by test suite, we were only running tests on one platform (PHP 5.3.3 on Ubuntu 12.04). Now, we test multiple versions of PHP, which has increased the size of the testing matrix from 4 jobs to 10. This is larger than the maximum number of jobs that can be run simultaneously on Travis (currently 5), meaning that we have to wait for the first half of the jobs to finish before all jobs in the second half can start. In testing, shrinking the size of the matrix down to 3 jobs can reduce wait times by as much as 66%.
Additionally, the other issues that prompted breaking up the tests by test suite are either no longer …
> Travis: Run all tests in one job per platform

- bin/acl-config
- DirectorIterator::getExtension did not exist until PHP 5.3.6
The DirectoryIterator::getExtension method was not added until 5.3.6, this causes an issue when used on CentOS6 systems that install 5.3.3 by default.
The code does not execute on CentOS6 & PHP 5.3.3. This modification should resolve that
> PHP 5.3.3 fix for DirectoryIterator::getExtension

- bin/xdmod-upgrade
- configuration/portal_settings.ini
- open_xdmod/modules/xdmod/build.json
- package.json
- shippable.yml
This seems to work with my changes to the docker file to allow the base shippable image to be version 7.0.1
even though https://app.shippable.com/github/plessbd/xdmod/runs/9/summary/console failed, it was because of the UI tests which seem to have a few more bugs to work out and not because of the shippable updates
> Updates shippable to image 7.0.1

- classes/XDUser.php
- docs/faq.md
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
See title.  Any suggestions for a better error message are welcome.
If the public user data is missing, the portal will not be displayed and a blank screen is presented instead.  This happens if the database is not migrated from 6.6. to 7.0.  This PR changes the behaviour to display:
```
{"success":false,"count":0,"total":0,"totalCount":0,"results":[],"data":[],"message":"Public User not found","code":0}
```
Which at least includes an error message.
- Installed 6.6
- Upgraded to 7.0
- (Did not run `xdmod-upgrade`)
- Loaded portal
- Observed error message
> Throw exception if Public User data is not found

- bin/acl-config
Update user displayed message when ACL info is not in the module config
file.
> Update user displayed message when ACL info is not

- classes/ETL/Configuration/EtlConfiguration.php
- classes/ETL/EtlOverseer.php
As discussed with @ryanrath and @jpwhite4 we should only attempt to verify data endpoints for actions that are enabled. This PR tidys up previous work and ensures that this is the case.
We were attempting to verify data endpoints for actions that were not enabled.
2 global data endpoints ("Utility DB" and "Cloud DB") are defined and 5 actions configured with no
"enabled" key defined (the default is `"enabled": true`).
```
smgallo@smgallo-dev:etl$ ./etl_overseer.php -c ../../../etc/etl/etl.json -p jobs-cloud -s '2009-10-15' -e now -k year  -v info -t|grep "Verifying endpoint"
2017-09-26 10:09:33 [info] Verifying endpoint: ('Utility DB', class=ETL\DataEndpoint\Mysql, config=datawarehouse, schema=modw, host=tas-db1-nofw.ccr.buffalo.edu:3306, user=xdmod)
2017-09-26 10:09:33 [info] Verifying …
```
> Only verify data endpoints for enabled actions

- classes/ETL/DataEndpoint/Filter/ExternalProcess.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DataEndpoint/DirectoryScannerTest.php
While reviewing @jpwhite4's code I noticed that I had an undefined variable in the ETL external process error reporting. This fixes that and also reduces the log level of the DirectoryScanner tests from `INFO` to `WARNING` for cleaner test output.
Bugfix
Ran tests.
> Fix ETL external process error messages

- classes/NewRest/Controllers/WarehouseControllerProvider.php
- html/gui/js/ExportPanel.js
- html/gui/js/modules/job_viewer/ChartPanel.js
- html/gui/js/modules/job_viewer/JobViewer.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/exportDialog.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/usageTab.page.js
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/xdmod.page.js
The chart export and printing in the job viewer is now updated to use the same Export and Print toolbar buttons as the rest of XDMoD. The main improvement is that the image size, font size and title presence are now configurable. Secondary improvement is that export UI is now consistent with the rest of XDMoD.
Add configurable export to job viewer; Make Job viewer UI consistent with XDMoD.
New tests will have been added in the SUPReMM module.
- New feature (non-breaking change which adds functionality)
> Add Export support to JobViewer

- classes/DataWarehouse/Visualization/HighChart2.php
The scale factor for the subtitle spacing was incorrect and caused the
title and subtitle to overlap at the bigger font sizes. This uses the
correct scaling factor. The spacing is identical between old and new
code at a font size of 2.
Original (note how the 'y' in by and 'l' in Behavioral overlap):
What it looks like now:
> Adjust subtitle spacing.

- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/reportGenerator.js
Report generator test would sometimes fail because it checked the available charts too soon. This polls the available chart list to wait for it to be populated.
> Impove robustness of report generator autotest

- classes/ETL/Aggregator/AggregatorOptions.php
- classes/ETL/Aggregator/pdoAggregator.php
- classes/ETL/Ingestor/IngestorOptions.php
- classes/ETL/aRdbmsDestinationAction.php
- tools/etl/etl_overseer.php
When executing multiple ETL actions that insert data into the same table it is not necessary to call `ANALYZE TABLE` after each action, only the final one.
Added "quarter" to the list of ETL chunk size options.
Performance improvements.
Ran Jetstream ingestion and verified that `ANALYZE TABLE` is only called when expected.
> Allow ETL ingestors to skip calling ANALYZE TABLE

- html/gui/js/FilterDimensionPanel.js
Fix the filer dialog clear all button so that it actually clears all of the filters.
The clear all button does not clear all of the filters. The bug is caused because the code uses the wrong ExtJS API call to obtain the filter information. The wrong code does a substring match on the decimal representation of the numerical ID. For example, if the filter with id 2 is in the list then the clear all button may clear any filter with id 20 - 29 or 200 - 299 or 2000 - 2999. The filters are processed in alphabetical order rather than numerical order.
In metric explorer on the XSEDE instance click "Add filter" -> "Resource" and select "ANL VIS" and "SDSC DTF" now click "Clear All" button. Observe that the "SDSC DTF" checkbox is incorrectly still checked.
Ran the test in 'steps to reproduce' and …
> Fix the filer dialog clear all button so that it actually clears all of the filters.

- classes/ETL/EtlOverseer.php
- configuration/etl/etl.d/verify.json
- configuration/etl/etl_tables.d/verify/verify_xdmod_dw_job_ingest.json
Add verification action for ingestion of jobs into XDMoD data warehouse by checking which active resources have not reported jobs for D days. Essentially, the following query is run:
```
SELECT
r.id AS id,
r.name AS name,
r.code AS code,
max(maxts.max_ts) AS last_entry_date,
5 AS number_of_days
FROM `modw`.`resourcefact` AS r
JOIN ( SELECT resource_id, MAX(j.end_time) AS max_ts FROM modw.jobfact j GROUP BY j.resource_id ) AS maxts ON maxts.resource_id = r.id
WHERE r.end_date IS NULL
AND maxts.max_ts < (NOW() - INTERVAL 5 DAY)
GROUP BY r.id, r.name, r.code;
```
**Note that not all resources have accurate end/decommision dates in the database so we can control the resources to be checked using the `etl_overseer.php` `-x` or `-r` options.**
See also PR ubccr/xdmod-xsede#59.
Catch failure of …
> Add verification action for ingestion of jobs into XDMoD data warehouse

- html/gui/lib/oldie-array-includes-polyfill.js
- html/index.php
Add polyfill for Array.prototype.includes() which is missing from IE.
We started using .includes() in #271, turns out that it is not in IE. Rather than removing the calls to the function this just adds the capability to browsers that don't already have it.
Manually checked that export works in IE. Ran the automated tests in SauceLabs.
> Add polyfill for Array.prototype.includes() which is missing from IE.

- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/Query/TimeAggregationUnit.php
- open_xdmod/modules/xdmod/component_tests/lib/QueryTest.php
Fix issue and update for later code changes to work.
In updating code to work with cloud metrics found an issue where the get min and max date range would actually return a day previous to the allowed range.  This fixes that error and sets up for the new period tables by bounding the range to be bound to the min and max job time.
Also combined into one database query instead of a possible 4 from before.
Ran old code and got duration returned which is the only places where getMinMax was called and compared to the new way.  Added tests to make sure this stays the same in the future.
> Update TIme Aggregation Unit

- classes/ETL/Configuration/EtlConfiguration.php
The ETL code registers global data endpoints and any endpoint associated with an **enabled** action. This means that a global endpoint could be registered even if the actions that it applied to are **disabled**. This PR changes the behavior to only automatically the global "utility" endpoint defined in the top level `etl.json` file as it may be used by `etl_overseet.php` to look up resource codes from the database. Since global endpoints are applied to individual actions withing their scope, these will still be registered for if any action that uses them is enabled.
Registering global endpoints with no enabled actions was causing testing to fail when it could not connect to the XDCDB mirror.
1. Renamed a global endpoint database to an incorrect name
2. Disabled all actions that the …
> Do not automatically register global endpoints

- bin/acl-config
- classes/XDUser.php
- configuration/etl/etl_sql.d/acls/xdmod/create_public_user.sql
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-setup.tcl
Until we completely remove role usage we need to create a 'Public' role as
well as an association to this role for the Public User. As such, we need to ensure that the Public role exists and that the Public User has a relation to it. In addition, the enumAllAvailableRoles function needs to be updated so that it can take this new role into account.
Without these changes the Public User's 'activeRole' returns the user role. This leads to unexpected behavior when viewing the Usage tab ( i.e. there are a number of Realms that are missing when logged in as the Public User ).
Manual Tests performed: 
Test 1:
- Navigate to XDMoD ( do not login )
- Click the Usage tab
- Double check that the 'Accounts' and 'Allocations' realm are visible / enabled.
Test 2: 
- Navigate to XDMoD ( login as a 'usr' …
> Update public user

- html/gui/js/Viewer.js
Revert viewer.js to commit 250daeb3204fdaf80b12fe181c388c4507245c2b overriding the erroneous changes introduced in #268
> Revert viewer.js to commit 250daeb3204fdaf80b12fe181c388c4507245c2b

- html/gui/css/LoginPrompt.css
- html/gui/js/CCR.js
Use ExtJS to generate the button chrome rather than rolling our own.
Was:
Now:
And 
consistency
Tested with
* Linux
* firefox
* chrome
* OSX
* firefox
* safari
* chrome
* Windows 7
* IE11
> Make the login button a real ExtJS button.

- classes/User/Roles/CenterDirectorRole.php
- classes/XDUser.php
- open_xdmod/modules/xdmod/component_tests/artifacts/.gitignore
- open_xdmod/modules/xdmod/component_tests/artifacts/update-artifacts.sh
- open_xdmod/modules/xdmod/component_tests/lib/User/Roles/CenterDirectorRoleTest.php
- open_xdmod/modules/xdmod/component_tests/lib/User/Roles/CenterStaffRoleTest.php
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- open_xdmod/modules/xdmod/component_tests/runtests.sh
Adding component tests that exercise the functions in XDUser, CenterDirectorRole and CenterStaffRole that still use the `Role`, `UserRoles` and `UserRoleParameters` tables. Some of these new tests utilize documents that have been added to the `xdmod-test-artifacts` repo. 
Expand the test coverage for one of our major classes: `XDUser`. 
CenterDirector and CenterStaff were included as they utilize the table `UserRoleParameters`.
... all of them?
> XDUser & Center[Director|Staff]Role Tests

- tools/dev/manage_saved_charts.php
While running an analysis I found that I had several charts with the same set of 20+ filters. Rather than need to add each of these filter sets to multiple charts and, in some cases multiple data series per chart, I developed a tool to provide a developer with the ability to copy filters from one chart to another.  Given a particular user, the following scenarios are supported:
- List all saved metric explorer charts
- List the global filters for all charts (or a specific chart)
- List the local filters for each data series for all charts (or a specific chart)
- Copy filters between charts and/or data series in a chart. This includes
- Copy global filters from one chart to another
- Copy global filters from one chart to a data series in another (or the same) chart
- Copy data series …
> Tool for copying filters between metric explorer charts

- bin/xdmod-slurm-helper
- open_xdmod/modules/xdmod/component_tests/lib/SlurmHelperTest.php
- open_xdmod/modules/xdmod/component_tests/scripts/sacct
Replaces use of PHP `system` with `proc_open`, etc..  Adds additional error checking and tests.
Previously, if the sacct command or whatever is used to run sacct (e.g. ssh) failed, no errors would be reported.
Ran xdmod-slurm-helper on test system.  Added new tests.
> Improve xdmod-slurm-helper sacct error checking

- configuration/etl/etl.d/storage.json
- configuration/etl/etl_tables.d/storage/directory.json
- configuration/etl/etl_tables.d/storage/file_system.json
- configuration/etl/etl_tables.d/storage/user.json
- configuration/etl/etl_tables.d/storage/user_usage.json
Update storage ETL configuration.
Storage ETL wasn't working with the changes from ubccr/xdmod#180.
> Update storage ingestors for StructuredFileIngestor

- classes/OpenXdmod/Migration/Version701To710/ConfigFilesMigration.php
- classes/XDUser.php
- configuration/datawarehouse.json
- configuration/etl/etl_sql.d/acls/xdmod/user_acl_group_by_parameters.sql
- open_xdmod/modules/xdmod/tests/lib/Xdmod/ConfigTest.php
- The GroupByProvider.php class already exists in OpenXDMoD but does not exist
in datawarehouse.json. This caused a problem replicating the behavior of
records being inserted into UserRoleParameters for users being assigned the
Center Director or Center Staff. The reason for this problem is that the
param_name column in UserRoleParameters holds what amounts to hard coded
group_by names, while in the new user_acl_group_by_parameters the equivalent
column is group_by_id ( an actual fk to the group_by table ). The problem then
becomes, how do you create a reference to a group_by that doesn't exist? Well,
you don't, hence the creation of this PR.
We also ensure that the user experience doesn't change by *not* adding a
record to roles.json ( a user needs an entry in query_descripters to have …
> Completing the addition of GroupByProvider to OpenXDMoD

- classes/XDUser.php
- Just migrating this function over to utilize the user_acl_group_by_parameters
table instead of UserRoleParameters.
Continue migration of XDUser functions to acl tables
Component Tests for this function were added to XDUserTest.php. There are 4 test functions and a total of 12 cases.
- `XDUserTest.php::testIsCenterDirectorOfOrganizationValidCenter`
- cases included for the following users: 
- centerdirector
- centerstaff
- principal
- normaluser
- Public User
- `XDUserTest.php::testIsCenterDirectorOfOrganizationInvalidCenter`
- cases included for the following users: 
- centerdirector
- centerstaff
- principal
- normaluser
- Public User
- `XDUserTest.php::testIsCenterDirectorOfOrganizationNull`
- `XDUserTest.php::testIsCenterDirectorOfOrganizationEmptyString`
Additionally the component, …
> Updated the isCenterDirectorOfOrganization function to use acls

- bin/xdmod-upgrade
- classes/OpenXdmod/Setup/Console.php
- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade.tcl
Adds better checking for yes/no responses during the upgrade process and outputs a message if no upgrade occurs.
Also replaces the non-interactive upgrade option with an expect script.
Previously, if a user entered "y" instead of "yes", the upgrade script would exit and it was not obvious that the migrations were not performed.
> Improve upgrade prompt

- classes/XDUser.php
- configuration/etl/etl_sql.d/acls/xdmod/create_public_user.sql
- configuration/roles.json
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- open_xdmod/modules/xdmod/tests/lib/Xdmod/ConfigTest.php
- Just another incremental PR for converting XDUser over to acls. 
- Also reduced the lines of code where I could.
To continue migrating XDUser to acls.
Tests have been included for this function as well as functions that utilize this function. They include: 
- `getMostPrivilegedRole`
- `getAllRoles`
- `setActiveRole`
- `__construct` ( via the testCreateUser* functions )
These tests reside within `component_tests/lib/XDUserTest.php`
> Update _getFormalRoleName to use the acl table

- bin/xdmod-ingestor
- classes/DB/Aggregator.php
- classes/DB/Exceptions/TableNotFoundException.php
- classes/DB/FilterListBuilder.php
Don't attempt to create filter list tables if the tables for a realm don't exist.
The storage realm is currently optional and not created by default.  If someone attempts to manually create the filter lists (which should never actually be necessary) it results in errors.
Installed and ran `xdmod-ingestor --build-filter-lists`.
> Only create filter lists for realms with tables

- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-setup.tcl
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade.tcl
The expect script can "gobble" the spawned processes exit status.  Lets not do that...
> update tests to catch and throw errors properly

- open_xdmod/modules/xdmod/automated_tests/package.json
The webdriverio dependency was set to be ^4.9.4 (my bad) this allows it to be updated to newer versions, the newer versions have changed some things though and until we can go through the tests and make them work with the newer version just force it to be 4.9.4 and only that known version.  We should probably do this for all versions of things going forward.
> test updates

- html/controllers/user_admin/update_user.php
- the structure of acls as they're sent over from the front end has changed from
['acl1', 'acl2', 'acl3'] -> {'acl1': ['center1', 'center2'], 'acl2': []}
and as such the function used to test for the absence of the 'mgr' role needs
to be changed from `in_array` to `array_key_exists`.
Because you should be able to modify your own user.
Manual Test:
-  Login to the internal dashboard 
- Select 'User management' tab
- Select the 'Existing Users' tab
- Double click on the account that you are currently logged in as.
- Click the checkbox next to the 'Principal Investigator' acl. ( It doesn't matter if it was checked previously or not )
- Click 'Save Changes' 
- It should save successfully. 
- To double check force refresh the page and navigate to the acct again.
- Ensure that the 'Principal …
> Updating update_user to handle new acl structure

- open_xdmod/modules/xdmod/automated_tests/webdriverHelpers/waitForAllInvisible.js
- open_xdmod/modules/xdmod/automated_tests/webdriverHelpers/waitForInvisible.js
- open_xdmod/modules/xdmod/automated_tests/webdriverHelpers/waitForLoadedThenClick.js
1 second to wait was causing errors in the tests, update the default to be 5 seconds.  This also makes the timeouts a bit more consistent, these are also just defaults.
At some point we should look into the real timings and set better defaults.
> update timeouts from 1s to 5s to be more consistient

- classes/XDUser.php
- html/controllers/user_admin/create_user.php
- open_xdmod/modules/xdmod/component_tests/lib/User/Roles/CenterDirectorRoleTest.php
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- A slight change that modifies XDUser so that during construction it honors the
`primary_role` parameter which is used to populate the `activeRole` property.
- Updated the create_user.php to take this change into account ( it now provides
ROLE_ID_USER )
Ensure that current uses of XDUser::_construct do not break and behave as intended.
Added a component test to ensure we test for the desired behavior implemented by this change.
- i.e. that the primaryRole supplied during XDUser construction is taken into consideration when retrieving / populating the activeRole.
> XDUser Construction: Primary Role

- open_xdmod/modules/xdmod/automated_tests/package.json
When pulling in the automated test dependencies on shippable,  the 'wdio-cromedriver-service' has been updated to '0.1.2' which breaks the automated tests.
Fix the automated tests by pinning the version of wdio-chromedriver-service to one that we know works
manual tests: 
tested the update in another branch that was run through shippable
> Pinned automated test dependency

- open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
making the test set have a name caused it to not be unique cause I forgot some parts of the name, this fixes it.
> make the regression test names actually be unique

- bin/acl-config
- Changed the default log level to be `ERR` so that the script runs silent by
default.
We should only see log entries on error.
Manual Tests: 
**Test 1:**
- Logged into xdmod-dev
- Manually updated the default log level of acl-config
- ran acl-config 
- noted that there was no output to stdout
> Updating default log level for acl-config

- html/internal_dashboard/js/AccountRequests.js
- html/internal_dashboard/js/CurrentUsers.js
- html/internal_dashboard/js/UserManagement/Panel.js
- Previously both 'Account Requests' and 'Existing Users' would create their own
instances of `XDMoD.AdminPanel`. This caused issues as there were `id`
properties being set in 'AdminPanel' which, since there were two sets of dom
trees, were not unique.
- This creates one instance of `XDMoD.AdminPanel` and passes it to CurrentUsers
/ AccountRequests for them to use.
Would like the 'Status' to update regardless of which 'Create & Manage Users' button you click on which tab in what order. 
Manual Tests: 
**Test 1:**
- Navigate to 'User Management' -> 'XDMoD Account Requests'
- Click 'Create & Manage Users'
- Select the 'Current Users' Tab
- Click on a few users in the default group ( 'Demo Users' ).
- Ensure that the 'Status' is displayed / correct.
- Select …
> Update to ensure that only one AdminPanel is utilized

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
After updating a users acls, the acl display would be cleared, thus no longer showing the selected users acls. 
A users acls should be displayed after changes are saved. 
Manual Tests: 
**Test 1:**
- Login to the internal dashboard
- Select 'User Management' -> 'Existing Users'
- Select a user that has more than one acl
- Remove an acl from that user
- Save changes
- Expected: 
- The current acls for the user are displayed.
> User's acls were being cleared on save

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- record.data.id is a string while the FEDERATED_USER_TYPE is an int.
If a user can't change their type once they are 'Federated' then we should not allow users to be manually changed to 'Federated'.
Manual tests:
**Test 1:**
- Login to Internal Dashboard
- Select 'User Management' -> 'Existing Users'
- Double click a user
- Click the 'User Type' drop down
- Ensure that there is no 'Federated' available
> Should not be able to change a non-federated user to a federated user.

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- This calling of fetchUserDetails specified to not 'reset_controls' which meant
that the controls were cleared but never set. Updating this to
'reset_controls' to true means that they will be reset w/ the current values.
Enabling / Disabling a user should not clear their acls.
Manual Test:
**Test1:**
- Select 'User Management' -> "Existing Users"
- Double click a user to modify
- Select 'Disable Account' from the 'Actions' drop down
- Ensure that the acls are displayed as they were prior to disabling.
> enabling / disabling a user cleared acls

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- The Institution drop down was never 'disabled' as it seems the code intends
due to 'enabling' the userSettings component ( of which institution is a
child ) *after* the drop down was disabled. This caused institution to be
enabled. Causing an inconsistent user experience as on save, if the user was
not a campus champion, the institution box was disabled. This would make sense
if the only users that had an institution were campus champions, but because
the component was enabled, any user could have one.
If a user is able to add an institution via the admin interface then they should be able to remove it. Or, if the user is not eligible for having an institution value then it should not be possible to set one for them. 
Manual Tests: 
**Test 1:**
- …
> Fixing Enabling / Disabling of User Settings

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- Prior to PR: https://github.com/ubccr/xdmod/pull/373 there were two instances
of `SectionExistingUsers` which did not play well with `Ext.getCmp()`. Now
that we have made it so that there's only one instance of
`SectionExistingUsers` we can revert from using `document.getElementById` to
using `Ext.getCmp()`.
- This also resolves status display / coloring for IE !Edge
It's nice to be able to use your js framework. Also, IE !Edge compatability.
Manual Tests: 
**Test 1:**
- Login to Internal Dashboard
- Select 'User Management' -> 'Existing Users'
- Double click an existing user ( not your currently logged in user )
- Ensure that the 'status' is displayed / colored appropriately.
- Toggle the users 'Status' ( Enable / Disable user )
- Ensure that the change in status is reflected in the UI …
> Reverting txtAccountStatus to utilize Ext

- html/controllers/user_admin/create_user.php
- html/controllers/user_admin/enum_roles.php
- html/controllers/user_admin/update_user.php
- html/internal_dashboard/index.php
- html/internal_dashboard/js/admin_panel/AclGrid.js
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/ControllerTest.php
When XDMoD is operating with the feature MultipleServiceProviders = 'off' we still want to be able to record additional information for certain 'center' related acls. Previously we did the detection / processing of this on the back end. The detection / handing has been moved to the front end which allows our create / update back end processing to be consistent.
An additional property has been added to the enum_roles controller so that we are able to differentiate between when the UI should display the center selection components and when the acl requires additional center information. 
Simplify the back end processing code for creating / updating users. 
Manual Tests ( Open XDMoD, XSEDE XDMoD )
**Test 1:**
-  Login to the Internal Dashboard
- Select 'User Management' -> 'Existing Users'
- …
> Provide default center

- html/internal_dashboard/js/CurrentUsers.js
- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
Previously the 'Refresh' button would only refresh the users listed in the 'Existing Users' tab. If an admin had previously opened the 'Create & Manager Users' modal and was viewing the User Group that a new user had been added to this new user would not be displayed upon opening up the 'Create & Manage Users' modal again. 
Providing a consistent user experience
Manual Tests:
**Test 1:**
- Login to the Internal Dashboard in two separate sessions  
- In both sessions navigate to 'User Management' -> 'Existing Users'
- In session 1, click 'Create & Manage Users'
- Select the 'Federated' user type 
- close the 'Create & Manage Users' modal
- In session 2, click the 'Create & Manage Users' button
- Create a new user w/ the 'Federated' user type
- close the 'Create & Manage Users' modal
- In …
> Existing User Refresh

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- There are scenarios when the cmbUserType will not contain a value ( in this
case when a user is of the 'Federated' user type ). In that case we should
fall back to the `cached_user_type` variable that is populated when the user's
details are fetched.
We should be able to update a user regardless of their user type.
Manual Tests: 
**Test 1:**
- Navigate to 'Manage Users' -> 'Existing Users' 
- Select a user that is of the 'Federated' user type
- Ensure that the User Type displays 'Federated'
- Add an acl
- Click 'Save Changes'
- Ensure that the update processes succefully
> Account for Federated User Type when updating a user

- html/internal_dashboard/css/AdminPanel.css
- Previously the application of this rule to the 'Map To' or 'Institution'
fields in `SectionNewUser.js` would blow the drop down button off the right
hand side of the control. This change instead displays the error symbol on the
right hand side of the combobox next to the drop down button.
Not having portions of the UI dissapear unexpectedly is a good thing
Manual Tests: 
**Test 1:**
- Navigate to 'User Management' -> 'Existing Users'
- Click the 'Create & Manage Users' button
- Select 'New User'
- Enter first, last and user name. Enter an email address
- Select the 'Campus Champion' acl 
- Click 'Save User' 
- Ensure that the 'Map To' combobox is marked as being in error but that you can still see / utilize the drop down button
- Select a person from …
> Fixing Admin Panel error css rule

- html/internal_dashboard/js/admin_panel/SectionNewUser.js
When creating an XDMoD user and mapping them to an HPC user, an admin can click on the "Find" button to attempt to discover the proper user based on first and last name. This currently displays a grid with no instructions where the admin must double-click a row to select a user. Modify this dialog to improve instructions and add an OK and Cancel button to improve usability.
Current dialog:
Updated dialog:
Improved usability.
Manually tested on dev.
1. Select user, click OK. User set in Create User dialog.
2. Select user, click Cancel. No user set in Create User dialog.
3. Do not select user, click OK, received proper error message.
4. Do not select user, click Cancel. No user set in Create User dialog.
> Improve usability of dashboard Select User Dialog

- classes/ETL/Aggregator/pdoAggregator.php
Improve logging message when start_day_id and/or end_day_id are not specified for the source aggregation table.
Improved troubleshooting
Yes.
> Improve error message when start_day_id and/or end_day_id not present

- html/gui/js/modules/metric_explorer/MetricExplorer.js
- Legend item edit box is now displayed next to the legend
item that is being edited.
- Text box expands a bit to allow for longer strings to be fully
visible.
> Metric explorer edit legend item UI improvements

- html/gui/js/FilterDimensionPanel.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- This change adds a select all button to the filter dialog box. Now that
a large number of filters can potetially added or removed in one go,
this change also performance optimizations when large numbers of filters
change.
- Select all button is grayed out if there are more than 150 filters
since more that this number has a detrimental performance impact on
several parts of the XDMoD UI (the database seems to cope fine though).
> Add 'Select All' button to filter dialog.

- classes/DataWarehouse/Query/Jobs/Statistics/NodeUtilizationStatistic.php
- classes/DataWarehouse/Query/Jobs/Statistics/UtilizationStatistic.php
- The utlization statistic takes an eye-watering large amount of time to
run (130s) to generate 30 days of data. This new query returns the
identical results but runs in ~700 ms.
- Also skip running the aggregate query when group by is none.
> Improve the performance of the Utilization stats

- classes/DataWarehouse/Access/Usage.php
This bug was introduced many years ago when the Usage Explorer was
change to use the ME backend. It has been reported many times since then
too:
https://app.asana.com/0/39210960934587/141779761478379
https://app.asana.com/0/159049597309611/72083170607090
https://app.asana.com/0/16817869275975/101854225421037
Once the regression tests pull request #378 is merged then I'll update
this with the extra regression tests to demonstrate the guide lines
selection working correctly.
> Make show_guide lines button work again.

- classes/DataWarehouse/Data/SimpleTimeseriesDataset.php
- classes/DataWarehouse/Query/Query.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
Fixes issue with data filtering when an unpriv user tries to view
timeseries data for a realm / stat that is protected (i.e. has
additional role-specific filters applied).
Added integration test that confirms the correct behaviour.
> Fix incorrect data filtering

- composer.json
- composer.lock
profiling the code showed that ~10% of the time of every call the the webserver was spent loading the php-sql-parser library (which is not even used by the webserver code!).
Ran regression tests with timing and compared the old code with the new code:
you get a 10% performance improvement.
> Update php-sql-parser to newer release that does not autoload itself

- bin/xdmod-slurm-helper
- Add resource name to temporary log files
- Don't delete temporary log file when debugging
When debugging slurm shredding/ingestion issues it is desirable to have access to the output from the `sacct` command used by the helper script.
Ran the helper script with and without the `--debug` option.  Examined temporary directory and inspected files produced by helper script.
> Update slurm helper script

- open_xdmod/modules/xdmod/automated_tests/wdio.conf.js
Update to remove ie and firefox from sauce testing as they do not currently work
> update chrome version, remove IE/Firefox from sauce testing

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- html/internal_dashboard/js/admin_panel/SectionNewUser.js
Federated users should only be created through SSO. This removes the Federated option from the new user dialog.  Additional work is planned to handle filtering on the endpoint that serves the data rather than several places in the front end, see [Allow enum_user_types to filter certain types](https://app.asana.com/0/39212635865052/561134350668840).
Bugfix
Tested hotfix on metrics-dev.
>  Disable selection of federated type in new user dialog 

- html/gui/js/modules/metric_explorer/MetricExplorer.js
When plotting a pie chart there is no series.legendItem object. Rather than introducing more convoulted code, this pull request simply reverts the legend item behaviour to the original version. i.e. legend menu appears at click location.
> Revert change to legend item menu location

- classes/DB/FilterListBuilder.php
When generating filters via `FilterListBuilder()`, the filter list tables are cleared using `DELETE FROM`. This generates 1.5M delete events that must be replicated to the slave database. From the MySQL manual: "TRUNCATE TABLE is treated for purposes of binary logging and replication as DROP TABLE followed by CREATE TABLE—that is, as DDL rather than DML"
TRUNCATE TABLE cannot be used if there are triggers (as they won't fire) or foreign keys (ON DELETE clauses will not run) but there are none on the filter tables:
```
SELECT * FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'modw_filters'
AND CONSTRAINT_NAME != 'PRIMARY';
SELECT * FROM information_schema.TRIGGERS
WHERE TRIGGER_SCHEMA = 'modw_filters'
OR EVENT_OBJECT_SCHEMA = 'modw_filters';
```
Improve database and …
> Change DELETE FROM to TRUNCATE TABLE in filter generation

- classes/DB/PDODBMultiIngestor.php
This is a bug found during code inspection. The PDODBMultiIngestor creates a temporary file for use in an SQL load data infile query. This file is not flushed before the sql call so the records may not be written to disk which could result in data loss.
This change closes the file handle before calling mysql. This will ensure that the file contents are flushed to disk.
> Ensure file is flushed before running load

- classes/DB/PDODBMultiIngestor.php
- classes/ETL/Ingestor/pdoIngestor.php
For historical reasons, the ingestors have always translated `empty($value)` to an empty string. However, since the `empty()` function returns `true` for values of `NULL`, `""`, `0`, `0.0`, and `"0"` this translates valid integer values of 0 to empty strings, which is not desirable in many cases. For numeric values, [MySQL converts](https://dev.mysql.com/doc/refman/5.5/en/insert.html) the empty string back to zero on insert but this causes numerous warnings during the ETL process.
For example, XSEDE defines a person_id = 0 as the Unknown user but this id gets stripped out on ingestion and replaced by an empty string forcing us to convert 0 to -1 in our ingestion queries. 
Cleaning up ETL warnings.
Deploy 2 instances of XDMoD, each configured to talk to a different docker database.
``` …
```
> Do not translate 0 to the empty string during ETL

- docs/hierarchy.md
Fix typos - two misspellings of "hierarchy" and Ingestor command is xdmod-ingestor not xdmod-ingest
>  Fix misspellings of "hierarchy" and ingest-xdmod typo in 8.0 hierarchy.md

- docs/hierarchy.md
Fix typos - two misspellings of "hierarchy" and Ingestor command is xdmod-ingestor not xdmod-ingest
>  Fix misspellings of "hierarchy" and ingest-xdmod typo in 7.5 hierarchy.md

- docs/hierarchy.md
Fix typos - two misspellings of "hierarchy" and Ingestor command is xdmod-ingestor not xdmod-ingest
> Fix misspellings of "hierarchy" and ingest-xdmod typo in 6.6 hierarchy.md

- docs/hierarchy.md
Fix typos - two misspellings of "hierarchy" and Ingestor command is xdmod-ingestor not xdmod-ingest
>  Fix misspellings of "hierarchy" and ingest-xdmod typo in 7.0 hierarchy.md

- docs/hierarchy.md
(For completeness) Fix typos - two misspellings of "hierarchy" and Ingestor command is xdmod-ingestor not xdmod-ingest
>  Fix misspellings of "hierarchy" and ingest-xdmod typo in 7.1 hierarchy.md

- docs/hierarchy.md
(For completeness) Fix typos - two misspellings of "hierarchy" and Ingestor command is xdmod-ingestor not xdmod-ingest
>  Fix misspellings of "hierarchy" and ingest-xdmod typo in 6.5 hierarchy.md

- open_xdmod/modules/xdmod/component_tests/README.md
- open_xdmod/modules/xdmod/component_tests/lib/BaseTest.php
- open_xdmod/modules/xdmod/component_tests/lib/ETL/IngestorTest.php
- open_xdmod/modules/xdmod/component_tests/lib/QueryTest.php
- open_xdmod/modules/xdmod/component_tests/lib/Roles/CenterStaffRoleTest.php
- open_xdmod/modules/xdmod/component_tests/lib/SlurmHelperTest.php
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- open_xdmod/modules/xdmod/component_tests/runtests.sh
- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/TestFiles.php
Bring the ACL and other tests up to date so they work with both the Open XDMoD and XSEDE docker images. To do this the following steps were taken:
- Two different methods were being used to retrieve files from two different locations from [xdmod-test-artifacts](https://github.com/ubccr/xdmod-test-artifacts). Switch instances of `BaseTest::getFile()` to use `TestHarness\TestFiles` (from the integration tests) instead.
- When comparing user objects the entire JSON export of the object was compared, including database keys. Since keys may change while the values remain the same (e.g., if values were added in a different order or if additional values were added) we don't want to compare the keys. Filter only the fields that matter.
- Removed hardcoded Open XDMoD test values and used data from …
> Improve XSEDE ACL tests

- configuration/etl/etl.d/hpcdb-modw.json
- configuration/etl/etl_tables.d/hpcdb-modw/allocation-on-resource.json
- configuration/etl/etl_tables.d/hpcdb-modw/allocation.json
- configuration/etl/etl_tables.d/hpcdb-modw/person.json
- configuration/etl/etl_tables.d/hpcdb-modw/request.json
hosts and job_record contain duplicate entries and are expected to.  This supresses those warnings.
This also fixes other tables having warnings that were appearing about fields not having defaults.  Instead of allowing them on the table level, this just sets them on the ingest query.
> Supress and fix wanrings

- tools/etl/dump_database_table_definition.sh
tempfile has been deprecated, this also makes this work in centos
https://manpages.debian.org/stretch/debianutils/tempfile.1.en.html#BUGS
use the globally installed jq
> update dump database tables script

- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Visualization/HighChart2.php
- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
*This pr is intended to address plotting of single point datasets, regardless of selected time aggregation. (The second commit does the same for non-timeseries plots so they display properly in e.g. Summary tab.)* 
This change fixes some faulty logic that determines whether plot point markers will be displayed in line and area charts. Previously, a blank plot resulted from plotting a dataset with a single timeseries point and a long Duration with daily aggregation. 
Example: Usage tab plot with single y data point and more than 30 time points appears to be empty (note that not all x-axis time points are labeled here):
Whereas: Fix to line plot with single y data point and more than 30 time points correctly displays the point:
The change counts up *y* points (plottable points) in …
> Handle single-point timeseries plotting bug in our highcharts wrappers.

- tools/dev/verify_table_data.php
When verifying ETL ingest or simply comparing the data in 2 tables, we often see cases where one or two columns differ in some rows of the source table as compared to the destination table. Previously, we were able to identify these missing rows but it was a manual process to determine whether or not the entire row was missing in the destination, differed in some significant way, or simply had a different modification time due to different ingest times.
We can now specify `--show-row-differences` and, based on the table primary key, determine if a row with the same key exists in the destination and if so, what columns are different. Excluded columns are not used for the comparison. For example:
```
php verify_table_data.php -v info -s modw -d modw_aws -t person -x order_id -x ts -x ts_ts …
```
> Add option to show columns that differ when comparing tables

- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByProvider.php
The `organization_id` column has been renamed to `resource_organization_id`.
This was causing a problem when logging into the site as a center director ( sql
syntax error as the column was not found ).
Users should be able to login regardless of their Acl assignments
Manual Test:
- Login as a user who's highest privileged acl is center director to an unpatched XDMoD 8.0 site. 
- Notice that an exception is presented and the site is unusable. 
Apply this PR
- Login as a user who's highest privileged acl is center director
- Notice that an exception is **not** thrown and the site is usable again
**NOTE**: I didn't add any new tests as just running the automated tests on an XSEDE instance would find this.
> Updating filter column

- bin/xdmod-build-filter-lists
- bin/xdmod-ingestor
- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
Fix xdmod-build-filter-lists so that the command line flags that control log levels work and the long command line flag to specify the realm works.
Add the filter list building back to being run in the `xdmod-ingestor` command, thus keeping the same behaviour as the release software.
> Fix filter building

- classes/Authentication/SAML/XDSamlAuthentication.php
- classes/NewRest/Controllers/UserControllerProvider.php
- classes/XDUser.php
- configuration/apache.conf
- configuration/constants.php
- db/data/moddb.sql
- db/migrations/7.5.0-8.0.0/moddb.sql
- docs/_includes/menu.md
- docs/faq.md
- docs/simpleSAMLphp.md
- html/controllers/user_admin/delete_user.php
- html/controllers/user_admin/update_user.php
- html/gui/css/LoginPrompt.css
- html/gui/general/login.php
- html/gui/js/CCR.js
- html/gui/js/profile_editor/ProfileEditor.js
- html/gui/js/profile_editor/ProfileGeneralSettings.js
- html/index.php
- html/internal_dashboard/js/UserStats.js
- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- html/internal_dashboard/js/admin_panel/SectionNewUser.js
- open_xdmod/modules/xdmod/automated_tests/package.json
- open_xdmod/modules/xdmod/automated_tests/runtests.sh
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/SSOLogin.js
- open_xdmod/modules/xdmod/automated_tests/wdio.conf.js
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/ControllerTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UserControllerProviderTest.php
- open_xdmod/modules/xdmod/integration_tests/scripts/samlSetup.sh
- shippable.yml
Use Single Sign On (SSO) instead of Federat(ed|ion)
> Disambiguate the word Federat(ed|iion)

- classes/ETL/DbModel/AggregationTable.php
- classes/ETL/DbModel/Column.php
- classes/ETL/DbModel/Table.php
When a table column is to be dropped by ETLv2, log a warning so the pipeline can be run in dryrun mode and verified prior to potentially losing data.
Manually tested against XSEDE docker.
> Log a warning on drop column

- classes/ETL/Aggregator/pdoAggregator.php
- classes/ETL/DbModel/Query.php
- classes/ETL/Ingestor/StructuredFileIngestor.php
- classes/ETL/Ingestor/pdoIngestor.php
- classes/ETL/aRdbmsDestinationAction.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DbModel/DbModelTest.php
Database column names can be specified in JSON configuration files and may contain SQL reserved words such as `order` and `group`. To support these as column names, they must be quoted using the database system quote character (``` ` ``` in MySQL and `"` in Postgres and Oracle).
Improved handling to allow any column name to be used. One of our tables has a column named `order`.
Ran component and unit tests against XSEDE docker instance, as well as XSEDE jobs ingestion.
> Quote database column names to support reserved keywords

- classes/ETL/Aggregator/pdoAggregator.php
Provide support for child classes to override or expand the rows deleted from the aggregation table when updating a particular aggregation period. This is useful when a child class needs to also delete data from additional related tables.
Needed by @jpwhite4 for SUPReMM.
Tested against XSEDE docker:
```
$ docker run -h database --rm -it -p 3306:3306 tas-tools-int-01.ccr.xdmod.org/xdmod-centos7:xsede8.0-latest /bin/bash
$ /root/bin/services start
$ mysql modw_aggregates;
MariaDB [modw_aggregates]> create table jobfact_by_year_orig like jobfact_by_year;
Query OK, 0 rows affected (0.02 sec)
MariaDB [modw_aggregates]> create table jobfact_by_day_orig like jobfact_by_day;
Query OK, 0 rows affected (0.01 sec)
MariaDB [modw_aggregates]> insert into jobfact_by_year_orig select * from …
```
> More flexible aggregation period deletes

- classes/ETL/EtlOverseer.php
- classes/ETL/EtlOverseerOptions.php
- tools/etl/etl_overseer.php
Load resource codes from the database only as needed when specified in an action configuration or on the command line.
Bootstrap actions cannot rely on `modw.resourcefact` existing so it cannot be queried.
The following cases specify a resource in the action configuration:
```
$ php etl_overseer.php -a JetstreamApiStagingJobRecordIngestor -v debug -t |grep modw.resourcefact
SELECT id, code from modw.resourcefact
$ php etl_overseer.php -a XdcdbJobRecordStagingIngestor  -v debug -t |grep modw.resourcefact
SELECT id, code from modw.resourcefact
```
The following cases demonstrate command line resource arguments:
```
$ php etl_overseer.php -a XdcdbJobRecordIngestor -v debug -t |grep modw.resourcefact
$ php etl_overseer.php -a XdcdbJobRecordIngestor -v debug -t -x IU-TACC-JETSTREAM |grep …
```
> Load ETL resource codes as needed to allow for bootstrapping actions

- open_xdmod/modules/xdmod/integration_tests/scripts/samlSetup.sh
Just added a line to the `samlSetup.sh` script to remove `package-lock.json` as it has a SHA1 hash specified for a dep `xmldom` that doesn't match. This keeps `npm instal` from running successfully && keeps the saml tests from passing.
**NOTE: I've opened an issue w/ `saml-idp` for this problem (https://github.com/mcguinness/saml-idp/issues/32). In the mean time this should allow our shippable builds to pass.** 
I'm a fan of Shippable builds that pass.
Manual tests were performed: 
- Manually spin up an xsede docker image
- Make sure that the line `rm -f package-lock.json` is added to `samlSetup.sh`
- Execute `samlSetup.sh` 
- Open a web browser and navigate to the hosted XDMoD site
- Login via SAML
- Notice that the login is successful
> Removing invalid package-lock.json

- classes/NewRest/Controllers/WarehouseControllerProvider.php
Error Message:
<b>Warning</b>:  json_encode(): double NAN does not conform to the JSON spec, encoded as 0 in <b>/data/www/jpwhite4/share/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/JsonResponse.php</b> on line <b>127</b><br />
<br />
This code change modifies any float NaNs to be the string 'NaN' in the data that goes out over the network. The javascript front-end code can handle the string NaN if it sees it.
Tested by viewing job SDSC-COMET 15595784_1 on my port.
> Convert NAN to NAN

- classes/ETL/EtlOverseer.php
- tools/etl/etl_overseer.php
Pipeline name verification is performed in `etl_overseer.php` but when calling without that wrapper script, pipeline names should also be verified. Note that this needs to happen after the `EtlConfiguration` object is created but before actions are actually executed by `EtlOverseer`.
Manually tested by removing checks from `etl_overrseer.php`
> Add pipeline name verification in EtlOverseer::verifySections()

- bin/acl-config
A managed table ( acl_group_bys ) was added because it was not added during the initial commit.
Because this table should be "managed" ( i.e. completely re-generated from the config file source ) to accurately reflect the state of those configuration files.
Manual Tests: 
- Have a db w/ the acl_group_bys table in an inconsistent state ( the db values are different than the config file values 
- run acl-config
- notice that acl_group_bys should now be consistent with the config file values
> Adding a managed table that was initially missed

- classes/OpenXdmod/Setup/DatabaseSetup.php
When using proc_open and ignoring things you can get into a situation where the process gets blocked.
In this case call the etlv2 directly instead and avoid the issue all together.
> Stop using proc_open for calling etl, instead invoke directly

- classes/DataWarehouse/Access/Common.php
- classes/DataWarehouse/Access/MetricExplorer.php
- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Visualization/HighChart2.php
- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
- html/gui/js/HighChartPanel.js
- html/gui/js/HighChartWrapper.js
- html/gui/js/modules/Usage.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
- html/highchart_template.html
- html/index.php
- libraries/charting.php
- open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageChartsTest.php
The javascript functions needed for the Highcharts charts are now defined in javascript rather than in php. The API calls that return jchart data now return properly encoded json rather javascript.
The regression tests have been updated: there was a bug in the previous javascript encoding code that did not handle data with single quote characters. The buggy code is removed by this change.
Note that where possible I have tried to keep the existing javascript code in place unmodified (to reduce the chance of inadvertent regressions).
> Remove javscript from php chart code

- classes/ETL/DbModel/Constraint.php
- classes/ETL/DbModel/ForeignKeyConstraint.php
- classes/ETL/DbModel/Table.php
- open_xdmod/modules/xdmod/tests/lib/ETL/DbModel/DbModelTest.php
Adds foreign key constraint support to ETL.
Tables in `mod_hpcdb` have foreign key constraints.  In order to improve job ingestion these tables should be managed by the ETL process.
Updated ETL tests.
> Add foreign key constraints to ETL

- classes/ETL/Ingestor/pdoIngestor.php
- classes/ETL/aOptions.php
Add 2 new ETL options for flexibility with larger datasets
- `db_insert_chunk_size` The number of seconds to allot for the timeout per file per record chunk
- `net_write_timeout_per_db_chunk` The number of records per chunk (e.g., LOAD DATA INFILE statement)
@jpwhite4 was seeing "MySQL server has gone away" errors when ingesting SUPReMM data.
Tested against XSEDE docker instance.
> Allow net write timeout and chunk size as ETL variables

- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/XdmodTestHelper.php
The version of libcurl that ships with Centos 7 needs to have the CURLOPT_POSTFIELDS option set when POSTing. If not then it sends a Content-Length of -1 which results in a 400 Bad Request from the webserver.
Bug fix.
> Ensure post/patch requests are configured correctly in test harness

- classes/OpenXdmod/Migration/Etlv2Migration.php
- classes/OpenXdmod/Migration/MigrationFactory.php
`xmod-upgrade` automatically runs ETLv2  for all etlv2 sections (pipelines) that are marked
as migrations. Migration sections (pipelines) are determined based on their name. The name must end in the string 'migration-X_Y_Z-A_B_C' for migrations from XDMoD version X.Y.Z to A.B.C
The migrations are processed in alphabetical order by name.
The SUPReMM module needs to run an etlv2 pipeline at upgrade time.
> Run all Etlv2 migration pipelines on xdmod-upgrade

- configuration/etl/etl_action_defs.d/cloud_openstack/event.json
- configuration/etl/etl_tables.d/cloud_common/event.json
Added submission_venue_id column to event table and for open stack ingestion set the submission_venue_id to be 3 which matches the row in the submission_venue table for data ingested from the OpenStack API.
Tested with docker.
> Add submission venue for events

- html/index.php
This change fixes a regression that was introduced in #519. The JavaScript variable `CCR.xdmod.ui.mappedPName` needs to be encoded using JavaScript encoding not URL encoding.
Old:
New:
> Fix encoding for javascript

- classes/DataWarehouse/Query/Cloud/GroupBys/GroupBySubmissionVenue.php
- configuration/datawarehouse.d/cloud.json
- configuration/etl/etl_data.d/jobs/submission_venue.json
- configuration/etl/etl_tables.d/jobs/submission_venue.json
- configuration/roles.d/cloud.json
- tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/datawarehouse.json
- tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/roles.json
Adding a Group By for the Submission Venue
We would like to be able to see data based on the submission venue such as the difference between Jetstream Atmophere portal or the Jetstream API
Manual testing using XSEDE docker
> Add submission venue group by

- classes/ETL/Ingestor/StateReconstructorTransformIngestor.php
Fixes a bug where the order by was following the dummy row union, causing a valid row to be discarded instead of the dummy row.
We like good data
Yes
> Correct order by placement in event reconstruction

- open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
Adds backslash to exception name so that is resolves properly.
Fixes:
```
PHP Fatal error:  Class 'Controllers\PHPUnit_Framework_ExpectationFailedException' not found in /xdmod/open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php on line 88
```
> Fix exception outside namespace

- html/gui/js/modules/job_viewer/AnalyticChartPanel.js
- html/gui/js/modules/job_viewer/JobPanel.js
- html/gui/js/modules/job_viewer/JobViewer.js
This change cleans up the UI for the analytics panel removing superfluous text and condensing whitespace (as per the UI recommendations from D L'averne). Also remove the hardcoded metrics from the front end. 
Old
New
Job viewer also included a significant amount of code that as responsible for managing the DOM ids. This change also removes the hard-coded analytics names and removes the unneeded id management code.
> Tidy up the Simplify job viewer analytics handling

- bin/acl-import
- bin/acl-xdmod-management
- open_xdmod/build_scripts/templates/install.template
Changes the path of ACL commands being executed by other ACL commands so that they are absolute paths.
See #544.  For non-RPM installations there is no guarantee that the user will have the Open XDMoD `bin` path in their `PATH` environment variable.  This results in a variety of problems since it isn't obvious that the commands are not running properly.
> Use absolute paths for executing ACL commands

- classes/CCR/MailWrapper.php
- html/controllers/mailer/contact.php
- html/controllers/mailer/sign_up.php
The "Contact Us" and "Sign Up" dialogs sent emails where the reply address was the noreply address. The XDMoD ticketing system used the reply address from the reply address field (which as you recall was set to the noreply address). This reply address caused the email reply to bounce (due to it being sent to a noreply address).
This changes the email headers so that:
a) The XDMoD ticketing system now gets the correct reply address
b) The Sender email header is now set so that the actual message sender information shows up in mail clients.
Original:
Now:
Also view from email client of email sent directly
> Ensure Contact Us and Sign Up emails have correct metadata

- classes/ETL/Ingestor/StateReconstructorTransformIngestor.php
Please do not merge prior to merging [#584](#584)
When ingesting a discrete set of cloud data, we may run into the issue of having a start date for a VM but no clearly defined end. To remediate this issue, we enable specification of a custom default end date as a string in the etl process.
To use, specify the -d option with etl overseer. Some example commands:
`etl_overseer -r RESOURCE -d end_time 'now - 7 days' -p cloud-state-pipeline`
`etl_overseer -r RESOURCE -d end_time '2018-02-26 + 1 second' -p cloud-state-pipeline`
`etl_overseer -r RESOURCE -d end_time '+ 14 days' -p cloud-state-pipeline`
See above.
Yes.
> Enable User Defined Default Times

- open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
- open_xdmod/modules/xdmod/regression_tests/runtests.sh
The test harness has a mechanism to create test artifacts if they are absent. This is used to update the tests when the code changes. The harness did not correctly create the non-reference files.
> Fix generation of test artifacts

- configuration/etl/etl_action_defs.d/jobs/xdw/host.json
Changes the job host ingestion to match the job ingestion.  Specifically, a separate table is used to limit which jobs are ingested instead of using the overseer options.
This was broken during my attempt to restore features that had been previously removed.
> Adjust job hosts ingestion to match job ingestion

- configuration/etl/etl.d/hpcdb.json
- configuration/etl/etl.d/shredder.json
- configuration/etl/etl.d/staging.json
- configuration/etl/etl.d/xdmod-migration-7_5_1-8_0_0.json
- configuration/etl/etl_sql.d/hpcdb/fields-of-science-hierarchy.sql
- configuration/etl/etl_sql.d/jobs/shredder/job-slurm.sql
Changes config sections used by ETL.  Also adds schema qualifiers to a couple SQL statements.
These sections do not exist in the XSEDE XDMoD configuration.  This
prevents errors in that situation.  Since we require a single database
user to have access to all the databases any section may be used as long
as all database queries contain schema names for each table.
> Remove use of shredder and hpcdb config sections

- classes/Xdmod/Template.php
Checks that the expected template file is a file and suppresses warning messages from `file_get_contents`.
The upgrade process checks for the existence of template files for each file in `portal_settings.d` to determine what modules are installed.  If a template does not exist it currently produces a warning message such as:
```
PHP Warning:  file_get_contents(/usr/share/xdmod/templates/etl/portal_settings.template): failed to open stream: No such file or directory in /usr/share/xdmod/classes/Xdmod/Template.php on line 88
```
This change will prevent that warning message.
> Improve template class error handling

- classes/ETL/Configuration/Configuration.php
- classes/ETL/EtlOverseer.php
- classes/ETL/aAction.php
- classes/ETL/iAction.php
- open_xdmod/modules/xdmod/component_tests/lib/ETL/BaseEtlTest.php
- open_xdmod/modules/xdmod/component_tests/lib/ETL/IngestorTest.php
- open_xdmod/modules/xdmod/tests/lib/ETL/SqlParser/SqlParserTest.php
Provide a factory method `aAction::factory()` for creating action objects directly. This is useful during testing and also when executing actions via the `EtlOverseer` class.
Simplify testing.
Ran unit and component tests.
> Improve method of calling single ETL action during testing

- configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
- configuration/etl/etl_action_defs.d/cloud_common/cloud_transient.json
- configuration/etl/etl_tables.d/cloud_common/cloud_transient.json
- configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
Adding submission_venue_id field to tables used for cloud aggregation. This field is needed for the Submission Venue group by
Tested by running aggregation on my local docker
> Add submission venue id to cloud aggregation

- configuration/etl/etl_action_defs.d/cloud_openstack/raw_cloud_job_logs.json
- configuration/etl/etl_action_defs.d/cloud_openstack/staging_event.json
- configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
In Open Stack there are heartbeat events that occur after the VM has been shut down. These heartbeat events have a state that is not active and need to be filtered out. If not filtered out then a second row for an instance is created in the cloud_event_transient table which causes incorrect data when aggregation is run. 
Heartbeat events are events that let us know that a VM is still active. It is expected that heartbeat events only exist when a VM is running. This appears to not be the case for Open Stack. In Open Stack heartbeat events for instances are named compute.instance.exists and they all have a state property. 
When an instance is running the state property equals active. After an instance is shutdown one more heartbeat event for that instance occurs with a state of stopped or …
> Filter out Open Stack heartbeat events with stopped or deleted state

- classes/DataWarehouse/Query/Cloud/GroupBys/GroupByProject.php
Add a where clause to the Project group by in the Cloud realm to make sure data is joined on resource id as well as account id.
When grouping by a project in the metric explorer if the VM does not have an account assigned to it the account id is set to 1 which means Unknown.  This account id exists for each XSEDE resource. This group by does not join on the resource id, just the account id. Because of this the value reported for Unknown is the correct value for that statistic times the number of resource id's with the same account id in the Accounts table. Adding a where clause using the resource id prevents this from happening and returns the correct data.
This changes is needed because otherwise data displayed when grouping by Project in the Cloud may return incorrect data
Tested in …
> Add resource id where clause to Project group by in cloud realm

- configuration/etl/etl_data.d/cloud_openstack/openstack_event_map.json
Updating the mappings for Open Stack events to our event_type table.
Some events in our Open Stack logs were not mapped to an event in the event_type table and should have been and one Open Stack event was mapped to the wrong event type. The mappings added will map.
- compute.instance.power_off.end to SUSPEND 
- compute.instance.power_off.end to RESUME
- compute.instance.power_on.start to REQUEST_RESUME
Correct mappings mean more accurate data reporting
Testing in Docker locally
> Update mappings from open stack events to event_type table

- configuration/etl/etl.d/hpcdb-xdw.json
Adds `"analyze_table": false` to job records/task ETL action.
This action has timed-out multiple times (`(sql: ANALYZE TABLE `modw`.`job_records`, stacktrace: [...] Ingestion failed: xdmod.hpcdb-xdw-ingest.job-records-job-tasks (ETL\Ingestor\DatabaseIngestor): Error executing Post-execute tasks  SQL Exception: 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away'`).
> Change ETL configuration for job records/tasks

- classes/ETL/aRdbmsDestinationAction.php
- open_xdmod/modules/xdmod/component_tests/lib/ETL/IngestorTest.php
If `hide_sql_warning_codes` is set and there are no unfiltered warnings log the message about SQL warnings as a notice.
Currently, if the log level is warning and the `hide_sql_warning_codes` is used, then a warning message is displayed even when all SQL warnings have been filtered out.  It would be preferable to not display the message as a warning if it is not followed by any warnings, but to continue to display the message as a warning if it is followed by warnings.
Added new test to ensure no warning messages are displayed when all warnings are filtered out.
> Change logging of ETL SQL warnings

- classes/ETL/Maintenance/ManageTables.php
Change the `ManageTables` action to use the `Configuration` class to parse the table definition file. This will eliminate warnings such as `[warning] ETL\DbModel\Table: Attempt to set unsupported property: '#'`. The current `ManageTables` action uses the `Table` class to parse the table definition file, which uses the `JsonFile` class under the hood. This does not take advantage of the transformers such as comment filtering and RFC6901 JSON references available in the `Configuration` class. 
Reduce unnecessary warnings and take advantage of existing functionality.
Ran existing tests and tested manually to verify that warnings are no longer thrown.
> Use Configuration class to parse table definition rather than JsonFile

- tools/dev/manage_saved_charts.php
While checking the likely impact of changing statistic identifier strings, I found it useful to be able to dump the JSON representation of chart objects stored in the database.
Used during code examination.
> Add support for dumping chart config objects as JSON

- configuration/logrotate.conf
Fix logrotate rule to avoid errors when `/var/log/xdmod` has ownership `apache:xdmod`.
```
error: skipping "/var/log/xdmod/dwi.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/xdmod/exceptions.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/xdmod/query.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell …
```
> Minor fix to logrotate rule

- configuration/etl/etl_action_defs.d/common/hpcdb/email-addresses.json
- configuration/etl/etl_action_defs.d/common/hpcdb/system-accounts.json
Adds additional "records" to the ETL "source_query" for ingestion into the HPCDB system accounts table.  Also adds the same for the HPCDB email addresses table which isn't used in Open XDMoD, but may as well have the proper primary keys.
This is needed to prevent duplicates from being inserted during ingestion into the HPCDB.
Ran automated tests.
> Add primary keys to ETL source queries

- configuration/roles.d/cloud.json
- tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/roles.json
This changes disables the User group by in the Cloud realm
The User group by in the Cloud realm joins the the modw.systemaccount table to get user information and rows are only added to this table if the have run a job on a resource. Since the cloud realm is not tracking jobs but instead events there in no existing mechanism to load the users listed on these events into the systemaccount table. 
In the next release after 8.0 a way to ingest users listed in the cloud logs will be created so that the User group by can be enabled.
> Disabling the User group by for the Cloud realm

- classes/OpenXdmod/Setup/AddResourceSetup.php
- classes/OpenXdmod/Setup/AdminUserSetup.php
- classes/OpenXdmod/Setup/Console.php
- classes/OpenXdmod/Setup/DatabaseSetup.php
- classes/OpenXdmod/Setup/ListResourcesSetup.php
- classes/OpenXdmod/Setup/Menu.php
- classes/OpenXdmod/Setup/ResourcesSetup.php
- classes/OpenXdmod/Setup/SetupItem.php
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-setup.tcl
`xdmod-setup` add resource menu hard-codes a resource type of 1 (HPC). Prompt the user for the resource type, defaulting to HPC. Allowable types are currently HPC and Cloud. Use the `etc/resource_types.json` file to map from the string to `resouce_type_id`.
Needed by @chakrabortyr and @eiffel777 for adding cloud resources during testing.
Manual and shippable.
> Prompt for resource type in xdmod-setup

- configuration/etl/etl.d/jobs_cloud_eucalyptus.json
- configuration/etl/etl.d/jobs_cloud_openstack.json
- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
Currently, in etl.d/jobs_cloud_eucalyptus and etl.d/jobs_cloud_openstack the path to the directory containing log files is a hardcoded placeholder directory that is should be replaced manually when adding a new cloud resource. This change will allow us to use an ETL command line variable named CLOUD_EVENT_LOG_DIRECTORY specified using the -d command instead of having to manually change the directory when a new resource is added. Below is an example of the new command line argument that should be used.
```
php /usr/share/xdmod/tools/etl/etl_overseer.php -p jobs-cloud-ingest-openstack -r openstack -d "CLOUD_EVENT_LOG_DIRECTORY=/path/to/openstack/data"
```
The tests were also updated to use -d flag when ingesting cloud event data.
Using a command line variable to specify the location of the …
> Changing path to look for cloud event logs to use an ETL command line variable

- classes/ETL/EtlOverseerOptions.php
Add support for `number_of_days` as an overseer restriction in ETL queries. This will be used to query jobs that were modified in the past N days. We can now ingest using 2 methods:
- use `--number-of-days | -n` to ingest job records modified in the past N days (the proposed default)
- use `--start-date | -s` and/or `--end-date | -e` to ingest jobs that ended between the specified start and end dates (good for historical re-ingestion)
Manual ingest using docker.
> Support for ingesting job records modified in the past N days

- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
This command is causing the shippable builds in the supremm module to fail due
to the directory already existing. I just added -p so that it will continue
on if it already exists.
It's nice when Shippable passes
Tested w/ the docker image / process used in the xdmod-supremm shippable process.
> Added the -p flag to mkdir in bootstrap

- classes/XDChartPool.php
- classes/XDReportManager.php
- html/controllers/report_builder/enum_available_charts.php
- html/controllers/report_builder/enum_reports.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/ReportBuilderTest.php
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/cd_enum_available_charts.json
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/cd_enum_reports.json
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/cs_enum_available_charts.json
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/cs_enum_reports.json
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/pi_enum_available_charts.json
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/pi_enum_reports.json
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/usr_enum_available_charts.json
- tests/artifacts/xdmod-test-artifacts/xdmod/report_builder/output/usr_enum_reports.json
For the following controller operations:
- `report_builder/enum_available_charts.php`
- `report_builder/enum_reports.php`
The following values are not used:
- `has_charts_in_other_roles`
- `charts_in_other_roles`
- `has_reports_in_other_roles`
- `reports_in_other_roles`
This consequently means that the following functions are not used:
- `XDChartPool::enumChartsUnderOtherRoles`
- `XDReportManager::enumReportsUnderOtherRoles`
Which means we no longer need to populate / reference the `active_role` column
in:
- `moddb.ChartPool`
- `moddb.Reports`
And that the report_builder test output needs to be updated for:
- [user]_enum_available_charts
- [user]_enum_reports
In addition to removing code that is no longer used, this also saves us from having to update / migrate these usages of …
> Remove chart / report active role usage

- configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
Currently, the sql query that updates a volume asset with an end time joins against the openstack_raw_event table and uses a where clause to find all volume.delete.end events to find the end time. When testing on metrics-dev it became apparent that this was taking far too long to complete. 
To reduce the query time we can create a temporary table with all the necessary volume.delete.end information and join against that table which is a significantly smaller dataset to join against.
Sql statement to update volume asset end times is taking too long
> add temporary table that contains volume delete event information and join against it to get the time a volume was deleted

- classes/ETL/Ingestor/CloudStateReconstructorTransformIngestor.php
- configuration/etl/etl_action_defs.d/cloud_common/cloud_state.json
- configuration/etl/etl_action_defs.d/cloud_common/cloud_transient.json
- configuration/etl/etl_action_defs.d/cloud_common/initialize_unknown_dimension_values.json
- configuration/etl/etl_tables.d/cloud_common/account.json
- configuration/etl/etl_tables.d/cloud_common/asset.json
- configuration/etl/etl_tables.d/cloud_common/avail_zone.json
- configuration/etl/etl_tables.d/cloud_common/cloud_transient.json
- configuration/etl/etl_tables.d/cloud_common/event.json
- configuration/etl/etl_tables.d/cloud_common/event_reconstructed.json
- configuration/etl/etl_tables.d/cloud_common/host.json
- configuration/etl/etl_tables.d/cloud_common/image.json
- configuration/etl/etl_tables.d/cloud_common/instance.json
- configuration/etl/etl_tables.d/cloud_common/instance_type.json
- configuration/etl/etl_tables.d/cloud_common/region.json
- open_xdmod/modules/xdmod/component_tests/lib/ETL/CloudStateReconstructorTransformIngestorTest.php
This pull request enables proper support for ingestion of multiple resources. We now properly key on resource_id AND instance_id when generating cloud tables. Additionally, we address a bug in the MyISAM engine by reordering key pairs to ensure auto-incremented keys are ordered first. A logical error in event reconstruction was also addressed.
Lastly, any lingering defaults of 1 were set to -1 for consistency with the rest of XDMoD data.
Consistency, bugfixes, and deliverable mandates.
Manual tests on metrics-dev and additional unit tests to ensure proper event reconstruction.
> Proper Support For Multiple Cloud Resource Ingestion + Ingestion Bugfixes

- configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
There is a query that gets the assets for an event in configuration/etl/etl_action_defs/cloud_openstack/event_assets.json that is running slow once you have a larger set of data. This query has a where query that uses the volume_id and adding an index on that column speeds up the query
Slow queries are bad
> Adding index to openstack_staging_event table 

- Dockerfile
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/input/create_users.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/create_user-cd.one-center.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/create_user-cs.one-center.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/create_user-normal_user.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/create_user-pi.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/create_user-usr_dev.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/create_user-usr_mgr.json
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/create_user-usr_mgr_dev.json
1. Delivers all mail to /var/mail/root 
1. Prevent invalid sendmail configuration from causing errors
1. Enable future testing of email send verification
```diff
diff --git a/docker/xdmod/Dockerfile b/docker/xdmod/Dockerfile
index f9d0044..2a5804d 100644
--- a/docker/xdmod/Dockerfile
+++ b/docker/xdmod/Dockerfile
@@ -26,12 +26,13 @@ RUN yum install -y \
google-chrome-stable \
nodejs \
jq \
+    postfix \
php-mbstring \
https://github.com/ubccr/xdmod/releases/download/v$REL/xdmod-$REL-$BUILD.el7.noarch.rpm
RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install git2u
-RUN yum -y remove ius-release
+RUN yum -y remove ius-release ssmtp
RUN yum clean all
RUN rm -rf /var/cache/yum
@@ -49,6 +50,15 @@ RUN php -r "copy('https://getcomposer.org/installer', …
```
> update to 'working' email

- configuration/etl/etl.d/staging.json
- configuration/etl/etl_action_defs.d/common/staging/resource.json
Creates resource records for all resources in `resources.json` (even if they are not present in `mod_shredder.staging_resource`).  This assigns a primary key to the resource that is used throughout the ETL process.
Cloud resources don't include the resource name in their data.  Since the `resource_id` must be known before the data is inserted into the relevant tables this value must be present in `modw.resourcefact` before the cloud data is ingested.  These changes provide a mechanism to add records to `modw.resourcefact` when no other data for that resource exists in the database.
Added a record to `resources.json` and ran:
```
/usr/share/xdmod/tools/etl/etl_overseer.php \
-a xdmod.staging-ingest-common.resource-config \
-a xdmod.staging-ingest-common.resources \
-a …
```
> Ingest resource names from `resources.json`

- configuration/etl/etl_sql.d/cloud_eucalyptus/post_ingest_updates.sql
- configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
Add resource_id to where clause when updating end time for instance in post ingest
Adding the resource_id to the where clause makes sure that you are getting the correct instance and resource.
> Add resource_id to where clause when updating end time for instance in post ingest

- open_xdmod/modules/xdmod/regression_tests/runtests.sh
The commit 6eeea8dfeccb9bbfae30e1b3f760d4493a20d5a9 erroneously removed the UsageChartTests.
> Fix test harness run script

- configuration/etl/etl.d/jobs_cloud_common.json
- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
- open_xdmod/modules/xdmod/integration_tests/scripts/helper-functions.tcl
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-setup.tcl
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade-add-cloud-resource.tcl
Updating the xdmod-setup.tcl and adding xdmod-upgrade-add-cloud-resource.tcl file to programmatically create cloud resources for testing instead of manually add a resource to the database. Also adding etl actions to jobs-cloud-common.json to ingest resources from the resources.json config file.
In xdmod-setup.tcl a series of prompts were added so that a cloud resource can be added for testing the same way that regular HPC resources are added in that file. When the upgrade tests are run a file called xdmod-upgrade-add-cloud-resource.tcl was added to add a cloud resource for running the upgrade tests.
Once the resources are added in using the .tcl files they then need to be imported into the database. To do this 4 actions where added to the jobs-cloud-common.json file based off the …
> Update xdmod setup tcl script

- configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
Removing sql statement that truncates modw_cloud.openstack_staging_event
The modw_cloud.openstack_staging_event table is the source of uniqueness for the event_id values that are loaded in the event table. Since this table is truncated every time the jobs-cloud-extract-openstack the autoincrement key gets reset and the rows used to prevent duplicates being added are removed causing duplicate data to be loaded into he event table and be aggregated on. Removing the truncate table statement fixes this problem.
Tested locally in docker
> Removing statement that truncates openstack_staging_event table

- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-setup.tcl
- open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade-add-cloud-resource.tcl
Longer timeouts needed to allow for acl-config to run. It takes ~40 seconds to run in the supremm module CI process. 
Also simplify timeout settings
> Bump up expect timeouts to account for slow acl-config program

- configuration/etl/etl_action_defs.d/cloud_eucalyptus/staging_event.json
Fixes typo in join conditions.
Current action is producing error messages:
```
2018-09-11 05:41:33 [warning] Exception thrown by xdmod.jobs-cloud-eucalyptus.EucalyptusRawCloudVolumeIngestor (ETL\Ingestor\StructuredFileIngestor) but stop_on_execution=false, continuing
2018-09-11 05:41:44 [warning] SQL warnings on table '`modw_cloud`.`eucalyptus_staging_event`' generated by action xdmod.jobs-cloud-eucalyptus.EucalyptusCloudStagingEventIngestor
2018-09-11 05:41:44 [warning] Warning 1292 Truncated incorrect DOUBLE value: '172.17.0.31'
```
No tests.
> Fix typo in Eucalyptus Cloud action

- html/gui/general/login.php
Html escaping of the `$formal_name` variable that is populated ( in some cases ) via the `xd_user_formal_name` request parameter. 
A vulernability report was submitted by Graham Ryder from Cambridge that detailed
two vulnerabilities that a pen test found w/ their instance of XDMoD. This commit
resolves one of these vulnerabilities referred to as: CVE-2018-16960. This relates
to a XSS vulnerability found in the  page that was not escaping request
data before inserting it into the page. The other is resolved by https://github.com/ubccr/xdmod/pull/670
> Addressing Vulnerability Report

- html/controllers/user_admin/enum_institutions.php
Per testing by @plessbd. When initializing more than one new user account from
requests, unless the user's 'Organization' was found by name in the db, then
when a person was selected to map the new user to the organization id would be
displayed not the organization name. The steps to re-produce are:
- Start with at least 2 user account requests
- Select the first user account request
- Click 'Initialize New User Dialog'
- Assign a Person to this User.
- click 'cancel'
- Select the next user account request
- Click 'Initialize New User Dialog'
- Assign a Person to this User.
- Notice that the 'Institution' box displays a number instead of a name.
The reason this was occurring is that the data store used to populate the
Institution drop down was only being refreshed ( without a filter ) the …
> Fix for user organization not populating

- classes/Rest/Controllers/PersonControllerProvider.php
Updated the person organization rest path to accept negative numbers
We now have the Unknown Person who will always have an id of -1. To support the
lookup of this person's organization we need to update this route to accept
negative numbers.
Manual Tests:
- Create a new user and attempt to assign the 'Unknown User' Person to them.
- Modify an existing user and attempt to assign the 'Unknown User' Person to them.
- Initialize a user account request and attempt to assign the 'Unknown User' Person to them
- Initialize a user account request and attempt to assign the 'Unknown User' Person to them
> Updating the person organization route to accept negative numbers

- configuration/etl/etl.d/jobs_cloud_eucalyptus.json
- configuration/etl/etl_schemas.d/cloud/volume.schema.json
The EucalyptusRawCloudVolumeIngestor action was using event.schema.json as it's schema file when ingesting eucalyptus volume information. This schema did not match he json being ingested in EucalyptusRawCloudVolumeIngestor and was causing errors. This schema should only be used for EucalyptusRawCloudEventLogIngestor. For EucalyptusRawCloudVolumeIngestor a  new schema was created to match the json being ingested
Using the wrong schema file was preventing eucalyptus volume information from being ingested.
> adding correct schema file for ingesting eucalyptus raw volume information

- classes/Rest/Controllers/WarehouseControllerProvider.php
Updated the mostPrivilegedRole check to include a test for `$user->getPersonId() !== -1`. The mostPrivilegedRole property is what controls the automatic setting of quick filters on the front end.
If the user is assigned to the Unknown Person than the person filter will
not be automatically selected.
Manual Tests
- Create / find a user that's associated with the Uknown person.
- Log in as the user and ensure that there are no quick filters automatically selected.
> Updating quickfilters to not automatically select for the Unknown Person

- classes/DataWarehouse/Query/Storage/GroupBys/GroupByNone.php
Disables the trend line displayed by default on the storage summary charts.
These trend lines were not consistent with defaults for other realms.
Tested manually on development server.
> Disable storage "Group By None" default trend line

- classes/XDUser.php
- email_templates/password_reset.template
- html/controllers/user_admin/pass_reset.php
- html/controllers/user_auth/pass_reset.php
… template.
Addresses one of my gripes in Asana about our forgot password emails not explicitly stating when the reset link expires.
Minimizes support questions, user friendliness.
Sent a bunch of emails to myself in Docker
> Added Locale Specific Password Expiration Times in Forgot Password Email

- classes/XDWarehouse.php
- html/controllers/sab_user/enum_tg_users.php
- open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/internalDashboard.js
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/ControllerTest.php
- tests/artifacts/xdmod-test-artifacts/xdmod/controllers/output/sab_user_enum_tg_users.json
Fix display of person name to use long_name field from database instead of reconstructing on internal dashboard 
Specifically for the federation this is needed with duplicate names.
Locally modified and tested the federation hub to make sure things still worked
> Use long_name field from database

- classes/Authentication/SAML/XDSamlAuthentication.php
- configuration/portal_settings.ini
- docs/simpleSAMLphp.md
- templates/portal_settings.template
- We are no longer notifying the user when we are unable to identify which
organization they are associated with.
- We are now **always** notifying the admin when we assign a user the unknown
organization.
- Since we're always notifying the admin we no longer need the
`email_admin_sso_unknown_org` property.
We should make sure to only notify the people who can do something about a particular situation. 
Manual Tests were performed: 
- Sign in via SSO with:
- A User that has an organization that will not be identified
- Check that an email was sent correctly to the admin address
- Sign in via SSO with:
- A User that has an organization that will be identified
- Check that no email was sent
- Sign in via SSO with:
- A User that will be matched with a valid person 
- Check that no email was …
> Updating who is notified when SSO unknown org occurs

- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
Adding a call to `acls-import` to the bootstrap fresh_install. 
This will ensure that test users created during the bootstrap process have their
person / organization set appropriately. This will no longer be necessary once
we update the script that creates the users.
All Automated Tests: Unit, Component, Integrated, UI
Manual Test: 
- Spin up a fresh docker w/ a fresh install
- `mysql moddb`
- `SELECT id, username, person_id, organization_id`
- Ensure that all person_id's == -1 || >= 1
- Ensure that all organization_id' == -1 || >= 1
> Updating test users created during docker bootstrap

- classes/ETL/LockFile.php
- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
When running the ETLv2 as part of setup a directory for the lock files would get created `sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'xdmod'` owned by the root user.  
Subsequent calls to ETLv2 as the xdmod user would produce a warning of `[warning] Error creating lock file '/tmp/xdmod/etlv2_17065': fopen(/tmp/xdmod/etlv2_17065): failed to open stream: Permission denied`.
This would then allow multiple ETLv2 processes to clobber each other
This update sets the default lock file directory to just be `sys_get_temp_dir()` allowing multiple processes to create and read the lock files and not clober each other.  As well as forces the CI tests to simulate this case.
Another ticket will be created that will cause this warning to actually be an error.
> ELT V2 Update

- classes/Authentication/SAML/XDSamlAuthentication.php
- classes/DataWarehouse.php
- configuration/user_management.json
- open_xdmod/modules/xdmod/build.json
The sql query to identify a person from a username is now defined in a config file. This allows us to override the configuration for the XSEDE module (which uses a different lookup).
The code has also been updated to only map a username to a person if a unique mapping exists. Sites that have multiple different people with the same usernames on different resources will have to update the configuration file to define how to find the user properly.
> Make person lookup configurable

- configuration/etl/etl_action_defs.d/cloud_eucalyptus/instance.json
- configuration/etl/etl_action_defs.d/cloud_eucalyptus/volume.json
- configuration/etl/etl_action_defs.d/cloud_openstack/instance.json
- configuration/etl/etl_action_defs.d/cloud_openstack/volume.json
Add resource_id to where clause for cloud instance etl action for joining to both the account table and the user table
If the resource_id is not used in the where clause it is possible that the wrong account or user can be assigned to an instance if the same project name or username exists for two resources.
Tested in local docker manually and ran all component, integration and regression tests
> Add resource_id to where clause for cloud instance etl action

- classes/Authentication/SAML/XDSamlAuthentication.php
- classes/DataWarehouse.php
- classes/Models/Services/Organizations.php
- classes/OpenXdmod/Migration/Version751To800/DatabasesMigration.php
- classes/Rest/Controllers/AuthenticationControllerProvider.php
- classes/XDUser.php
- configuration/etl/etl_tables.d/xdb/users.json
- configuration/portal_settings.ini
- docs/simpleSAMLphp.md
- html/controllers/user_admin/get_user_details.php
- html/controllers/user_admin/update_user.php
- html/gui/general/login.php
- html/internal_dashboard/controllers/pseudo_login.php
- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- html/internal_dashboard/user_check.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/BaseUserAdminTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/SSOLoginTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UserAdminTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UserOrganizationTest.php
- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/PeopleHelper.php
- open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/XdmodTestHelper.php
- open_xdmod/modules/xdmod/integration_tests/phpunit.xml.dist
- open_xdmod/modules/xdmod/integration_tests/scripts/samlSetup.sh
- shippable.yml
- templates/portal_settings.template
- tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/input/create_users.json
Added additional functionality to both SSO & normal login path that makes sure
that the user that is authenticating has an up to date organization_id. A user's
organization can become out of date if the person they are associated with has
their organization changed. It can also occur if a User's person is updated but not their organization. 
We also do not check the organization if the user has been assigned the unknown
person or organizations.
Added a new `MailHelper` class that's a thin wrapper around
`MailWrapper::sendMail` to catch / log any exceptions that may be encountered
while sending an email.
We need to be able to account for when a user's assigned person has their organization updated. 
Manual Tests Performed:
- Manually update a centerdirector's user's person to somebody with …
> Update sso user retrieval

- classes/Models/Services/Organizations.php
The order of rows in an SQL union is not deterministic. You need to add an explicit order by clause if you want the order to be guaranteed. The original code assumed that the results would be ordered but there was no order by clause.
> Fix Organizations::getNameById

- etl/js/lib/dataset_processor.js
- etl/js/package.json
The nodejs mongo driver version support period ended (a while ago). This updates to a supported version.
Of course, the API changed in between versions so there are some code changes that accompany the driver update.
> Update Mongo Driver to a currently maintained version

- html/gui/js/modules/job_viewer/JobViewer.js
- html/gui/js/modules/job_viewer/SearchPanel.js
The job viewer search panel is hardcoded to ~1000 x 600 px and cannot be resized and scrollbars are disabled. It gets aligned to the top left so is unusable on a screen that is shorter than ~600px since the buttons at the bottom are not displayed. 
This change makes it so that the panel window will show scrollbars if necessary so that the ui component is usable on small displays.
> Allow search panel scroll bars on small displays

- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/Query/iJobMetadata.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- configuration/portal_settings.ini
- html/gui/js/modules/job_viewer/SearchPanel.js
- html/index.php
- templates/portal_settings.template
This change updates the internal API for the job viewer. The is a corresponding pull request
for the supremm realm updates. 
API updates to make it easier to support multiple realms in the job viewer. The changes are as follows:
- Add interface class that documents the job metadata API
- Change the JobDataset API to remove the realm-specific knowledge for primary key and 'Quick Lookup' searches of the database. The realm-specific code is moved to the realm-specific implementation.
- Remove the numeric-only constraint for local job id from the 'Quick Lookup' search on the front end. This realm-specific constraint is now managed in the realm-specific code.
- Remove the "singlejobviewer" configuration parameter from the portal_settings file. The job viewer is now automatically enabled if …
> Update Job Viewer API

- classes/DataWarehouse/Access/Usage.php
- open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
Added the ability for Usage chart requests to provide non-numeric values for
'_filter' parameters. The new feature will attempt to translate these
non-numeric values into appropriate id values that can be used during chart
generation. Specifically this new feature is to support integration w/
Coldfront.
> Add new functionality to Usage chart requests

- classes/OpenXdmod/Build/Packager.php
- open_xdmod/modules/xdmod/build.json
- open_xdmod/modules/xdmod/integration_tests/scripts/validate.sh
- shippable.yml
When building a module (or when copying the files under open_xdmod/*), the installer ignored the exclude_paths and exclude_patterns settings from the build.json file. This lead to work-arounds such as #715.
This change makes it so that these settings are honoured and reverts the workaround that was added in #715. Also adds a test to check that the new code works properly.
> Implement path filtering for modules

- classes/DataWarehouse/Access/Usage.php
- html/gui/js/modules/Usage.js
The thumbnail charts view in the Usage tab has been painfully slow since the usage backend was replaced by a shim layer that uses the metric explorer backend. 
This pull request does not fix the poor performance of the backend code. Instead it makes the thumbnail charts load asynchronously. The user interface is still responsive while the charts are loading and the charts are loaded from top to bottom so the visible ones are likely to be rendered first (although this is not guaranteed due to the async nature).
Changing the loader code to only load the visible charts is left as an exercise for Ben.
> Asynchronous loading of Usage tab thumbnail charts 

- classes/Authentication/SAML/XDSamlAuthentication.php
as reported by @treydock 
```
Dec 19 12:24:17 xdmod-test simplesamlphp[88861]: 4 [TR5d8c0783] The class or interface 'SimpleSAML_Auth_Simple' is now using namespaces, please use 'SimpleSAML\Auth\Simple'.
```
> Fix deprecation warning

- classes/ETL/EtlOverseer.php
If resource codes are specified for either inclusion or exclusion the mapping between resource codes and database ids is loaded and the resource codes are verified against this mapping. If only inclusion or exclusion resources were specified, a `null` would be passed to `array_merge()` causing an error. This PR casts the value to an array to mitigate this.
Fixes error when running ETL on XSEDE
```
Warning: array_merge(): Argument #1 is not an array in /data/www/xdmod/share/classes/ETL/EtlOverseer.php on line 185
```
Manual testing on XSEDE development instance.
> Explicitly cast potentiall nulls to array for array_merge()

- classes/XDUser.php
This specifically removes the microtime from lastLoginTimestamp, but will also effect this line: https://github.com/ubccr/xdmod/blob/xdmod8.1/html/index.php#L520
Which will now show the ProfileEditor for Single Sign On (SSO) users that just so happen to have their account created and their login happen within the same second.
This maintains the previous functionality.
This does not address the following issues:
User is created and the first login does not happen in the same second (all non SSO users)
User refreshes the page / leaves and comes back without logging out will continue to see the profile editor dialog.
This might be fixed at a later date.
> Make lastLogin time be floored to the second instead of microtime

- classes/OpenXdmod/Migration/Version800To810/DatabasesMigration.php
- classes/Rest/Controllers/MetricExplorerControllerProvider.php
- html/controllers/ui_data/summary3.php
- open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Migration/Version800To810/DatabasesMigrationTest.php
The current code had paths in both the summary controller and metric explorer rest stack that tried to handle the case where metric explorer saved chart data was stored in the pre-XDMoD 5.5 format. Needless to say it is a bit wastefull to run these checks every time and it also has an impact on code maintenance. 
This change runs the migration once in the upgrade so that any pre XDMoD 5.5 save charts will be converted to the current format. The code that handles the old format is removed.
<ESC>:wq
> Add migration for Metric Explorer query store.

- etl/js/.eslintrc.json
- etl/js/lib/etl_profile.js
- etl/js/lib/etlv2.js
The postprocessing SQL statements were previously executed after the end of data for each resource. This meant that the same statement was executed multiple times on systems that had multiple resources. When the query is executing the database is locked so no ingestion can happen. On our staging system (that has a slow database) the postprocessing query took so long to run that it ended up hitting the mongo connection timeouts for some of the resources.
This changes the framework to not execute the SQL in the ingestion process at all. Instead it is written to an ETLv2 config file and must be executed in the etlv2 pipeline before aggregation.
Note that there are two commits - the first one fixes up the style. The actual code changes are in the second commit.
> Move the postprocessing SQL to the aggregation pipeline

- docs/_includes/menu.md
- docs/storage.md
Adds introductory paragraphs to storage documentation (credit to @smgallo ).  Also improves the input format explanation, moves the link the menu and changes the heading to be consistent with the cloud documentation.
No tests.
> Improve storage documentation

- classes/Models/Services/Parameters.php
`Parameters::getParameters` needed to have a case `institution` to support
Campus Champions users.
**NOTE: For a future PR, this should be redone in a way so as to allow modules to configure which acls require additional information and where to get it.** 
Campus Champions in an XSEDE install should work.
Manual Testing was performed: 
- Assign a user the 'Campus Champion' acl
- Log in as that user
- Ensure that all of the charts etc. show up as expected on the 'Summary' tab.
- Previously, no data was shown as `Parameters::getParameters` didn't know how to handle a request for `institution` parameters.
> Add support for campus champion parameters

- classes/ETL/DataEndpoint/DirectoryScanner.php
When running the DirectoryScanner ETL DataEndpoint in docker using the latest overlay2 storage driver and PHP 5.4, the `DirectoryScannerTest::testPatternFilters()` automated tests would fail because an incorrect number of files (exactly 2 times the expected number) was returned from a directory scan. When using the aufs driver (as shippable.com does) this did not manifest.
The error occurs when the `CallbackFilterIterator::rewind()` method is called twice in a row. The set of records returned by the iterator is duplicated. Since we iterate over the set using `foreach` and a `rewind()` is called under the hood by PHP it is not necessary to explicitly call it ourselves.
**Note that this bug does not manifest in PHP7 running in docker.**
Rescue developers from insanity wondering why tests …
> Don't automatically rewind DirectoryScanner file handle

- classes/DataWarehouse/Access/MetricExplorer.php
- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/QueryBuilder.php
- classes/Models/Services/Acls.php
- classes/Models/Services/Organizations.php
- classes/Models/Services/Parameters.php
- classes/Rest/Controllers/MetricExplorerControllerProvider.php
- classes/Rest/Controllers/UserControllerProvider.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- classes/XDUser.php
- html/controllers/metric_explorer/get_dw_descripter.php
- html/controllers/user_interface/get_menus.php
- html/index.php
- libraries/roles.php
- open_xdmod/modules/xdmod/component_tests/lib/AclsTest.php
- open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
- open_xdmod/modules/xdmod/tests/lib/NewRest/Controllers/BaseControllerTest.php
This is it, the last PR before being able to remove the Role* classes. 
Active / Primary Role, as a concept, no longer applies to XDMoD Users. Instead we have replaced it with Most Privileged Role. This PR implements those changes by doing the following:
- Remove usage of the last function that instantiates roles: `XDUser::assumeActiveRole`
- Migrate function that utilized `User::assumeActiveRole`, `XDUser::getAllRoles` to return an array of strings ( acl names: 'cd', 'cs', 'usr' etc. ) as opposed to an array of Role objects. 
- This change necessitated updating code that operated on the results of `XDUser::getAllRoles` to account for the change in type. Mainly replacing: `$role->getIdentifier()` -> `$role`. 
- Since we are no longer instantiating Roles this means that, oddly enough, a …
> Active, Primary, Most Privileged Role Consolidation

- classes/CCR/ColumnLayout.php
- classes/Rest/Controllers/SummaryControllerProvider.php
- html/gui/js/modules/NoviceUser.js
This is needed for the Center Director and Center Staff views. To
configure a panel as a top panel set "region" to "top" in the
portlet configuration for the role.
Also added support for overriding preset charts (this is setup to
match the existing summary tab behavior).
Also fixed a bug where the summary page didn't render correctly if you loaded the interface with a different tab first.
> Added support for creating a full width top panel.

- etl/js/etl.js
- etl/js/lib/etl_profile.js
The  javascript-based ETL test harness was not setting the process exit code appropriately when the tests failed. In addition the tests were failing
> Fix test harness for javascript-based ETL code

- bin/xdmod-ingestor
- bin/xdmod-shredder
- classes/ETL/Ingestor/HpcdbHostsIngestor.php
- classes/OpenXdmod/DataWarehouseInitializer.php
- classes/OpenXdmod/Shredder/Storage.php
- configuration/etl/etl.d/hpcdb-xdw.json
- configuration/etl/etl.d/ingest_resources.json
- docs/storage.md
Mirrors changes in #739.  Adds storage options to the `xdmod-shredder` and `xdmod-ingestor` command line utilities.  Also splits out the actions from one of the job pipelines into a separate "common" pipeline that contains actions that are needed by both the jobs realm and storage realm.
This change will allow for more uniform use of command line utilities for the storage realm.
Tests to be added in separate pull request.
> Add storage shredder/ingestor support

- html/gui/js/modules/Usage.js
The updates to add category support to the usage tab tree caused the reload button to break. This fixes it.
> Fix reload button in Usage Tab tree

- templates/roles.d/cloud.json
This adds two default summary tab charts when the cloud realm is enabled.
> add some summary charts for the cloud realm

- classes/DataWarehouse/Query/TimeAggregationUnit.php
- open_xdmod/modules/xdmod/tests/lib/DataWarehouse/Query/TimeAggregationUnitTest.php
Found during testing of the Job Efficiency Report code. Added a new unit test to check correct behaviour. Note that if we add support for geological eras to the code then the tests will likely need updating.
> Fix path to exception in TimeAggregationUnit::factory

- classes/ETL/Ingestor/RestIngestor.php
- classes/ETL/Maintenance/VerifyDatabase.php
- classes/ETL/Utilities.php
- classes/ETL/VariableStore.php
`ETL\Utilities::substituteVariables()` was deprecated by `ETL\VariableStore`. This removes the last remmants.
> Remove deprecated code

- configuration/etl/etl_action_defs.d/cloud_generic/instance_type.json
- configuration/etl/etl_action_defs.d/cloud_openstack/instance_type.json
- configuration/etl/etl_tables.d/cloud_generic/raw_event.json
- configuration/etl/etl_tables.d/cloud_generic/raw_instance_type.json
Updates the generic tables to use string / decimal for dates in the cloud realm.
@eiffel777 said he was able to verify the changes.
> Fix for generic cloud datetime, and openstack instance type datetime

- configuration/etl/etl.d/jobs_cloud_generic.json
- configuration/etl/etl_sql.d/cloud_generic/post_ingest_updates.sql
- configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
- configuration/etl/etl_tables.d/cloud_common/event.json
- configuration/etl/etl_tables.d/cloud_common/event_reconstructed.json
- configuration/etl/etl_tables.d/cloud_common/instance_type.json
- configuration/etl/etl_tables.d/cloud_generic/staging_event.json
- configuration/etl/etl_tables.d/cloud_openstack/raw_volume.json
- configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
Found some more places where the generic and openstack datetimes needed to be fixed.
Whitespace changes from `(16, 3)` to `(16,3)` is required so that the ETL does not do an alter table
Travis will have to be overridden.
> More fixing for datetime changes

- configuration/etl/etl_action_defs.d/cloud_generic/event_asset.json
removing duplicate join statement that was causing 1066 Not unique table/alias error when ingesting data in the generic cloud format
Tested manually
> removing duplicate join statement that was causing 1066 Not unique table/alias error

- configuration/etl/etl_action_defs.d/cloud_generic/union_user_pi_resource.json
- configuration/etl/etl_action_defs.d/cloud_openstack/union_user_pi_resource.json
This prevents the usernames that are null for a cloud event from being ingested and causing an error when running the cloud ingestor pipelines
Manually tested in docker and passed existing tests
> Prevent null usernames being added when ingestion cloud data

- configuration/etl/etl.d/jobs_cloud_generic.json
- configuration/etl/etl.d/jobs_cloud_openstack.json
- configuration/etl/etl_action_defs.d/cloud_generic/staging_event.json
- configuration/etl/etl_action_defs.d/cloud_openstack/staging_event.json
Changing where cloudstaging action gets user id from. Instead of using mod_shredder which does not exist in the xsede version use modw.systemaccount instead and add resource_id to join clause.
This also fixes this error.
```
ETL\EtlOverseer: Error verifying data endpoints:
('Cloud DB', class=ETL\DataEndpoint\Mysql, config=datawarehouse, schema=mod_shredder, host=tas-db1.ccr.buffalo.edu:3306, user=xdmod): Schema 'mod_shredder' does not exist for user 'xdmod'
#0 /data/www/xdmod/share/classes/ETL/EtlOverseer.php(379): ETL\EtlOverseer->verifyDataEndpoints(Object(ETL\Configuration\EtlConfiguration), true)
#1 /data/www/xdmod/share/tools/etl/etl_overseer.php(612): ETL\EtlOverseer->execute(Object(ETL\Configuration\EtlConfiguration))
#2 {main}
```
Prevents errors with being used with XSEDE and …
> Changing where staging action gets user id from for cloud data

- composer.json
- configuration/linker.json
**NOTE:** The Travis tests will fail because we changed `composer.json` but there is no accompanying change to `composer.lock`. This is expected. 
The problem is that when these entries were only in `composer.json` the
classpath was determined prior to run time, aka. before any other modules are
installed. So, if a module has code installed to any of these paths they will
not be found at round time. By moving them back into `linker.json` we resolve
this problem.
runtime exceptions bad
All automated tests on OpenXDMoD docker ( upgrade / install )
> Addressing problem found by @jtpalmer

- configuration/etl/etl_tables.d/cloud_generic/staging_event.json
- configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
In PR #797  the Person and System Account group bys were added to the Cloud realm. In that PR the person_id field was added to the staging tables with a default of NULL and was added to the Primary Key on that table. This caused the error below on the xdmod-dev database.
```
xdmod.jobs-cloud-extract-openstack.OpenStackCloudStagingEventIngestor (ETL\Ingestor\DatabaseIngestor): 
Error managing ETL table for 'xdmod.jobs-cloud-extract-openstack.OpenStackCloudStagingEventIngestor': 
SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
```
This error doesn't show up on metrics-dev or in the my docker but does on xdmod-dev and it seems to be because metrics-dev and my docker run MySQL 5.5 and xdmod-dev …
> Change cloud person username fields to be not null

- open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
In order to leverage the `bootstrap.sh` script while building a docker image from the current git repo, we need to ignore the exit status of 1 that `rpm -qa | grep ^xdmod` returns when there are no XDMoD rpms installed. Otherwise, `set -e` and `set -o pipefail` will cause the script to abort.
Need to be able to leverage existing bootstrap commands rather than maintain them separately in the Dockerfile.
Built a dockerfile.
> Ignore having no XDMoD rpms to remove in bootstrap on fresh install

- configuration/etl/etl.d/jobs_cloud_common.json
When `xdmod-ingestor` is run with no options it tries to ingest data from both the openstack and generic raw cloud tables. If no data has ever been shredded in one of the two formats the error below will occur. Adding both the openstack and generic raw tables to the CloudTableManagement action prevents this error from occurring.
```
2019-01-16 04:15:19 [error] xdmod.jobs-cloud-extract-generic.GenericCloudInstanceTypeIngestor (ETL\Ingestor\DatabaseIngestor): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'modw_cloud.generic_cloud_raw_instance_type' doesn't exist Exception: 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'modw_cloud.generic_cloud_raw_instance_type' doesn't exist'
2019-01-16 04:15:19 [warning] Stopping ETL due to exception in …
```
> Adding cloud raw tables to cloud manage tables action

- classes/CCR/MailWrapper.php
- classes/OpenXdmod/Migration/Version800To810/ConfigFilesMigration.php
- configuration/portal_settings.ini
- open_xdmod/modules/xdmod/integration_tests/email-subject-test.sh
- open_xdmod/modules/xdmod/integration_tests/runtests.sh
- templates/portal_settings.template
Add an email subject prefix to all outbound emails.
This was tested in a docker by looking at `/var/mail/root` and sending some test emails.
> Add email subject prefix

- open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
- open_xdmod/modules/xdmod/regression_tests/runtests.sh
Add the ability to record timings of the regression tests and update runtests to be a tiny bit smarter @jtpalmer if this makes it more difficult for you to refactor as part of your storage work let me know and I will kill it.
> allow for timing to be recorded and fix up runtests

- docs/cloud.md
- docs/ingestor.md
- docs/shredder.md
Updated the cloud docs for release prep
We're getting ready for 8.1
N/A
> Updated Cloud Documentation for 8.1 Release

- classes/Configuration/ModuleConfiguration.php
Made sure that the handling of the `extends` keyword only occurs if the current Configuration is for a local config file.
If `extends` is processed for a local config file, it is entirely possible ( really probable ) that the target will not be present. This will cause the code to throw an exception as it won't be able to properly resolve the configuration data.
Manually verified that I was able to re-produce the error within an xsede docker & the refactored configuration files. Applied the required `if` statement and re-verified that `acl-config` now finishes without a problem.
> Only process extends for non local config files in `ModuleConfiguration`

- html/gui/js/modules/Summary.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
This change removes some of the coupling of the Summary tab and the Metric Explorer tab. The Summary tab no longer modifies a private member variable of the metric explorer. Instead the Metric
Explorer just fires an event at the Summary tab and does not have its internal state modified by an external class.
This de-coupling will lead to cleaner code in the upcoming novice user tab.
> Decouple the metric and summary tabs

- classes/OpenXdmod/DataWarehouseInitializer.php
The previous SQL statement answered the question, Is there a $realm that has
been installed. This updated version answers the question, Is there an acl that
grants access to this realm. This corresponds w/ having an entry in
`roles.json#<role>#query_descripters` w/ a `realm` property = $realm, that is
both enabled and visible.
Get things working 
Modified the `bootstrap.sh` file to only install the `Jobs` realm then ran the integration tests. The `getDWDescripters` tests failed as expected. 
Did a fresh_install and nothing borked, weee.
> Update `isRealmEnabled` sql

- classes/OpenXdmod/Setup/DatabaseSetup.php
- configuration/etl/etl.d/storage.json
Add a storage bootstrap pipeline to the setup process.  These tables would be automatically created, but it's preferred to create them during setup for a future manually database setup process.
> Add missing bootstrap pipeline

- classes/OpenXdmod/DataWarehouseInitializer.php
This PR does two things. It add the jobs-cloud-common pipeline to cloud ingestor to prevent errors from occurring during ingestion when the cloud realm is enabled but no cloud data has been shredded. It also adds debug messages to the functions is DatawarehouseInitializer.php that run ingestion and aggregation pipelines when checking to see if the realm they are ingesting data for is enabled.
Manually tested in docker and ran tests in docker as well.
> Add jobs cloud common pipeline to cloud ingestor

- bin/acl-config
So it turns out that PHP prepared statement variable binding doesn't play well
with SQL `IN` statements. Just moving things around a bit so that instead of
supplying the `IN` clause w/ a bind parameter we instead just populate it in the
base query string.
This PR is related to: https://ubccr.freshdesk.com/a/tickets/12470
It's nice to have a `recover` mode that actually functions
Manual Tests performed on a local docker instance.
> Updated SQL construction for `tablesExist`

- tests/ui/test/specs/xdmod/SSOLogin.js
the sso logout ui tests are sometimes failing with
```
Element <a href="javascript:CCR.xdmod.ui.actionLogout()" id="..._link">logout</a> is not clickable at point (223, 20). Other element would receive the click: <div class="ext-el-mask" id="ext-gen452" style="display: block; width: 2560px; height: 1600px; z-index: 9000;"></div>
```
this should help that
> Wait for loading mask to disappear on SSO logout

- configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day_joblist.json
Need to ensure that the jobid column in the joblist table matches the datatype of the column it references. i.e job_tasks.job_id
> Fix datatype of job_id column

- classes/Configuration/Configuration.php
- classes/ETL/DbModel/Entity.php
- classes/ETL/Maintenance/ManageTables.php
- classes/ETL/aEtlObject.php
- tests/unit/lib/ETL/DbModel/DbModelTest.php
General code cleanup and consistency update:
- Change `Configuration::getTransformedConfig()` to `toStdClass()` for consistency with other code.
- `Configuration::initialize()` now returns `$this` to support method chaining.
- Use `Configuration` in the ETL `DbModel` rather than `parseJsonFile` to enable support for comments, inclusion, and references.
- Remove deprecated `aEtlObject::parseJsonFile()`
General improvements and cleanup
Yes.
> General code cleanup

- tests/ci/scripts/create_xdmod_users.php
the `create_xdmod_users.php` script had default file with user and passwords hard coded to the path that shippable checks the repo out to
Lets just make it relative to the script itself.
> update path in creat_xdmod_users.php to be relative

- background_scripts/etl_aggregation_table_manager.php
- classes/CCR/Loggable.php
- classes/Configuration/CommentTransformer.php
- classes/Configuration/Configuration.php
- classes/Configuration/StripMergePrefixTransformer.php
- classes/ETL/Configuration/EtlConfiguration.php
- classes/ETL/DataEndpoint/aStructuredFile.php
- classes/ETL/DbModel/AggregationTable.php
- classes/ETL/DbModel/Entity.php
- classes/ETL/Maintenance/ManageTables.php
- classes/ETL/Utilities.php
- classes/ETL/VariableStore.php
- classes/ETL/aAction.php
- classes/OpenXdmod/Migration/Etlv2Migration.php
- classes/OpenXdmod/Migration/Migration.php
- tests/artifacts/xdmod/etlv2/configuration/output/xdmod_etl_config_8.0.0.json
- tests/component/lib/ETL/CloudStateReconstructorTransformIngestorTest.php
- tests/component/lib/ETL/DbModel/DbModelTest.php
- tests/component/lib/ETL/EtlOverseerTest.php
- tests/unit/lib/ETL/Configuration/ConfigurationTest.php
- tests/unit/lib/ETL/Configuration/EtlConfigurationTest.php
- tests/unit/lib/ETL/Configuration/IncludeTest.php
- tests/unit/lib/ETL/Configuration/Rfc6901Test.php
- tests/unit/lib/ETL/SqlParser/SqlParserTest.php
- tools/etl/etl_action_state_mgr.php
- tools/etl/etl_overseer.php
- tools/etl/etl_table_manager.php
The `Configuration` and extending classes such as `EtlConfiguration` and `XdmodConfiguration` are now used to process all XDMoD configuration files and local overrides (e.g., `roles.json` and files in `roles.d`) as well as ETL configuration files. The extremely flexible nature of these files introduces significant overhead when the same configuration file is required in multiple locations throughout the code to perform a given operation.
This implements an object cache so that the same global configuration file (e.g., `roles.d`) and local configuration files (e.g., files in `roles.d`) only need to be parsed once with the resulting object stored in an object cache. Subsequent accesses are retrieved from the cache. The unique cache key is generated using the following pieces of information: …
> Performance improvements by providing caching for Configuration objects built from JSON configuration files

- tests/ui/test/specs/xdmod/metricExplorer.page.js
Fixed the way that chart title is tested in ME
I changed the way that the current test checks to make sure the HighCharts graph displays correctly.  The issue was that the test was trying to set the title of the chart too quickly, so I modified the test to wait and change the title when it was possible.
Also modified setDateRange to properly wait until the mask disappears before setting the date.
It fixed a failed test when UI tests were run
Created instance of XDMoD in docker container and ran the UI Tests.
Docker container using tas-tools-ext-01.ccr.xdmod.org/centos7_6-open8.1.2:latest image.  ran "~/bin/services start", then ran UI tests
> Fixing timing issues in Metric Explorer UI Tests

- .travis.yml
As per the title.
Travis CI have moved their default integration to Xenial (Ubuntu 16.04), which does not support PHP 5.4. Blog post [here](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment).
Surely.
> Update Travis YML to explicitly use Ubuntu 14.04

- classes/XDUser.php
The logic should be:
User must have one: center staff / center director
**not**
User must have both: center staff / center director
**facepalm**
Manual Testing on xdmod-dev
> Fixed `getResources` authorization logic

- classes/ETL/Configuration/EtlConfiguration.php
As per discussion with @ryanrath improve error message clarity when `options_class` key is not defined for an ETL action.
> Improve error message for ETL action

- docs/configuration.md
Update processor buckets documentation to indicate that it is necessary to re-ingest the processor buckets file and re-aggregate job data after the processor buckets file is changed.
The file is documented, but the steps necessary after changing the file were missing.
https://listserv.buffalo.edu/cgi-bin/wa?A2=ind1907&L=CCR-XDMOD-LIST&X=8FDFD967F24AD32380&Y=jtpalmer%40buffalo.edu&P=3668
Manually ran the commands that are added to the documentation.
> Improve processor buckets documentation

- classes/Rest/Controllers/SummaryControllerProvider.php
- classes/XDReportManager.php
- configuration/assets.json
- configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
- configuration/etl/etl_tables.d/xdb/reports.json
- html/gui/js/modules/ReportGenerator.js
- html/gui/js/modules/summary/RecentChartsReportsPortlet.js
- html/gui/js/report_builder/ReportsOverview.js
This PR adds the recent charts and report portlet. The following files were changed:
- `classes/Rest/Controllers/SummaryControllerProvider.php` was updated to add a new REST endpoint `recentchartsreports`. This endpoint returns a user's recent charts and reports in JSON format. 
- `configuration/etl/etl_tables.d/xdb/reports.json`  was updated to modify the `Reports` table to include the last modified date.
- `configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json` was added to add the last modified field to the `Reports` table when migrating. 
- `classes/XDReportManager.php` was updated to return the newly added`last_modified` field when `fetchReportTable` is called. 
- ` configuration/assets.json` was updated to include the this portlet
- `html/gui/js/modules/ReportGenerator.js` was …
> Add recent charts and reports portlet

- tests/ui/test/specs/xdmod/metricExplorer.page.js
Have seen intermittent problems with the build on the supremm module where the metric explorer UI tests have been failing.
This change improves the robustness of the metric explorer load chart function to properly wait until the chart is loaded and the metric catalog has finished its animation.
> Increase robustness for tests

- html/gui/js/modules/job_viewer/JobViewer.js
kWh is apparently more understandable than the SI unit.
> Convert Joules to kWh for display in job viewer.

- html/gui/js/modules/job_viewer/JobViewer.js
This change adds a tooltip that shows the unmodified value in the
summary tab of the jobviewer. The tooltip is only added if the value
was reformatted.
Also remove a chunk of unnecessary code that manipulated the store for some reason.
> Add tooltips to jobviewer Summary value column

- html/gui/js/modules/NoviceUser.js
- html/gui/js/profile_editor/ProfileEditor.js
Why the gap at the bottom?
This is the height of the first tab so that when the user selects the Settings tab the box will not resize (and hence the close button will appear to be stationary)
Then the reset button is clicked (and the reset is sucessful) the summary page will be reloaded with the defaults and the button disabled.
The button is clickable even if the user is already using the default layout. It is too much effort to grey this out in this case.
> Added reset summary page layout UI

- html/gui/js/modules/NoviceUser.js
This PR fixes a bug in the User Tour creating that was causing multiple User Tours to be created when the summary tab is refreshed and then shown at the same time.
> fixing new user tour so duplicate tours are not made when the summary tab is refreshed

- html/gui/js/profile_editor/ProfileEditor.js
Turns out that the compositefield type was unnecessary and triggered an exception deep in the ExtJs code.
> Fix exception thrown in ExtJS

- classes/Rest/Controllers/SummaryControllerProvider.php
- configuration/roles.d/summary.json
Update the default setting for the novice user summary page to match the original design. Also add etlv2 variables for the person_id and person_name to allow this information to be used in chart filter configuration settings.
> Set default chart configuration

- html/gui/css/viewer.css
- html/gui/js/modules/summary/JobPortlet.js
Create a standard style for the grid "no data" messages. The various
portlets that could have no data available should use these css classes
for consistency.
> Unify the no data error messages.

- bin/acl-config
- bin/xdmod-ingestor
- classes/ETL/DataEndpoint/ConfigurationFileEndpoint.php
- classes/OpenXdmod/DataWarehouseInitializer.php
- classes/OpenXdmod/Setup/DatabaseSetup.php
- classes/OpenXdmod/Setup/ResourcesSetup.php
- configuration/etl/etl.d/acls-xdmod-management.json
- configuration/etl/etl.d/ingest_resources.json
- configuration/etl/etl.d/resource_types.json
- configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
- configuration/etl/etl_action_defs.d/acls/realms.json
- configuration/etl/etl_action_defs.d/common/hpcdb/resource-type-realms.json
- configuration/etl/etl_action_defs.d/common/staging/resource-type-realms.json
- configuration/etl/etl_tables.d/common/hpcdb/resource-type-realms.json
- configuration/etl/etl_tables.d/common/staging/resource-type-realms.json
- configuration/roles.json
- tests/integration/lib/Controllers/UserAdminTest.php
Added Resource Types -> Supported Realms relations that we then use to filter what data `acl-config` processes.
We wanted to be able to only process, in `acl-config` the realms that are currently enabled. To accomplish this we associated resource_types w/ the appropriate realms. Then we select all currently installed resources and their types and retrieve a distinct list of the realms for those types. 
There was also a few changes made to support Trevor's realm separation work ( Making it so that XDMoD doesn't need to have the Jobs realm installed to function properly. ). 
- All automated tests for: Fresh Install & Upgrade
- Manually tested on xdmod-dev
> Updated to add resource_types and resource_type_realms

- configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
- configuration/etl/etl_tables.d/common/hpcdb/system-accounts.json
- configuration/etl/etl_tables.d/jobs/xdw/system-account.json
- configuration/etl/etl_tables.d/storage/staging/usage.json
Cloud usernames can be whole email addresses, up the system username to be able to support this
> Increase size of system username column

- html/gui/js/modules/job_viewer/AnalyticChartPanel.js
The error messages in the job viewer chart analytics had two problems.
1) there was no word wrapping enabled so the text would be truncated if the browser
window was too small.
2) the text was not updated on a resize event. An example of the text display after a window
maximise is shown below.
This update fixes the word wrap and ensures that the text is re-rendered if the window is resized. 
I did a quick test for memory leaks by adding the following to the JobPanel.
```diff
diff --git a/share/html/gui/js/modules/job_viewer/JobViewer.js b/share/html/gui/js/modules/job_viewer/JobViewer.js
index bc8fcf6..2af7106 100644
--- a/share/html/gui/js/modules/job_viewer/JobViewer.js
+++ b/share/html/gui/js/modules/job_viewer/JobViewer.js
@@ -798,6 +798,12 @@ XDMoD.Module.JobViewer = …
```
> Fix display bugs in the error message for the job viewer analytics.

- html/gui/js/Portlet.js
- html/gui/js/modules/HelpTip.js
This PR has three updates for related to Help Tips.
1. Scroll target element into view. When showing a Help Tip the target element the tip is being shown next to may be outside the viewable area. To make sure the target is in the viewable area the help tip will look through all of the parent elements of the target element and find a parent element that is scrollable and then scroll the element into view. 
2. For Portlets, by default css selector are searched only within the portlet. Since a majority of portlet help tips will target elements within their portlet by default the ID of the portlet will be added to the target element. To search for an element globally, place a backslash ("/") at the beginning of the css selector you are using. 
3. Display help tips within viewable areas. …
> Updates to Help Tips

- docs/ingestor.md
Fixes formatting, grammar and accuracy.
There were formatting, grammar and accuracy issues with the documentation.
No tests.
> Improve xdmod-ingestor documentation

- classes/DataWarehouse/Export/BatchProcessor.php
- classes/DataWarehouse/Export/FileManager.php
- classes/DataWarehouse/Export/QueryHandler.php
Updates data warehouse export batch process to remove files corresponding to deleted requests.
Don't want files that should be deleted to stick around indefinitely.
> Remove data files for deleted export requests

- classes/OpenXdmod/Migration/Version812To850/ConfigFilesMigration.php
- configuration/portal_settings.ini
- tests/ui/test/specs/xdmod/about.js
- tests/ui/test/specs/xdmod/about.page.js
> update roadmap url

- html/gui/js/modules/dashboard/ReportThumbnailsComponent.js
- html/gui/js/modules/dashboard/SavedChartsReportsComponent.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
Fix bug: Chart Thumbnail open in metric explorer fails if existing chart has same name
Fix bug: Chart Thumbnail model chart missing loading mask
Fix bug: Refresh field in the search bar for saved charts and reports is cleared when refresh is clicked
Bug Fix
Manual test
> Bug fixes: Add mask and make chart name unique

- classes/Rest/Controllers/DashboardControllerProvider.php
- configuration/roles.d/dashboard.json
- docs/dashboard.md
The "summary_charts" configuration setting in the roles configuration is not used in the new dashboard.
The summary_0(X) nonsense is removed.
Remove some unused setting in the chart config and change the chart names to be more descriptive.
> Update dashboard chart display algorithm

- html/gui/js/CCR.js
The metric explorer uses a renderer to convert the internal ids to
the human readable values for many of the combo boxes. The lookup
function was incorrectly using the store.find() call which only
performs a substring match. In the observed case the defined metrics
were:
job_count_bad => 'Number of Inefficient Jobs'
job_count   => 'Number of Jobs'
so when the code looked up the text for the job_count metric
the find() function would match the job_count_bad string
and the wrong text would be displayed.
This bug has been in the system forever. Why have we not noticed
it before. Well the backend code sorts the data
so that the human readable strings appear in alphabetical order. So
for example the resource / resource_type group by ends up sorted in the
following order:
resource => 'Resource' …
> Fix metric explorer metric and dimension display bug.

- classes/Realm/Statistic.php
- tests/unit/lib/Realm/StatisticTest.php
If the unit name is not already included in the statistic name, include it at the end in parenthesis. This mirrors existing functionality in v8.5.
> Fix statistic name to include unit if not already in name

- bin/acl-config
- classes/DataWarehouse/Access/MetricExplorer.php
- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Data/ComplexDataset.php
- classes/DataWarehouse/Data/SimpleDataset.php
- classes/DataWarehouse/Data/SimpleTimeseriesDataset.php
- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/Query/TimeseriesQuery.php
- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
- classes/Models/Services/Acls.php
- classes/Realm/Realm.php
- classes/Realm/iRealm.php
- html/controllers/metric_explorer/get_dw_descripter.php
Standard error marker statistics have historically been used for generating error bars for statistics that average a set of data. These statistics are not shown in the metric catalog, but are hidden from the user and used behind the scenes. They were named by prefixing the statistic name with "sem_" (e.g., sem_avg_processors). Now that the statistics include the realm name (e.g., Jobs_avg_processors) we cannot simply prefix the name with "sem_" but need to insert it after the realm (e.g., Jobs_sem_avg_processors).
In addition, the `acl-config` script stored the realm name as lowercase in the database (e.g., "Jobs" was stored as "jobs"), however in `Acls::getDescriptorsForUser()` this would prevent us from properly constructing the names of the SEM statistics and they would not match …
> Improve handling of Standard Error Marker (sem) statistics

- html/gui/js/CCR.js
- html/gui/js/modules/Usage.js
- Fixed std-error checkbox being enabled vs. disabled for statistics.
- Fixed chart exception handling to work when the response does not contain
json. Uses the standard `presentFailure` function instead of a message box.
- Also updated the `presentFailure` function so that the wrapped message is
displayed on the next line.
Having a UI that works as expected is good.
Manual testing was performed on local docker instances.
> Fix Usage UI Regression

- classes/DataWarehouse.php
- html/controllers/metric_explorer/get_dw_descripter.php
This change prevents the information for a realm being shown in the Usage and Metric Explorer tabs. The reason for this change is that we do not want the JobEfficiency realm to be shown in the Usage and Metric Explorer tabs since it only exists for the purpose of the Job Efficiency dashboard.
There will be a pull request in the xdmod-supremm repo that sets the 'show_in_catalog' flag to false and a corresponding test that confirms that this works.
> Add ability to hide realm from the metric catalog

- classes/DataWarehouse/Data/SimpleDataset.php
- classes/DataWarehouse/Query/TimeseriesQuery.php
Fix `getAlias()` and `getLongNameColumnName()` calls found during @plessbd testing that @smgallo missed.
- `$stat->getAlias()` -> `$stat->getId()`
- `$groupby->getLongNameColumnName()` -> `sprintf('%s_name', $group_by->getId())`
> Fix stragglers for getAlias and getLongNameColumnName

- classes/DataWarehouse/Access/MetricExplorer.php
Statistic ids are now prefixed with the realm id. Ensure this is the case when working with statistic names that were not queried from XDMoD, such as test data.
> Ensure statistic ids are prefixed with realm id

- tests/ui/test/specs/xdmod/usageTab.js
- tests/ui/test/specs/xdmod/usageTab.page.js
Just adding a couple of tests to make sure that the `Display` -> `Std Err Bars` | `Std Err Labels` menu items are disabled / enabled when they are supposed to be.
UI working == good
Manual testing was performed on local docker instances for both upgrade && install
- [] Bug fix (non-breaking change which fixes an issue)
> Add Usage Explorer Tests

- classes/Realm/GroupBy.php
- classes/Realm/Realm.php
- classes/Realm/Statistic.php
- classes/Realm/iGroupBy.php
- tests/artifacts/xdmod/realm/datawarehouse.d/add-cloud-groupby.json
- tests/artifacts/xdmod/realm/datawarehouse.d/cloud.json
- tests/artifacts/xdmod/realm/datawarehouse.d/jobs.json
- tests/component/lib/Query/AggregateQueryTest.php
- tests/unit/lib/Realm/GroupByTest.php
- tests/unit/lib/Realm/RealmTest.php
Added support for the following:
- GroupBys now support customizing the chart display type used for a particular dataset:
```javascript
"dataset_type_to_chart_display_type_map": {
"aggregate": "bar",
"timeseries": "area"
}
```
- GroupBys now support an alternate group by column. This was needed for the GroupBy Username where we group by the username and not the system account id:
```javascript
"alternate_group_by_columns": [
"username"
]
```
- Made hierarchy constants available for substitution in statistics and group bys
> GroupBy Enhancements for Jobs Realm

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
- tests/ui/test/specs/xdmod/internalDashboard.js
- tests/ui/test/specs/xdmod/internalDashboard.page.js
- There was a problem when the user settings ( User Type, Map To, Institution
etc. ) were updated but the changes discarded. This was caused by these
elements not being reset to their original values. That function has been
added.
- Tests have also been added so that we can be sure this behavior doesn't crop
up again.
infinite loop bad
Manual Testing was performed along with the addition of automated tests to catch this problem in the future.
> Fixing an infinite loop when discarding user changes

- bin/acl-config
- classes/DataWarehouse/Access/Usage.php
- classes/DataWarehouse/Query/Query.php
- classes/DataWarehouse/Query/TimeAggregationUnit.php
- classes/Realm/Realm.php
- classes/Realm/iRealm.php
- classes/User/Elements/QueryDescripter.php
- html/controllers/metric_explorer/get_dw_descripter.php
Add `getRealmIds()`, `getStatisticIds()`, `getGroupByIds()` methods rather than calling `array_keys()` on the associative array of names.
> Add convenience function for getting realm/statistic/groupby ids

- classes/Realm/Realm.php
- tests/component/lib/Query/AggregateQueryTest.php
When using a non-standard configuration file location we always re-load the configuration class. Otherwise, tests that reference different locations or artifacts will fail depending on the order that they are run in.
> Force realm config load if using alternate config location

- bin/xdmod-update-resource-specs
The resource file name referenced in `xdmod-update-resource-specs` does not match the real file name.
The script references a `resource-specs.json` while the actual file name is `resource_specs.json` (underscore `_` vs. dash `-`).
Running the current script results in the following error
```
PHP Warning:  file_get_contents(/etc/xdmod/resource-specs.json): failed to open stream: No such file or directory in /usr/share/xdmod/classes/CCR/Json.php on line 26
2019-10-02 09:33:17 [critical] Failed to read file '/etc/xdmod/resource-specs.json' (stacktrace: #0 /usr/bin/xdmod-update-resource-specs(168): CCR\Json::loadFile('/etc/xdmod/reso...')
#1 /usr/bin/xdmod-update-resource-specs(18): main()
#2 {main})
```
With the change, the script doesn't fail and the resource file is updated correctly.
> xdmod-update-resource-specs: fix resources file name

- classes/Realm/GroupBy.php
- classes/Realm/Realm.php
- classes/Realm/iGroupBy.php
- configuration/datawarehouse.d/ref/group-by-none.json
- configuration/datawarehouse.d/ref/group-by-time-period.json
- tests/unit/lib/Realm/GroupByTest.php
Change `available_for_drilldown` in the group by configuration to `show_in_catalog` to be consistent with Realms and Statistics.
> Change GroupBy available_for_drilldown to show_in_catalog

- bin/acl-config
- html/gui/js/modules/metric_explorer/MetricExplorer.js
* add error message to acl log on failed section load
* surface errors when get_dw_descriptor fails to load in metric explorer. 
Eventually these errors should be more user friendly but this is a step in the right direction
> update error handling

- classes/Realm/GroupBy.php
- tests/artifacts/xdmod/realm/datawarehouse.d/jobs.json
- tests/component/lib/Query/AggregateQueryTest.php
- tests/unit/lib/Realm/GroupByTest.php
- tests/unit/lib/Realm/RealmTest.php
Some group bys (e.g., GroupByQueue) need the ability to specify more than a single join condition when applying the group by.
> Support additional join conditions for group bys

- html/gui/js/modules/job_viewer/SearchPanel.js
Fix bug in job viewer search dialog where the realm for the search was hardcoded to the dialog box setting for the advanced search dialog. This meant that basic search would fail to load correct data if the realm setting in the advanced search dialog was different from the basic search setting (when the search was originally run). Also the advanced search would also be wrong if you changed the realm value after running the search.
Tests for this scenario have been added to the xdmod-supremm module in PR: https://github.com/ubccr/xdmod-supremm/pull/196.
> Fix bug in job viewer save search when multiple realms available

- configuration/etl/etl_sql.d/cloud_openstack/unknown_domain.sql
- configuration/etl/etl_tables.d/cloud_common/domains.json
After merging the domain / submission venue PR & deploying this to our dev server, a couple of exceptions showed up in the  nightly logs. These changes are meant to address these exceptions. 
Specifically: 
- `unknown_domain.sql`: The `resource_id` returned by the insertion subquery ( 30 ) is different then the one for the record that already exists ( - 1 ). I've updated the insertion query to only insert if there does not already exist a record with an id of `1` ( which denotes our `unknown domain` ). 
- `domains.json`: Received an exception `General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) ` when the `unknown_domain.sql` was executed. To resolve this I've added an explicit `utf8` charset to the table definition.
Being able to run …
> Updating a few `domains` related files to address run time exceptions

- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
There was a problem when updating a user's Person which caused the Person's name
disappear after saving the change. This was caused by `resetUserSettings` &
`revertUserSettings` being called in reverse order.
> Fixing issue found by @plessbd in User Management

- bin/xdmod-ingestor
The `xdmod-ingestor` command runs `acl-config` as part of the processing. The return value of the command was not being checked so the follow on processing in the ingestor would still run even if `acl-config` failed. This has the potential to cause database corruption (of course the database is probably corrupt if acl-config fails, but this at least has a `--recover` flag).
> Propogate errors in acl-config subprocess run

- classes/OpenXdmod/DataWarehouseInitializer.php
- Added a `getEnabledRealms` function that operates solely off of config files
and not the db. This resolves some complexity / problems that arose with the
ETL processes during install / upgrade.
Simplify the upgrade / install ETL by not requiring some DB tables to be present @ shred / ingest time.
- Manual tests ( queries ) were performed to ensure that data was present where expected. 
- All automated tests were executed in both upgrade / install paths and passed.
> Update DWI's `isRealmEnabled` to be config file based

- classes/OpenXdmod/DataWarehouseInitializer.php
- configuration/etl/etl.d/staging.json
- configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
- configuration/etl/etl_sql.d/cloud_openstack/unknown_resource_type.sql
- tests/ci/validate.sh
- Revert the change to the primary key value for the 'UNK' resource
type. This is now the same value (0) as previous s/w versions.
- Ensure the 'UNK' resource is added to the various resource type tables
in the jobs_staging pipeline.
- Enuse that the 'UNK' rows are added on upgrade path too.
- Revert the addition of the ingest-resource-types pipeline when
shredding jobs. This was added in #1006 possibly as a work around for
the fact that the staging pipeline had not been modified appropriately.
- Add a test to make sure this does not happen again.
> Ensure resourcetypes table is correctly populated.

- classes/DataWarehouse/Export/QueryHandler.php
- configuration/portal_settings.ini
- templates/portal_settings.template
Changes `portal_settings.ini` and corresponding template to store data warehouse export retention configuration as a string.
The `\Xdmod\Template` class requires all configuration values to be strings.
No new tests.
> Store warehouse export retention value as string

- classes/OpenXdmod/DataWarehouseInitializer.php
The new configuration API has an odd feature where the default settings
have this behavior:
if the parsed data has a top level json array and there is one entry in the array then the
entry is returned, If there are multiple entries in the array then an
array is returned. This requires the developer to handle the one and
many cases separately.
This lead to a bug because the code assumed that the data was always being returned in 
an array. This change sets the configuration class parameter `force_array_return`
so that the resource information is always returned in an array data structure.
This API design seems bug prone since the defaults settings are almost always not what you want. See  issue for follow up:  https://app.asana.com/0/342819846538629/1146629814310601
> Fix configuration settings for configuration class.

- tests/integration/lib/Controllers/ControllerTest.php
- line 342: The code fragment `. "\n"` was meant to be *inside* the
`file_put_contents` parenthesis.
- Removed the unused function `arrayRecursiveDiff`
- Refactored duplicated code in `testListUsers` and `testEnumExistingUsers` into
a new function `compareUsers`.
- Added documentation to the `entryExists` function.
While fixing the bug that SonarCloud found I noticed it had flagged sections of code in the same file as being duplicates, and while refactoring the duplicate code out into a new function I found that the `arrayRecursiveDiff` function was no longer used. 
All automated tests for an upgrade / fresh_install
> Fixing a bug found by sonarcloud and general code cleanup

- classes/ETL/DataEndpoint/JsonFile.php
- configuration/etl/etl_schemas.d/cloud_openstack/event.schema.json
During testing we found that the schema validation for cloud events was not
actually validating anything due to a misconfiguration of the schema file.
Instead of failing it just ignored everything.
After updating the schema we also needed to ensure that type coercion was
enabled as the data files encode `2` as `"2"`.
If we want to validate things then the validation should work.
all automated tests.
> Updating cloud event schema and coercing types

- classes/DataWarehouse/Export/QueryHandler.php
- classes/Rest/Controllers/WarehouseExportControllerProvider.php
- tests/artifacts/xdmod/integration/rest/warehouse-export/input/create-request.json
- tests/artifacts/xdmod/integration/rest/warehouse-export/input/delete-request.json
Modifies data warehouse batch export request creation to check if a user already has a matching request in the submitted or available state to prevent duplicate requests.
https://app.asana.com/0/15230011293693/1146676887787305
Added test data set.  (Another test artifact was creating duplicates so those changed as well.)
> Prevent creation of duplicate export requests

- shippable.yml
on failures the logs sometimes get truncated this prioritizes the logs that get output so that we can hopefully get better logging.
> Make shippable failure logging better

- configuration/etl/etl_action_defs.d/cloud_openstack/event.json
- configuration/etl/etl_action_defs.d/cloud_openstack/staging_event.json
Adding a coalesce statement on the staging and event table so users that are not in the systemaccount table will not be dropped from ingestion and aggregation. This will help with ubccr/xdmod-xsede#161
Events with users that are not found in the systemaccount table are dropped from ingestion the jobs-cloud-extract-openstack.OpenStackCloudStagingEventIngestor action is run. This change makes sure those events are not dropped. This is mainly needed so that in for cloud resources in the XSEDE modules we can update events whose users are not yet in the XDCDB at a later date.
All automated tests run and pass
> Adding coalesce statement for users that are not found in system account table

- configuration/etl/etl.d/jobs_cloud_openstack.json
It seems that the truncate_destination directive for the openstack staging table was erroneously removed in #797. This adds it back in.
Ran automated tests in docker
> Add truncate_destination directive back to openstack staging event action that was erroneously removed

- bin/acl-config
Change `acl-config` error message to add additional details.
Specifies the command to run so you don't need to look it up and provides a URL so you don't need to search for it.
> Change ACL error message

- docs/faq.md
- docs/software-requirements.md
Update MySQL configuration suggestions.
Received at least one error that was solved by setting `innodb_stats_on_metadata = off`.  The notes about `max_allowed_packet` may also be outdated.
> Update MySQL configuration suggestions

- classes/XDUser.php
- html/controllers/metric_explorer/get_rawdata.php
- html/internal_dashboard/controllers/pseudo_login.php
- html/password_reset.php
- tests/integration/lib/Controllers/MetricExplorerTest.php
This pull request has several small updates to improve handling of untrusted user supplied data. Since these are all fixes for the same class of problem I have put them into the same pull request but kept the individual changes as separate commits.
1. Improve input validation for get_rawdata endpoint.
The get_rawdata metric explorer endpoint had some rather  obfuscuted code that checked for valid   data in the start and    limit variables. This code was difficult to understand and    it also triggered false positives in the code analysis software.
There was also a minor inconsistency if the start parameter    was missing from the request. The row data were returned    as if the start parameter was 0 but the totalAvailable metric    was not returned.
This update changes the code to use the …
> Improvements validation of untrusted input.

- classes/DataWarehouse/Query/Storage/GroupBy.php
- classes/DataWarehouse/Query/Storage/GroupBys/GroupByUsername.php
- classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
Fixes the storage realm `GroupByUsername` class.
This bug breaks the system username filter.
> Fix storage realm username GroupBy

- classes/ETL/DataEndpoint/Filter/ExternalProcess.php
The unit tests were not passing in my docker. The reason was because there is no guarantee that the process has exited by the time the `proc_get_status()` function is called. So the test would fail if the process was still in the running state when the status function was executed.
This change removes the `proc_get_status()` call and instead uses the return value from the proc_close which is guaranteed to give a yes/no answer.
> Fix race condition in test harness

- classes/ETL/DbModel/ForeignKeyConstraint.php
- classes/ETL/DbModel/Table.php
- configuration/etl/etl_tables.d/acls/report_template_acls.json
- tests/artifacts/xdmod/etlv2/dbmodel/output/alter_table-charset.sql
- tests/artifacts/xdmod/etlv2/dbmodel/output/alter_table_manually-charset.sql
- tests/ci/validate.sh
- tests/unit/lib/ETL/DbModel/DbModelTest.php
Also fix the ETLv2 code to correctly handle modifications to foreign
keys.
> Fix foreign key constraint on moddb report_template_acls

- classes/ReportTemplates/ParameterizedReportTemplate.php
- classes/ReportTemplates/VariableReportTemplate.php
This report template supports variable substitution for any
users acl parameters. The parameter IDs and names are available.
This template will be used in the XSEDE 8.6 release, but belongs in the code since it does not contain any XSEDE-specific  stuff.
See the corresponding XSEDE pull request for example of how it is used.
> Add report template that supports variable substitution.

- classes/XDReportManager.php
The pull request #967 added extra code to the report manager that
manipulated the start and end times of charts in a report. This broke
the report generator. These changes appear to not be necessary at all
and must have been added by mistake.
> Revert XDReportManager changes from #967

- classes/Rest/Controllers/DashboardControllerProvider.php
The getRoleReport() decoding was manging the chart data. This is seen
for charts that have either & or = in the config.
For example:
global_filters=%7B%22data%22%3A%5B%7B%22id%22%3A%22institution%3D400%22%2C%22value_id%22%3A%22400%22%2C%22dimension_id%22%3A%22institution%22%2C%22checked%22%3Atrue%7D%5D%2C%22total%22%3A1%7D
> Character encoding is not commutative.

- html/gui/js/HighChartPanel.js
- html/index.php
- libraries/charting.php
Fix issue with the chart tooltip displaying the wrong date when
the system timezone is a negative offset from UTC. That is countries
located east of the prime meridian.
See https://help.xdmod.org/a/tickets/14165
> Fix chart time display when the system timezone has a positive offset from UTC

- classes/XDUser.php
Change the text of the organization affiliation change user notification email, the contact email address used in the message, and the reply-to address.
I'm not sure what is the best contact email to use in this email, but it's definitely not the "sender" email, which in our case is a "do-not-reply" email address.  I think the contact page email makes sense, but there is also an argument for using the technical support email address.  We use the same email address for both so it doesn't make any difference to us.
I've also removed a blank line, and replaced "@" with "at" since using "@" is an unnecessary abbreviation.
No tests.
> Update organization affiliation change email

- classes/XDUser.php
The previous email text did not say what had actually changed, what
steps had been taken nor what (if anything) the poor user was supposed
to do about this.
This text conjures up the image of some sort of Orwellian bureaucracy
where sinister faceless operatives were updating your records behind the
scenes and you are allowed to know that the record had been modified
but are not permitted to see it or be told what actually changed.
This code path is tested in the ci tests. The resultant email is included below for reference. In this test Reed Bunting changes from Screwdriver to "Organization 2".
```
From ccr-xdmod-help@buffalo.edu  Tue Dec 10 19:06:59 2019
Return-Path: <ccr-xdmod-help@buffalo.edu>
X-Original-To: centerdirector@example.com
Delivered-To: root@03ac3e5e60b3.localdomain
Date: …
```
> Update email notification text to be less mysterious.

- html/controllers/user_admin/empty_report_image_cache.php
The internal dashboards 'Empty Report Image Cache' only clears the
database contents. The code that retrieves the images checks the
filesystem before the database, so if the file is already on the
filesystem it will served and the database cache will never be
consulted.
This update adds a call to the existing XDReportManager function that cleans up
all report image files.
> Clear report cache operation will remove image files too.

- classes/DataWarehouse/Query/Cloud/GroupBys/GroupByDomain.php
- classes/DataWarehouse/Query/Cloud/GroupBys/GroupByServiceProvider.php
If a group by does not have an addWhereJoin function it will fail when looking at a timeseries chart and paging is disabled for the chart. 
> adding addWhereJoin to domain and service provider cloud group bys

- html/gui/js/modules/dashboard/ReportThumbnailsComponent.js
This mitigates the UI lockup when trying to click on a Usage chart from
a report thumbnail (asana issue
https://app.asana.com/0/159049597309611/1153563882786297)
A complete fix will be to actually support all types of charts that can
be shown (Usage, Custom Queries, App Kernel . etc. ). But this at least
ensures that the UI does not lockup.
> Only try to load metric explorer charts.

- classes/Rest/Controllers/DashboardControllerProvider.php
This addresses asana issue https://app.asana.com/0/159049597309611/1153459826874569
Note that I checked the various other chart parameters and the timeseries parameter is the only one that appears to cause breakage. 
The parameters "show_guide_lines" and "showContextMenu" still appear as y/n values. However these are not actually used anywhere.
> Fix decoding of report chart settings in the dashboard controller.

- classes/XDUser.php
When this function is used in an XSEDE installation it's not just CS/CD that need to use this
function. Per a convo w/ @jpwhite4, this function does not need to be filtered. There will be an
accompanying PR in the AppKernels repo (https://github.com/ubccr/xdmod-appkernels/pull/74).
To allow PO's to utilize the Center Report Card Dashboard component
Open XDMoD: all automated fresh install / upgrade 
- [] New feature (non-breaking change which adds functionality)
> Removing cs,cd restrictions on getResources

- html/gui/js/modules/dashboard/JobComponent.js
This fixes a regression introduced in f4628aebdd5a8427f34dc41a03980d65dcc42ad5
The correct code uses a page size of 10 for single user view.
> Fix page size in JobComponent single user view.

- configuration/linker.php
- docs/support.md
We often get error log reports with messages like the following:
```
PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/xdmod/share/html/index.php:180) in /opt/xdmod/share/configuration/linker.php on line 179
```
These are of course completely useless and are caused by the error
handler trying to set the headers and failing. The issue is that the
orignal message that the error handler is supposed to output does not
make it to the logs.
This change ensures that the exception handler only tries to set headers
if they have not already been sent and updates the documentation to
encourage folk to look in the xdmod exceptions log.
I manually tested this by adding a `throw new Exception` in index.php and loading the page.
> Don't bother trying to set headers if not possible.

- html/gui/js/modules/Usage.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
The "Err Bars" and "Err Labels" columns in the "Data" menu in the metric
explorer were incorrectly shown or incorrectly not shown in certian
circumstances.
a) if a chart was 'geared over' from the Usage Tab then the "Data" menu would
always show the "Err Bars" and "Err Labels" checkboxes regardless of whether
they should have been shown.
b) if data were added to the metric explorer from the "Metric Catalog" then
the "Data" menu would never show the checkboxes regardless of whether they
should have been shown.
If data are added to a chart via the "Data Series Definition" dialog then the
checkboxes are correct.
This change fixes it so the checkboxes work correctly.
**Old:**
**New:**
**Old:**
**New:**
> Fix stderr checkbox disablement in Metric Explorer.

- classes/Configuration/Configuration.php
- classes/ETL/DataEndpoint/JsonConfigFile.php
- classes/ETL/DataEndpoint/JsonFile.php
- classes/OpenXdmod/Shredder.php
- tests/artifacts/xdmod/configuration/input/to_assoc_array.json
- tests/artifacts/xdmod/configuration/output/single_resource.json
- tests/artifacts/xdmod/configuration/output/single_resource_force_array_return.json
The `XDMoDConfiguration` class has problems parsing some of the xdmod configuration files. There have been a couple of attempts to workaround the problem notably f989888b0 and 7c497ac4c
but both of these did not fix the underlying design problem. 
The underlying problem is that the `JsonFile.php` parser is designed to be used
to parse structured record-based json data. It includes support for parsing hybid json-like files
that contain multiple json blobs and it has code that validates the files based on a very
limited set of allowable content structure. The XDMoD configuration files are not record-based
json, they do not contain multiple json blobs and they do not conform to the content structure
that the JsonFile class is designed to handle.
My proposed solution is to stop using the …
> Proposed Fix for the underlying json config parsing problems

- classes/DataWarehouse/Access/RawData.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- html/index.php
Previously, even though the raw data was protected by ACLs the list of
realms was not. So a user could see all realms that supported raw data
access (even if they did not have permission to see the realm itself).
This scenario is not seen in the default open xdmod installs since all
uses have access to jobs and supremm realms. This is seen in the XSEDE
version where different roles have different realm access.
Also add the capabilty to disable a realm from raw data access via the
config file.
> Enforce realm acls for show raw data endpoints.

- html/gui/js/modules/Usage.js
- tests/integration/lib/Controllers/UsageExplorerTest.php
As far as I can tell this was used in `Visualization/Chart.php`
to determine whether to add an image `menu_dropdown.png`. This presumably had
an event on it in the javascript, but I couldn't find it, not could I find the png
file. This all predates Highcharts.
Below is a snippet of the original code. Note that the chart setting `interactive_elements` is used to initialise the class member variable `_interative_elements`
```php
public function addTitle(\BaseChart &$base_chart_object, $include_title_map = false, &$dataset = NULL)
{
if($this->getShowTitle() && !isset($this->hasTitle))
{
$title = explode(' by ', $this->getTitle());
$titleText = '';
if($this->_interactive_elements===true && $this->getTitle() != "Empty Dataset")
{
if(isset($title[0])) $titleText = …
```
> Remove write-only chart parameter.

- composer.json
- composer.lock
when trying to access the old http address:
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
> Maven changed their download url

- classes/Rest/Controllers/WarehouseControllerProvider.php
- html/gui/js/modules/job_viewer/JobViewer.js
- html/gui/js/modules/job_viewer/SearchHistoryTree.js
The search history in the job viewer always displayed all possible
realms that could have search history regardless of whether there were
any saved searches. This was reported as a bug by a user. The realm
nodes in the tree would have a triangle mark indicating that the could
be unfolded, but when the unfold was clicked then it would dissaper.
old:
new:
This change makes it so that the search history only shows the realm
folder nodes for realms that have search history. If there a no saved
searches then an assist panel is shown.
There is a corresponding pull request in the supremm module that updates the UI tests to confirm the new code works.
> Improve search history panel UI.

- classes/Rest/Controllers/DashboardControllerProvider.php
- classes/XDReportManager.php
This pull request cherry-picks the commits from three bug fixes that went into the XSEDE 8.6 release.
These are:
#1190 
#1178 
#1177
> Cherry Pick important bugfixes from 8.6

- html/gui/general/login.php
Replaces #1198 
detect if login is within an iframe and do not redirect to the portal, instead send a `postMessage` to `window.top`
Use the following in window.top to recieve message and react accordingly
```javascript
window.addEventListener("message", receiveMessage, false);
function receiveMessage(event) {
if (event.origin !== "{FQDN OF XDMOD INSTANCE WITH PROTOCOL AND PORT IF NEEDED}"){
console.log('Received message from untrusted origin, discarding');
return;
}
if(event.data.application == 'xdmod'){
if(event.data.message == 'loginComplete'){
console.log('XDMoD has logged in successfully');
}
if(event.data.message == 'error'){
console.log('ERROR: ' + event.data.info);
}
}
}
```
> Use `postMessage` to alert `window.top`on framed login

- docs/configuration.md
- docs/integrations.md
- docs/simpleSAMLphp.md
documentation updates for CORS and SSO embedding
> Documentation Updates

- classes/ETL/State/StateManager.php
This was found by the sonar cloud analysis
> Fix typo in ETL StateManager exception handler

- html/gui/js/modules/job_viewer/JobViewer.js
If the data to be displayed has units of bytes then a negative value
means that the information is unavailable. This change updates the
formatter to correctly display this.
old:
new:
https://app.asana.com/0/342819846538629/1137562460528392
> Update job viewer formatter to handle N/A case for byte data.

- html/gui/css/viewer.css
There is no such css attribute as valign. Found by sonar cloud analysis
> Fix syntax error in viewer.css

- tests/integration/lib/TestHarness/XdmodTestHelper.php
The disable ssl checks used to be necessary when we used self-signed
certs on the dev machine. No longer needed.
> Removed unused curl settings in test helper.

- html/gui/js/CCR.js
When clicking the login button focus on the username field when the form activates.
Verified that this works with and without SSO enabled.
This should have been part of #1115
> Focus on the Username field when the Login Button is clicked

- background_scripts/report_schedule_manager.php
The report schedule text in the database for annual reports is "Annually"
and for biannual reports "Semi-annually". The report generator had the
wrong words.
> Fix report generation for annual and biannual reports.

- classes/Configuration/Configuration.php
- classes/ETL/Configuration/EtlConfiguration.php
Ensure function prototype is correct for cleanup() function.
Ensure member variables are declared before they are used.
These errors showed up when I was running the unit tests on my ubuntu
box (php 7.2.24). It seems that earlier versions of php let you get away
with it but not in later versions.
> Fix bugs in Configuration classes.

- classes/ETL/Configuration/EtlConfiguration.php
As far as I can tell there is no way in the current code to get into
this if statement. However, I suppose this protects the code against
misuse by a class that inherits from this one.
> Fix typo in EtlConfiguration

- classes/DataWarehouse/Export/BatchProcessor.php
- classes/DataWarehouse/Export/FileManager.php
- classes/DataWarehouse/Export/FileWriter/FileWriterFactory.php
- classes/DataWarehouse/Export/QueryHandler.php
- classes/Rest/Controllers/WarehouseExportControllerProvider.php
- tests/artifacts/xdmod/schema/warehouse-export/GET-requests.schema.json
- tests/component/lib/Export/ExportDBTest.php
Adds additional logging and improves existing logging to add more details.
The logged information is necessary to provide details on the use of the data warehouse export features.
https://app.asana.com/0/15230011293693/1146676887787307
No tests
> Improve data warehouse export logging

- bin/acl-config
- bin/xdmod-ingestor
- classes/OpenXdmod/Setup/DatabaseSetup.php
- configuration/etl/etl.d/acls-import.json
- configuration/etl/etl.d/acls-xdmod-management.json
- configuration/etl/etl_tables.d/acls/group_bys.json
- configuration/etl/etl_tables.d/acls/realms.json
- configuration/etl/etl_tables.d/acls/staging/acl_group_bys.json
- configuration/etl/etl_tables.d/acls/staging/acl_hierarchies.json
- configuration/etl/etl_tables.d/acls/staging/acl_tabs.json
- configuration/etl/etl_tables.d/acls/staging/acl_types.json
- configuration/etl/etl_tables.d/acls/staging/acls.json
- configuration/etl/etl_tables.d/acls/staging/group_bys.json
- configuration/etl/etl_tables.d/acls/staging/hierarchies.json
- configuration/etl/etl_tables.d/acls/staging/modules.json
- configuration/etl/etl_tables.d/acls/staging/realms.json
- configuration/etl/etl_tables.d/acls/staging/statistics.json
- configuration/etl/etl_tables.d/acls/staging/tabs.json
- configuration/etl/etl_tables.d/acls/staging/user_acl_group_by_parameters.json
- configuration/etl/etl_tables.d/acls/staging/user_acls.json
- configuration/etl/etl_tables.d/acls/statistics.json
- configuration/etl/etl_tables.d/acls/user_acls.json
- `acl-config`:
- Added Lock File protection to protect against multiple copies of `acl-config` running simultaneously 
- Added a signal handler that should ensure the lock file is unlocked when `acl-config` is ctrl-c'd etc. 
- We no longer need to run `acls-xdmod-management` multiple times within `acl-config`, we now run 
it once after the backup tables are handled.
- We've refactored the way that `acl-config` works, previously we wholesale Truncated / re- 
populated the "managed" tables ( any table that we can completely recreate from available 
configuration files ) and then re-populated the "non-managed" tables i.e. `user_acls` and 
`user_acl_group_by_parameters`. This method did not allow us to utilize db transactions as both 
`TRUNCATE` and DDL ( drop / create / update table ) force …
> Cleanup / make acl-config more resilient

- bin/xdmod-ingestor
Make sure the realm specified for aggregation matches a supported realm.
Adds error checking for values specified to the `--aggregate=` option of the `xdmod-ingestor` script.
It's too easy to misspell a realm name and no useful feedback is given when this happens.
https://ubccr.freshdesk.com/a/tickets/22838
No new tests.
> Improve ingestor option error checking

- configuration/etl/etl_action_defs.d/cloud_generic/instance.json
This fixes the following error seen in the metrics-dev logs.
```
2020-02-12 04:19:05 [warning] SQL warnings on table '`modw_cloud`.`instance`' generated by action xdmod.jobs-cloud-extract-generic.GenericCloudInstanceIngestor
2020-02-12 04:19:05 [warning] Warning 1052 Column 'service_provider' in group statement is ambiguous
```
Ran in docker and manually tested
> Adding table name to remove ambiguity from group by statement

- configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
Removes a file from a definition file list in an ETL migration configuration.
Including aggregate table definitions doesn't work properly with the `ETL\Maintenance\ManageTables` class.  There is no way to specify the aggregation units resulting in incorrect table names.
The first problem is this warning:
```
2020-02-20 17:52:36 [warning] ETL\DbModel\Table: Attempt to set unsupported property: 'table_prefix'
```
The ETL system then creates the table without the aggregate unit suffix:
```
2020-02-20 17:52:38 [notice] Table `modw_cloud`.`cloudfact_by_` does not exist, creating.
```
Manually inspected output from the upgrade script and checked the database to see the `cloudfact_by_` table was not created.
> Remove `cloudfact_by_.json` from migration definition file list

- classes/ETL/DbModel/ForeignKeyConstraint.php
- classes/ETL/DbModel/Index.php
- tests/unit/lib/ETL/DbModel/DbModelTest.php
Adds additional error checking to the initialize functions of the index and foreign key constraint database models.
The `initialize` functions use the `columns` from the configuration when a `name` is not specified.  The `columns` are required local properties of the entities, but their existence is not verified until the parent `initialize` function is called.  This function must be called last in the child `initialize` because the parent `initialize` uses the `name` configuration to set the entities `name`.
Without this change any missing columns produce an `Undefined property: stdClass::$columns` error which cannot be caught and logged.
Added new tests.
> Add additional ETL DB Model error checking

- classes/DataWarehouse/Query/Jobs/GroupBys/GroupByUsername.php
- tests/regression/lib/Controllers/MetricExplorerChartsTest.php
- tests/regression/runtests.sh
Also added a regression test to check that the remainder calculation is
performed correctly.
The System Username group by in the Jobs realm used an incorrect column name when building the where conditions that are used in the remainder calculation in the metric explorer. This means that the "Avg of N others" calculation was actually the "Avg of all values". This fixes the query and adds a test to confirm the correct value. I've also added a couple of tests for the other types of remainder calculation.
> Fix show remainder calculation for Jobs by System Username.

- classes/DataWarehouse/Access/ReportGenerator.php
- html/controllers/report_builder/download_report.php
- html/controllers/report_builder/save_report.php
- html/controllers/report_builder/send_report.php
- html/report_image_renderer.php
- tests/unit/lib/DataWarehouse/Access/ReportGeneratorTest.php
This pull request adds input validation filters to the user-supplied
untrusted data provided to the report generator controller endpoints.
The modifications do not change any of the data serialization or api of
the endpoints.
The user-supplied report text (title, header, footer etc.) is modified
to filter out data that does not have a valid character encoding. This
mitigates a bug in the report generator if you tried to create a report
with a filename containing an invalid character such as 😊 then the UI would
show an error message:
```
There was a problem creating / updating this report.
(SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like')
```
the new behaviour is that the report will save ok …
> Add input validation to report generator controller endpoints.

- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
- tests/regression/lib/Controllers/MetricExplorerChartsTest.php
If you have multiple datasets in the metric explorer and tick 'show
remainder' then the remainder calculation is incorrect for all but the
dataset with the largest series count. This is because the maximum
number of series per dataset is used to compute the remainder rather
than the number of series for each dataset.
Also added a test to confirm the correct behaviour.
> Fix multi-timeseries dataset-show-remainder bug.

- composer.json
- composer.lock
add chromelogger as a dev dependency
allows you to do things like the following when debugging and view the output in the developer tools of the browser:
```php
ChromePhp::log('Hello console!');
ChromePhp::log($_SERVER);
ChromePhp::warn('something went wrong!');
```
see https://craig.is/writing/chrome-logger
for firefox extension: https://addons.mozilla.org/en-US/firefox/addon/chromelogger/
> Make development easier...at least for ben

- tests/artifacts/xdmod/regression/chartFilterTests.json
- tests/regression/lib/Controllers/MetricExplorerChartsTest.php
- tests/regression/lib/TestHarness/Utilities.php
These tests confirm that the chart filters filter the data correctly
and have the correct chart subtitles. All filters available for each
realm are tested with a single metric and group by none.
This also includes the machinery to generate expected test results.
The test for Cloud Filter by instance type is absent. This is because
this filter does not work. Once the instance type filtering is fixed
then a test should be added.
> Added regression tests for chart filters.

- bin/xdmod-build-filter-lists
- classes/DB/FilterListBuilder.php
found a few bugs in the filterlistbuilder...
> Fix some bugs in FilterListBuilder

- configuration/etl/etl_tables.d/cloud_openstack/domain_submission_venue.json
Removes foreign key constraints from the ETL table definition for `modw_cloud`.`domain_submission_venues`.
MyISAM tables do not support foreign key constraints.  This results in the ETL system attempting to alter the table every time data is ingested:
```
2020-02-18 13:01:40 [debug] Discover table 'modw_cloud.domain_submission_venues'
2020-02-18 13:01:40 [notice] Altering table `modw_cloud`.`domain_submission_venues`
2020-02-18 13:01:40 [debug] Alter table SQL ('Cloud DB', class=ETL\DataEndpoint\Mysql, config=datawarehouse, schema=modw_cloud, host=localhost:3306, user=xdmod):
ALTER TABLE `modw_cloud`.`domain_submission_venues`
ADD CONSTRAINT `fk_dsv_domain_id` FOREIGN KEY (`domain_id`) REFERENCES `domains` (`id`) ON DELETE CASCADE,
ADD CONSTRAINT `fk_dsv_submission_venue_id` FOREIGN KEY …
```
> Remove foreign key constraints from MyISAM table

- classes/ETL/DbModel/ForeignKeyConstraint.php
- classes/ETL/DbModel/Table.php
- tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/alter-table.json
- tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/create-table.json
- tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/verification-failure.json
- tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/verification.json
- tests/unit/lib/ETL/DbModel/DbModelTest.php
- tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
Add support for foreign key constraints that reference a schema that is different from the one that they belong to.  Also refactor some tests.
It's possible for a foreign key constraint to reference a table in a different schema so the database model should support that.
See https://app.asana.com/0/15230011293693/1163079712082841
Added new tests.
> Add referenced schema to foreign key constraints

- tests/integration/lib/BaseTest.php
- tests/integration/runtests.sh
- tests/regression/runtests.sh
The integration and regression tests should not get their
test parameters from the system that they are testing. If the
system to test is broken then the test may erroneously pass.
For this pull request: the old code was querying XDMoD
to find out what realms existed and then only testing the realms
that XDMoD reported as present. **This is not the way it should be done.**
What should actually happen is that the developer sets up XDMoD
with the desired set of realms and then the tests check that
the desired set of realms are actually present.
> Improve robustness of integration and regression tests.

- configuration/etl/etl_schemas.d/cloud_openstack/event.schema.json
Update the json schema for openstack events to allow null for the user_name field. This allows events whose user_name field has a null value to be ingested. Any event with a user_name of null will be assigned to the unknown value when aggregated.
> Update openstack json event schema definition 

- classes/ETL/DbModel/Table.php
- tests/unit/lib/ETL/DbModel/TableTest.php
Allow the table schema to be set in the constructor or after instantiation as long as it is the same each time.
The table schema may be set in the `table_definition` or the destination endpoint or not at all.  This change allows the schema to be specified in both places as long as it is the same in both places.  Changes in #1257 broke this behavior.
Added new tests.
> Adjust ETL database model table schema assignment

- classes/Rest/Controllers/WarehouseControllerProvider.php
- html/gui/js/modules/job_viewer/SearchPanel.js
- tests/integration/lib/Rest/JobViewerTest.php
Original Bug Report:
https://app.asana.com/0/342819846538629/828830620362347
When entering a Search Title that contains html encodable values ( <, >,
& etc ), saving and then editing the search causes the encoded title to
be editable, not the decoded title.
Example:
- Search Title: Pwned!<script>alert(1)</script>
- When viewed this displays correctly as text. But if you 'edit' the
search you will instead see
the value below.
- Encoded: `Pwned!&lt;script&gt;alert(1)&lt;/script&gt;`
- This is what you see when editing the search.
- If you save the search after editing it then it will then become:
- Pwned!&amp;lt;script&amp;&lt/script&amp;&gt;
Description:
the .text element contains html content. but you have to put normal
text in the form field.
--
the actual fix for the problem is the one …
> Fix html decoding in Job Viewer -> Edit Search

- classes/ETL/Utilities.php
- classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
Sets `analyze_table` in the ETL configuration options to false to prevent tables from being analyzed or optimized during the re-aggregation of jobs data for the 9.0 migration.
Analyzing and optimizing tables is slow and could cause a time out with the database.
> Don't analyze tables during jobs aggregation for GPU data migration

- classes/DataWarehouse/Access/Usage.php
This removes code that is no longer necessary since PR #1263 was merged. The code is no longer needed since the project filter in the cloud realm uses the project name instead of the id now.
> Removing code path for cloud project filter that is no longer necessary

- classes/ETL/JsonPointer.php
When parsing an invalid json it is supposed to throw an error (according to documentation and code calling the function expecting it)
> Throw Expected exception when JSON is invalid

- classes/Rest/Controllers/WarehouseControllerProvider.php
The job viewer rest api has an unusual code path to get the list of jobs
for a given saved search. There is a 302 redirect when the interface
gets the list of jobs. There is no 302 redirect for any of the other
equivalent queries (such as list of information for a job). All of the
required information to respond to the request is in the original request.
This pull request removes the redirect. The path that wasa being
redirected to still remains so as to not break compatibility with any
external systems (they both call the same underlying function).
This was observed while testing #1268
> Remove unnecessary redirect in the job viewer rest stack.

- etl/js/lib/etl_profile.js
The join field should be set to the table name not the column
name. The tests associated with this fix are in
https://github.com/ubccr/xdmod-supremm/pull/224
> Fix typo in etl groupby generation code.

- bin/xdmod-upgrade
- classes/OpenXdmod/Migration/Version851To900/ConfigFilesMigration.php
added updating version variable in modules portal setting upon upgrade.
In appkernels version variable doesn't do much but it will be nice to have matching config version and software.
The big question is should it really be in core xdmod or in xdmod-appkernel. This would largely depends on how user is going to upgrade their system. In xdmod-upgrade, we did mentioned update supremm/appkernel tools first and then run xdmod-upgrade. Under this scenario it should work.
Since there are no other changes in appkernels.ini besides version and I don't anticipate any change in near future, just version update should be fine for a while.
> added updating version in appkernels.ini upon upgrade

- configuration/etl/etl_tables.d/jobs/hpcdb/jobs.json
- configuration/etl/etl_tables.d/jobs/shredder/job.json
- configuration/etl/etl_tables.d/jobs/staging/job.json
- configuration/etl/etl_tables.d/jobs/xdw/job-tasks.json
Change definition of columns that contain GPU counts so they are `NOT NULL` and default to `0`.
It was previously possible to have `NULL` values which produces warning messages:
```
2020-03-31 04:22:32 [warning] SQL warnings on table 'job_tasks' generated by action xdmod.hpcdb-xdw-ingest-jobs.job-records-job-tasks (filtering codes: 1062)
2020-03-31 04:22:32 [warning] Warning	1263	Column set to default value; NULL supplied to NOT NULL column 'gpu_count' at row 2
```
No new tests.
> Default GPU count to zero

- html/gui/js/modules/Usage.js
When there is an error in get_menus it can get 'lost' behind a 'Loading...' this will surface the error so that an admin can fix the configuration files.
> Surface Error instead of sitting on "Loading..."

- html/gui/js/report_builder/ReportCreator.js
- tests/ui/test/specs/xdmod/reportGenerator.js
- tests/ui/test/specs/xdmod/reportGenerator.page.js
Rename report generator "File Name" to "Report Name".
https://app.asana.com/0/15230011293693/62691924780819
> Rename report file name input field

- classes/DataWarehouse/Data/RawDataset.php
XDMoD filters data for accounts with the DEMO type (to facilitate
demonstrations without revealing potentially sensitive info).
This error is seen when using a demo user account to try to view a
job in the job viewer.
> Fix bug viewing raw data as demo user.

- configuration/assets.json
- html/.eslintrc.json
- html/gui/js/modules/dashboard/JobComponent.js
- html/gui/js/modules/job_viewer/JobGrid.js
This job grid is to be used by the job efficiency component as well as the
JobComponent so it makes sense to move the code into its own class.
This change does not alter the behaviour of the JobComponent but there are a couple of changes:
1) The refresh function is now triggered by an event.
2) The jobgrid has the capability of doing drilldown for a different realm than the original query realm.
> Move the job grid into its own class.

- html/gui/js/HighChartWrapper.js
The code tries to shade the legend background when the data in the chart
are restricted by roles. This happens e.g. when you have user role and
try to plot some supremm data. Pie charts do not have legends so the
series.legendItem property is absent. This change makes sure the legend
background colour is only changed if there is a legend to change.
> Fix bug in highchart wrapper code.

- classes/DataWarehouse/Query/Query.php
Since I dont exactly remember what errors this was hiding, I am specifically only catching that the realm does not exist so that the metric explorer will still allow multiple realms to be shown while only filtering the one that has the groupby
> "Revert" #1247

- configuration/datawarehouse.d/ref/Cloud-statistics.json
Seems that this is used when there is more than one dataset on the plot, this makes it what it was before the groupby refactor
> Update 'unit' for cloud realm stats to be what it was

- configuration/datawarehouse.d/ref/Cloud-group-bys.json
This adds alternate_group_by_columns to the Project and Instance Type group bys. One place the column in `alternate_group_by_column`, when present, is used is in the group by WHERE clause to filter results. If alternate_group_by_column is not specified the column(s) in `attribute_to_aggregate_table_key_map` are used instead. For the Project and Instance Type group by's the correct column for WHERE clause is the `display` column not the `instance_type_id` specified in `attribute_to_aggregate_table_key_map`. 
An example of the difference in the sql when alternate_group_by_column is used is shown in the Instance Type group by sql below.
Query before change: 
```sql
SELECT
duration.id as 'day_id',
DATE(duration.day_start) as 'day_short_name',
DATE(duration.day_start) as 'day_name', …
```
> Add alternate_group_by_column field to Project and Instance Type group by

- classes/DataWarehouse/Data/TimeseriesDataset.php
- tests/regression/lib/Controllers/MetricExplorerChartsTest.php
Fix regression bug introduced in timeseries plot optimizations.
Steps to reproduce:
Use the metric explorer to plot multiple datasets with different number of series in each.
Switch on paging and page past the max series in one of the datasets.
A test has been added to prove the fix.
> Fix regression bug when paging datasets.

- classes/DataWarehouse/Access/MetricExplorer.php
- classes/DataWarehouse/Visualization/HighChart2.php
- classes/DataWarehouse/Visualization/HighChartTimeseries2.php
- classes/ETL/DbModel/Query.php
- classes/Models/Services/Acls.php
- classes/Models/Services/Realms.php
- classes/Realm/GroupBy.php
- classes/User/Elements/QueryDescripter.php
- configuration/datawarehouse.d/ref/Cloud-group-bys.json
- configuration/datawarehouse.d/ref/Jobs-group-bys.json
- configuration/datawarehouse.d/ref/Storage-group-bys.json
- configuration/datawarehouse.d/ref/group-by-common.json
- configuration/datawarehouse.d/ref/group-by-hierarchy.json
- configuration/datawarehouse.d/ref/group-by-none.json
- configuration/datawarehouse.d/ref/group-by-time-period.json
- etl/js/lib/etl_profile.js
- html/controllers/metric_explorer/get_dw_descripter.php
- html/controllers/user_interface/get_menus.php
- tests/artifacts/xdmod/realm/datawarehouse.d/add-alternate-class.json
- tests/artifacts/xdmod/realm/datawarehouse.d/add-cloud-groupby.json
- tests/artifacts/xdmod/realm/datawarehouse.d/cloud.json
- tests/artifacts/xdmod/realm/datawarehouse.d/jobs.json
- tests/component/lib/Query/AggregateQueryTest.php
The XSEDE GroupBys need to be able to use a secondary table to link to aggregates (through the account table to the grant table) this update allows that, while getting rid of the need for the attribute_table key as it is provided by the first (and usually only) join table in the attributes value query.
> updates needed for xsede groupbys

- html/gui/js/report_builder/ReportCreator.js
- tests/ui/test/specs/xdmod/reportGenerator.js
After saving a report using "Save As" the report that is currently being edited is switched to the newly created report.
https://app.asana.com/0/15230011293693/62691924780821
Updated automated tests.  Tested manually.
> Switch to new report after "Save As"

- classes/DataWarehouse/Export/FileManager.php
- tests/artifacts/xdmod/component/export/file_manager/input/export-requests.json
- tests/component/lib/Export/FileManagerTest.php
Adds a `README.txt` file to the data warehouse export zip file that contains a description of all the exported fields.
~~**NOTE: This depends on and includes all the commits from  #1298 as of now**~~
https://app.asana.com/0/15230011293693/1146676887787308
Updated automated tests.  Tested manually.
> Add README to data warehouse export zip files

- classes/ETL/Aggregator/pdoAggregator.php
The etl logs aggregation finish at notice and start at info, this makes them both notice, also adds the action name for easier parsing at a later time.
> make logging betters

- bin/xdmod-shredder
- docs/resource-manager-lsf.md
- docs/resource-manager-pbs.md
- docs/resource-manager-sge.md
- docs/resource-manager-slurm.md
- docs/shredder.md
Update shredder documentation.  Specifically, improve the documentation regarding shredding all the files in a directory.
This documentation has been inaccurate for many years.
> Update shredder documentation

- background_scripts/etl_aggregation_table_manager.php
- tools/etl/etl_action_state_mgr.php
- tools/etl/etl_overseer.php
- tools/etl/etl_table_manager.php
Replaces the `DWI` identification strings with more specific names.
The ident `DWI` has a specific meaning in the XSEDE ETL processes.  It is used to identify the `dw_extract_transform_load` process.  There is a script that checks to make sure this process has been run in the past couple days.  If all these other scripts use the same ident then the check script is unable to notify us that the ETL script has not been running.
I haven't tested this.  I'm not sure if there could be any side effects so I've requested reviews from many team members.
> Change ETL logging identification strings

- classes/Realm/GroupBy.php
This change fixes an issue seen with the group by Grant Type in the XSEDE realm.
and is seen when using a group by configuration that has multiple joins and the
dimension table primary key is not stored in the fact tables.
See pull https://github.com/ubccr/xdmod/pull/1288 for more context.
> GroupBy refactor bugfix.

- html/unit_tests/index.html
- html/unit_tests/phantom.js
Replaces use of [RawGit](https://rawgit.com/) with [unpkg](https://unpkg.com/).  Changes the version of `chai` to 3.4.1 because version 3.4.2 is not available on [npm](https://www.npmjs.com/package/chai?activeTab=versions).  Also adds an `onResourceError` handler to improve debugging.
These unit tests were [failing on Travis CI](https://travis-ci.org/github/ubccr/xdmod/jobs/692763131#L1197) and RawGit has reached the end of its useful life.
Tested manually and on Travis CI.
> Update PhantomJS unit tests

- bin/xdmod-check-config
- docs/software-requirements.md
- open_xdmod/modules/xdmod/xdmod.spec.in
- tests/ci/bootstrap.sh
Removes the `php-mcrypt` requirement from the RPM SPEC files. Removes `php-mycrypt` during tests bootstrap.  Removes `php-mcrypt` check and documentation.
It would appear that `php-mcrypt` is no longer required.  It was required by earlier versions of `simpleSAMLphp`, but not by the currently used version.
Updated tests bootstrap to remove `php-mcrypt`.
> Remove php-mcrypt requirement

- bin/xdmod-check-config
Adds checks for PHP APCu and Multibyte String functions to make sure the corresponding extensions are installed and enabled.
When I was removing the mcrypt requirement I noticed that checks for these extensions were missing.  These checks serve as a sanity check to assist in debugging.
> Update xdmod-check-config script

- open_xdmod/build_scripts/templates/install.template
- open_xdmod/modules/xdmod/xdmod.spec.in
Changes the default permissions of the log directory to be `0770`.
This is intended to improve security.
> Change default log directory permissions

- classes/Rest/Utilities/Authentication.php
- configuration/logrotate.conf
**NOTE** there will be an accompanying PR for ccr-private as there's one usage of `session_manager.log` there. 
- Removed the creation / use of the logger that wrote the session information to the file `session_manager.log`. 
- Removed the entry in the logrotate configuration file that referenced `session_manager.log`
This file was identified in the security review by TrustedCI via the
XDMoD-2020-0002 vulnerability report. Additional changes tracked in
https://app.asana.com/0/342819846538629/1178746552707810
All automated tests
> Removing unused log file exposing user sessions

- classes/CCR/Log.php
Change the default file and directory permissions for log files created by the `CCR\Log` class.  Also updates the class constructor to allow these permissions to be changed.
Note that log files created directly by the `Log` class are not changed.
https://app.asana.com/0/342819846538629/1178746552707810/f
> Change default log file permissions

- classes/OpenXdmod/DataWarehouseInitializer.php
Log messages at the same level for similar things.
before:
```
[root@xdmod9 /]# xdmod-ingestor --realm Cloud --debug
2020-06-18 13:24:37 [notice] xdmod-ingestor start (process_start_time: 2020-06-18 13:24:37)
2020-06-18 13:24:41 [notice] Jobs realm not enabled, not aggregating
2020-06-18 13:24:41 [notice] Storage realm not enabled, not aggregating
2020-06-18 13:24:41 [notice] xdmod-ingestor end (process_end_time: 2020-06-18 13:24:41)
[root@xdmod9 /]#
```
after:
```
[root@xdmod9 /]# xdmod-ingestor --realm Cloud --debug
2020-06-18 13:24:37 [notice] xdmod-ingestor start (process_start_time: 2020-06-18 13:24:37)
2020-06-18 13:24:41 [notice] Jobs realm not enabled, not aggregating
2020-06-18 13:24:41 [notice] Cloud realm not enabled, not aggregating
2020-06-18 13:24:41 [notice] Storage realm …
```
> consistient log levels

- html/gui/general/login.php
Seemes I messed up while testing the other CORS changes to make sure that login actually sets the cookies.  This will actually set the cookies.
> set cookies so that iframed login works

- configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_.json
- configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day.json
Dimensions can never be null.
Update typo in comment fields.
> Fix bugs in definition of job fact tables.

- docs/configuration.md
Update the processor buckets configuration documentation.
The format of the processor buckets data file changed slightly, years ago, but the example wasn't updated.
No tests.
> Update processor buckets documentation

- configuration/etl/etl_tables.d/cloud_common/cloud_resource_specs.json
The vcpus field for the cloud_resource_specs table had the nullable property set to be true. This is incorrect and in MySQL 5.7 or higher causes an error since this field is part of the primary key.
```
xdmod.jobs-cloud-common.CloudTableManagement (ETL\Maintenance\ManageTables): Error managing ETL table `modw_cloud`.`cloud_resource_specs`: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
```
Setting the field to be `nullable: false` fixes the problem
Tested manually
> Change table definition for vcpus field for the cloud_resource_specs table 

- bin/xdmod-check-config
Updates the `xdmod-check-config` script to warn about PHP 7.  Also changes the comparison function used.
We've been getting more support requests from users that have PHP 7 installed and Open XDMoD does not currently work with PHP 7.
> Update PHP version check

- configuration/logrotate.conf
- docs/configuration.md
- docs/upgrade.md
- templates/apache.conf
Replace Apache log rotation using `logrotate` with `rotatelogs`.
https://app.asana.com/0/342819846538629/1182411629511737/f
> Use piped logging to rotate Apache logs

- docs/hierarchy.md
Adds a reference to the PI configuration for job data.  Adds the SQL commands to reset the hierarchy.  Also adds some other minor formatting changes.
There's been at least one support request asking about how to reset the hierarchy.
Tested the commands manually.
> Update hierarchy documentation

- classes/Realm/GroupBy.php
- configuration/datawarehouse.d/ref/group-by-common.json
- tests/component/lib/Query/AggregateQueryTest.php
See https://app.asana.com/0/342819846538629/1184363894649545
will also need updates in the Job Performance module and the XSEDE module.
> Fix groupby resource

- classes/Rest/Controllers/WarehouseControllerProvider.php
- tests/integration/lib/Rest/WarehouseControllerTest.php
This is needed for the ondemand integration. If the filters parameter is
absent then the behaviour is unchanged so this should not cause any regressions.
This filtering works in identical way to the metric explorer global filters so
any caveats for that code also are applicable here.
> Add ability to apply filters to the aggregatedata request.

- configuration/etl/etl.d/acls-import.json
- configuration/etl/etl_sql.d/acls/xdmod/create_public_user.sql
- configuration/etl/etl_sql.d/cloud_generic/post_ingest_updates.sql
- configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
- configuration/etl/etl_sql.d/cloud_openstack/unknown_domain.sql
- configuration/etl/etl_sql.d/cloud_openstack/unknown_resource_type.sql
Update SQL queries to use `//` or change configuration to specify `;`.  Also removes Roles table query.
The delimiter changes will fix any incorrect SQL statement counts and improve error reporting.  The `Roles` tables isn't being used so that query should be removed.
> Update SQL delimiters

- html/index.php
Adding an informational alert for when either ingestion or `acl-config` has
not been run.
This is to address:
https://app.asana.com/0/342819846538629/1185258719202835
Manually tested.
> Adding an alert to notify users when ingestion has not been run.

- configuration/datawarehouse.d/ref/Jobs-statistics.json
Removed some of the nonsensical language from the description and unremoved
some less unsensible test.
> Update the utilization metric description to be less terrible.

- html/gui/js/CCR.js
Also update the tooltip to be slightly less uninformative.
This increases the width of the button. However there is still plenty
of space in the top toolbar. The width of the page that causes the
Help button to disappear is still mcuh narrower than any usable width
for the rest of XDMoD.
The rest of the labels and paths are unchanged
> Rename internal dashboard button from "Dashboard" to "Admin Dashboard"

- docs/howto-node-utilization.md
Updates the node utilization documentation with instructions on how to add the statistic.
The node utilization statistic is not enabled by default and this result in it's removal during the group by refactoring.
https://app.asana.com/0/342819846538629/1185671232325737/f
Tested instructions manually.
> Update node utilization documentation

- tests/ci/validate.sh
Quotes variables used in the shell script and use bash `[[` for comparisons.  Also fixes a typo.
If tables don't exist then an additional error message is produced:
```
./tests/ci/validate.sh: line 25: [: -ne: unary operator expected
```
> Improve CI validate script

- docs/cloud.md
- docs/configuration.md
- docs/install-rpm.md
- docs/install-source.md
- docs/logo-image.md
- docs/module-assets.md
- docs/modules.md
- docs/nginx.md
- docs/simpleSAMLphp-ldap.md
Mostly making sure that "Open XDMoD" is being used and white space changes.
Preparing for the next release.
No tests.
> Minor documentation changes

- docs/etl/data-verification.md
Updates help text for `verify_table_data.php`.
Text didn't match the output from the actual command.
> Update ETL table data verification help text

- docs/_data/toc.yml
- docs/configuration.md
- docs/dashboard-devel.md
- docs/dashboard.md
First crack at adding dashboard documentation. There was an existing page that had developer documentation that was called dashboard.md so the diff looks a bit messy. 
Also bear in mind that these docs are intended for a sys admin to configure their XDMoD instance. How to use the dashboard is documented in the user manual (which is also getting updated).
> Add documentation for the dashboard.

- classes/DataWarehouse/Access/Common.php
- classes/DataWarehouse/Access/MetricExplorer.php
- classes/DataWarehouse/Access/Usage.php
Found when switching to `chromium` that the PDF export has metadata that is sometimes only populated with the filename, this put it to something useful.
> Populate PDF MetaData with more than a filename

- docs/software-requirements.md
- docs/upgrade.md
- libraries/charting.php
- open_xdmod/modules/xdmod/xdmod.spec.in
`ghostscript` was added to set proper pdf width and height, this can be done with `rsvg-convert` and the metadata can be added with `exiftool` use these tools instead as they are "smaller"
Another PR will be added to cleanup all the temporary files.
Url for exiftool comes from yum
```text
$ yum info perl-Image-ExifTool
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
* base: mirror.clarkson.edu
* epel: ord.mirror.rackspace.com
* extras: mirror.atlanticmetro.net
* updates: mirror.atlanticmetro.net
Installed Packages
Name        : perl-Image-ExifTool
Arch        : noarch
Version     : 12.00
Release     : 1.el7
Size        : 15 M
Repo        : installed
From repo   : epel
Summary     : Utility for reading and writing image meta info
URL         : …
```
> Replace ghostscript with exiftool

- classes/Rest/Utilities/Authentication.php
- classes/XDUser.php
This change is to address
https://app.asana.com/0/808093868887967/1188274656222915 . These problems were
brought to our attention via our 2019 engagement with TrustedCI. Specifically,
we now ensure that only a single user record is returned from these queries,
anything else is considered an exception.
automated tests were performed
> Verifying User Query Count to address TrustedCI feedback

- html/gui/css/viewer.css
Fix CSS syntax for `.x-form-check-wrap`.
I noticed this while I was editing the file for #1435 .  It appears that the line was accidentally split in 2013.  This does slightly alter the appearance of ExtJS checkbox form elements.
> Fix checkbox CSS syntax

- classes/OpenXdmod/Migration/AclConfigMigration.php
- classes/OpenXdmod/Setup/AclConfig.php
- classes/OpenXdmod/Setup/DatabaseSetup.php
- configuration/constants.php
- open_xdmod/build_scripts/templates/install.template
Update executing of `acl-config` to use the absolute path.
This has been an issue because `acl-config` may not be in the `PATH` environment variable (for the source installation).  It's also possible that another command named `acl-config` may be in the `PATH` before the correct version (see #1306).
https://listserv.buffalo.edu/cgi-bin/wa?A2=CCR-XDMOD-LIST;a2f9993d.2008
https://listserv.buffalo.edu/cgi-bin/wa?A2=CCR-XDMOD-LIST;59d4a324.2008
> Use absolute path when running acl-config

- html/gui/js/TGUserDropDown.js
- html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
Updates the `TGUserDropDown` (used for the "Map To" field when creating users in the internal dashboard) to execute the cascade options after the field is set programmatically. (Previously the cascade options were only executed after the `select` event which is only triggered by a user selecting an item from the drop down.)
Using the "Find" option during user creation wasn't setting the institution which then produces an error message when attempting to create the user.
https://app.asana.com/0/807770147051221/1193376020829900/f
> Fix institution loading during manual user creation

- classes/DataWarehouse/Data/RawStatisticsConfiguration.php
- configuration/rawstatistics.d/20_jobs.json
Change the format used for variable substitution in `rawstatistics.json` configuration files.
This changes the syntax for variable substitution to match the format used by the ETL configuration files (as well as using the same PHP class).  It also adds the other PHP constants that are not current used to the list of substitutions.
I'll update the upgrade documentation later since there will may be more changes made to the format of these files.
This is intended to make the substitutions more uniform with those used by the ETL and `datawarehouse.json` configuration file.
It is also a step working towards https://app.asana.com/0/342819846538629/1185671232325739/f
Tested manually in the job viewer.
> Change raw statistics variable substitution format

- html/gui/js/modules/Dashboard.js
The new user tour dialog checking-and-showing code runs every time the
dashboard is loaded. The dashboard is reloaded when you navigate to it
and the data have changed. I.e. multiple times per session. This change
sets a flag so that the tour checking code only runs once.
While investigating this issue I noticed another bug where the response
data was being parsed even in the error case (which lead to a unhandled exception
in the javascript). This mitigates this problem by switching the
code to use the success callback function. In the error case the request
will be retried the next time the dashboard loads. I saw the load failure
case when using XDMoD on a noisy wi-fi connection.
Asana issue:  https://app.asana.com/0/808093868887967/1140113137533641
> Only show the New User Tour Dialog once per session.

- classes/Authentication/SAML/XDSamlAuthentication.php
The previous code was bad.  It just got the "last" configured information.
This update uses the configured authsource to get its IdP and use that information to get the proper metadata.
This has been tested on metrics-dev by switching the configured authsource
> Update SSO to pull the configured SP's IdP metadata directly

- templates/apache.conf
tacc-frontera was flagged by a vulnerability can reported to UB's InfoSec
office. Per their recommendations I'm adding these changes to disable the
vulnerable SSLv3 protocol.
https://us-cert.cisa.gov/ncas/alerts/TA14-290A
Mo secure is mo better
> Disabling SSLv3 to prevent Poodle Attack

- tests/ci/scripts/qa-test-setup.sh
It was found that while the new qa setup worked well for checking XDMoD
modules ( which have a remote upstream added in shippable.yml ), it had started
failing to pass when run for XDMoD proper due to not being able to identify a
remote branch to check against. Thankfully Shippable provides this information
in the `$BASE_BRANCH` environment variable so, if we're running in Shippable
then update the `build_args` to specify the BASE_BRANCH as the remote for
`build.sh`.
This was tested with a straight XDMoD install & a module build ( SUPREMM ) to make sure that things were still working w/ the modules.
> Updating qa-test-setup to include remote branch for Shippable

- html/about/links.html
- html/about/openxd.html
- html/about/supremm.html
- html/about/xdmod.php
Change deprecated html in balance of About pages, in keeping with SonarCloud recommendations. Elements affected are `<font>` and `<b>`. Note that deprecated html in the About tab's publications, presentations, and staff pages has recently been addressed in other PRs (#1474, #1470). This PR replaces #1472.
This change brings the pages of the About tab in compliance with current html guidelines. It will also make these pages more accessible to screen readers, as it replaces the use of arbitrary font elements with the more expressive section heading elements.
- viewed changed files in browser
- deployed branch in docker instance for viewing
> Remove remaining deprecated html from About tab pages

- tests/ci/scripts/qa-test-setup.sh
I've updated the `qa-test-setup` script  to not explicitly set a remote branch for `build.sh`. This was causing problems because it was using the `BASE_BRANCH` env variable which in certain situations would be empty. This ultimately had `build.sh` erroring out w/ the message: `Could not resolve remote branch: `. 
It's a good thing to have our QA tests actually run.
I've tested this change locally w/ both a base XDMoD & SUPREMM build using the last merged PR's for both as the target. Both builds complete successfully.
> Updating QA Setup Script to not explicitly set remote branch for build.sh

- classes/DataWarehouse/Access/BatchExport.php
- classes/DataWarehouse/Access/RawData.php
- classes/DataWarehouse/Export/RealmManager.php
Use `array_values` to re-index returned arrays.
These arrays are created using `array_filter` and that may produce gaps in numeric array keys.
No new tests.
> Fix filtered indexes

- bin/acl-config
- configuration/etl/etl_tables.d/acls/module_versions.json
Updates `TIMESTAMP` columns in the `moddb.module_versions` table and updates PHP code to insert both date and time into the `created_on` column.
Due to how MySQL handles timestamp columns this table was triggering an alter statement by the ETL system.  See https://github.com/ubccr/xdmod/blob/xdmod9.5/classes/ETL/DbModel/Column.php#L186 for more about how those columns are handled by the ETL system.
I noticed the table was being altered while I was debugging some role configurations.  Since the `ALTER` statement doesn't do anything this will prevent it from being executed every time `acl-config` is used.
Ran `acl-config --debug` then checked for `ALTER` statements.  Then checked contents of `moddb.module_versions`.
> Update moddb.module_version table

- background_scripts/update_check.php
- bin/xdmod-admin
- bin/xdmod-import-csv
- bin/xdmod-ingestor
- bin/xdmod-shredder
- bin/xdmod-slurm-helper
- bin/xdmod-update-resource-specs
- bin/xdmod-upgrade
- tests/artifacts/xdmod/component/slurm_helper/sacct.json
- tests/component/lib/SlurmHelperTest.php
Replaces use of the logger with writing directly to STDERR.
This code may run before the logger object has been created so the errors aren't logged.  This will at least output the error messages.  I recently ran into this issue and noticed that some of the scripts are already writing to STDERR in this situation.
Updated tests.
> Change top-level exception handling in scripts

- classes/CCR/DB/MySQLHelper.php
Replaces the use of `--defaults-file` with `--defaults-extra-file`.
Changes to the MySQL configuration were being ignored resulting in errors.
https://app.asana.com/0/0/1199666656644652/f
Changed the socket in /etc/my.cnf (and /etc/php.ini).  Before the change the socket configuration would be ignored by anything using the `MySQLHelper` class.
> Fix mysql command line defaults file option

- html/index.php
The lang=en should be in the html tag because the whole document
is in english not just the document head.
> Fix bug in language definition in main html page.

- classes/CCR/Logger.php
We ran into a problem described in this PR: https://github.com/ubccr/xdmod/pull/1490 After some research I found that the
root of the problem is this function json_encode'ing `$record` when the contents
of `$record` may contain objects that do not support `JsonSerializable` but that
do implement `toString()`. After a conversation w/ Joe it's been decided that
our Logging API will be to support the logging of arrays w/ objects that
implement a `toString()` function. The eagle-eyed may notice that this solution
differs from the one I put forth in the above PR. The reason being that the
original solution only supported the use case of having an array w/ top level
value objects and would not work as expected if a nested array is supplied with
an object that implements `toString()`.
It's nice …
> Updating the logging code to not throw away all class information

- classes/ETL/Ingestor/pdoIngestor.php
The data encoding in the mysql LOAD DATA INFILE mechanism
in the pdoIngestor was incorrect. It did not properly encode
the data in the cases where the various delimiter characters appeared
in the fields.
The correct algorithm is to enclose a field in the field enclosure
character if the field contains any special character. In addition
the field enclosure character and the escape character must be
escaped with an escape character.
Also, the various delimiter characters were class member
variables. However, their values were not actually used to generate the SQL
so if they were ever changed then the code would not have worked.
> Fix data encoding in etlv2 pdoIngestor

- html/controllers/report_builder/download_report.php
- tests/integration/lib/Controllers/ReportBuilderTest.php
The download_report controller endpoint already checks that the
filename is acceptable. However, in the case of an invalid filename
it potentially would try to open a file called [TMPDIR]/.[SUFFIX].
This change add an explicit exit if an invalid filename is supplied.
Also add a test for this scenario and to check some of the other input
validation code.
> Improve input validation for download_report controller

- html/gui/js/modules/Usage.js
This fixes an issue with adding data to charts that were originally configured by "gearing over" from the Usage tab.
Steps to reproduce the original problem:
1) View a chart in the Usage tab
2) Gear over to load the chart in the Metric Explorer
3) Add data for a _different_ realm to the chart
4) The Realm label  should appear as a prefix for the dataset labels for each dataset. But is is missing for the first dataset.
For the original bug report see:
See https://app.asana.com/0/808093868887967/1184327725706337
Note the bug is fixed by the one line that populates the category object property. However, in investigating the bug there were several other configuration keys that were not defined. This change also ensures that all the required properties are given a value.
> Add missing attributes when gearing over from Usage to Metric

- html/gui/js/modules/Dashboard.js
The "Don't show me this again" checkbox only did something if
the user clicked "no" to view the tour. However the user interface
gives no indication that the checkbox only works when you click no.
This changes the code so that the checkbox is honoured independently
of whether you click yes or no. The annoying popup that you get when
you click no is still shown.
I also couldn't help myself and removed some cruft - you don't need
to specify any parameters to the viewedUser endpoint.
See asana issue: https://app.asana.com/0/808093868887967/1145221540055486
> Ensure "Don't show me this" checkbox is honoured

- classes/OpenXdmod/Migration/Version900To950/DatabaseMigration.php
- configuration/etl/etl_tables.d/cloud_common/cloud_resource_specs.json
- configuration/etl/etl_tables.d/cloud_common/staging_resource_specifications.json
This PR changes the constraints on the modw_cloud.cloud_resource_specifications and modw_cloud.staging_resource_specifications tables to prevent there being more than one row for a host for a day. Previously, you could have two rows for a host on a day which would cause incorrect data and/or errors when trying to aggregate the cloud resource specifications data.
Preventing errors and incorrect data
Tested in docker. Both fresh install and the upgrade
> Changing constraints on cloud resource specifications tables to prevent extra rows

- configuration/etl/etl_tables.d/jobs/xdw/jobhosts.json
Adding an index to the jobhosts table to help with queries in the federated module that load the jobhosts from the federation instance jobhosts table to the federation hub jobhosts table.
It helps speed up queries in the federated module
Tested on the federated AMNH site
>  Add an index to the modw.jobhosts table to help with queries in the federated module

- classes/DataWarehouse/Query/Jobs/RawData.php
This was requested by the OnDemand folks and will be used to display
in their web interface. There is a corresponding change to the supremm
realm too.
This change does not result in any changes to the XDMoD user interface.
> Add walltime_accuracy metric to job summary data.

- classes/OpenXdmod/DataWarehouseInitializer.php
The pipelines that are run when ingesting data in the generic cloud data format need to be updated to include some pipelines that allow you to use the cloud realms without having the jobs realm existing.
We want the cloud realm to be able to exist independently of the jobs realm
> Updating pipelines that get run when ingesting data in generic cloud data format

- configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation_by_day.json
Adding columns to cloudfact_by_day aggregation to match the aggregation of the other time periods and to make sure it is compatible with the #1469 
> Add columns to cloudfact_by_day aggregation

- libraries/charting.php
Starting with chromium-headless-89.0.4389.82-1.el7.x86_64 chrome crashes on
exit (due to the fortify stack smashing code firing). This appears to happen
on exit and does not prevent chrome from rendering the svg. This change
works around the problem by using the presence of valid output as the
test condition and ignores the chrome exit code.
> Change chromium output error detection.

- configuration/etl/etl_sql.d/cloud_common/delete_session_records.sql
- configuration/etl/etl_tables.d/cloud_common/event_reconstructed.json
- configuration/etl/etl_tables.d/cloud_common/session_records.json
This PR adds two indexes and changes the query that is used during the aggregation process that removes all the sessions for instances we are aggregating from the session_records table. The previous query does not scale well when dealing with a larger amount of instances in the aggregation. One example of this is when trying to ingest 4-5 months of data from the Jetstream resource which can cause this action to take a very long time to complete.
This should make this action perform better if there is a larger number of instances included in the aggregation
> Change query that deletes session records to have better performance

- configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
The truncate_destination directive for the cloud_resource_specs table during the upgrade was in the wrong spot meaning the table was not truncated.
> Move truncate_declaration directives to correct spot for cloud resource specs migration

- docs/upgrade.md
Adding documentation to detail how to re-shred, ingest and aggregate cloud data because of a bug with the cloud memory buckets after upgrading to xdmod9.5
> Adding documentation related to cloud upgrade for 9.5 release

- classes/DataWarehouse/Query/Cloud/JobDataset.php
- classes/OpenXdmod/Migration/Version900To950/DatabaseMigration.php
- configuration/etl/etl.d/jobs_cloud_common.json
- configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
- configuration/etl/etl_action_defs.d/cloud_common/host.json
- configuration/etl/etl_action_defs.d/cloud_common/initialize_unknown_dimension_values.json
- configuration/etl/etl_data.d/cloud_common/host.json
- configuration/etl/etl_sql.d/migrations/9.0.0-9.5.0/modw_cloud/update_hosts_table_index.sql
- configuration/etl/etl_tables.d/cloud_common/host.json
This PR fixes three issues.
1. Using the correct table for the time field in the `JobDataset.php` file. The `session_records` table has the `start_time_ts` and `end_time_ts` columns that should be used for the start time and end time parameters. It was trying to use the instance table which does not have those columns.
2. Changing the `host` table to have a single autoincrement column instead of a composite autoincrement. In PR #1263 we changed most of the cloud realm dimension tables that use a composite autoincrement key to use a single unique column for the autoincrement key. At the time the `host` table was not used for anything so it was not converted. It is now being used in the cloud instance viewer and Data Export and should be changed to match the other cloud realm dimension …
> Updates for cloud Data Export and migration pipelines.

- configuration/etl/etl_sql.d/migrations/9.0.0-9.5.0/modw_cloud/update_hosts_table_index.sql
The 9.5 release changes the `host` table in `modw_cloud` to have a single auto-increment column instead of a multi-column one. When running the migration SQL to update the `event` table with the value from the new auto-increment column on the host table it is possible the primary key on an updated row can match the primary key on a row that is not yet updated causing a primary key duplicate error. This PR helps prevent this by removing the primary key during the update and then adding it back after the update is done.
Tested an upgrade in a docker container with a production copy `modw_cloud` and the upgrade was successful.
> Update host dimension migration sql to avoid primary key duplicate during migration

- classes/XDReportManager.php
The database stores the format of a PDF report as `Pdf` and when checking if a pdf of a report should be created strtolower should be used to compare to `pdf`. If not, the pdf will not be made, and when the report is emailed it will fail to find the pdf to attach.
This makes sure that PDF reports will be created.
Tested in docker and on metrics-staging
> Use strtolower to check format for a PDF report

- configuration/etl/etl_action_defs.d/common/hpcdb/resources.json
Change the HPcDB resource ingestor to use 0 for the `resource_type_id` when no resource type is found.
https://app.asana.com/0/0/1200481198259375/f
Previously, -1 was used for unknown values.  Since the unknown resource type uses 0 this will fix that.  I don't think this has ever worked since it appears that the unknown resource has always used 0.
> Fix resource ingestor default resource type

- NOTICE
- bin/xdmod-check-config
- classes/OpenXdmod/Setup/GeneralSetup.php
- docs/configuration.md
- docs/dev-code-organization.md
- docs/notices.md
- tests/ci/scripts/xdmod-setup-start.tcl
Removes references to Java (and PhantomJS) that should have already been removed (possibly in #1341 and #1413).
- Removes references to Java libraries that are no longer used.
- Updates `xdmod-check-config` to no longer check for Java.
- Removes Java questions from setup process.
Java is not used anymore so these references are no longer relevant.
No tests.
> Remove Java configuration and documentation

- bin/xdmod-check-config
- classes/CCR/Log.php
- docs/software-requirements.md
- open_xdmod/modules/xdmod/xdmod.spec.in
- tests/ci/bootstrap.sh
- Remove PEAR MDB2 dependencies.
- Update `xdmod-check-config`.
- Remove comment referencing PEAR `Log.php` file.
- Update CI bootstrap to remove MDB2 packages.
These dependencies are no longer required.  See #1461 
https://ubccr.freshdesk.com/a/tickets/26898
No new tests.
> Remove PEAR Log dependencies

- classes/Xdmod/SlurmResourceParser.php
- tests/artifacts/xdmod/unit/slurm-resource-parser/alloc-tres-gpu-count.json
Adds support for slurm TRES accounting data that includes a GPU type specifier.  (eg. <code>gres/gpu<b>:tesla</b>=4</code>)
This was missing in the initial implementation and was reported by an Open XDMoD user.
https://app.asana.com/0/1200028182662861/1200481198259377/f
> Improve Slurm TRES GRES/GPU parsing

- bin/xdmod-check-config
- docs/software-requirements.md
Removes references to `php-gmp` from the documentation and `xdmod-check-config`.
I can't find anywhere that GMP is required.  None of the `gmp_*` functions are used anywhere in Open XDMoD.
No new tests.
> Remove PHP GNU Multiple Precision dependency

- bin/xdmod-slurm-helper
Changes the default end time used by the `xdmod-slurm-helper` to be the current time.
With the previous default end time it was possible that the default end time would be before the default start time.  This resulted in an error message from `sacct`.
See https://app.asana.com/0/159049597309611/1199962348183946/f
Tested manually on metrics-dev.
> Change slurm helper default end time

- .circleci/config.yml
The QA scripts will use the environment variable TRAVIS_COMMIT_RANGE to determine which commits to use when running the linter on the changed code. If this environment variable is not set then the script will attempt to diff against
upstream/HEAD.
The upstream/HEAD diff is a problem when trying to ci test against old branches since the diff will incorrectly compare the set of changes against the latest build and not the correct target branch.
This changes the code to set the commit range appropriately so the scripts diff against the correct commit.
> Use the git-provided commit range.

- composer.json
- composer.lock
- html/highchart_template.html
- html/index.php
- html/internal_dashboard/index.php
- html/password_reset.php
The `ready()` function in jQuery 3 has different behaviour
than the one in 1.x and cannot be used in the chart export
code path. This has been replaced with an event listener for
DOMContentLoaded. Only other changes are updating the filename.
> Update jQuery to 3.6.0

- bin/acl-config
Original query was pulling from the acls / group_bys table as opposed to the
acls_staging and group_bys_staging tables. This will resolve the issue on
It's nice when queries work and don't error out.
Manual testing was performed to initially confirm that the fix worked on metrics-dev.
> Updating acl_dimension_staging population query

- tests/ui/test/specs/xdmod/loginPage.page.js
- tests/ui/webdriverHelpers/waitForAllInvisible.js
Recent circle-ci builds have been failing due to timeout errors in a few different places. This has been happening even for pull requests that do not change the indelying code.
This pull requst adds an extra mask invisible check and increases the "mask disappear" timeout in the hope of mitigating these type of errors.
> More robustness improvements for webdriverio-based UI tests

- classes/CCR/CCRDBHandler.php
- configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
- configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_logger/alter_log_id_seq.sql
- db/data/mod_logger.sql
- db/schema/mod_logger.sql
- I've moved from the previous INSERT / DELETE algorithm to using an UPDATE.
This allows us to remove the explicit transaction management as we only have one
query that applies modifications as opposed to two. This new method was chosen
after a conversation with @jpwhite & @gmdean.
- To implement this change there were a couple of small changes that needed to
be made to the log_id_seq table schema & it's initial population.
- `mod_logger`.`log_id_seq`.`sequence` has had it's `AUTO_INCREMENT` keyword
removed as we'll be manually controlling the way the sequence is generated.
- Since the `sequence` column is no longer an `AUTO_INCREMENT` we need to add
an initial value, this has been done in `data/db/mod_logger.sql` by inserting
an initial value of `0`.
These changes are an attempt to …
> Updates to mod_logger tables

- configuration/constants.php
- html/gui/js/CCR.js
This is still somewhat arbitrary, but 2 is the shorted username seen
at UB.
The regular expression change has been tested by manual install \<looks around shiftily\> _on metrics prod_!
This fixes an issue reported by two different users where they were unable to create a user account with username less than 5 characters long.
> Set minimum username length to 2.

- configuration/etl/etl_action_defs.d/jobs/hpcdb/jobs.json
- configuration/etl/etl_action_defs.d/jobs/xdw/job-records-job-tasks.json
Fix QOS bug.  See #1589
`modw` does not allow NULL, but `mod_hpcdb` does.
```
2021-12-19 04:30:20 [warning] Warning	1263	Column set to default value; NULL supplied to NOT NULL column 'qos_id' at row 1
```
> Fix null QOS ID

- configuration/etl/etl_tables.d/jobs/hpcdb/jobs.json
Adding an index to the nodecount column speeds up the `hpcdb-xdm-ingest-jobs.node-count` action. When using this index the action takes less than 10 seconds where before it would take around 5 minutes on our development server. This was supposed to be part of #1579 but was missed.
We would like ingestion to be as quick as possible.
Tested in docker and on metrics-dev
> Adding index to nodecount column

- configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
- configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_shredder/update_storage_datetimes.sql
- configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/update_cloud_resource_datetimes.sql
- tests/ci/bootstrap.sh
In #1592 column type changes were made to the `modw_cloud.cloud_resource_specs` and `mod_shredder.staging_storage_usage` tables to get rid of warnings that were being shown. That column change caused a change in format of the dates from `2021-01-01 12:00:00` to `2021-01-01T12:00:00Z`. There needs to be a migration pipeline that changes the existing dates in these columns to the correct format.
Ingesting the cloud resource specs and storage data again in the upgrade helps to test that this works.
> Adding migration pipeline to put dates in cloud resource specs and storage tables into correct format on upgrade

- tests/ci/bootstrap.sh
Redhat moved the centos8 repos to vault today. These changes allow our
Centos8 builds to work while we move towards supporting Rocky.
To get our Centos8 builds working long enough for us to move to Rocky.
> Temporary Fix for Centos8 repo change

- classes/XDAdmin.php
- configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
- configuration/etl/etl_tables.d/xdb/session-manager.json
- configuration/etl/etl_tables.d/xdb/users.json
Refactor SQL and add indexes to `moddb.Users` and `moddb.SessionManager` tables.
Note that the `SessionManager` table is already included in the InnoDB migration so does not need to be included in the migration changes here.
User reported this query taking longer than a minute resulting in a time out in the admin dashboard.
https://app.asana.com/0/807770147051221/1201757805272796/f
https://ubccr.freshdesk.com/a/tickets/29169
Ran original query using development database and compared output with that from the new query.
> Refactor admin dashboard user listing query and add indexes to Users and SessionManager tables

- classes/ETL/Maintenance/ExecuteSql.php
Adjusts regular expressions used to remove comments in SQL to use `PCRE_MULTILINE`.
From https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php:
By default, PCRE treats the subject string as consisting of a single "line" of characters (even if it actually contains several newlines).
Without this modifier only a single line is removed when there are multiple comments of the same style.  This produces confusing output in error messages.  Now all the comments will be removed.
See https://app.asana.com/0/1200028182662861/1201795993165108/f
No new tests.
> Fix comment removal in ETL SQL execution

- html/controllers/metric_explorer/get_rawdata.php
- html/gui/js/AddDataPanel.js
- html/gui/js/CCR.js
Comparing floats as strings is not desirable due to the way they are represented
internally. Per [https://www.php.net/manual/en/language.types.float.php](https://www.php.net/manual/en/language.types.float.php) they
should be compared to within a certain number of digits. This was found by
investigating an error where the "Show Raw Data" context menu item was not
showing the associated jobs. It turns out that the id's being compared were the
following:
- 0.22694672549385309
- 0.22694672549385
The latter number having been truncated after 14 digits, which was a problem
as they were being compared as strings, not floats. By comparing them as floats
we can mitigate this type of rounding / truncating error in the future.
This was found as part of manual on testing XDMoD & SUPREMM on CentOS8. …
> Updating the datasetid float comparison (PHP7.2)

- Gemfile
*Replaced:*
`require 'json'`
`require 'open-uri'`
`versions = JSON.parse(open('https://pages.github.com/versions.json').read)`
`gem 'github-pages', versions['github-pages']`
*with:*
`gem 'github-pages', 226`
1. `open-uri` depricated
2.  using 226 is more direct instead of parsing JSON data when accessing 'github-pages` gem
3. fixes `Net::OpenTimeout` error when trying to generate webpage with jekyll
1. No longer had timeout error
2. Manually checked JSON data to ensure correct key-value pair of 'github-pages': '226'
3. Change was discussed between me and Joseph
> Update Gemfile Ruby Code

- Gemfile
Changed the 226 on line 13 to the string '226'
The change I had previously made to this file neglected the fact that the key-value pairs at https://pages.github.com/versions.json are strings. This change fixes that. Otherwise, the gem would not have been accessible.
I rebuilt the Open XDMoD website in my own test environment, which only generated after changing 226 into the string '226' in Gemfile.
> Update Gemfile - '226'

- classes/DataWarehouse/Data/RawStatisticsConfiguration.php
- classes/ETL/aAction.php
Adds variable substitution for hierarchy info used in ETL table definitions (see ubccr/xdmod-supremm#255) and `alias` configuration used in the raw statistics configuration.
This fixes table comment fields and aliases used in generated queries.
Tested manually using `mysqldump` to check tables and checking the query log for aliases used in generated SQL queries.
> Add missing variable substitutions

- classes/ETL/Ingestor/ExplodeTransformIngestor.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- ExplodeTransformIngestor: this function was causing a warning to be thrown during ingestion / aggregation w/ PHP7.2 on Rocky8 
- WarehouseControllerProvider: This update was found when testing the single job viewer and clicking on the executable information tab. This was missed when updating the PHP Mongo code to work w/ PHP7.2 & it's new mongodb library. Similar changes were made in `classes/DataWarehouse/Query/SUPREMM/JobMetadata.php::getJobSummary` line 129
These changes fix issues found during testing for the hpc-toolset-tutorial.  
Automated testing
> Additional php7 updates

- classes/DataWarehouse.php
Use correct scope when calling destroy() method
Change the scope from a global function to local class method.
`__destruct`  method referenced a seemingly nonexistent global `destroy()` function. It should have been calling its own class' `destroy()` method.
> fix: Use correct scope when calling method

- html/gui/js/CCR.js
- html/index.php
- Added an optional section/property in `portal_settings.ini` ( section `sso` and property `direct_link` ) that when set to a string that PHP evaluates to boolean true, allows for the bypassing of the normal login modal window and immediately begins the SSO login process. 
- index.php: Added a small section that reads the new `sso:direct_link` property from portal_settings and includes that as a javascript variable: `CCR.xdmod.SSODirectLink`. 
- CCR.js: Added a small section that immediately starts the SSO Login process if `CCR.xdmod.SSODirectLink` is present and true. 
These changes make it possible to configure XDMoD to, when setup to use SSO,
bypass the normal login modal and for the auth process to begin
immediately upon clicking the `Sign In` link.
This feature came out of a desire …
> Bypass Login Modal for SSO

- html/gui/js/SignUpDialog.js
- html/gui/js/modules/Usage.js
These XSEDE-specific code paths are no longer needed.
> Remove XSEDE-specific code from base module.

- html/gui/js/CCR.js
- html/index.php
This PR updates the Contact Us button to instead redirect to a configured URL for ACCESS tickets. This only works if the configured URL is present, else it will default to Open XDMoD's functionality.
1.) Checks if 'tech_support_url' is set in configuration.
2.) If 'tech_support_url' is present, then the Contact Us button redirects to that site instead of the dropdown menu.
Without tech_support_url set:
With tech_support_url set:
In the screenshot the Contact Us button will redirect to the configured URL.
ACCESS XDMoD does not need the same dropdown menu for this button as Open XDMoD.
https://app.asana.com/0/1202679277743034/1202840692396198
Tested on my development port.
> Update Contact Us button for ACCESS XDMoD

- configuration/etl/etl.d/xdmod-migration-10_0_0-10_5_0.json
- configuration/etl/etl_tables.d/xdb/report-template-charts.json
There is no unique index on the report template charts which means that the normal etlv2 ingestion code cannot be used to sync the template definitions with the database. You would have to write custom SQL to update an existing row. Also if you run the existing ingestor more than once you'll get more than one copy of each chart in every report!
Also change the database charset and collation to be utf8mb4 so that non-latin characters can appear in the templates.
These changes are needed so that we can easily have xdmod modules install templates.
> Update table definition for ReportTemplateCharts

- classes/ETL/Utilities.php
- configuration/etl/etl.d/acls-xdmod-management.json
- html/controllers/report_builder/enum_templates.php
The report template acls were controlled by the contents of one file
(`etc/etl/etl_data.d/acls/report-template-acls-staging.json`) and the
acl data base was loaded with the file contents each time acl-config was run. Since Open XDMoD modules cannot modify existing files, there was no mechanism for a module to add a new report template acl.
This adds a subdirectory (`report-template-acls-staging.d`) that is scanned for files that will be appended to the report acl templates table. Open XDMoD modules can just add their settings to a file in this directory and it will be loaded when acl-config runs.
It also fixes a problem with the enum_templates controlller endpoint where it would return a json object rather than a json array if the DashBoard report templates were not at the end of the list …
> Add ability to for modules to specifiy report templates.

- docs/howto-node-utilization.md
Updated the text of the node_utilization How-To section to include language about needing to restart php-fpm in addition to httpd for changes to show up in the UI. 
Recently had a conversation w/ somebody on the HPC Toolset Slack / XDMoD Channel that was attempting to use this How-To and wasn't seeing the `node_utilization` statistic show up after having run `acl-config` and restarting `httpd`. I realized that he would also need to restart `php-fpm`, so in an effort to help other people who may run into the same problem I've added the additional verbiage in this commit. 
I read it?
> Updating node_utilization how-to to mention restarting php-fpm

- libraries/charting.php
Looks like the console output change somewhere between chromium 99 and 109. This code handles both scenarios:
the old output and the new output.
> Handle change to output of chromium 109

- tests/regression/lib/Controllers/UsageChartsTest.php
The UsageChartsTest was not loading the expected results file because the variable containing the filename was not initalised when it needed to be used.
Leading to this message:
```
PHP Warning:  file_get_contents(): Filename cannot be empty in /root/xdmod/tests/regression/lib/Controllers/UsageChartsTest.php on line 119
```
and the tests all getting skipped.
This change fixes the problem so that the tests are actually run.
> Fix regression test runner.

- configuration/etl/etl.d/xdmod-migration-10_0_0-10_5_0.json
- configuration/etl/etl_tables.d/jobs/shredder/job.json
This adds an index to mod_shredder.shredded_job. The purpose is so speed up the ingestion action that ingests the qos_name field. This action takes about 3-4 minutes now and with an index it will likely be around a second or so.
Speed up ingestion time.
Tested in docker and on metrics-dev
> Add index for qos_name ingestion

- html/gui/js/CCR.js
This prevents windows from attempting to sync their shadows if they have not been rendered.
If the "My Profile" window had a "Role Delegation" tab and was opened, there was a console error caused by the window being told to sync its window shadow before the window had been rendered.
1. Set up the test environment.
1. New environment:
1. Set up my port (9001) on `xdmod-dev` by running the script `update-open-xdmod-portal.php` with the branch `xdmod10.5-xsede`.
1. Copy in the changed files from this Pull Request.
1. Log in.
1. Old environment:
1. Spin up a Docker container from the image `tools-ext-01.ccr.xdmod.org/xdmod-10.0.0:centos7.9-0.6`.
1. Upgrade to the latest Open XDMoD 10.5 version.
1. Merge in the changed files.
1. Run the `~/bin/services start` command and open a browser to …
> Prevent unrendered windows from attempting to sync shadows.

- .circleci/config.yml
- background_scripts/chrome-helper/.eslintrc.json
- background_scripts/chrome-helper/chrome-helper.js
- background_scripts/chrome-helper/package-lock.json
- background_scripts/chrome-helper/package.json
- configuration/constants.php
- libraries/charting.php
- open_xdmod/build_scripts/templates/install.template
- open_xdmod/modules/xdmod/assets/setup.sh
- open_xdmod/modules/xdmod/xdmod.spec.in
The feature that we were previously using in chromium_headless v110 and earlier seems to have been removed in v111. This changes the code to use puppeteer-core to interact with chromium.
This change is intended to be a drop in replacement: The portal_settings config that specifies the path to chromium is still used and we package the puppeteer code so no need for post install steps.
> Add helper script that runs chromium.

- tests/regression/lib/TestHarness/RegressionTestHelper.php
This fixes a bug in the regression tests which give false positives for all tests that return csv data. `json_decode` return NULL when it cannot decode the data passed to it. Most of the regression test are csv data. The `json_decode` of this csv data returns NULL which passes the check in line 386 and line 390 and returns true, passing the test.
https://github.com/ubccr/xdmod/blob/c6f2e50231916a32d075bddb48285fbed76fd020/tests/regression/lib/TestHarness/RegressionTestHelper.php#L385-L392 
Tested in docker by changing a regression test to fail before and after the change
> Include is_null check in RegressionTestHelper when checking json_decoded data

- bin/xdmod-check-config
- open_xdmod/build_scripts/templates/install.template
- open_xdmod/modules/xdmod/xdmod.spec.in
- tests/ci/validate.sh
Add an extra flag to the installer and new substituted string in the xdmod-check-config command so we can tell the difference between an rpm install and source code install. 
On an RPM -based install the check config script will list the installed xdmod rpms and output the results of the rpm verify command.
The additional output for an RPM install would look a bit like this:
```
RPM Installed Packages:
xdmod-10.5.0-1.0.el7.noarch
File status:
S.5....T.  c /etc/xdmod/hierarchy.json
S.5....T.  c /etc/xdmod/organization.json
S.5....T.  c /etc/xdmod/portal_settings.ini
S.5....T.  c /etc/xdmod/resource_specs.json
S.5....T.  c /etc/xdmod/resources.json
```
> Add support for checking rpm install state in check-config

- bin/xdmod-check-config
Adds check for the (required) nodejs software. Also adds a check for the optional mongo driver.
Example of the output on a system with mongo driver and nodejs installed:
```
------------8<---------------
OK       PHP Timezone set
OK       Chromium configured
OK       sendmail executable installed
OK       nodejs v16.14.0
Optional prerequisites
INFO     PHP MongoDB client driver installed
```
and similarly if node and mongo are absent:
```
------------8<---------------
OK       PHP Timezone set
OK       Chromium configured
OK       sendmail executable installed
NOT OK   nodejs sh: node: command not found
Optional prerequisites
INFO     PHP MongoDB client driver not found
```
> Improvements to xdmod-check-config

- classes/DataWarehouse/Access/Common.php
- classes/DataWarehouse/Access/MetricExplorer.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- html/controllers/common_params.php
- html/controllers/metric_explorer/common.php
- tests/integration/lib/Controllers/MetricExplorerTest.php
- tests/integration/lib/Controllers/UsageExplorerTest.php
- tests/integration/lib/Rest/JobViewerTest.php
The xdmod-supremm module build has been updated to check for errors/warnings. Needless to say I found some.
The default value for the font size must be a numeric string - and not a text string. Also an error in the updateHistory rest endpoint. (these two changes have tests in the supremm module that check them).
Add some checks for data validity and hoy out an execption if the checks fail.
The corresponding pull request in the supremm module is https://github.com/ubccr/xdmod-supremm/pull/342
> Fixes for warnings generated with the supremm module tests

- bin/acl-config
- classes/DataWarehouse/Access/Usage.php
- classes/Realm/Realm.php
- classes/Realm/Statistic.php
- classes/Realm/iStatistic.php
- classes/User/Elements/QueryDescripter.php
- html/controllers/metric_explorer/get_dw_descripter.php
- html/controllers/user_interface/get_menus.php
- html/gui/js/AddDataPanel.js
- html/gui/js/modules/metric_explorer/MetricExplorer.js
This PR contains changes to allow group by's to be hidden for a specific statistic instead of a whole realm. To denote the hidden group by's for a statistic a field `hidden_groupby` can be added to a statistic definition in the config files in `datawarehouse.d`.
Example: 
```
"active_person_count": {
"description_html": "The total number of users that used ${ORGANIZATION_NAME} resources.",
"formula": "COUNT(DISTINCT(agg.person_id))",
"name": "Number of Users: Active",
"precision": 0,
"unit": "Number of Users",
"hidden_groupbys": ["resource", "pi"]
}
```
Changes were made to `acl-config` to make sure the `visibility` fields was set correctly in the appropriate acl role tables. A `hidden_groupby` property was added to the `classes/Realm/Statitstic.php` class and in …
> Allowing group bys to be hidden for a specific statistic

- configuration/etl/etl_tables.d/cloud_common/instance_type_union.json
Adding default values for modw_cloud.instance_type_union table prevents the following warning
```
[warning] Warning 1364 Field 'instance_type_id' doesn't have a default value
```
> Adding default values for modw_cloud.instance_type_union table

- html/gui/js/modules/job_viewer/AnalyticChartPanel.js
Before:
After (this also includes the styling changes in #1739 
Note this depends on a pull request in the xdmod-supremm repo that changes the error output to not add html entitires.
> Add word wrap to job viewer analytics error messages

- html/gui/js/modules/job_viewer/AnalyticChartPanel.js
Changes the icon to better match the original one remove the bold font and set the font size and face to match the original.
This does not address the word wrap (which will be in a different pull request).
HighCharts original version:
Ploty version with this code change:
Original plotly version:
> Update styling of error message to match highcharts version.

- tests/regression/runtests.sh
This makes it so that, when running the regression tests, `Ctrl-C` (`SIGINT`) interrupts all subprocesses.
When manually running `runtests.sh` and typing `Ctrl-C`, the main process would interrupt, but the subprocesses would continue running. This was inconvenient when testing new edits to the regression tests.
1. In a Docker container running `tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.3`:
1. Run the following.
```
~/bin/services start
git clone https://github.com/ubccr/xdmod /xdmod
cd /xdmod
composer install
cd tests/regression
XDMOD_REALMS=jobs,storage,cloud ./runtests.sh
```
1. Type `Ctrl-C` and confirm subprocesses continue running and producing output.
1. Once the output finishes, run the following.
```
git clone https://github.com/aaronweeden/xdmod -b …
```
> Make `Ctrl-C` interrupt regression test subprocesses.

- html/gui/js/modules/job_viewer/GanttChart.js
The range values for job peers plots did not include the timezone so the plot range is incorrect for any resources that use a different timezone than the webbrowser timezone.
Before:
After:
> Fix range setting for job peers plots.

- classes/DataWarehouse/Query/Cloud/JobDataset.php
- classes/DataWarehouse/Query/Gateways/JobDataset.php
- classes/DataWarehouse/Query/Jobs/JobDataset.php
- docs/xdmod-rest-schema.json
This PR makes it so the warehouse raw data queries involving start and end dates use the portal's local time zone instead of UTC.
There are corresponding PRs for https://github.com/ubccr/xdmod-supremm/pull/356 and https://github.com/ubccr/xdmod-xsede/pull/439.
The rest of the XDMoD portal uses the portal's local time zone when dealing with date ranges. For consistency, this PR makes the raw data queries also use the portal's local time zone.
For the Jobs realm, this will have the added benefit of enabling https://github.com/ubccr/xdmod/pull/1780.
In addition to ensuring the regression tests still pass:
1. Run the script from https://github.com/ubccr/xdmod-xsede/pull/436.
1. For the differences in the `Cloud` realm:
1. Copy the "only in old" lines into a file, run  `awk -F "', '" '{print …
> Use the portal's time zone for raw data query dates instead of UTC.

- .circleci/config.yml
- tests/regression/lib/Rest/WarehouseRawDataTest.php
This PR adds a CircleCI step to automatically catch inconsistent test namespaces so that the manual test from https://github.com/ubccr/xdmod/pull/1789 doesn't need to be performed.
This PR also fixes the namespace of `tests/regression/lib/Rest/WarehouseRawDataTest.php` to be consistent with the other test files. That file was added in https://github.com/ubccr/xdmod/pull/1788 after https://github.com/ubccr/xdmod/pull/1789 had already been merged, so it was not caught when manually checking the namespaces for https://github.com/ubccr/xdmod/pull/1789.
To make sure the CircleCI step worked, I first committed just `.circleci/config.yml` to make sure it failed, then committed the change to `tests/regression/lib/Rest/WarehouseRawDataTest.php` to make sure it passed.
> Catch inconsistent test namespaces in CircleCI.

- classes/Rest/Controllers/BaseControllerProvider.php
- classes/Rest/XdmodApplicationFactory.php
- tests/integration/lib/BaseTest.php
- tests/integration/lib/Controllers/MetricExplorerTest.php
- tests/integration/lib/Controllers/UserControllerProviderTest.php
- tests/integration/lib/Rest/AuthenticationControllerProviderTest.php
- tests/integration/lib/Rest/DashboardControllerProviderTest.php
- tests/integration/lib/Rest/WarehouseControllerProviderTest.php
- tests/integration/lib/Rest/WarehouseExportControllerProviderTest.php
- tests/integration/lib/TestHarness/XdmodTestHelper.php
This PR fixes a bug in the validation of REST parameters in the `getParam()` method of `BaseControllerProvider` in which array parameters were not properly caught as being invalid. `filter_var()` was returning `false` but only being checked for `null`.
This PR also fixes a bug in `XdmodApplicationFactory` with processing array POST data that was exposed when testing the bug above; if non-string data was sent in a POST, it would still attempt to `json_decode` it. Now, instead, it decodes that data as null.
This PR also adds the ability to make `PUT` requests with `XdmodTestHelper`, which is needed by https://github.com/ubccr/xdmod-appkernels/pull/95.
This PR adds integration tests of array parameters for endpoints that call `getParam()`.
Additional integration tests are added in …
> Fix validation of REST array parameters.

- tests/integration/lib/BaseTest.php
This PR adds the ability to test for invalid REST floating point and Boolean parameters using the existing method `IntegrationTests\BaseTest::provideRestEndpointTests()`.
This PR also adds an exception to that method if an option is provided that is unrecognized. This is to help with development of new tests that use the method by helping catching typos in option names.
The main `xdmod` module has no calls to the methods `getFloatParam()` and `getBooleanParam()` from `Rest\Controllers\BaseControllerProvider`, but the `xdmod-appkernels` module does. https://github.com/ubccr/xdmod-appkernels/pull/95 adds tests of invalid floating point and Boolean parameters that will use the changes in this PR.
To make sure this didn't cause any changes in the tests that are run, in a Docker container …
> Add integration tests of invalid REST floating point and Boolean parameters.

- .circleci/config.yml
In conjunction with https://github.com/ubccr/xdmod-qa/pull/29, this PR moves the automated check of inconsistent test namespaces from https://github.com/ubccr/xdmod/pull/1795 out of the `xdmod` CircleCI config and into the `xdmod-qa` style tests for PHP files that have been added or changed. This way, the code does not have to be duplicated in the CircleCI config of each submodule of XDMoD, and it does not have to run for every file, only those that changed.
In a Docker container running `tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.3`:
```
git clone https://github.com/ubccr/xdmod /xdmod
git clone https://github.com/aaronweeden/xdmod-qa -b lint-test-namespaces /xdmod-qa
cd /xdmod-qa
composer install
cd /xdmod
```
Change namespaces in the `tests` directories and confirm …
> Remove test namespace linting.

- classes/DataWarehouse/Query/Jobs/JobDataset.php
This PR optimizes raw data queries in the Jobs realm by using `WHERE` conditions on the `end_day_id` field of `modw.job_tasks` instead of the `end_time_ts` field. This PR also removes the `DISTINCT` modifier for single-day queries.
There is also a PR for https://github.com/ubccr/xdmod-xsede/pull/433.
The new query is much faster (<10 seconds per single-day query compared to ~200 seconds), and in conjunction with https://github.com/ubccr/xdmod/pull/1792 and https://github.com/ubccr/xdmod-data/pull/19, it makes the data analytics framework more responsive.
In addition to ensuring the regression tests from https://github.com/ubccr/xdmod/pull/1788 still pass:
1. Run the script from https://github.com/ubccr/xdmod-xsede/pull/436 with the `--time` argument.
1. Set `'new': …
> Optimize raw data job queries.

- tests/regression/lib/TestHarness/RegressionTestHelper.php
This PR adds functionality to allow the raw data requested in the regression tests to be sorted before it is saved to or compared against a test artifact file. This is useful for the `SUPREMM` realm in the `fresh_install` test mode, since in this case the order of the results returned is nondeterministic across multiple CI runs. This also means there do not need to be separate test artifacts in the `SUPREMM` realm for `fresh_install` and `upgrade` test modes, so this PR also removes the code that separates those.
This PR allows the regression tests in https://github.com/ubccr/xdmod-supremm/pull/354 to pass.
I confirmed the CI tests still pass for this PR, and I ran the manual tests described in https://github.com/ubccr/xdmod-supremm/pull/354.
> Add sorting functionality to raw data regression tests.

- html/gui/js/modules/job_viewer/JobPanel.js
This PR makes the Job Viewer's analytics panel explicitly display the metrics in the order they are currently displayed (1. `CPU User`, 2. `Homogeneity`, 3. `CPU User Balance`, 4. `Memory Headroom`, 5. `Walltime Accuracy`) rather than displaying them in whatever order they are returned by the `rest/warehouse/search/jobs/analytics` endpoint. This will be needed for https://github.com/ubccr/xdmod-supremm/pull/256 since that PR will cause the metrics to be in a different order when they are returned by the endpoint.
In a Docker container running `tools-ext-01.ccr.xdmod.org/xdmod-job_performance-10.5.0:rockylinux8-0.1`:
1. Run the following commands:
```
export COMPOSER_ALLOW_SUPERUSER=1
export XDMOD_REALMS='jobs,storage,cloud,supremm,jobefficiency'
export XDMOD_IS_CORE=yes
export …
```
> Add explicit ordering for Job Viewer analytics panel.

- html/gui/js/profile_editor/ProfileApiToken.js
Currently, if someone has an expired API token, they see:
Instead, they should see:
There is already code to do this, but it was mistakenly using the creation date of the token rather than the current time to determine if a token is expired. This PR fixes it.
On my port on `xdmod-dev`:
1. Before updating with the changes from this PR,
1. Expire my current token manually in the database.
1. Go to my XDMoD portal, click `My Profile`, and click `API Token`.
1. Confirm it shows the wrong message.
1. Update my port with the changes from this PR, and repeat the same steps, confirming that it shows the right message.
1. Generate a new token, close the `My Profile` window, reopen it, and confirm the message is still correct.
> Fix API token expiration message.

- 10.5/support.md
- _config.yml
This PR updates the list of supported versions on the website.
It moves 10.0 to the list of unsupported versions and removes it from the table of currently supported versions on https://open.xdmod.org/10.5/support.html, since support for it ended September 10, 2023.
It also mentions that we generally release one or two (instead of just two) versions per year, and it removes the comment about why we only released one version in 2022.
It also removes 8.5 from the list of unsupported versions in the website menu, to continue listing only the 3 most recent unsupported versions.
It also adds the `effervescence` style to old pages that use `page.menu_markdown` so that a line can appear in between the `page.menu_markdown` and version list once https://github.com/ubccr/xdmod-jekyll-theme/pull/17 …
> Update list of supported versions on website.

- tests/regression/lib/Controllers/UsageChartsTest.php
This change fixes a syntax error in the Usage Charts regression test. It also updates the generic PHP `Exception` to the builtin `UnexpectedValueException` to pass the code quality tests.
This fixes a bug originally introduced in https://github.com/ubccr/xdmod/pull/1699. I noticed this bug when I made some breaking changes to the imagehash installation that caused the Usage Charts regression test to fail. Instead of throwing an Exception when imagehash was unavailable on the system, the test reported a syntax error.
Tested in a docker container:
`$ docker run -it --rm -p 8443:443 tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.2 /bin/bash`
Inside the container clone the latest version of the upstream code:
`git clone https://github.com/ubccr/xdmod.git /root/scratch/xdmod` …
> Fix syntax error in regression test

- classes/OpenXdmod/Migration/ConfigFilesMigration.php
This PR fixes a bug in which double quotes are not properly escaped when migrating portal settings.
This was noticed when testing the upgrade path for the `ondemand` module.
In `xdmod-ondemand`, in `configuration/portal_settings.d/ondemand.ini`, the value for `webserver_format_str` has backslash-escaped double quotes.
When running the test steps below (which are based on the CircleCI upgrade path for `xdmod-ondemand`) (and instead cloning `https://github.com/ubccr/xdmod` into `/xdmod`), after running the first set of commands, the file `/etc/xdmod/portal_settings.d/ondemand.ini` had unescaped quotes.
This is because when the file is parsed in `classes/OpenXdmod/Migration/ConfigFilesMigration.php` in the function `writeModulePortalSettingsFile` when it calls `parse_ini_file`, the …
> Escape double quotes when migrating portal settings.

- classes/ETL/DataEndpoint/WebServerLogFile.php
- composer.json
This PR updates the web server log file parser to allow `@` in remote user values.
Remote user values are logged by some identity providers in the form `<user>@<domain>`. This PR makes sure that the log parser does not skip these lines. This is relevant for the `ondemand` module and was noticed when testing the upcoming OnDemand realm in ACCESS XDMoD.
I tested this by running `xdmod-ondemand-ingestor` on my port on `xdmod-dev` with log files containing user values containing `@`. Before the changes in this PR, the lines are skipped; after, they are ingested.
> Allow `@` in remote user format string when parsing web server log files.

- classes/CCR/Logger.php
- classes/CCR/RequestLogger.php
- classes/Rest/XdmodApplicationFactory.php
- configuration/etl/etl.d/xdmod-migration-10_5_0-11_0_0.json
- configuration/etl/etl_sql.d/migration/cleanup_log_table.sql
The `username` property was not being properly populated for rest request logging. This commit resolves that problem.
I'll also be looking to resolve escaping in the log messages.
> Updating Rest Logging to include the username

- configuration/etl/etl.d/xdmod-migration-10_5_0-11_0_0.json
The endpoint config values for the etlv2 migrations should should match the config values used in other pipelines that use these tables, such as in `etc.d/staging.json` and `etl.d/hpcdb.json`.
Tested locally in docker
> Changing etlv2 endpoint config value used for migration etlv2 actions

- docs/software-requirements.md
These changes update the installation instructions for Rocky 8.
We have received a couple tickets regarding the installation of the MongoDB PHP driver on Rocky 8. The current version `1.18.1` is not compatible with PHP 7.2. The current compatible version of the driver is `1.16.2`. The `php-mysql` package is also not available on Rocky 8 so I have updated the instructions to install `php-mysqlnd` instead (which is currently being used in our CI test images [here](https://github.com/ubccr/xdmod/blob/xdmod11.0/tests/ci/Docker/Dockerfile.rocky8.xdmod-base)) and `php-pear` to install the mechanism to install the MongoDB driver.
Tested in fresh `rockylinux:8` container using the updated installation instructions.
> Update software requirements for Rocky 8

- html/gui/js/modules/job_viewer/ChartPanel.js
The event listener needs to only be added on a newPlot to readded to an existing one.
Tested on my port by repeatedly drilling down on a GPU timeseries plot.
> Fix MaxListenersExceededWarning warning.

- NOTICE
jQuery was removed in PR #1756 along with `jquery-base64`.
Make NOTICE accurate
> Remove `jquery-base64` from NOTICE

- tools/etl/etl_overseer.php
This is based on #1827 but makes it configurable (with the default being no change in behavour)
Tested manually by running:
```
./share/tools/etl/etl_overseer.php  -v debug
```
and then checking the database to see a log was written:
```
mysql mod_logger
> select * from log_table order by id desc limit 1;
```
then doing the same but with the `--log-to-database no` option (no write happened) and then same again but with the `--log-to-database yes` option (did write).
> Add configuration setting for the ETL process log database output

- tools/etl/etl_overseer.php
This allows etl_overseer.php to be used to bootstrap XDMOD instances where running xdmod-setup is not possible, like when running Puppet
I use Puppet to bootstrap XDMOD and running 'xdmod-setup' isn't possible so I run commands like:
```
/usr/share/xdmod/tools/etl/etl_overseer.php -p xdb-bootstrap -p jobs-xdw-bootstrap -p xdw-bootstrap-storage -p shredder-bootstrap -p staging-bootstrap -p hpcdb-bootstrap -p acls-xdmod-management -p logger-bootstrap
```
This is failing without this change, examples:
```
[root@rocky-8 /]# /usr/share/xdmod/tools/etl/etl_overseer.php -l sections
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mod_logger.log_id_seq' doesn't exist in /usr/share/xdmod/classes/CCR/DB/PDODB.php:185
Stack trace:
#0 …
```
> Disable db logging for etl_overseer

- .gitignore
- classes/ETL/DataEndpoint/WebServerLogFile.php
- tests/artifacts/xdmod/etlv2/dataendpoint/input/webserverlogfile/test.log
- tests/unit/lib/ETL/DataEndpoint/WebServerLogFileTest.php
This PR updates the web server log parser to split the request line (i.e., `%r`, e.g., `GET /index.html HTTP/1.1`) into its three parts (i.e., `%m %U %H`) so these can be parsed separately.
This enables https://github.com/ubccr/xdmod-ondemand/pull/50.
I added unit tests to make sure a log is correctly parsed whether the format is `%r` or `%m %U %H`. I also tested ingesting logs on my port on `xdmod-dev` with the changes from https://github.com/ubccr/xdmod-ondemand/pull/50 and the PRs on which it depends.
> Parse request method, URL, and protocol separately in web server logs.

- tests/regression/lib/TestHarness/RegressionTestHelper.php
This PR fixes the regression tests of the `/warehouse/raw-data` endpoint such that, if the `sort` option is `true`, the last newline character of the sorted response text stays at the end rather than being moved to the beginning.
This makes it easier to view and debug the expected test artifacts and actual responses for the tests in question. In addition, https://github.com/ubccr/xdmod-supremm/pull/381 depends on this PR.
In a Docker container running `tools-ext-01.ccr.xdmod.org/xdmod-job_performance-10.5.0:rockylinux8-0.1`, I cloned copies of this branch and the branch from https://github.com/ubccr/xdmod-supremm/pull/381, manually followed the `upgrade` steps for CircleCI, and confirmed the regression tests all pass.
> Fix sorting in regression tests of raw data.

- classes/Rest/Controllers/BaseControllerProvider.php
- Added checking the results of the PHP built in function `getallheaders()` for the presence of the `Authorization` header due to Silex seeming to remove the header ( or at least it's not present when using `request->headers->[all()|get()|has()]`
So it looks like Silex removes the `Authorization` header for some reason so I've added a fall back of checking the results of the PHP built in function `getallheaders`.
I also added a couple of comments to help with reading things after the fact.
Automated Tests.
> Fixing Token Header Auth

- classes/CCR/Loggable.php
- classes/Configuration/CommentTransformer.php
- classes/Configuration/Configuration.php
- classes/Configuration/IncludeTransformer.php
- classes/Configuration/JsonReferenceTransformer.php
- classes/Configuration/JsonReferenceWithFallbackTransformer.php
- classes/Configuration/JsonReferenceWithOverwriteTransformer.php
- classes/Configuration/ModuleTransformer.php
- classes/Configuration/StripMergePrefixTransformer.php
- classes/Configuration/aUrlTransformer.php
- classes/Configuration/iConfigFileKeyTransformer.php
- docs/etl/json-references.md
- tests/unit/lib/ETL/Configuration/IncludeTest.php
- tests/unit/lib/ETL/Configuration/JsonReferenceWithFallbackTest.php
- tests/unit/lib/ETL/Configuration/Rfc6901Test.php
This PR adds an `JsonReferenceWithFallbackTransformer` that allows configuration files to contain a `$ref-with-fallback` key. This is similar to the `$ref` key, but instead of the value being a single JSON pointer, it is an array of JSON pointers. If there is an error transforming the first JSON pointer in the array, it tries the next JSON pointer in the array, and so on. If it fails to transform the last JSON pointer in the array, it raises an exception just as `$ref` would.
This PR adds an `$exceptionLogLevel` parameter to `getContentsFromUrl()` so that any `No such file or directory` errors are logged at the debug level instead of the error level. This change exposed a bug in `logAndThrowException()` in which the `log_level` option was not properly processed; this PR fixes that bug as …
> Add `JsonReferenceWithFallbackTransformer`.

- classes/ETL/Ingestor/RegexTransformIngestor.php
_NOTE: This PR should not be merged unless https://github.com/ubccr/xdmod-ondemand/pull/50 is also merged; otherwise `xdmod-ondemand` ingestion will break._
This PR allows the `RegexTransformIngestor` to transform multiple columns.
This enables https://github.com/ubccr/xdmod-ondemand/pull/50, specifically the ability to transform `app`, `request_path`, `reverse_proxy_host`, and `reverse_proxy_port` in the same pipeline action (`ondemand.log-ingestion.normalize-staging`).
I tested ingesting logs on my port on `xdmod-dev` with the changes from https://github.com/ubccr/xdmod-ondemand/pull/50 and the PRs on which it depends.
> Allow multiple columns in `RegexTransformIngestor`.

- docs/install-source.md
- docs/software-requirements.md
This PR updates the source install documentation to:
- Move the instructions about changing the prefix to above the commands, to encourage reading the instructions before running the commands.
- Add in the proper `-el8` suffix to the source filename, with instructions to replace it with `-el7` if applicable.
- Use `#` as the terminal prompt symbol for all three commands, for consistency.
This PR also ports the changes from https://github.com/ubccr/xdmod/pull/1830 to the `xdmod11.0` branch.
On my Mac with a cloned copy of the `gh-pages` branch of `xdmod` and Jekyll installed, I copied in the changes from this PR to the `10.5` directory, ran the commands below, and confirmed the output looks correct.
```
git submodule init
git submodule update --remote
sudo networksetup -setv6off 'Wi-Fi' # …
```
> Update source install docs, port software requirement docs from 10.5 to 11.0.

- tests/unit/lib/ETL/Configuration/JsonReferenceWithFallbackTest.php
Not exactly sure how this was missed, but it was.
> Updating PHPUnit Test that should have been updated in the PHP 7.4 merge.

- classes/ETL/DataEndpoint/aStructuredFile.php
- classes/OpenXdmod/Migration/ConfigFilesMigration.php
- classes/OpenXdmod/Migration/Migration.php
This code was causing warnings to be generated when testing with PHP 7.4. It turns out that trying to create a `Configuration` object for an entire directory will do that. Upon further investigation I found that the only time this property was used was to access it's `baseDir` value ( Which is always equal to the `CONFIG_DIR` class constant). I just updated the uses of this property to instead use `CONFIG_DIR` and removed the now unused `config` property. 
Less warnings == less support tickets.
> Fix Migration Class Warning Generation

- classes/Rest/Controllers/WarehouseControllerProvider.php
- tests/integration/lib/Rest/WarehouseControllerProviderTest.php
This PR provides better exception handling for REST requests to the warehouse raw data endpoint when the realm has not been configured to provide raw data (e.g., the Storage realm).
For example, previously, this request: 
```
GET /rest/warehouse/raw-data?realm=Storage&start_date=2024-01-01&end_date=2024-01-01
```
would respond with `500 Internal Server Error` with no message. This PR changes it to respond with `400 Bad Request` with the message `The requested realm is not configured to provide raw data.`
This PR adds an integration test to make sure that requests to the `Storage` realm, which is not configured for raw data, respond with the correct status code and message.
I also updated my port on `xdmod-dev` and tested to make sure requests for the `OnDemand` and `Requests` realms, …
> Handle REST exceptions for realms that are not configured to provide raw data.

- open_xdmod/modules/xdmod/assets/setup.sh
- open_xdmod/modules/xdmod/assets/symfony_http-foundation_CVE-2019-10913.patch
- open_xdmod/modules/xdmod/build.json
- tests/ci/scripts/qa-test-setup.sh
This patch sets up the patch pipeline in `build.json` and updates a few files that will cause issues during the CI / QA tests / build process. These changes originated in https://github.com/ubccr/xdmod/pull/1891 ( which will be merged in 11.5 ).
- `open_xdmod/modules/xdmod/assets/setup.sh`:
- Removed the Composer Install section as this + the dangling `cd` was causing the composer dependencies of `qa` to be installed in the xdmod directory. This probably wasn't a problem or caught before because we were not previously patching files.
- Changed the `cd $xdmod_dir`to a `pushd | popd` so that we reset the cwd after the script runs.
- `open_xdmod/modules/xdmod/build.json`
- added entries to support patching files. This necessitated adding the `rm -rf vendor/` and `composer install` due to the …
> Patch for symfony/http-foundation: CVE-2019-10913

- classes/Rest/Controllers/WarehouseControllerProvider.php
- tests/integration/lib/Rest/WarehouseControllerProviderTest.php
This PR refactors the validation of the `realm` parameter for REST requests to the warehouse raw data endpoint.
Now, instead of responding with a message of `Invalid realm`, the message provides more information depending on the reason for the error:
* `No realm exists with the requested name.`
* `The requested realm is not configured to provide raw data.`
* `Your user account does not have permission to get raw data from the requested realm.`
In the last example above, it now responds with `403 Forbidden` instead of `400 Bad Request`.
In addition to updating the expected message in an integration test, I also updated my port on `xdmod-dev` and made sure the following tests passed with different roles and different realms, making the following request (replacing `<token>` with the user's …
> Refactor REST warehouse raw data realm validation.

- classes/Rest/Controllers/BaseControllerProvider.php
- tests/integration/lib/BaseTest.php
Additional Validation of both ISO8601 Date & Unix Timestamp parameters REST parameters have been added. 
Aaron noted in https://app.asana.com/0/159049597309611/1208001546005418/f that it seemed like invalid values ( ex. `2024-01-99`) were being accepted for date parameters provided to rest endpoints.
These changes add additional validation to both ISO8601 Date & Unix Timestamp parameters where `DateTime::getLastErrors()` is checked to see if there are any warnings or errors before possibly returning a value.
New tests were added per conversation with Aaron.
All automated tests were run / passed.
> Adding logic to catch invalid datetime values

- classes/OpenXdmod/Migration/Version1050To1100/DatabasesMigration.php
- configuration/etl/etl.d/xdmod-migration-10_5_0-11_0_0.json
- configuration/etl/etl_tables.d/cloud_common/instance_type_union.json
Add default value for `modw_cloud.instance_type_union` table. This makes it so warning during ingestion do not happen. The `1` value is the Unknown value from `modw_cloud.instance_type`
> Add default value for modw_cloud.instance_type_union table

- docs/install-rpm.md
- docs/openidc.md
- docs/simpleSAMLphp-ldap.md
- docs/simpleSAMLphp.md
- docs/upgrade.md
- docs/xdmod-rest-schema.json
This PR backports documentation changes from the `xdmod11.0` branch to the `xdmod10.5` branch: OpenIDC documentation (https://github.com/ubccr/xdmod/pull/1810), broken link fixes (https://github.com/ubccr/xdmod/pull/1808), the version number fix in the REST API docs (https://github.com/ubccr/xdmod/pull/1784), and various other doc fixes (https://github.com/ubccr/xdmod/pull/1912).
> Backport docs changes from 11.0 to 10.5.

- docs/upgrade.md
Added additional documentation on how to update the xdmod DB user to work when the XDMoD webserver is migrated to a new host. 
It's important for installations that host the XDMoD DB on a different server than the XDMoD Web Server to ensure that the database user XDMoD uses is updated to reflect a change in the XDMoD Web Server's hostname. Failure to do this will result in XDMoD not being able to funciton due to permission denied errors.
> Add additional information for 11.0 upgrade

- docs/upgrade.md
`make` package is required to run `yes '' | pecl install mongodb-1.18.1`.
> Add missing dependency for mongodb PHP Pear package

- docs/support.md
This PR updates the support documentation to extend the support window for version 10.5 to March 31, 2025, to give people more of a transition period for upgrading to 11.0.
> Extend support window for 10.5.

- docs/faq.md
- docs/latest-releases.md
- docs/software-requirements.md
Also fix some other errors about ssl config and clarify timezone setting reqs
> Update software requirements docs to expunge Centos 7

- 11.0/software-requirements.md
- sitemap.xml
This PR ports https://github.com/ubccr/xdmod/pull/1937 to `gh-pages`.
> Update version of MongoDB in software requirements docs.

- html/index.php
This PR updates the HTML metadata description to include ACCESS and to include what are in the metadata keywords since Google doesn't use the metadata keywords.
The current metadata description is out of date. Here is how it appears when searching Google for ACCESS XDMoD:
> Update HTML metadata description.

- classes/ETL/Maintenance/ExecuteSql.php
The ETL maintenance class `ExecuteSql` only uses `destinationEndpoint`, not `sourceEndpoint`. However, when exceptions are logged, it tries to report the `sourceEndpoint`. This PR fixes this to instead report the `destinationEndpoint`.
I ran an SQL query on my port on `xdmod-dev` that I knew was incorrect, and it reported the following (note that the endpoint is not reported):
```
xsede.migration-11_0_0p1-11_0_0p2.MapUnknownOodPeople (ETL\Maintenance\ExecuteSql): Error executing SQL Exception: 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'modw.page_impressions' doesn't exist'
```
Then I applied the fix, ran it again, and the endpoint is now reported in the exception:
```
xsede.migration-11_0_0p1-11_0_0p2.MapUnknownOodPeople (ETL\Maintenance\ExecuteSql): Error executing SQL …
```
> Add missing endpoint to exception message in `ExecuteSql`.

- classes/OpenXdmod/Migration/Version1100To1101/DatabasesMigration.php
- configuration/etl/etl.d/xdmod-migration-11_0_0-11_0_1.json
This adds the migration pipeline for the columns added in https://github.com/ubccr/xdmod/pull/1957. The cloud-state-pipeline etl pipeline has been added to the migration to re-aggregate the cloud realm so these columns are added and the columns are populated. These columns are used in the xsede module at this point in time.
This replaces #1936
> Add upgrade pipeline for person and PI organization in cloud realm

- classes/DataWarehouse/Visualization/AggregateChart.php
This pull request addresses multiple issues with swapping the X-Y axis.
1) Incorrect Y-axis legend configuration when there are multple datasets using different axes 
2) Corrupted x-axis legend configuration when "show remainder disable paging" is selected.
Before (note the wrong title on the y-axis and the vertical misalignment of the data, and the incorrect data ordering):
After:
Before (note the messed up x-axis): 
After:
The change to fix problem (1) is to update the swap axis code to swap the correct axes!
The change for fix problem (2) involves moving the call to truncate the datasets to before the chart configuration is attempted. The chart truncate causes the categorical axis to be regenerated. When this was happening during the chart config with swap XY enabled then the chart …
> Fix issues with swap XY axis.

- classes/ETL/Aggregator/pdoAggregator.php
Currently, if `pdoAggregator` is used to aggregate a single day, the day it displays in the log is off by one. I noticed this when manually aggregating a day (`2016-11-01`) of Gateways data:
```
sudo -u xdmod /data/www/xdmod/share/tools/etl/etl_overseer.php -v debug -a xsede.science-gateway.AggregationByDay -s '2016-11-01 00:00:00' -e '2016-11-01 23:59:59' -f
...
[info] Aggregated day (1/1) 201600306 02 11 2016
```
That should instead be `01 11 2016`.
This is because the `Y00z` format string counts days of the year starting at zero, but MySQL `DAYOFYEAR` counts starting at one.
This PR fixes how the day is displayed. It also changes the format to match what is used often elsewhere, `Y-m-d`.
Tested by aggregating a day of Gateways records on `xdmod-dev` and confirming the displayed day is …
> Fix how `pdoAggregator` logs the day that was aggregated.

- html/about/presentations.html
- html/about/publications.html
Update Papers and Presentations pages with information from 2024
> Updating publications and presentations 2024/2025

- classes/OpenXdmod/Migration/MigrationFactory.php
This PR adds the ability to add additional database migration classes by defining them in the same namespace and ending their names with `DatabasesMigration`.
This is useful for, e.g., https://github.com/ubccr/xdmod-ondemand/pull/84.
I tested https://github.com/ubccr/xdmod-ondemand/pull/84 in tandem with this PR.
> Add ability to add additional database migration classes.

- open_xdmod/modules/xdmod/xdmod.spec.in
This PR fixes a date in the spec file's changelog. This fixes a warning when building the RPM: `warning: bogus date in %changelog`.
> Fix date in spec changelog.

- docs/install-rpm.md
- docs/upgrade.md
This PR updates the docs as follows:
* Explain that when upgrading via RPM, the GitHub URL can be directly installed via `dnf`, and if modules are installed, their RPMs need to be installed in the same `dnf install` line.
* Mention to be aware of `.rpmnew` and `.rpmsave` files.
* Make sure the source upgrade instructions link to the module upgrade pages instead of their install pages.
> Update RPM install/upgrade instructions.

- bin/xdmod-ingestor
- classes/OpenXdmod/DataWarehouseInitializer.php
- configuration/etl/etl.d/hpcdb.json
- configuration/etl/etl_action_defs.d/storage/hpcdb/usage-to-ingest-date-range.json
- configuration/etl/etl_action_defs.d/storage/hpcdb/usage-to-ingest-new-usage.json
- configuration/etl/etl_action_defs.d/storage/xdw/storagefact.json
- configuration/etl/etl_tables.d/storage/hpcdb/usage-to-ingest.json
The Storage realm does not have the ability to ingest data by date range like the Jobs realm does. For the Storage realm, the command `xdmod-ingestor --start-date "2020-01-01" --end-date "2022-01-01"` does not ingest data for the specified time range. The Storage realm only ingests information that has not already been ingested into `modw.storagefact`. This allows the storage realm etl process to use the values supplied with the `--start-date` and `--end-date` flags.
> Add ingestion by date range for Storage realm

- tests/playwright/lib/internal_dashboard.page.ts
- tests/playwright/playwright.config.ts
Removed some calls to `isVisible()` function which returns a boolean
which was being ignored by the code.
Add extra wait so the internal dashboard is loaded before proceeding.
Run tests in serial mode to mitigate race conditions in the XDMoD database.
> Robustness improvements for playwright

- tests/regression/lib/Controllers/UsageChartsTest.php
These changes add the ability to, by specifying a env variable, to instruct the UsageChart image export tests to save the actual images to the `/tmp/` directory so that they can be compared to another set of images to determine why these tests may be failing.
These changes will also output a metadata file to be used in further determining potential similiarities in test failures.
> Adding ability to save Regression Test UsageChart images

- html/gui/js/PlotlyChartWrapper.js
Should have been in original conversion (PR #1822). This update makes all XDMoD charts timezone aware. Plotly JS does not support timezones. Therefore, moment js was utilized to convert the dates to the web server's timezone.
This bug was found by @ryanrath and Shava. The the following [chart](https://xdmod-dev.ccr.xdmod.org:9004/#main_tab_panel:metric_explorer?config=eyJmZWF0dXJlZCI6ZmFsc2UsInRyZW5kX2xpbmUiOmZhbHNlLCJ4X2F4aXMiOnt9LCJ5X2F4aXMiOnt9LCJsZWdlbmQiOnt9LCJkZWZhdWx0RGF0YXNldENvbmZpZyI6e30sInN3YXBfeHkiOmZhbHNlLCJzaGFyZV95X2F4aXMiOmZhbHNlLCJoaWRlX3Rvb2x0aXAiOmZhbHNlLCJzaG93X3JlbWFpbmRlciI6ZmFsc2UsInRpbWVzZXJpZXMiOnRydWUsInRpdGxlIjoidW50aXRsZWQgcXVlcnkgMSIsImxlZ2VuZF90eXBlIjoiYm90dG9tX2NlbnRlciIsImZvbnRfc2l6ZSI6Mywic2hvd19maWx0ZXJzIjp0cnVlLCJzaG93X3dhcm5pbmdzIjp0cnVlLCJkYXRhX3Nlcmllc …
> Plotly JS charts now consider timezones

- tests/playwright/lib/metricExplorer.page.ts
- tests/playwright/tests/metricExplorer/metricExplorer.spec.ts
Saw an intermittent failure in the Metric Explorer tests - looked to be caused by the test running while the data catalog was still moving. This update ensures the data catalog animation should have ended. Also click on the top left, which moves the mouse pointer away from any location that has hover overs (this also was seen in a error case where the hover over was in the way).
> Increase robustnification.

- classes/Models/Services/Tokens.php
- classes/Rest/Controllers/BaseControllerProvider.php
- docs/data-analytics-framework.md
- docs/xdmod-rest-schema.json
- html/controllers/metric_explorer/get_dimension.php
- html/controllers/metric_explorer/get_dw_descripter.php
- html/controllers/user_interface/get_charts.php
- tests/integration/lib/TokenAuthTest.php
- user_manual_builder/About.rst
This PR removes the ability to authenticate to the Data Analytics Framework REST API via API token in GET or POST parameters and makes it so the token must be provided via `Authorization` header. The GET/POST param functionality was in place for CentOS 7 to work around the `Authorization` header being eaten by Apache, and it is no longer needed.
These changes mean the current method of counting Data Analytics Framework requests for our reporting KPIs will no longer work (they involved reading the logs with `ident = 'rest.logger.db' or ident = 'controller.log'` and searching for the `Bearer` parameter). To correct this, this PR adds logging with a new `ident = 'daf'`.
This PR also updates the error messages and documentation to use consistent lowercasing of "token" and to move the …
> Remove Data Analytics Framework token authentication via GET/POST params.

- configuration/etl/etl.d/xdmod-migration-11_0_0-11_5_0.json
The `xdmod-xsede` module has a different `ingest_resources.json` file that does not have the same actions so even though the migration is not run for ACCESS XDMoD it still checks this file. When it does the references are either the wrong etl actions or do not exist. To prevent this, I just copied the necessary etl actions into the migration file.
> Moved 11.5 etl migration actions into migration etl file instead of referencing them

- classes/Models/Services/Tokens.php
- classes/Rest/Controllers/BaseControllerProvider.php
- classes/Rest/Controllers/WarehouseControllerProvider.php
- classes/Rest/Controllers/WarehouseExportControllerProvider.php
- html/controllers/metric_explorer/get_dimension.php
- html/controllers/metric_explorer/get_dw_descripter.php
- html/controllers/user_interface/get_charts.php
- tests/integration/lib/TokenAuthTest.php
This PR restores the ability to authenticate to the Data Analytics Framework REST API via API token in a `Bearer` parameter of GET or POST requests instead of an `Authorization` header. This functionality had been removed in #2028, but after that PR was merged, it was discovered that the eating of the `Authorization` header described in that PR also happens in Rocky 8, and a proper fix requires an update to the Apache configuration. Because updating the Apache configuration requires the admin to make manual changes, this is deemed a substantial enough change to warrant deferring it to a major release. So, for now, we are rolling back to allowing the `Bearer` parameter to be used when making GET/POST requests.
This PR also refactors the code a bit to make it easier to read and maintain. …
> Restore Data Analytics Framework token authentication via GET/POST params.

- docs/cloud.md
- docs/etl/data-endpoint-oracle.md
- docs/etl/data-verification.md
- docs/etl/json-references.md
- docs/gateways-realm.md
- docs/integrations.md
- docs/module-assets.md
- docs/openidc.md
- docs/shredder.md
We had a bug report (and suggested code change) from @einonm about broken links in the documentation files. 
We use Jekyll with the github-pages Jekyll plugins which includes the Jekyll Relative Links plugin which converts
markdown links into html links with the correct path. It turns out that the relative links plugin will (silently)
fail to translate the links if there are line breaks in the markdown or extra spaces in the references (see the changes
in shredder.md). In my testing I also found that the jekyll version on github pages would fail to process files if they were missing the title directive.
This pull request fixes the incorrect syntax and adds title sections for all pages.
I note that we want to have the links with the ".md" suffix so that the pages work both when viewed in …
> Fix syntax errors in markdown files.
